### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alexaguilar89** [MicrosoftDocs/azure-devops-docs#10028]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be0bdbf7-3132-9007-6c6a-368c5bcb0f3d
* Version Independent ID: 58118f61-f88f-24b9-b785-d8f9d8a1fefd
* Content: [Administer code, wiki, and work item search - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/search/administration?view=azure-devops-2020)
* Content Source: [docs/project/search/administration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/search/administration.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by alexaguilar89** [comment]
Ok

**Comment by msebolt** [comment]
@alexaguilar89  Thank you for reaching out.

You can provide additional comments below, otherwise for further options, please try one of the following channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
