### ISSUE TITLE
i already bought access for test plans and was able to link the Azure subscription, but still showing us free trial available. can you please guide me on the process so we will be billed through our Azure subscription? Thanks

### ISSUE THREAD

**Issue by jlabustro** [MicrosoftDocs/azure-devops-docs#10021]
[Овдје унесите повратне информације]

---
#### Детаљи документа

⚠ *Не уређујте ову секцију. Она је неопходна за повезивање проблема слиједом docs.microsoft.com ➟ GitHub.*

* ID: ccdd484b-488b-1863-848a-49c12848264a
* Version Independent ID: bb3baa44-be50-3ad5-5e70-a354bc2cafea
* Content: [Buy access to Azure Test Plans - Azure DevOps Server](https://docs.microsoft.com/bs-cyrl-ba/azure/devops/organizations/billing/buy-access-tfs-test-hub?view=azure-devops-2019)
* Content Source: [docs/organizations/billing/buy-access-tfs-test-hub.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/billing/buy-access-tfs-test-hub.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@jlabustro Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
