### ISSUE TITLE
What is “myhealth.web”?

### ISSUE THREAD

**Issue by alexislefebvre** [MicrosoftDocs/azure-devops-docs#10024]
On this page: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#run-a-specific-service-image

We can see this:

```yaml
- task: DockerCompose@0
  displayName: Run a specific service
  inputs:
    # …
    serviceName: myhealth.web
    # …
```

Could you please explain what `myhealth.web` is?

It's the only occurrence in the documentation: https://github.com/MicrosoftDocs/azure-devops-docs/search?q=myhealth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d767aebb-620e-9ad3-e906-3e2bafa02ee9
* Version Independent ID: c8cb5a48-ccdf-778c-1547-a10db74cb56c
* Content: [Docker Compose task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker-compose.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/docker-compose.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by alexislefebvre** [comment]
It looks like it will create an alias hostname `myhealth.web` that will be bound to this service.

**Comment by msebolt** [comment]
@alexislefebvre Thank you for the question.

`serviceName` is the reference to keyword **service** used in Docker Compose, see [here](https://docs.docker.com/compose/networking/).

Also note that [run service images](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#run-service-images) includes all network services, opposed to [run specific image](https://docs.microsoft.com/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops#run-a-specific-service-image) that runs a specific selection.

For additional support options, please move this to one of the following channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Otherwise, for any other documentation-specific concerns, please comment below.

**Comment by alexislefebvre** [comment]
Thanks for your answer. So if I understand correctly, `serviceName: myhealth.web` correspond to that docker-compose configuration:

```yaml
services:
  myhealth.web:
    build: .
```
