### ISSUE TITLE
AzureDevOps - Usage of AzurePowershell Task for Set-AzKeyVaultSecret

### ISSUE THREAD

**Issue by ktdixit** [MicrosoftDocs/azure-devops-docs#10032]
Hello, 

I am using a Secret Pipeline Variable in AzureDevOps Release Pipeline and using AzurePowerShell Task (version: 5.*). 

My requirement is to create/update the keyvault secret value. 

Command in AzurePowershell: 

**$Secretvalue = ConvertTo-SecureString $env:Test1 -AsPlainText -Force
Set-AzKeyVaultSecret -VaultName $env:keyVaultName -Name 'Test1' -SecretValue $Secretvalue**

This is not working.. Error message below: 

##[error]Cannot bind argument to parameter 'String' because it is an empty string.
##[error]PowerShell exited with code '1'.

Please provide a fix. I want to use secret variable (Test1) value during release time

**Comment by TimShererWithAquent** [comment]
@ktdixit Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
