### ISSUE TITLE
Microsoft Flow / Parameters / Variables issue

### ISSUE THREAD

**Issue by thenecroscope** [MicrosoftDocs/azure-devops-docs#10033]
Hi,

I'm not sure if I'm adding this in the correct forum.

I have an issue when using the Microsoft Flow - Azure DevOps 'Queue a new build connector' / template.

When using MS Flow to send a request to Azure DevOps without parameters everything works as expect.
When I started to add parameters within the Flow DevOps connector, then things are a bit unclear to me at the minute.

I'm able to get this working, but I have to create variables instead of Parameters. Ideally I would prefer to use the Azure DevOps Parameters feature but I just cannot get this to work. The only way I think I can this to work is to somehow assign the Parameters to variables or the reverse and then call these later on using my powershell step.

I hope that makes some sense!

thanks,

**Comment by TimShererWithAquent** [comment]
@thenecroscope - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
