### ISSUE TITLE
How can I find the managed identity ID used by the service connection and what permissions are assigned to it? 

### ISSUE THREAD

**Issue by mpchen** [MicrosoftDocs/azure-devops-docs#10043]
If I choose the "Manage Identify" option to create a service connection to ARM, how can I find out the ID of the managed identity being created and what roles are assigned to it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5093b8d4-43df-12c3-591d-43e174e630cd
* Version Independent ID: 4a9bf702-1b28-33ef-9a26-fcf9dadaa7c2
* Content: [Troubleshoot Azure Resource Manager service connections - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops)
* Content Source: [docs/pipelines/release/azure-rm-endpoint.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/azure-rm-endpoint.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@mpchen - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
