### ISSUE TITLE
Wrong parameter name 'kubernetesServiceEndpoint'?

### ISSUE THREAD

**Issue by illeszsolt** [MicrosoftDocs/azure-devops-docs#10073]
In the documentation the parameter is referred as 'kubernetesServiceEndpoint', but when I add a new HelmDeploy@0 task from the UI it generates 'kubernetesServiceConnection' if connectionType is 'Kubernetes Service Connection'. It seems 'kubernetesServiceConnection' works, but I am not sure which parameter name is the correct one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **atulmal**

**Comment by steved0x** [comment]
They are both "correct" due to a feature by which task inputs can have a name plus optional aliases.

This issue is fixed in our new task reference here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
