### ISSUE TITLE
Project, and Organization Request Access

### ISSUE THREAD

**Issue by RiadKatby** [MicrosoftDocs/azure-devops-docs#10085]
Can we use this feature for those whom has access to organization and has no access to some projects? so they can ask for access to specific project ?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 112fefce-9444-4cd0-d680-7960955e1d18
* Version Independent ID: bf19c853-7988-53f3-aaed-98479a522d14
* Content: [Disable Request Access policy - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/disable-request-access-policy?view=azure-devops)
* Content Source: [docs/organizations/accounts/disable-request-access-policy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/disable-request-access-policy.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@RiadKatby Thanks for your question. It looks like you're asking a product question, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
