### ISSUE TITLE
Scale Set Agent Support on RHEL

### ISSUE THREAD

**Issue by huntleyh** [MicrosoftDocs/azure-devops-docs#10098]
Is there any plan to support RHEL for Scale Set Agents? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Thanks for your question. It looks like you're asking a question about feature support, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
