### ISSUE TITLE
Can we upload a delete nuget package back with same name into the same nuget feed

### ISSUE THREAD

**Issue by Bangarraju1005** [MicrosoftDocs/azure-devops-docs#10105]
Can we upload a delete nuget package back with same name into the same nuget feed.

**Comment by Bangarraju1005** [comment]
Any update on my ask

**Comment by TimShererWithAquent** [comment]
@Bangarraju1005 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
