### ISSUE TITLE
.NET/NuGet pipeline caching with $(UserProfile) variable causes error

### ISSUE THREAD

**Issue by Ogglas** [MicrosoftDocs/azure-devops-docs#10110]
For .NET/NuGet pipeline caching it ways:

```
variables:
  NUGET_PACKAGES: $(UserProfile)/.nuget/packages
```

https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget

Every other cache uses something like:

```
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
```

Using `$(UserProfile)` results in the following error:

> Determining projects to restore...
> C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(560,5): error : 'NUGET_PACKAGES' must contain an absolute path '$(UserProfile)/.nuget/packages'. [D:\a\1\s\Solution\project.csproj]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@Ogglas - Thanks for your question. I'm going to change this to doc bug, since we should look at this example to see if there's a problem. In the meantime, please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

CC @ramiMSFT for awareness

**Comment by ramiMSFT** [comment]
@Ogglas Thank you for your feedback!
