### ISSUE TITLE
Job executing with out of range IP

### ISSUE THREAD

**Issue by thegrew** [MicrosoftDocs/azure-devops-docs#10126]
Hi All
After whitelisting the ranges (for all geographies) in the document we were still having issues with an inbound connection from Azure Devops. When running checks from the pipeline the external IP address being reported is: 51.104.206.1 which isn't within a valid range in this json file: [https://www.microsoft.com/en-us/download/details.aspx?id=56519](https://www.microsoft.com/en-us/download/details.aspx?id=56519). I have checked and it is a Microsoft IP so should it's range be included as well.
Thanks
Ali

**Comment by TimShererWithAquent** [comment]
@thegrew Thanks for your question.

It looks like you've encountered an issue with the product itself (in the json file), rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug](https://developercommunity.visualstudio.com/search?space=21) here.
