### ISSUE TITLE
Retain indefinitely limit

### ISSUE THREAD

**Issue by MrVhek** [MicrosoftDocs/azure-devops-docs#10120]
Hello, question about the "retain indefinitely" action on a release or a build. Do there is a limit on the number of release/build, we can flag with it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Retention policies for builds, releases, and test - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml#release)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@MrVhek Thanks for your question. It looks like you're asking a question about the product, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by MrVhek** [comment]
@TimShererWithAquent It is an issue with the documentation, because I cannot find this information on it. If you can add the information in the documentation it would be great.

**Comment by juliakm** [comment]
@MrVhek Are you using a release pipeline? If so, this FAQ from [Set retention policies for builds, releases, and tests](https://docs.microsoft.com/azure/devops/pipelines/policies/retention?view=azure-devops&tabs=yaml#if-i-mark-a-run-or-a-release-to-be-retained-indefinitely-does-the-retention-policy-still-apply) may be helpful.
