### ISSUE TITLE
External Data flow in Marketplace extensions?

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/azure-devops-docs#10151]
Hi,

We would like some clarity on the data flow of extensions when installing them.

For example:

1. There may be a simple extension where the data that the extension has access to is only processed within the Azure DevOps Service (or the end user client page) and the publisher does not have access to the data (in other words, the data does not flow to the publisher's servers for processing)
2. There may be another extension where the data flows to Github, Microsoft Power Automate or another 3rd party service for processing.

How can we find that information on a per extension basis?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57602814-9407-e62d-b33e-4c2ace34b2a2
* Version Independent ID: 5c43e752-cb19-7145-4fd1-b2363cffd1d0
* Content: [Trust a publisher in the Marketplace - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/trust?view=azure-devops)
* Content Source: [docs/marketplace/trust.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/trust.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@haneef95 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
