### ISSUE TITLE
Documented npm Example is Worse than Useless

### ISSUE THREAD

**Issue by derekrprice** [MicrosoftDocs/azure-devops-docs#10165]
I did some testing today with npm on a hosted pipeline. My baseline is a pretty consistent ~58s for npm install to run in said pipeline.  Following the documentation's npm example and caching the .npm directory, initial caching costs ~23s. Restoring the .npm cache takes ~68s. Subsequent runs of npm install still take ~44s. That this is a net loss is pretty much a no-brainer. There must be a better solution. Are there any circumstances where this cache task is actually helpful?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@derekrprice - It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

Also, here are some resources that you might find useful:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@ramiMSFT for awareness.
