### ISSUE TITLE
NuGet Security Analysis issue

### ISSUE THREAD

**Issue by v-tkhemasris** [MicrosoftDocs/azure-devops-docs#10168]
I got this error when building the pipelines (just create the demo generated project and didn't modify anything yet)

`NuGet Security Analysis found 1 vulnerable nuget.config file in the repository. Visit https://aka.ms/nugetmultifeed for more details.`

I tried to fix it but still no lucky. Anyone can help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9d58d3-169a-2ffd-5bcf-02daa8d8ac04
* Version Independent ID: a4ae226e-1622-fb62-cfb6-d06bc7c35e84
* Content: [Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/automate-terraform?view=azure-devops)
* Content Source: [docs/pipelines/release/automate-terraform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/automate-terraform.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@v-tkhemasris Thanks for your question. Sorry for the delay in response - 

It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
