### ISSUE TITLE
How can I set 'view build and release pipeline' as default permission for my Azure DevOps project?

### ISSUE THREAD

**Issue by su-jie** [MicrosoftDocs/azure-devops-docs#10174]
We want to publish a public facing project in Azure DevOps to let users see source code and how pipelines are configured. However 'view pipelines' is disabled by default. How can we enable that for everyone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Pipeline permissions and security roles - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* Technology: **devops-cicd-policies**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@su-jie Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
