### ISSUE TITLE
Is it possible to have multiple Azure Pipelines pools?

### ISSUE THREAD

**Issue by dhoare12** [MicrosoftDocs/azure-devops-docs#10188]
If we have certain workloads that we do not want using up all of our parallel jobs quota, is it possible to split our Azure Pipelines agent pool into two separate pools? We would then have those long-running workloads assigned to the second "slow lane" pool, preventing them from causing other jobs to wait in a long queue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d1ea36-caf8-c3f6-95f3-2d40ead86f5a
* Version Independent ID: 46755386-7c55-bd3a-7984-30687a4e94f3
* Content: [Configure and pay for parallel jobs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted#microsoft-hosted-cicd)
* Content Source: [docs/pipelines/licensing/concurrent-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/licensing/concurrent-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-licensing**
* GitHub Login: @steved0x
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@dhoare12 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
