### ISSUE TITLE
Kubernetes Kubeconfig service connection not working 

### ISSUE THREAD

**Issue by robduncan-novia** [MicrosoftDocs/azure-devops-docs#10194]
I have the same issue as: https://github.com/MicrosoftDocs/azure-devops-docs/issues/7142

However I cannot turn off the New Service Connection experience: 
![image](https://user-images.githubusercontent.com/69814868/107772591-54996c80-6d34-11eb-9762-e31b2db731cb.png)

And I can't setup a Azure Subscription connection as it is not able to see the namespaces in the private cluster:
![image](https://user-images.githubusercontent.com/69814868/107772971-dc7f7680-6d34-11eb-9e9a-ba854f72a67e.png)

Could you please advise how to get the Kubeconfig option to work?

**Comment by TimShererWithAquent** [comment]
@robduncan-novia - Thanks for your question. This looks like a support question (and a thorny one, looking through this and the linked issue), rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by qaiserali** [comment]
Hi,

We are also getting the same issue. Is there any fix for it?

/Qaiser

**Comment by WilliamAntonRohm** [comment]
@robduncan-novia, @qaiserali -- Rob, Qaiser, are you following a particular learn.microsoft.com article?  This repo is solely for documentation issues.
