### ISSUE TITLE
Is there any way to remove gradle wrapper from code?

### ISSUE THREAD

**Issue by SamYuan1990** [MicrosoftDocs/azure-devops-docs#10206]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#how-do-i-generate-a-wrapper-from-my-gradle-project

am I misunderstanding that I have to save wrapper jar in my code?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00499395-fdc3-b150-3469-aee2f9fb7cbc
* Version Independent ID: 44e630e1-1689-2d2e-212b-3ce2baf8771f
* Content: [Gradle build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/gradle.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/gradle.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@SamYuan1990 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
