### ISSUE TITLE
Not found how to add a new public upstream source

### ISSUE THREAD

**Issue by a1vanov** [MicrosoftDocs/azure-devops-docs#10217]
Hello

We need to add a new public maven upstream for http://jaspersoft.jfrog.io/jaspersoft/ in our ADS
I could not found how to do this. Soon we will have to add some other public artifacts repositories. 
It seems it is not easy to add a new maven upstream in Azure Devops Server.
Now we are considering to install Nexus to solve this problem.

Alexey

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c152cc-c1d1-abc1-1861-20aab95731bb
* Version Independent ID: 0d75b4b4-3297-fae7-9345-d863f67e6fed
* Content: [Set up upstream sources for your feed - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@a1vanov Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
