### ISSUE TITLE
Custom Rule creation on 2 conditions

### ISSUE THREAD

**Issue by MariaShams** [MicrosoftDocs/azure-devops-docs#10221]
I cannot find an option to create a rule on 2 conditions at a time. 
My desired rule is :
When a user is in the group [ group A]
AND 
State changes from state A to stateB
Then
Restrict transition to state C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4107b23a-ba0a-5a1b-b689-072717cfe8ec
* Version Independent ID: 1ed09ce9-be9b-6146-9cb8-a2a50e12a3c2
* Content: [Add a custom rule to a work item type - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/custom-rules?view=azure-devops)
* Content Source: [docs/organizations/settings/work/custom-rules.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/custom-rules.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@MariaShams Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
