### ISSUE TITLE
Work-items not linked to release when build in different project than repo

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/azure-devops-docs#10224]
Hey,

I have yaml definition in separate Azure DevOps project and my code in another one. In my yaml template, I am using resources repositories to set triggers and checkout my code repository.

Then I have classic release pipelines which are consuming my yaml build. All is fine, but in the linked document we can read, that using resources allow us to actually have full traceability of those consumed services, including work-items.
In my release pipeline, after deployment, I can't see any work-items connected to this build and they should be visible based on this doc.

The only solution I've found so far is to move yaml pipelines to my code repository. Could someone explain it to me? What is the best strategy of keeping those CI pipelines. I know, that preferably they should be near the code. But my project specification does not allow it and in the same time we need to have those work-items linked to release.

Thanks for help,
Rafal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@roofiq Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
