### ISSUE TITLE
Steps and error handling

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/azure-devops-docs#10235]
For a Step of a given kind, what can cause the Step to be in error? For eg for bash is it the return code of the script? For others? Does an error return prevent following Steps and also following Jobs from being executed? 

How should cleanup/teardown for a particular step be handled in case of an error? For eg if errexit is activated for a bash script, should teardown be handled within the script itself via trap or should it be handled somewhere in the Step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@kmathewmk -- thank you for your questions.  It looks like your questions are regarding a particular scenario or implementation, rather than an issue with the documentation.  Please see these sections:
- [Steps](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#steps), regarding `continueOnError`
- [Error action preference](https://docs.microsoft.com/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#error-action-preference)

As well, consider these resources:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by kmathewmk** [comment]
I find the documentation insufficient with regards to what triggers errors and how it affects following Steps and Jobs. A good example show best practices would also be useful. 

PowerShell (with LASTEXITCODE) is somewhat better documented compared to bash. For bash, I presume it is shell option 'errexit' and the exit code $?.

**Comment by WilliamAntonRohm** [comment]
@kmathewmk -- thank you for your followup.

@steved0x -- please look into this issue.
