### ISSUE TITLE
Getting error while extracting zipped files in pipeline

### ISSUE THREAD

**Issue by sachiney** [MicrosoftDocs/azure-devops-docs#10274]
**This is my code in Build pipeline:**

- task: ExtractFiles@1
          displayName: 'Extract the ZIP files'
          inputs:
            archiveFilePatterns: 'pipeline-scan-LATEST.zip'
            cleanDestinationFolder: false

**I am getting below error:**
Archive:  /home/vsts/work/1/s/pipeline-scan-LATEST.zip
  inflating: /home/vsts/work/1/s/pipeline-scan.jar  
##[error]Extraction failed for file: /home/vsts/work/1/s/pipeline-scan-LATEST.zip 
code: 1 
stdout: Archive:  /home/vsts/work/1/s/pipeline-scan-LATEST.zip
  inflating: /home/vsts/work/1/s/pipeline-scan.jar  
 
stderr: replace /home/vsts/work/1/s/README.md? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
 
error: undefined;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05de2755-a21b-91b8-46b3-05bcb55a1eb6
* Version Independent ID: ababbcfb-e7d4-68f7-423f-1e68201247f4
* Content: [Extract Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/extract-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/extract-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/extract-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by TimShererWithAquent** [comment]
@sachiney Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
