### ISSUE TITLE
Example does not work properly as intended in a Java project

### ISSUE THREAD

**Issue by sijucm** [MicrosoftDocs/azure-devops-docs#10285]
[Enter feedback here]

Microsoft, the example of using the pom with azure-functions-maven-plugin creates weird obj/ and extensions.csproj files on my local machine when doing mvn package command.

And when executing in azure devops pipeline it fails because the func-core-tools cannot be downloaded. I wonder why Microsoft decided to combine the packaging function and the local:run and deploy functions into one plugin and demand I give the configuration to my resource-group, etc. I will deploy it myself with the AzureFunctionDeploy in Azure devops.

Why does Microsoft example pom here copy the local.settings.json in the function package? Isn't that a big horror move considering local secrets are kept in the local.settings.json?

Why does Microsoft think that it is cool to create an extensions.csproj file (and obj/ folder) in the root of my Java project when running mvn package? That's not cool.

Microsoft, please let me do the packaging of the function and without all the nice run-local and deploy functionality. Or at least let me know how to package without the azure-functions-maven-plugin and what to include in the package and I can do it myself. No, I do not want to include local.settings.json in the package (clue: it is named local.*.*). This example does not help.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e576b8-a378-a985-33cb-8adb9d7d7957
* Version Independent ID: d1b99713-8e01-23d9-47b7-1a9b5c98d5ca
* Content: [Build and deploy a Java web app to Azure Functions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/java-function?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/java-function.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/java-function.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@sijucm Thanks for your feedback. It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. Consider the following resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Also, you can ask product questions and offer suggestions to the dev team. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
