### ISSUE TITLE
how to change azure pipeline npm package version

### ISSUE THREAD

**Issue by tjinjin95** [MicrosoftDocs/azure-devops-docs#10304]
hi, I installed nodejs (10.3.0), the corresponding NPM version is 6.1.0, but the version I need is
**nodejs == 10.3.0
npm ==6.14.10**
how could I change the npm version?
code is shown below.
![image](https://user-images.githubusercontent.com/30750867/110205675-76f65400-7eb4-11eb-93ad-d7d4db17f87b.png)
I could not complete the npm version change by the code, could you help me with the issue? thanks

**Comment by TimShererWithAquent** [comment]
@tjinjin95 - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
