### ISSUE TITLE
Download only last published package files in specific version

### ISSUE THREAD

**Issue by Yozahim** [MicrosoftDocs/azure-devops-docs#10324]
[Enter feedback here]
Is there a way to download only last published package files in specific version? Currently im storing recent 25 snapshots of artifact, but I do want to download with DownloadPackage task only the last published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8354ee-807f-0c1f-8e5b-9303c4591c60
* Version Independent ID: 1fd42523-8504-76cf-deec-26c5fccd0109
* Content: [Download Package task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-package.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@Yozahim Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
