### ISSUE TITLE
What happens if we try to checkout 2 repositories with the same name?

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/azure-devops-docs#10328]
What happens if we need to checkout two repositories with the same name (for instance, once hosted on AzureDevOps and one on GitHub)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@fleed Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
