### ISSUE TITLE
Import of multiple 'Tags' using .csv

### ISSUE THREAD

**Issue by Vincenzo92DK** [MicrosoftDocs/azure-devops-docs#10334]
Is it possible to add multiple tags when using the .csv import for new work items?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Bulk import or update work items using CSV files - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@Vincenzo92DK Thanks for your question. It looks like about your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by KathrynEE** [comment]
@ Vincenzo92DK - Thank you for your inquiry. You should be able to import multiple tags at a time using .csv. The quickest way to check is to export a query that contains mutliple tags to see the proper structure.  I believe the syntax is to separate the tags with a semi colon - something like the following:  `"service;customer focus; web" `. I have to double check but once I do, I'll update the article.
