### ISSUE TITLE
Dependency tracker does not work for PBI to PBI dependency

### ISSUE THREAD

**Issue by roshair** [MicrosoftDocs/azure-devops-docs#10346]
When I have a Producer and Consumer dependency as PBI, the extension reports dependency is created but the dependency is not visible. 

I am able to reproduce this behavior and have attached screenshots below. This behavior is only with PBI and not with User Story. I know Dependency Tracker extension is not under official support but any thoughts or pointers on this please?

**Comment by TimShererWithAquent** [comment]
@roshair Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
