### ISSUE TITLE
Please update the dockerfile to be used with a newer base image of ubuntu

### ISSUE THREAD

**Issue by Bjego** [MicrosoftDocs/azure-devops-docs#10379]
Hey guys,
I'm updating my docker based agent right now. 
I'm stuck with updating to ubuntu:focal (20) as the library libicu is ubuntu 18 only. 
As I do not know what's the sense to add this library, I can't move to a newer base image.

Maybe this is interesting:
https://askubuntu.com/questions/1225781/unable-to-locate-package-libicu60

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@Bjego - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by azilber** [comment]
@Bjego Please see our updated container image:  https://hub.docker.com/r/consultent/azure-pipelines-vsts-agent
It's not official, but we've made it a drop-in replacement.
