### ISSUE TITLE
I am not able to use the new Sprint columns in queries,  you can create them and see them in the sprint view but that's it.  In boards you can create custom board columns and then use these in queries

### ISSUE THREAD

**Issue by AnnaHin1** [MicrosoftDocs/azure-devops-docs#10378]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
@AnnaHin1 -- thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing.

In the meantime, consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If you think this is an issue with the product itself, rather than an issue with the documentation, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21) to get it in front of the right people.

**Comment by AnnaHin1** [comment]
have logged as an enhancement  - closing issue
