### ISSUE TITLE
azureSubscription parameter description is unclear

### ISSUE THREAD

**Issue by jgn-epp** [MicrosoftDocs/azure-devops-docs#10397]
I think the description of the parameter `azureSubscription` is confusing and unclear about what it is exactly. It is being described as an ARM subscription, but then in the examples you are describing it as ARM service connections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#example)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by WilliamAntonRohm** [comment]
@jgn-epp -- Jeppe, thank you for your feedback.

@N-Usha -- Usha, please look into this issue.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines&viewFallbackFrom=azure-devops#example

Please check it out and let us know what you think. Thank you.
