### ISSUE TITLE
The prerequisites seem to be missing a requirement.

### ISSUE THREAD

**Issue by BrianMinister** [MicrosoftDocs/azure-devops-docs#10447]
Below is the published prerequisite. However, on of my Project Collection Admins does not have rights to edit cards, while others do. It looks like having a Visual Studio Pro or Enterprise lic is also required, but not stated. The user does have a basic lic, but that is also deficient. Either the documentation needs to be updated or the feature needs to be fixed.

> Prerequisites
> Prior to customizing a process, we recommend that you review Configure and customize Azure Boards, which provides guidance on how to customize Azure Boards to meet your business needs. For a description of the different backlogs and boards, see Tasks supported by Backlogs, Boards, Taskboards, and Plans.
> 
> You must have an organization created in Azure DevOps Services. If you haven't created one yet, do that now.
> To create, edit, and manage processes, you must be a member of the Project Collection Administrators group, or have the corresponding permissions Create process, Delete process, Edit process, or Delete a field from organization set to Allow. See Set permissions and access for work tracking, Customize an inherited process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5969861-6f6b-3da1-7eb3-2ee278110937
* Version Independent ID: ae1c687d-7c93-ba01-f63c-2f1df95ed873
* Content: [Create and manage an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/manage-process?view=azure-devops)
* Content Source: [docs/organizations/settings/work/manage-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/manage-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@BrianMinister - Thank you for your inquiry. The Prerequisites as stated should be sufficient. Users with Stakeholder or Basic access should be able to edit processes if they have sufficient permissions. Could you perform a trace on the person having problems? Trace the permissions at the organization level per instructions provided here: https://docs.microsoft.com/en-us/azure/devops/organizations/security/troubleshoot-permissions?view=azure-devops#trace-a-permission.  

If the trace doesn't indicate where the problem is, I suggest you reach out to our [Developer Community Page](https://developercommunity.visualstudio.com/search?space=21) and report the issue. This isn't a document issue.
