### ISSUE TITLE
Tags and (blank)

### ISSUE THREAD

**Issue by MREM66** [MicrosoftDocs/azure-devops-docs#10445]
I tried to check for work items without tags and it is not working! Is it only working for special DevOps version?
![Tags](https://user-images.githubusercontent.com/81681641/113122311-ca3d9700-9213-11eb-93ac-3aaa4f8f1bd1.png)

**Comment by TimShererWithAquent** [comment]
@MREM66 - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
