### ISSUE TITLE
Arguments description does not correspond to YAML snippet

### ISSUE THREAD

**Issue by edrandall** [MicrosoftDocs/azure-devops-docs#10483]
[Enter feedback here]
The parameter description is inconsistent with the commented YAML snippet.  Just 2 examples:

YAML:
    #connectionType: 'connectedServiceName' # Options: connectedServiceName, connectedServiceNameARM
Description:
   Connection type | Required. Select Azure Resource Manager to invoke an Azure managment API or Generic for all other APIs.

YAML:
    #waitForCompletion: 'false' # Options: true, false
Description:
    Wait for completion | Required. How the task reports completion. Can be API response  (the default) - completion is when the function returns success within  20 seconds and the success criteria evaluates to true, or Callback - the external service makes a callback to update the timeline record.

The page itself could benefit from some example pipeline code.  The GUI screenshots aren't worth anything (we don't use the GUI - I don't even know where it is!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/invoke-rest-api-v1?view=azure-pipelines&tabs=yaml

Please check it out and let us know what you think. Thank you.
