### ISSUE TITLE
Task group in pipeline not updating after modifying

### ISSUE THREAD

**Issue by Ant-cpu** [MicrosoftDocs/azure-devops-docs#10506]
Hello there,

We have task group

![image](https://user-images.githubusercontent.com/74964582/114203556-f3bb9880-9960-11eb-9e30-f935e8f10d83.png)

which was modified to

![image](https://user-images.githubusercontent.com/74964582/114203717-15b51b00-9961-11eb-9752-55e472abf9dc.png)

and additional step was added inside task group

![image](https://user-images.githubusercontent.com/74964582/114204406-d20ee100-9961-11eb-827b-580ef7ff0a40.png)

Expectation:

Task group: ct.experimental should be simultaneously updated on all pipelines which used.

Result:

Old task on all pipelines

Right now we deleting old task and adding new one but old one shouldn't exist.

**Comment by TimShererWithAquent** [comment]
@Ant-cpu - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If there is a documentation issue around your question, at-mention me and we can look into it further.
