### ISSUE TITLE
AssignedTo is missing in BugTrend

### ISSUE THREAD

**Issue by Ahila-Thanarasu** [MicrosoftDocs/azure-devops-docs#10510]
In this page it was mentioned that, AssignedTo can be expanded. But there is nothing in query which returns AssignedTo.UserName. So whether AssignedTo can be expanded for WorkItemsSnapShot or not. Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362ba191-c87a-28aa-329e-cf3e5261833a
* Version Independent ID: a4023b7f-8eef-077f-f5e0-beaf5110ca50
* Content: [Bug trends sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-bugtrend?view=azure-devops&tabs=powerbi)
* Content Source: [docs/report/powerbi/sample-boards-bugtrend.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-boards-bugtrend.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@Ahila-Thanarasu - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
