### ISSUE TITLE
Test Runner MacOs Version

### ISSUE THREAD

**Issue by sammiekiogora** [MicrosoftDocs/azure-devops-docs#10526]
Is there a MacOs version of Test Runner?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20ab28c-41a4-9fde-b8fb-ab814e0295b3
* Version Independent ID: a479d74e-9b8b-6bb0-407a-1ba07edd1b9b
* Content: [Run manual tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-manual-tests?view=azure-devops#run-tests-for-desktop-apps)
* Content Source: [docs/test/run-manual-tests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/run-manual-tests.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@sammiekiogora - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
