### ISSUE TITLE
Runtime variables are not prompting the options when individually triggered by CI, whereas they give an option to change the value when I run manually

### ISSUE THREAD

**Issue by akhila31** [MicrosoftDocs/azure-devops-docs#10540]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by TimShererWithAquent** [comment]
@akhila31 - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing, or provide more context around the general task.

Also, if this is an issue with the product itself, rather than an issue with the documentation, you might want to look [here or create a bug here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by akhila31** [comment]
Hi @TimShererWithAquent , when I use below example mentioned in this page it works fine. But when the trigger is changed from none to a branch name, it just takes the default value, what if I want to choose any other option for the parameter "image"? can you please help me understand how can I work with below runtime parameters when the trigger is not "none".

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-16.04
  - macOS-latest
  - macOS-10.14

trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}

**Comment by TimShererWithAquent** [comment]
@akhila31 - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
