### ISSUE TITLE
Inputs name used for YAML example should be consistent with IntelliSense provided in vscode

### ISSUE THREAD

**Issue by ggirard07** [MicrosoftDocs/azure-devops-docs#10541]
Right now there is a lot of documentation examples about pipeline definition in YAML which seem to rely on input names.
Problem is this is not what we are facing as developpers because IntelliSense in pipeline extension for vscode relies on aliases instead. Same problem with pipeline editor provided in web interface, which also uses aliases. Documentation seem to be the only one using input name instead.

Here is an example about `DownloadPipelineArtifact`, where input names for example are `source` and `path` ([as in doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)) while intellisense and web editor use `buildType` and `targetPath` instead from input aliases:
![image](https://user-images.githubusercontent.com/2625886/114939267-31f80280-9e0e-11eb-8c0e-edca7d5e8fd4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@vijayma This suggestion seems to be more general than just the article referenced.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users).

The YAML block and the task input table all use the intellisense name as the primary name for the input.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-pipeline-artifact-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
