### ISSUE TITLE
Linking work items through # not working

### ISSUE THREAD

**Issue by mason3k** [MicrosoftDocs/azure-devops-docs#10546]
I have tried to enter '#' and the ID of the work item in a PR description, but it doesn't work. It just makes the ID a header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22780209-b809-62af-1d6e-ed4c91db867a
* Version Independent ID: 1d6afe6e-6420-2395-0e0b-05902572f7ab
* Content: [Link work items to other objects - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/add-links-to-work-items?view=azure-devops)
* Content Source: [docs/notifications/add-links-to-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/add-links-to-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@mason3k - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

(And just to try the "Have you turned it off and on again" question, you're not putting a space after the "#" character, are you?)
