### ISSUE TITLE
json schema validation is not correct

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/azure-devops-docs#10578]
The schema validation shows "Fixed " -- with the space after the word as valid.

![image](https://user-images.githubusercontent.com/1080406/115730075-fbf9d780-a353-11eb-82ae-0e08c706ab94.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0de805e4-ba04-930c-122e-2141242bb621
* Version Independent ID: 6e9ac100-aca4-4913-5c0d-8ea8c33ac49c
* Content: [Query Azure Monitor Alerts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-monitor?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-monitor.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/azure-monitor.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@RoopeshNair  There is a space after the word "Fired" in the yaml on the linked page. I don't know if that's the source of the value not accepted message.

**Comment by steved0x** [comment]
I fixed this in https://github.com/microsoft/azure-pipelines-tasks/pull/15311 and once it is merged, this fix will filter down. In the meantime, the pipeline should still validate and run. If you are using VS Code, you can save down the schema and remove the space, and point your VS Code at the updated schema to resolve the issue until the fix is published. Follow the steps here: https://github.com/Microsoft/azure-pipelines-vscode and when you save your version of schema, do a search for `"fired "` (including the quotes and it should take you to this line: `"enum": [ "Fired ", "Resolved" ]`. You can remove the space there and it should fix the local validation issue you are seeing.
