### ISSUE TITLE
Manage notes

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-devops-docs#10576]
What does the Manage notes permission entail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@cveld - Thanks for your question. It looks like you're looking for information about the product, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by cveld** [comment]
@TimShererWithAquent My point is, I am inviting you to write something about all the permissions. I expect to find this in the documentation.

**Comment by chcomley** [comment]
Hi @cveld, Sorry for the delay here. Wiki security is equivalent to [Git Repository Security](https://git-scm.com/docs/git-notes).
Thanks for reaching out!
