### ISSUE TITLE
AzureMonitor@1 drops the resource group from the REST query

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/azure-devops-docs#10582]
The REST call does not work - it is dropping the Resource Group in the Resource URI..

And how does it even work with "scheduled queries" ? that have a proper REST call of `alertRule=/subscriptions/xxxx-1e94-447b-bba2-xxxx/resourceGroups/spz-hot-path-dv-01/providers/microsoft.insights/scheduledqueryrules/hotpath-deploy-heartbeat-fail"`

![image](https://user-images.githubusercontent.com/1080406/115755801-b9dc9000-a36b-11eb-83d0-981b7f5abc3c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0de805e4-ba04-930c-122e-2141242bb621
* Version Independent ID: 6e9ac100-aca4-4913-5c0d-8ea8c33ac49c
* Content: [Query Azure Monitor Alerts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-monitor?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-monitor.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/azure-monitor.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@cicorias - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
