### ISSUE TITLE
Mandatory codeCoverageTool parameter is missing from this documentaton

### ISSUE THREAD

**Issue by acrov** [MicrosoftDocs/azure-devops-docs#10580]
The mandatory codeCoverageTool parameter is missing from this documentation and from the example YAML snippet.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@shashban "codeCoverageTool" doesn't appear in the snippet or in the table below. Has that param been removed?

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
