### ISSUE TITLE
How do you inject a variable group?

### ISSUE THREAD

**Issue by JohnGalt1717** [MicrosoftDocs/azure-devops-docs#10601]
Variable groups look great! But I can't see how in the documentation to inject the variable group into the yaml outside of the yaml. I can do this with variables themselves but not variable groups. 

The reason I want to do this is so that I can have one set of yaml across all environments and just change my variable group per environment and have it inject.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@JohnGalt1717 Hi James - Thanks for your question. Consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Usually, we close these support requests because we deal with the documentation. I'm going to hold this one open for a while -

For this article, did you encounter a specific problem in trying to work with the variable groups? Or was there someplace in the article where you expected to see how to do this? If so, I'll change this over to a doc issue.

**Comment by JohnGalt1717** [comment]
@TimShererWithAquent The issue is that the documentation doesn't explain how to do what I've outlined which I presume is possible. Hence why this is for documentation to explain this use case which will come up.

**Comment by lpacis** [comment]
@JohnGalt1717 You can link a variable group to a pipeline, and reference the variables from that group without explicitly adding them in the yaml. 

For instance if your VG had a var called WebApp and that VG was linked to your pipeline, $(WebApp) will resolve to the definition in your VG, even though your yaml doesn't have 
`variables:
- group: my-variable-group`

The docs for adding and using variable groups does mention this - https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=classic#use-a-variable-group
