### ISSUE TITLE
Install latest in major version not working for 5.x

### ISSUE THREAD

**Issue by vanderborghta** [MicrosoftDocs/azure-devops-docs#10607]
Based on the documentation, it should be possible to use UseDotNet@2 with "version: 5.x". However, if I do that on a windows-latest hosted agent, the following error ocurs:
![image](https://user-images.githubusercontent.com/11502775/116264146-593dc080-a77a-11eb-9b29-8031767bcae5.png)

It works fine when configuring on latest in major and minor (e.g. version: 5.0.x)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9660c58-3366-f1be-8380-d6cf1d3c0150
* Version Independent ID: 226a4fd8-bce8-3333-d8d6-7af933c7b060
* Content: [Use .NET Core task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/dotnet-core-tool-installer.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/dotnet-core-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by TimShererWithAquent** [comment]
@vanderborghta Thanks for your question. It looks like you're working through an issue with your scenario, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
