### ISSUE TITLE
can I use a global settings.xml for all build pipelines?

### ISSUE THREAD

**Issue by dreaminzero-cell** [MicrosoftDocs/azure-devops-docs#10612]
our pipelines share the same settings.xml configuration, it seemingly we have to upload the settings.xml to every repository, if it has any update, we need to refresh every repository.... It looks so hard.

So do we have any solution to workaround this?

**Comment by dreaminzero-cell** [comment]
maybe like this: --settings=$(mavenSettings.secureFilePath)
https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops
https://github.com/SI-Gen/jportal2/blob/8812f30e9ddb2f4f55514b51dda8ce7e8f392122/azure/snapshot-pipeline.yml#L24

but it still have some drawback... I have to configure it in every pipeline. If I have a global flag to tell all maven pipelines, you all should use the specified settings.xml, it looks perfect?

**Comment by TimShererWithAquent** [comment]
@dreaminzero-cell - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Discussions on Stack Overflow can be helpful in getting the configuration you want.
