### ISSUE TITLE
Display Scrollbar in Markdown Widget if needed

### ISSUE THREAD

**Issue by DaveSlinn** [MicrosoftDocs/azure-devops-docs#10620]
We have a markdown widget on our dashboard, but the content extends past the defined widget size.  I would have assumed that a scrollbar would appear when this happens, but instead it's simply cutting the overflow off.

![image](https://user-images.githubusercontent.com/18301427/116505484-40b3d000-a878-11eb-8032-d553d2bc8f05.png)

Is there an option to display a scrollbar on the widget?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21c46ee-e19c-9dc4-11c2-8749c6576925
* Version Independent ID: 09ad6f7f-5169-f1b5-4f71-410bd85c62df
* Content: [Add markdown content to a team dashboard - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/add-markdown-to-dashboard?view=azure-devops)
* Content Source: [docs/report/dashboards/add-markdown-to-dashboard.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/dashboards/add-markdown-to-dashboard.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@DaveSlinn Consider these resources to address your question:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If this is a feature that should be added to the product, create a dev issue. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
