### ISSUE TITLE
화면이 이상해요

### ISSUE THREAD

**Issue by KimHeeYong** [MicrosoftDocs/azure-devops-docs#10624]
[여기에 피드백 입력]

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [파이프라인에서 여러 리포지토리 체크 아웃 - Azure Pipelines](https://docs.microsoft.com/ko-kr/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs-pr.ko-KR/blob/live/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
According to an online translator, the title is "This screen is weird."

And it is. 

The "table" after the note in this section of the US version looks fine:

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#specify-multiple-repositories

The corresponding "table" in the Korean version is broken: 

https://docs.microsoft.com/ko-kr/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#specify-multiple-repositories

Table is in scare quotes above because these are rows and columns, not the plain markdown tables. This looks like a localization issue.
