### ISSUE TITLE
App Bundle Signing

### ISSUE THREAD

**Issue by sanjay3290** [MicrosoftDocs/azure-devops-docs#10635]
Hello there, can we sign and android app bundle with this ?

**Comment by TimShererWithAquent** [comment]
@sanjay3290 Thanks for your question. It looks like you're asking about the capabilities of the product itself, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
