### ISSUE TITLE
Maximum number of agent pools

### ISSUE THREAD

**Issue by vinsoyo** [MicrosoftDocs/azure-devops-docs#10648]
[Enter feedback here]

How many agent pools can exist in an organization ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f63ad-e95d-0105-c73a-de6e904edc09
* Version Independent ID: c97bfa1a-5aca-80a9-d9aa-8cca9987ad82
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@vinsoyo Since this is a question about the product itself, consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
