### ISSUE TITLE
How to get comment lists for workitems with ODataFeed?

### ISSUE THREAD

**Issue by v-bafa** [MicrosoftDocs/azure-devops-docs#10667]
In .Net, we could get the history comments of workitems with field "System.History". Would like to know how to get same data via ODataFeed? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0406dd-f852-001f-eba5-a665ed4ef7a0
* Version Independent ID: 51657f61-8b0c-3132-59d4-7d876b08af6d
* Content: [Data model for Analytics - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/data-model-analytics-service?view=azure-devops#entities)
* Content Source: [docs/report/extend-analytics/data-model-analytics-service.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/data-model-analytics-service.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@v-bafa Thanks for your question. It looks like you're looking for product information, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
