### ISSUE TITLE
Duplication, and gaps

### ISSUE THREAD

**Issue by ehavelaarsnz** [MicrosoftDocs/azure-devops-docs#10694]
Why are there duplicate descriptions - e.g. for 'Parent website name'
Also, it would be great if there was documentation for every YAML key in the example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@ehavelaarsnz  I think the duplicate instances refer to different lines in the example:

parentWebsiteNameForVD = Parent website name
parentWebsiteNameForApplication = Parent website name

That's not what I'd expect from a table like this, though. I'd expect to see the argument name.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/iisweb-app-management-on-machine-group-v0?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
