### ISSUE TITLE
How can we access the response of call and pass it to the next job i pipeline?

### ISSUE THREAD

**Issue by LadyJaz** [MicrosoftDocs/azure-devops-docs#10788]
How can we access the response of call and pass it to the next job i pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@LadyJaz - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
