### ISSUE TITLE
VSTS_AGENT_INPUT_PROXYURL does not take effect

### ISSUE THREAD

**Issue by wasytb72** [MicrosoftDocs/azure-devops-docs#10789]
After applying the variable, the agent does not use the proxy to browse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops&source=docs#customizing-pipeline-agent-configuration)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@wasytb72 Thanks for your question. This looks like a support question, rather than an issue with the documentation. We might also need more information to address your issue.

Consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If this turns out to be an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by wasytb72** [comment]
Thanks Tim,

I will close this issue and I will submit a bug then. Thank you.
