### ISSUE TITLE
PAT not working on Ubuntu

### ISSUE THREAD

**Issue by Iyappanj** [MicrosoftDocs/azure-devops-docs#10805]
I have created a PAT to use it on bash script. When I try to clone using below method, It is working on Windows but whereas in Ubuntu it is again asking for username and password.

git clone https://PAT@"URL_of _the_repo"

same command without any changes works in windows but not in ubuntu.

Git version in ubuntu - 2.17.1

**Comment by TimShererWithAquent** [comment]
Hi @Iyappanj 

Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing.

**Comment by Iyappanj** [comment]
@TimShererWithAquent I am not referencing any article. I just want to git pull a azure devops repo without any user interaction. This command - git clone https://PAT@"URL_of _the_repo" is working on Windows(git version - 2.31.1.windows.1)  but not on Ubuntu(git version - 2.17.1)

**Comment by Iyappanj** [comment]
Sorry @TimShererWithAquent , I believe on the windows it is working because of SSO. I want to know why this kind of approach - git clone https://PAT@"URL_of _the_repo  is not working on ubuntu ? It is asking for password in the prompt considering the token as username.

**Comment by Iyappanj** [comment]
To provide more information, This article - https://seb-nyberg.medium.com/accessing-git-repositories-on-azure-devops-using-personal-access-tokens-on-linux-7fa7495bf1e is working for git version - 2.17.1 but not for 2.7.4

**Comment by Iyappanj** [comment]
@TimShererWithAquent @steved0x Any update on this ?

**Comment by TimShererWithAquent** [comment]
@Iyappanj - Please be aware that this isn't a support channel. We address issues around the documentation, which is why I'm trying to find a devops article relevant to your issue. If this is a gap for us, we can try to figure out how to address it. 

While we research this, consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If you think the different behavior between different versions is a bug, to make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).
