### ISSUE TITLE
 Broken Table (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-devops-docs#10800]
Broken Table (ja-jp)
ja-jp:"https://docs.microsoft.com/ja-jp/azure/devops/repos/git/command-prompt?view=azure-devops"
![command-prompt_j](https://user-images.githubusercontent.com/40815708/119435400-fd546080-bd54-11eb-9989-fafd0515be39.png)

en-us:"https://docs.microsoft.com/en-us/azure/devops/repos/git/command-prompt?view=azure-devops"
![command-prompt_e](https://user-images.githubusercontent.com/40815708/119435405-ff1e2400-bd54-11eb-8ff9-d08a9c8d3d01.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29569b47-6acb-89e1-0c21-0dc9f3b6a745
* Version Independent ID: 743535b1-5a99-9ba2-22e8-23aae5367267
* Content: [Git command reference - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/command-prompt?view=azure-devops)
* Content Source: [docs/repos/git/command-prompt.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/command-prompt.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
The table is actually made of [columns](https://review.docs.microsoft.com/en-us/help/contribute/markdown-reference?branch=master#columns). Each row in the table is separated by a line (---). For some of the rows (not all), this is making the row designator be interpreted as a header, which breaks the display of the column. 

I'm not clear on why the English version works, while the Japanese version doesn't. I'm not going to try to reformat the content, since I don't have a ready way to know whether it would fix the Japanese version. 

One change that might fix it would be to remove the --- separators. Or maybe we need to consider this as a localization issue and look for a solution there.
