### ISSUE TITLE
cannot git pull or push from wsl2 environment

### ISSUE THREAD

**Issue by SoulRaider** [MicrosoftDocs/azure-devops-docs#10802]
cannot git pull/push from wsl2 environement but can do it in window environment in the same machine

![image](https://user-images.githubusercontent.com/11997237/119435741-59b38200-bd4d-11eb-8ae2-958280ca037e.png)
![image](https://user-images.githubusercontent.com/11997237/119435815-8798c680-bd4d-11eb-939b-7803c52aea8d.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e683a59-3ca8-f8c1-88d2-e535d5138201
* Version Independent ID: a460bd9b-c47f-eb9a-5840-9e87c7ecbcd6
* Content: [Announcement of upcoming change to Azure DevOps organizations located in East Asia - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/migrate/migration?view=azure-devops)
* Content Source: [docs/migrate/migration.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/migrate/migration.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @rajr
* Microsoft Alias: **rajr**

**Comment by TimShererWithAquent** [comment]
@SoulRaider - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

This might be a product bug. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
