### ISSUE TITLE
Default behavior and default value of 'overwriteBehavior' doesn't match

### ISSUE THREAD

**Issue by Kassoul** [MicrosoftDocs/azure-devops-docs#10821]
It looks like a mistake, doesn't it?

![image](https://user-images.githubusercontent.com/5912810/119668102-28af7c00-be37-11eb-8c12-ec79b64347b1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7068e469-201e-c820-4d27-b798ea799b70
* Version Independent ID: d6bb717a-1c44-43a1-c7a5-9616b257c0e0
* Content: [Service Fabric Application Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/service-fabric-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/service-fabric-deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/service-fabric-deploy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/service-fabric-deploy-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
