### ISSUE TITLE
Apparently incorrect default of pathToPublish

### ISSUE THREAD

**Issue by ddeml** [MicrosoftDocs/azure-devops-docs#10827]
The documentation seems to be incorrect: pathToPublish appears to default to '$(Build.BinariesDirectory)' and not '$(Build.ArtifactStagingDirectory)'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
The source code for the task shows `$(Build.ArtifactStagingDirectory)` and whne I add it using the task assistant, it also shows that value as the default.

https://github.com/microsoft/azure-pipelines-tasks/blob/318f0bf847bd04aefd5173df939a339552cf108d/Tasks/PublishBuildArtifactsV1/task.json#L32

![image](https://user-images.githubusercontent.com/1580889/207157143-b1577b4b-c805-4089-8964-518e16f848d7.png)

Please file a bug on the task repo here with more details of your scenario. 

https://github.com/microsoft/azure-pipelines-tasks/issues

Once that default value is fixed in the task source, it will automatically show up in our new task reference, which is generated from that source.

Thank you.
