### ISSUE TITLE
VSTest and MSBuild: document enableDefaultLogger parameter

### ISSUE THREAD

**Issue by rainersigwald** [MicrosoftDocs/azure-devops-docs#10839]
https://github.com/microsoft/azure-pipelines-tasks/pull/14331 added an `enableDefaultLogger` parameter to the VSBuild tasks, but it's not mentioned here.

cc @anatolybolshakov who made the change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vsbuild-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
