### ISSUE TITLE
AzureRmWebAppDeployment@4 Output Variables Documentation

### ISSUE THREAD

**Issue by ShawnNeckelmann** [MicrosoftDocs/azure-devops-docs#10843]
Could more documentation be provided for syntax/capturing the output variables?

Ex: I'd like to echo the hosted url.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c94df7-9de9-ea1a-8b77-d1e6023694dc
* Version Independent ID: a525989e-2e0a-0399-556e-9011ee95da4e
* Content: [Azure App Service Deploy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4?view=azure-pipelines#output-variables

Please check it out and let us know what you think. Thank you.
