### ISSUE TITLE
Not available in this source

### ISSUE THREAD

**Issue by pradeepradyumna** [MicrosoftDocs/azure-devops-docs#10850]
I'm unable to sync the packages. Even after connecting to the feed, I still get a warning icon on the packages. And in Nuget Package Manger console I'm getting "Not available in this source"

Just wanted to check, in the Feeds in my Azure account I see this.

> No packages have been promoted to this release view
> Look for the Promote button on any package.
> Learn more about views
> 

Is this what caused the nugget packages to not update in my solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5b066ca-c13e-9f25-3add-844012d105f1
* Version Independent ID: 47ac81a1-d4a7-8d74-b59a-2cf143a9684c
* Content: [Get started with NuGet packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops&tabs=windows#prerequisites)
* Content Source: [docs/artifacts/get-started-nuget.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/get-started-nuget.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@pradeepradyumna - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
