### ISSUE TITLE
Powershell script not working 

### ISSUE THREAD

**Issue by alexibraimov** [MicrosoftDocs/azure-devops-docs#10866]
[Enter feedback here]

Can I run a powershell script?

The config looks like this:

- task: SSH@0
  displayName: 'Run shell script on remote machine'
  inputs:
    sshEndpoint: 'Dev SSH service'
    failOnStdErr: false
    runOptions: script
    scriptPath: '$(Build.SourcesDirectory)\Pipelines\Scenarios\deployWebSite.ps1'
    readyTimeout: '20000'

This task does not work

##[error]At line:1 char:14
##[error]+ tr -d '\015' <./deployWebSite.ps1> ./deployWebSite.ps1._unix
##[error]+              ~
The '<' operator is reserved for future use.
##[error]    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
##[error]    + FullyQualifiedErrorId : RedirectionNotSupported
##[error]Error: Command tr -d '\015' <./deployWebSite.ps1> ./deployWebSite.ps1._unix exited with code 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad03c70-4014-135f-ffd3-245c08b3ce32
* Version Independent ID: 42a84b54-9ab7-89b2-00b1-efcfc6ba6eef
* Content: [SSH Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/ssh.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/ssh.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by AlexanderIbraimov** [comment]
My research is not helping.

**Comment by TimShererWithAquent** [comment]
@AlexanderIbraimov - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

It looks like the angled bracket is breaking it - the same error I get when I forget to use "-lt" in a comparison. Somebody on Stack Overflow probably knows how to troubleshoot this.

**Comment by AlexanderIbraimov** [comment]
I think this is a documentation issue. The documentation does not describe how you can run a PowerShell script

**Comment by AlexanderIbraimov** [comment]
I created a question on [https://stackoverflow.com/questions/67831616/running-a-powershell-script-on-a-remote-machine-doesnt-work-in-azure-devops](Stack Overflow). 
But I think the documentation is missing examples with powershell.

**Comment by alexibraimov** [comment]
-
