### ISSUE TITLE
Can carry over of velocity points in forecasting logic be turned off?

### ISSUE THREAD

**Issue by LisaAkers** [MicrosoftDocs/azure-devops-docs#10881]
I was confused by the results of forecasting, but see it is because the logic carries over velocity points.  Can this be turned off?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e47f8c5-7b66-ec49-a03c-1240ad9fe4f0
* Version Independent ID: 21551259-e300-329a-3ce1-95dbb4730bc5
* Content: [Forecasting - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/forecast?view=azure-devops)
* Content Source: [docs/boards/sprints/forecast.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/sprints/forecast.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@LisaAkers Thanks for your question. This looks like a question about the product configuration, rather than a documentation issue. Consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

However, we may need to clarify the docs, so I'll keep this issue open.

**Comment by KathrynEE** [comment]
@LisaAkers - Thank you for your inquiry. There is no way to change the logic flow of the forecast tool. It works as documented.
