### ISSUE TITLE
Variable Groups multiline string

### ISSUE THREAD

**Issue by sabman3** [MicrosoftDocs/azure-devops-docs#10890]
Is there a way to use a multiline string in a Variable Group variable and pass that to the notifyUsers argument of Manual Validation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by TimShererWithAquent** [comment]
@sabman3 - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
