### ISSUE TITLE
Helm deploy documentation missing useClusterAdmin option

### ISSUE THREAD

**Issue by yoadfe** [MicrosoftDocs/azure-devops-docs#10904]
helm deploy 0 task documentation (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops) missing useClusterAdmin option as can be seen here: https://github.com/microsoft/azure-pipelines-tasks/pull/10867 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **atulmal**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
