### ISSUE TITLE
Removing Testers of suite erases Outcomes

### ISSUE THREAD

**Issue by MarniFreese** [MicrosoftDocs/azure-devops-docs#10917]
When removing testers for a suite, it sometimes erases the outcome of the test cases in that suite. How can I remove only certain testers, without resetting the outcomes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985ecee3-e347-43bb-5ed2-08ce3aee7621
* Version Independent ID: fdf465fc-a9e1-0198-2e8c-e859c74252b3
* Content: [FAQs and problem solutions - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops)
* Content Source: [docs/test/reference-qa.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/reference-qa.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@MarniFreese - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If this issue needs to be addressed in the article, we can reopen.
