### ISSUE TITLE
Export a Process - Question

### ISSUE THREAD

**Issue by jonmikeli** [MicrosoftDocs/azure-devops-docs#10938]
Hi,

Is there a way to export a process (with all the WI definitions)?
I have already done this with Process Templates but I am not seeing anything possible at Azure DevOps right now.

I have tried this in case it could help in a way or another but no success:
https://docs.microsoft.com/en-us/rest/api/azure/devops/processadmin/processes/export%20process%20template?view=azure-devops-rest-6.1

By the way, this URL is broken (HTTP 404):
https://docs.microsoft.com/en-us/rest/api/azure/devops/processadmin/Processes.yml?view=azure-devops-rest-6.1

I do not see anything either at AZ CLI level:
https://docs.microsoft.com/en-us/cli/azure/devops?view=azure-cli-latest

Kind regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5969861-6f6b-3da1-7eb3-2ee278110937
* Version Independent ID: ae1c687d-7c93-ba01-f63c-2f1df95ed873
* Content: [Create and manage an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/manage-process?view=azure-devops)
* Content Source: [docs/organizations/settings/work/manage-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/work/manage-process.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@jonmikeli - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Thanks for finding the missing page. That lives in another repo - please file an issue here: https://docs.microsoft.com/en-us/rest/api/azure/devops/

I can follow the azure cli link. Maybe you had a connection problem?

**Comment by jonmikeli** [comment]
Hi Tim,

Thanks for your feedback.
I already had a look at the different provided links but I had not found the answers I was looking for.
It seems that exporting a custom process (inherited, not XML) is not possible and I wanted to double-check that.

I understand that this is not the right place to ask the question. I apologize.

**Comment by KathrynEE** [comment]
@jonmikeli - You may be able to export the process from Azure DevOps Services using https://github.com/microsoft/process-migrator.  There are no other options to export Inherited processes. If you run into issues using process-migrator, try reaching out to the Developer Community.
