### ISSUE TITLE
Query configuration question

### ISSUE THREAD

**Issue by sdamodar** [MicrosoftDocs/azure-devops-docs#10953]
In my case, ADO items are organized in a multilevel parent-child hierarchy.  

How do I configure the query such that I can filter mid-level items and show the output as:
parent item
  mid-level item (apply filter based on Tags)
    child item

**Comment by TimShererWithAquent** [comment]
@sdamodar - Thanks for your feedback; we appreciate it. To make sure we have all the information needed to address your issue, please let us know which article you’re referencing.

If your issue is a general one, not about a particular page, consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
