### ISSUE TITLE
No documentation on "uses:"

### ISSUE THREAD

**Issue by quasarea** [MicrosoftDocs/azure-devops-docs#10951]
Would be great to have some documentation on "uses:" definition, with example as I tried to use it and only got errors regarding type I'm passing:

```
uses: 
    repositories: a b c
```

I also found this example at https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#limit-job-authorization-scope-to-referenced-azure-devops-repositories which is totally different as does not groups uses subgroups:

```
steps:
- checkout: git://FabrikamFiber/FabrikamTools # Azure Repos Git repository in the same organization
- script: Do something with that repo

# Or you can reference it with a uses statement in the job
uses:
- FabrikamTools # Repository reference to FabrikamTools
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema&source=docs)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@quasarea Sorry for the delay on this. There is some documentation here in the YAML schema section for Job:

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#job

That example in the Azure Repos Git section is wrong and I will get that fixed up, the correct syntax is in the Job section in the YAML schema, each one is a list of one ore more repos or pools:

```
jobs:
- job: string  # name of the job (A-Z, a-z, 0-9, and underscore)
  displayName: string  # friendly name to display in the UI
.
.
.
  uses: # Any resources (repos or pools) required by this job that are not already referenced
    repositories: [ string ] # Repository references to Azure Git repositories
    pools: [ string ] # Pool names, typically when using a matrix strategy for the job
```

So it would be like this for your example:
```
jobs:
- job: string  # name of the job (A-Z, a-z, 0-9, and underscore)
  displayName: string  # friendly name to display in the UI
.
.
.
  uses: # Any resources (repos or pools) required by this job that are not already referenced
    repositories: 
    - a
    - b
    - c
```

I'll get this fixed up (and I will come back and update my example if I have got the spacing wrong since I am just typing into this box)

Thank you for letting us know and sorry that you ran into trouble
