### ISSUE TITLE
Assign multiple testers to single test case?

### ISSUE THREAD

**Issue by barrydurcan** [MicrosoftDocs/azure-devops-docs#10987]
What about where you want to assign multiple testers to a single test case ? The only way I can see to do this is assigning users to the entire suite and then deleting test points as they're not needed - very manual process - there has to be a better solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf72265-156c-de8c-d729-ba7b3b90193d
* Version Independent ID: 1a0c7272-6d36-6036-06cf-5801b55e2f70
* Content: [Create manual tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-test-cases?view=azure-devops)
* Content Source: [docs/test/create-test-cases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/create-test-cases.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@barrydurcan - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

You might want to make a feature request - the product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

If there are documentation fixes for us to make, we can re-open this item.
