### ISSUE TITLE
2 GitHub repos into 1 DevOps repo?

### ISSUE THREAD

**Issue by diberry** [MicrosoftDocs/azure-devops-docs#10999]
If I want to consolidate 2 GitHub repos and keep history, into a single DevOps repo - how do I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a9c9ac-02c4-839a-555b-8d9d22d08fab
* Version Independent ID: 259fcc03-e73d-2004-dfa6-067728a85981
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/import-git-repository.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@diberry - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If we should include this in the docs, we can re-open this issue.
