### ISSUE TITLE
Add detailes about zipAfterPublish

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/azure-devops-docs#11015]
I think the documentation lacks the information about the `zipAfterPublish` option.

I used it, but I don't know the zip file name, I can't take it and upload it (in the documentation they are always using the containing folder, but not the zip file itself, as far as I understand).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops-2020&tabs=dotnetfive)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
A search turned up one other article that mentions _zipAfterPublish_, which has a one-line explanation. I'm not sure that one addresses the question here. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

**Comment by baruchiro** [comment]
No, it didn't help.

> If `true`, folder created by the publish command will be zipped and deleted.

Let's say I'm publishing with `-o ./publishToHere`, and I set the `zipAfterPublish` to `true`.

Do you know where the zip will be and what will be its name?

(I think the result is `./publishToHere/publishToHere.zip` or `./publishToHere/projectName.zip`, depends on the second checkbox. It is not clear at all, I needed to print CLI commands inside the build to look for the zip.)

**Comment by TimShererWithAquent** [comment]
@baruchiro Yeah, I didn't think it really addressed your question. 

You might reach out to the dev community to see if this a known issue. [Submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

Also, here's some general resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
