### ISSUE TITLE
Stop & start the Linux agent will return "Cannot configure the agent because it is already configured"

### ISSUE THREAD

**Issue by jsancho** [MicrosoftDocs/azure-devops-docs#11010]
[Enter feedback here]
I've successfully configured the Azure Devops agent with a self-hosted container.

During the initial boot of the container everything works as expected. However, if the container is stopped and started again, the following error will show

>> Cannot configure the agent because it is already configured. To reconfigure the agent, run 'config.cmd remove or './config.sh remove' first.

I modified start.sh to run `config.sh remove` ahead of the default configuration command. but that makes the agent request the config parameters from standard input instead of using the docker ENV variables.

I'd say that start.sh script could be made to _**not run**_ the config command if already found locally.
That would allow us to stop and restart containers (like it could happen during a host reboot)

![image](https://user-images.githubusercontent.com/1547884/123613716-f7461980-d803-11eb-927a-ed0b13a83286.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@jsancho - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Also, you might search for the error at the [developer community](https://developercommunity.visualstudio.com/search?space=21).

If there are doc changes we need to make around this, we can reopen this issue.

**Comment by thombrink** [comment]
I'm having the same problem. The scripts from the doc's are working perfectly, but after a reboot it tries to run the config setup again and fails.

**Comment by TimShererWithAquent** [comment]
This could be a product issue. Consider [filing a bug here](https://developercommunity.visualstudio.com/search?space=21).
