### ISSUE TITLE
How to delete older task extension  + publish to org

### ISSUE THREAD

**Issue by venkat1017** [MicrosoftDocs/azure-devops-docs#11043]
We one extension with 5 different tasks and multiple versions of it. We want to completely remove the 2 extension task. we tried cleaning up the folder + the vss-extension.json and redeployed the extension. I can see the deployment successful but I don't see the changes on the organization the tasks are used. any idea how to achieve this. 

one way is to uninstall the extension from organization and reinstall it from the marketplace. Do we have a simpler way to achieve this ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650e14dd-88eb-e6ef-2afd-5357c9ccc62d
* Version Independent ID: 43864fb1-e3bf-e9b2-123e-5ea343ec4b25
* Content: [Uninstall disable extensions in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/marketplace/uninstall-disable-extensions?view=azure-devops&tabs=browser)
* Content Source: [docs/marketplace/uninstall-disable-extensions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/marketplace/uninstall-disable-extensions.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@venkat1017 - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
