### ISSUE TITLE
Why an Environment can only have resources like Kubernetes or a Virtual Machine?

### ISSUE THREAD

**Issue by MACEL94** [MicrosoftDocs/azure-devops-docs#11049]
Hi

what if my env is only a single web app or multiple web apps?
Shouldn't i write my pipeline as code(not only build but also release stages)?

What if my Staging env was composed by multiple web apps?
It would be nice to have full history divided by resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@MACEL94 It looks like you have a question or suggestion for the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21). 

If there's changes we need to make for the article, we can reopen this issue.

**Comment by MACEL94** [comment]
Ok , thank you
