### ISSUE TITLE
Option value casing mismatch

### ISSUE THREAD

**Issue by MathieuDSTP** [MicrosoftDocs/azure-devops-docs#11099]
![image](https://user-images.githubusercontent.com/483333/126339341-9e02eacb-e4e6-4863-9e85-da823580675b.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by pulkitaggarwl** [comment]
@aaronhallberg can you please have someone look at the issue.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
