### ISSUE TITLE
VssConnection doesn't seem to be included in latest nuget packages

### ISSUE THREAD

**Issue by AltarBeastiful** [MicrosoftDocs/azure-devops-docs#11093]
The Azure Devops connection example uses `Vssconnection` but it doesn't seem to be included in the latest libraries.
```
error CS0246: Le nom de type ou d'espace de noms 'VssConnection' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [AzureDevOps.WikiPDFExport\AzureDevOps.WikiPDFExport\azuredevops-export-wiki.csproj]
```
Is there any documentation provided with the latest Azure devops library client ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8505e8-cef0-fee8-866a-e000058ac233
* Version Independent ID: d6858ee2-4282-b4e1-fb3b-e8b531b950b7
* Content: [.NET Client Library Samples for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/samples?view=azure-devops)
* Content Source: [docs/integrate/get-started/client-libraries/samples.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/client-libraries/samples.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@AltarBeastiful - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
