### ISSUE TITLE
Unable to login using Azure DevOps PAT

### ISSUE THREAD

**Issue by olivetech101** [MicrosoftDocs/azure-devops-docs#11125]
![AzDoLoginPAT](https://user-images.githubusercontent.com/85228721/127139051-88fe00d3-374c-4b7c-946f-7e535734428e.png)

Unable to login using Azure DevOps PAT 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3bebb5-3c18-a905-67b7-a1c6bd4f4522
* Version Independent ID: d6c7802a-dfdf-9852-a51b-d2ba30be70fe
* Content: [Sign in with a Personal Access Token (PAT), Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows)
* Content Source: [docs/cli/log-in-via-pat.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/log-in-via-pat.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@olivetech101 - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
