### ISSUE TITLE
Associate JUnit results to Test Cases without VS

### ISSUE THREAD

**Issue by DavorJ** [MicrosoftDocs/azure-devops-docs#11135]
Is there any way to associate test case results returned from [publish test results](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=nunit2%2Cyaml) task to Azure DevOps Test Cases without Visual Studio?

We are mainly using R/Python and would also like to associate automatic test case results to DevOps Test Cases which are in turn associated to user requirement Work Items.

Or are we on the wrong track?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops#xaml-build)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@DavorJ - Thanks for your issue. Consider these resources to address your question:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

(From a cursory search of Stack Overflow, I think the answer is no, but you should give it a closer look. )

I think this issue was related (MicrosoftDocs/azure-devops-docs/issues/7385) and I'm going to keep this open as a doc enhancement, in case the question comes up again.
