### ISSUE TITLE
Azure Pipelines Classic Deprecation Timeline

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/azure-devops-docs#11131]
According to [this blog](https://medium.com/@wywywywy/azure-devops-pipeline-choosing-between-yaml-and-classic-ui-b5612c3e211a) the classic pipeline approach is being deprecated in future. 

Is this true and is there there an official doc that notes when this deprecation will occur?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36333c89-6223-73cb-ce45-6fbb2638722e
* Version Independent ID: 286b8f96-6374-fedd-8d8d-a37fa5e1948e
* Content: [Migrate from Classic to YAML pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/migrate/from-classic-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/migrate/from-classic-pipelines.md)
* Product: **devops**
* Technology: **devops-cicd-migrate**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@gregdegruy - It looks like you have a product question, instead of an issue about the documentation. Consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
