### ISSUE TITLE
Templates are notoriously hard to create due to privledges.  It seems that only project administrators can create templates.  This seems craze for projects with thousands of people on them, like bing.

### ISSUE THREAD

**Issue by JeffreyWolford** [MicrosoftDocs/azure-devops-docs#11137]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Use work item templates to update stories & more - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@JeffreyWolford Thanks for your question. It looks like you have a product question or suggestion, not a documentation issue. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

If doc changes come up from your suggestion, we can reopen this issue.

**Comment by KathrynEE** [comment]
@JeffreyWolford - To add or edit templates. a user must be a member of the team.  You can determine if a user is a member of a team by going to Project Settings>Permissions>Users, select a User and choose the Member of tab.
