### ISSUE TITLE
DownloadPackageV1 task version argument description improvement

### ISSUE THREAD

**Issue by robhalevt** [MicrosoftDocs/azure-devops-docs#11152]
In the Arguments section of this page change the description of the `version` argument from:
```
(Required) Version of the package.
```
to be:
```
(Required) Version of the package. Use `latest` to download the latest version of the package at runtime.
```
which is the help markdown from the [DownloadPackageV1 task](https://github.com/microsoft/azure-pipelines-tasks/blob/2ac137fe71414491a6ede8cad239ae7707527986/Tasks/DownloadPackageV1/task.json#L81).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff8354ee-807f-0c1f-8e5b-9303c4591c60
* Version Independent ID: 1fd42523-8504-76cf-deec-26c5fccd0109
* Content: [Download Package task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-package.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-package-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
