### ISSUE TITLE
This migration strategy breaks any release notes flow for the next release one makes.

### ISSUE THREAD

**Issue by da9l** [MicrosoftDocs/azure-devops-docs#11161]
If one have generated release notes in the end of the release making this migration breaks the comparison function in the addon. At least for the next release, after that it works again.

https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-XplatGenerateReleaseNotes

It seems like the continuity of the artifact used in the old classic pipeline is lost when a new pipeline is created.

Is there a way around this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36333c89-6223-73cb-ce45-6fbb2638722e
* Version Independent ID: 286b8f96-6374-fedd-8d8d-a37fa5e1948e
* Content: [Migrate from Classic to YAML pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/migrate/from-classic-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/migrate/from-classic-pipelines.md)
* Product: **devops**
* Technology: **devops-cicd-migrate**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@da9l - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
