### ISSUE TITLE
Undocumented property showWarnings in PowerShell@2

### ISSUE THREAD

**Issue by Kontekst** [MicrosoftDocs/azure-devops-docs#11160]
Property showWarnings is not documented on PowerShell@2 documentation page but it is used in AzureDevOps Release and is also in source code (https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/PowerShellV2/task.json)

Edit 1 - Also property runScriptInSeparateScope is not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/powershell-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
