### ISSUE TITLE
All migrated Work Items went to "New" status

### ISSUE THREAD

**Issue by hajtomoto** [MicrosoftDocs/azure-devops-docs#11178]
Hi

I used just a standard configuration.json
I enabled work items migration only and specify source and target connections (from on premise TFS 2019 to azure cloud)
Work Items migrated correctly but all been moved to "New" column in backlog, with each added tag containing previous status e.g
Work Item on TFS was Status Completed
Migrated Work Item on Azure Cloud is with Status "New" and tag:ScrumState:Completed
Process for each project looks the same so I dont understand why work items getting their status set to "new"

**Comment by TimShererWithAquent** [comment]
@hajtomoto - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If you do see documentation issues around this issue, please refer to the specific article where it occurs and we can reopen this.
