### ISSUE TITLE
Get Latest tag/buildId

### ISSUE THREAD

**Issue by rullymartanto** [MicrosoftDocs/azure-devops-docs#11195]
How to always get latest tag in here ?

![image](https://user-images.githubusercontent.com/5577057/129298881-5bec2298-080f-4308-a641-94168b18217f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabab0a1-052d-7a62-0773-5c6ad707752b
* Version Independent ID: 967fde84-2b93-ffa5-cb27-4f1dd4ecef49
* Content: [Deploy an Azure Web App Container - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp-on-container-linux?view=azure-devops&tabs=dotnet-core%2Cyaml)
* Content Source: [docs/pipelines/targets/webapp-on-container-linux.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/webapp-on-container-linux.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by TimShererWithAquent** [comment]
@rullymartanto - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
