### ISSUE TITLE
Incorrect parameter values for deploymentMode

### ISSUE THREAD

**Issue by tdgray** [MicrosoftDocs/azure-devops-docs#11218]
The documentation lists the possible values for deploymentMode as Incremental, Complete, and Validate. The functionality of these are described accurately, except 'Validate' should be 'Validation'. Unfortunately unknown values (like 'Validate') are ignored by the task and the default of Incremental applies, meaning anyone who follows this documentation will immediately deploy whatever they are attempting to validate assuming the validation succeeds, possibly overwriting production infrastructure (ask me how I know)..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
