### ISSUE TITLE
Pipeline Completion Triggers

### ISSUE THREAD

**Issue by Software-devs-bit** [MicrosoftDocs/azure-devops-docs#11225]
[Enter feedback here]
Is it possible to specify pre-deployment conditions, post-deployment conditions in YAML Pipelines just as in classic pipelines? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70217fc0-8411-04b1-d448-d013398c5ac8
* Version Independent ID: ed92b98e-2d6f-8dfb-9319-85c825b2cb30
* Content: [Classic release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@Software-devs-bit - Thanks for your product question. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

Also, consider these resources:  

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
