### ISSUE TITLE
Access denied error when running an agent release job

### ISSUE THREAD

**Issue by guybmayor** [MicrosoftDocs/azure-devops-docs#11234]
Hey, 

I started to get error messages in all of my release pipelines that say:

Job Issues
```
##[Error 1]
Access Denied: 0000000d-0000-8888-8000-000000000000 needs the following permission(s) on the resource /Organizations to perform this action: Read Organization resources 
```

the agent pool is: 
Azure Pipelines

I couldn't find any related documentation for this issue, or what is 0000000d-0000-8888-8000-000000000000 user.

Thanks

**Comment by TimShererWithAquent** [comment]
@guybmayor - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
