### ISSUE TITLE
Docker cache example doesn't work

### ISSUE THREAD

**Issue by AKockWorth** [MicrosoftDocs/azure-devops-docs#11243]
The Docker example doesn't work on an Ubuntu agent. For one, the Docker root is `/var/lib/docker`. Second, the directory tree is not accessible by the `vsts` user. I tried a recursive `chmod` but to no avail. So far, I haven't been able to cache docker image layers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images)
* Content Source: [docs/pipelines/release/caching.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/caching.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@AKockWorth Thanks for your question. I think you should reach out to the dev community about this one. Do a search or [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).  

Also, consider these resources: 

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Until we know if there's doc issues to follow up on, I'm going to close this one. We can reopen if necessary.
