### ISSUE TITLE
Git server plugin

### ISSUE THREAD

**Issue by tcartwright** [MicrosoftDocs/azure-devops-docs#11277]
Could you guys possibly add a nuget package for server plugins? I have written a git plugin, and need to use Microsoft.TeamFoundation.Git.Server.dll. However that dll is not under any nuget.  I currently have to add this dll, and the others I need into my repo. I could create one, but I would much rather use an official MSFT nuget package.

The nuget package also doesn't need to be GIT specific.

I assume you guys know this, but the dlls I ended up needing in my git plugin:

- Microsoft.TeamFoundation.Common.dll
- Microsoft.TeamFoundation.Framework.Server.dll
- **Microsoft.TeamFoundation.Git.Server.dll**
- Microsoft.TeamFoundation.SourceControl.WebApi.dll
- Microsoft.TeamFoundation.VersionControl.Client.dll
- Microsoft.TeamFoundation.VersionControl.Common.dll

**Comment by TimShererWithAquent** [comment]
@tcartwright - I think this should be a feature request, rather than a documentation issue. To make sure it gets in front of the right people, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21).

If there are documentation changes from this, we can reopen this issue.
