### ISSUE TITLE
Getting list of changes or commits associated with build

### ISSUE THREAD

**Issue by larderino1** [MicrosoftDocs/azure-devops-docs#11281]
Is there any way to get changes (or commits) associated with the build using predefined variables? 
---
#### Document Details

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@larderino1 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
