### ISSUE TITLE
Adnotation for listing variable groups

### ISSUE THREAD

**Issue by kamilporwitaccenture** [MicrosoftDocs/azure-devops-docs#11300]
Hi,

I tried to load secret variable value in my powershell script on local computer. Unfortunately, it seems such thing is not possible as the values of the secret variables is set as nulls.

Could You add an **direct** adnotation under _az pipelines variable-group variable list_ section that such direct load of secret variables values is not possible at the moment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@kamilporwitaccenture - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
