### ISSUE TITLE
How to get the reviewer and comment from a manual intervention task

### ISSUE THREAD

**Issue by djBo** [MicrosoftDocs/azure-devops-docs#11304]
Task Docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops

I am using this task as a pre-deployment stage, part of a larger deployment pipeline in yaml.

It pops up a nice right panel allowing a reviewer to cancel or continue, optionally providing a comment. It also displays our configured message. It works exactly as expected.

I would like to know how a subsequent stage can get the details for the reviewer (eg the person clicking resume) and the provided comment they have typed.

**Comment by TimShererWithAquent** [comment]
@djBo - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
