### ISSUE TITLE
I already have Team Administrator and Project Administrator roles but still can't edit Taskboard Styles

### ISSUE THREAD

**Issue by shunoraga** [MicrosoftDocs/azure-devops-docs#11338]
[Enter feedback here]
I already have Team Administrator and Project Administrator roles but still can't edit Taskboard Styles. I can edit everything in my project except this. 
I get this error: "You do not have sufficient permissions to configure cards for this team. You must either be a team administrator or a project administrator."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e5bfa-e2ea-c309-8487-3ba3236ee6ee
* Version Independent ID: 981fdeed-0f98-135c-effb-2446cff74ea9
* Content: [Add, remove team administrator - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/settings/add-team-administrator.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/add-team-administrator.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@shunoraga - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
