### ISSUE TITLE
Inconsistent or unclear documentation on merging multiple coverage reports

### ISSUE THREAD

**Issue by jcbcn** [MicrosoftDocs/azure-devops-docs#11331]
Under the Arguments heading - for the `summaryFileLocation` argument it says `Multiple summary files will be merged into a single report.` but then under the FAQ section it mentions that coverage data is not merged.

In practice, I see a merged coverage report when multiple files match my input. However the coverage percentage displayed on the pipeline run doesn't seem to match the merged report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ac4ff4-9839-6a6d-8d20-a25084d221ef
* Version Independent ID: bd09f139-8e69-8ea1-6671-b7bba8e17c23
* Content: [Publish Code Coverage Results task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/publish-code-coverage-results.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/publish-code-coverage-results.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@jcbcn - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If there are doc issues from this, we can reopen.

**Comment by jcbcn** [comment]
Hi @TimShererWithAquent, the first two sentences explain the inconsistency I've noticed in the docs.
