### ISSUE TITLE
I have exactly the same problem as described above. How was it resolved? I can't find any solution. Can you please share snippet with me? Thank you

### ISSUE THREAD

**Issue by AnFa1978** [MicrosoftDocs/azure-devops-docs#11359]
I have exactly the same problem as described above. How was it resolved? I can't find any solution. Can you please share snippet with me? Thank you

_Originally posted by @AnFa1978 in https://github.com/MicrosoftDocs/azure-devops-docs/issues/11314#issuecomment-920965477_

**Comment by TimShererWithAquent** [comment]
Hi @AnFa1978 - It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Unless @boris-tarasov-maersk posted the solution somewhere -

**Comment by boris-tarasov-maersk** [comment]
hi @AnFa1978
If you can, please update the titel so others can benefit of this case.

My solution looks like this:

  ${{ if eq(parameters.adoAgentPool, '') }}:
    pool:
      vmImage: ${{ parameters.adoAgentVmImage }}
  ${{ if ne(parameters.adoAgentPool, '') }}:
    pool: ${{ parameters.adoAgentPool }}

and lets choose between on-prem (self-hosted) and Azure DevOps hosted agents based on paramters.

**Comment by jswiniarski** [comment]
Hi @boris-tarasov-maersk 

Does this apply to pipeline (global) level pool or job pool?
When I use this method for top level pool I receive error "A template expression is not allowed in this context"

**Comment by boris-tarasov-maersk** [comment]
> Hi @boris-tarasov-maersk
> 
> Does this apply to pipeline (global) level pool or job pool? When I use this method for top level pool I receive error "A template expression is not allowed in this context"

Long time since. If I remember correctly this is job level.
