### ISSUE TITLE
Include "How to develop Azure Wiki Extension"

### ISSUE THREAD

**Issue by GeorgeS2019** [MicrosoftDocs/azure-devops-docs#11404]
[Enter feedback here]
This refers to this [page](https://docs.microsoft.com/en-us/azure/devops/extend/overview?view=azure-devops)

We need development instruction or sample on how to develop an Azure Wiki Extension, with specific focus on replacing or enhancing the Mermaid support in Azure Wiki.

Currently the Azure Wiki support is limited based on the [ 324 up votes of community feedback](https://developercommunity.visualstudio.com/t/add-support-for-plantuml/747577?from=email&viewtype=all#T-ND1537711).

It only supports [a subset diagram features](https://developercommunity.visualstudio.com/t/more-diagram-capabilities-mermaid-and-p/1122269?from=email&viewtype=all&space=21&q=plantuml) of Mermaid

The community has since 2019 requested with a 324 up votes to address the Azure Wiki gaps for better diagram capabilities:
- more mermaid diagrams
- (better) support of PlantUML

The discussion summaries how the community on self initiative to address this [limitation](https://developercommunity.visualstudio.com/t/add-support-for-plantuml/747577?from=email&viewtype=all#T-ND1537711)

Although there has been [a completed solution to the feedback](https://developercommunity.visualstudio.com/t/Extend-MarkdownWiki-to-support-mermaid/365751?space=21&q=plantuml), it is a partial solution

=> SOLUTION

The community need a way on self initiative to address the Azure Wiki Gap that could decide [if the community to stay royal and commitment to Azure DevOps solution](https://github.com/MicrosoftDocs/azure-devops-docs/issues/11404#issuecomment-925868729)

The community need the Azure Wiki mermaid implementation to make available as an Azure Devops Extension (open source github), so the community could use the extension development project to update the mermaid implementation and also to use the project as template to implement Azure Wiki PlantUML support ASAP!!!!.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d1eca9-3a6d-e9e5-c424-30f4d4b8b544
* Version Independent ID: 2b542142-15dd-c4ad-8dde-c3df0b6204c8
* Content: [Developing extensions for Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/overview?view=azure-devops)
* Content Source: [docs/extend/overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/overview.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by GeorgeS2019** [comment]
> [Convince your company to move to another tool](https://developercommunity.visualstudio.com/t/add-support-for-plantuml/747577#T-N1537766), that’s what I’m doing.

![image](https://user-images.githubusercontent.com/49812372/134525993-9e84e59d-cf6e-4583-bffd-62a99356507a.png)

**Comment by agoodwin** [comment]
We're using Azure DevOps Server (i.e. on-premise), which has no support for Mermaid diagrams at all.

After some thinking about it, what we decided to do is use the live editor: https://mermaid.live/

Which allows you to quickly and easily copy a Markdown formatted image and link of your diagram, e.g.

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZylcbiAgICBCIC0tPiBDe0xldCBtZSB0aGlua31cbiAgICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICAgIEMgLS0-fFR3b3wgRVtpUGhvbmVdXG4gICAgQyAtLT58VGhyZWV8IEZbZmE6ZmEtY2FyIENhcl1cbiAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjp0cnVlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0)](https://mermaid.live/edit#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZylcbiAgICBCIC0tPiBDe0xldCBtZSB0aGlua31cbiAgICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICAgIEMgLS0-fFR3b3wgRVtpUGhvbmVdXG4gICAgQyAtLT58VGhyZWV8IEZbZmE6ZmEtY2FyIENhcl1cbiAgIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9)

With the Markdown for that diagram being:
``` markdown
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZylcbiAgICBCIC0tPiBDe0xldCBtZSB0aGlua31cbiAgICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICAgIEMgLS0-fFR3b3wgRVtpUGhvbmVdXG4gICAgQyAtLT58VGhyZWV8IEZbZmE6ZmEtY2FyIENhcl1cbiAgIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjp0cnVlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6dHJ1ZX0)](https://mermaid.live/edit#eyJjb2RlIjoiZ3JhcGggVERcbiAgICBBW0NocmlzdG1hc10gLS0-fEdldCBtb25leXwgQihHbyBzaG9wcGluZylcbiAgICBCIC0tPiBDe0xldCBtZSB0aGlua31cbiAgICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICAgIEMgLS0-fFR3b3wgRVtpUGhvbmVdXG4gICAgQyAtLT58VGhyZWV8IEZbZmE6ZmEtY2FyIENhcl1cbiAgIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6dHJ1ZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOnRydWV9)
```

I feel a bit bad for the Mermaid people, because it's putting the load onto their servers, however I assume they wouldn't provide this functionality if it was really a problem for them.

Using this approach allows you to use all of the latest feature set of Mermaid diagrams, no matter where Microsoft are with Azure DevOps. It's also still easy to edit your diagrams, because the generated markdown has a link to the Mermaid live editor with your diagram pre-loaded.

The good thing as well is that the full diagram source is embedded in the Base64-encoded part of the image/link URLs in the Markdown, so in the worst case, if it all goes offline, you can salvage your diagram source by decoding your image links.

The only real downside I'd say is the requirement to have your diagrams go through a public website, which may not be appropriate if you're putting a lot of detail of your IP into your diagrams. But otherwise, we've found this to be a good stop-gap solution.

**Comment by GeorgeS2019** [comment]
@chcomley I mobilize feedback to the Microsoft ML/AI teams [to address the gaps and limitations](https://github.com/dotnet/TorchSharp/discussions/334). We need to make Azure Wiki more flexible like VS Code to support new diagram capabilities through, if possible, same extension capabilities like VS Code. The discussion has gathered many hacks how to address the Azure Wiki since last 2 years.  If possible, [please summaries the hack ideas/feedback here](https://developercommunity.visualstudio.com/t/add-support-for-plantuml/747577?from=email&viewtype=all#T-ND1537711) so we know Microsoft has correctly captured the requirements (based on community feedback) how Azure Wiki can best support the community in term of diagram capabilities.

**Comment by chcomley** [comment]
Hi @GeorgeS2019, I've looked over your [feature request](https://developercommunity.visualstudio.com/t/add-support-for-plantuml/747577?from=email&viewtype=all#T-ND1537711) and see that there's a collection of responses and 355 votes. Here's hoping it gets more traction, thank you.

I'll share what I know about Azure DevOps Wiki: We don't intend to add major new features to the Wiki product in Azure DevOps moving forward, but we do intend to round out and improve the existing feature set. This includes updating the version of Mermaid charts that Wiki uses, and will likely include adding support for additional Mermaid chart diagram types, as well. We don't yet have that work scheduled, but expect to add it to the roadmap within the next month or two.

As for the article of mention, it's intended to present conceptual content about extension development for Azure DevOps, rather than targeted instructions. Since there's no required updated, I'm closing this issue. Feel free to @mention me if needed. Thank you!

**Comment by v-andrew** [comment]
@chcomley Is it going to be available in the DevOps server or Azure-hosted only?

**Comment by biltongza** [comment]
@chcomley it's a while since "the next month or two", do you have any ideas if this will ever make it to the roadmap?

**Comment by chcomley** [comment]
Thanks for your questions. I'm adding @aaronhallberg to provide more information. Thanks!
