### ISSUE TITLE
Manual Validation task should have "Send Attachment feature"

### ISSUE THREAD

**Issue by AvinashMitta** [MicrosoftDocs/azure-devops-docs#11401]
HI Team,

While using manual validation task it sends an email for approval while pausing the stage .This is very good option ,but it would be more usable if we have an option to send an attachment so that approvers will have some context .
Let me know if that is possible? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43cdab75-b48a-ba18-11da-a50ed8e680a6
* Version Independent ID: 8422d73e-5a3f-91d6-edbc-ccd9c968cc9a
* Content: [Manual Validation task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/manual-validation.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/manual-validation.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @raiyan
* Microsoft Alias: **moala**

**Comment by TimShererWithAquent** [comment]
Hi @AvinashMitta - Thanks for your question. It looks like you have a question about your implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Also, you might want to do a feature request. To make sure it gets in front of the right people, please [submit your request here](https://developercommunity.visualstudio.com/search?space=21).

If there are doc issues, we'll reopen this issue.
