### ISSUE TITLE
I like to show only "overview" and "boards" to "TeamB"

### ISSUE THREAD

**Issue by lordisp** [MicrosoftDocs/azure-devops-docs#11414]
I have `Project-A` with two Teams. `Team-A` and `Team-B`. `Team-A` are Contributors and `Team-B` some kind of `Stakeholders`.

The `Project-A` is using all features from `Overview` to `Artifacts`

In order to reduce confusions for `Team-B`, I like to hide all Features besides `Overview` and `Boards`.

With some `RBAC` I was able to reduce the view to   `Overview`, `Boards`, `Pipelines` and `Artifacts` for `Team-B`. How can I hide `Pipelines` and `Artifacts` only for `Team-B`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a46752f-3ee0-1503-9423-740ae926c25f
* Version Independent ID: 78a11eae-b3b7-5e6f-971a-4abc5716013d
* Content: [Turn a service on or off - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/set-services?view=azure-devops)
* Content Source: [docs/organizations/settings/set-services.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/settings/set-services.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@lordisp - Thanks for your question. It looks like you're working through an issue with your scenario, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
