### ISSUE TITLE
Copy Files task: Contents is marked as required but has a default

### ISSUE THREAD

**Issue by stefandrissen** [MicrosoftDocs/azure-devops-docs#11424]
````
(Required) File paths to include as part of the copy. Supports multiple lines of match patterns.
````
But at the end of the section:
````
Default value: **
````
So either the contents are optional or there is no point in documenting a default value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
It is marked as required in the task source code for the task (they are open source) https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/task.json#L46

In this case, I believe you cannot specify an empty string for this parameter, so that is the logic for it being required.

Please check this task article in our new task reference which s now generated using the task source code and metadata from the task.json.
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/copy-files-v2?view=azure-pipelines&tabs=yaml&viewFallbackFrom=azure-devops

**Comment by stefandrissen** [comment]
Fair enough that it is not a documentation error, just nonsense on the part of the task, or I'm not understanding what ``required`` means and what a ``default value`` means. The v2 task still contains the same contradiction:

```
Contents - Contents
string. Required. Default value: **.

The file paths to include as part of the copy. This string supports multiple lines of match patterns.
```
I'll create an issue over on the task.
