### ISSUE TITLE
is there a way to have as possible values of a parameter the branches of another repository

### ISSUE THREAD

**Issue by yazbekhe** [MicrosoftDocs/azure-devops-docs#11459]
- if i want to create another parameter that have as possible values the list of branches of the current repo. how to do that?

- i want to let the user choose the branch to clone of another repo for example

resources:
  repositories:
  - repository: mytest
    type: git
    name: mytest
    ref: $(BranchBinariesName)

parameters:
- name: BranchBinariesName
  type: string

variables:
- name: BranchBinariesName
  value: "${{ parameters['BranchBinariesName'] }}"

stages:
- stage: test1
  displayName: "test"
  pool:  myBuilder
  jobs:
  - job: display
    displayName: 'display'
    timeoutInMinutes: 210    
    steps:
    - checkout: mytest

so i need that the possible values of the parameter  BranchBinariesName be the available branches of the repo mytest

**Comment by TimShererWithAquent** [comment]
@yazbekhe - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
