### ISSUE TITLE
mismatch in example snippet and arguments section

### ISSUE THREAD

**Issue by ktremain** [MicrosoftDocs/azure-devops-docs#11542]
One of the arguments in the "Yaml snippet" example code is "azurePowerShellVersion"  
In the arguments section, its listed as "TargetAzurePs" which causes confusion when trying to review the required arguments  
Please can this be reviewed and corrected - Thanks! :)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcda4373-62ae-e1ae-c15d-63f441179b47
* Version Independent ID: 305f78c0-2e89-78f2-d2d1-89471602610c
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
They are both correct due to [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users). This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:

Please check it out and let us know what you think. Thank you.

**Comment by steved0x** [comment]
https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/azure-powershell-v5?view=azure-pipelines
