### ISSUE TITLE
Date of last penetration test done on Azure DevOps Services

### ISSUE THREAD

**Issue by RobinZergiebel** [MicrosoftDocs/azure-devops-docs#11573]
Hey,

For some reason my [other issue](https://github.com/MicrosoftDocs/azure-docs.de-de/issues/710) I created ~1 year ago got deleted. In this issue I was told to contact secure@microsoft.com regarding this information. However, I was told via this mail address that it was just for reporting vulnerabilities and got no answer.

In the linked document you state:

> The Azure DevOps Services team conducts regular, security-focused penetration testing of Azure DevOps.

I just need a date when the last penetration test was done so that I can document this for our security team.

Cheers,
Robin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Data protection overview - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/data-protection.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by TimShererWithAquent** [comment]
@steved0x Can you help direct this issue? Thanks -

**Comment by steved0x** [comment]
#investigating

**Comment by steved0x** [comment]
@RobinZergiebel Sorry for this delay, I am trying to find out this for you.

#investigating

**Comment by steved0x** [comment]
@RobinZergiebel Sorry that it took my so long to run this down. The most recent date of penetration for Azure DevOps (as of the time of me writing this comment) was September 2021, and can be viewed on the [Service Trust Portal](https://servicetrust.microsoft.com/ViewPage/TrustDocumentsV3?command=Download&downloadType=Document&downloadId=ce44654a-f397-4aab-a45c-876fe4dd9cbf&tab=7f51cb60-3d6c-11e9-b2af-7bb9f5d2d913&docTab=7f51cb60-3d6c-11e9-b2af-7bb9f5d2d913_Pen_Test_and_Security_Assessments). Although the report is free, it requires an Azure Cloud Services login to view the report, but there is also an option for a free (no credit card required) trial. Once you are logged in, look for **Azure DevOps - Penetration Test Summary Reports (September 2021)** and you can download it from there. It should be the 2nd one down from the top.

I will add a link to the trust center from this article so that other customers can find the report.
