### ISSUE TITLE
Need to attach a link to an image

### ISSUE THREAD

**Issue by EdwardQuentin** [MicrosoftDocs/azure-devops-docs#11609]
I'm building a process flow using individual images for each box and would like to attach links to those boxes, basically making each box a link. The link button doesn't work the way I'd like it to work (it places the link above the image instead of making the box itself a hot link). I can't pull up the entire wiki page HTML, otherwise I'd be able to see how the image markdown looks in the raw code and drop the href link accordingly. All I can see is the image markdown code:

![text](image url)

Where do I put the <a href="url"></a> markdown so that the image becomes the hotlink? Is this supported?

**Comment by TimShererWithAquent** [comment]
Hi @EdwardQuentin - to find out about supported features or to request features, check out the dev community. To make sure you gets in front of the right people, please [submit your issue here](https://developercommunity.visualstudio.com/search?space=21).

If there's a doc issue for a specific article, we can reopen this issue.
