### ISSUE TITLE
Unanswered on this page: how to get project admin access

### ISSUE THREAD

**Issue by chasm2018** [MicrosoftDocs/azure-devops-docs#11617]
[Enter feedback here]
This page is supposed to provide info on how to get Project Admin access. Instead, it explains how to look up the organization owner (and change them). And how to look up the Project Admin list and add people to it. Where do I find out how to request Admin access?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20dce3f1-1133-3084-c5f4-7a5d6d0d6cf8
* Version Independent ID: 31579324-f0e5-607a-caa1-ec31b444af79
* Content: [Find an admin or organization owner - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/lookup-organization-owner-admin?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/security/lookup-organization-owner-admin.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/lookup-organization-owner-admin.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by TimShererWithAquent** [comment]
@chasm2018 Thanks for your question. While we look into changes for this article, consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by KathrynEE** [comment]
@chasm2018 - To get elevated permissions, you need to be added as a member of the Project or Project Collection Administrators group - or have permissions at the level set to **Allow**. This is documented here: [Set permissions at the project- or collection-level](https://docs.microsoft.com/en-us/azure/devops/organizations/security/set-project-collection-level-permissions?view=azure-devops&tabs=preview-page). I'll add a link and instructions to the article you reference so that is clear.
