### ISSUE TITLE
deploymentMode 'Validate' option incorrect

### ISSUE THREAD

**Issue by lymedo** [MicrosoftDocs/azure-devops-docs#11648]
#deploymentMode: 'Incremental' # Options: Incremental, Complete, **Validate**

**Validate** option results in a default Incremental deployment.

Correct option is:

deploymentMode: 'Validation'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa4bb5b-30b2-bb87-5a4d-d1fd4f8b9860
* Version Independent ID: aba4f40c-5b1d-404e-7594-aa8887ad5ce5
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
