### ISSUE TITLE
Documentation page for Build Machine Image (Packer) Argument column does not accurately specify the arguments

### ISSUE THREAD

**Issue by keiranm** [MicrosoftDocs/azure-devops-docs#11672]
The documentation on this page:
https://docs.microsoft.com/en-au/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops is not clear and descriptive.

The "Argument" column lists a short description of the argument and the NOT actual argument itself.

The Argument column should contain the yaml text field itself.

The example the Argument "Packer template" should actually be "templatetype:" - I should not have to guess which is which.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48bb33c0-8993-0ddd-1d91-3ccba738f180
* Version Independent ID: 96b2b795-99b3-7a06-522d-75bcee49e595
* Content: [Build Machine Image task - Azure Pipelines](https://docs.microsoft.com/en-au/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/packer-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/packer-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by TimShererWithAquent** [comment]
@keiranm Thanks - this table could be improved -

**Comment by steved0x** [comment]
@keiranm Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-au/azure/devops/pipelines/tasks/reference/packer-build-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

This shows the exact YAML input names (and aliases) and in the Inputs table that follows that YAML syntax block, we list the UI name of the input (from the Task assistant) along with the YAML name and any aliases.

Please check it out and let us know what you think. Thank you.
