### ISSUE TITLE
Is greater than supported?

### ISSUE THREAD

**Issue by garfbradaz** [MicrosoftDocs/azure-devops-docs#11675]
I know `-equal` is supported but is greater than? I want to say I want an agent with a `PowerShell` version greater than 5.* for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
Hi @garfbradaz - It looks like this one is already on our radar: MicrosoftDocs/azure-devops-docs/issues/11442 - Let me know if that issue doesn't quite cover yours - we can reopen this one or add to that one. 

You can reach out to [the dev team here](https://developercommunity.visualstudio.com/search?space=21), since this is a product question, until we get the article updated.
