### ISSUE TITLE
External guest access did not exist

### ISSUE THREAD

**Issue by Cugtyt** [MicrosoftDocs/azure-devops-docs#11681]
![image](https://user-images.githubusercontent.com/16632454/144398438-0de481e1-94e6-4a4d-9028-a5664750ec67.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite guest external users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
Hi @Cugtyt Can you give us some more information? Was that an error you encountered when you tried to do this? Where in the article did you encounter the issue? 

These resources might be helpful:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by Cugtyt** [comment]
Hi @TimShererWithAquent , [add-external-user](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops) this doc said "The user policy, External guest access, must be On for the organization that you want to invite external users to. See the following image example." but as shown above, **External guest access** not exist.

**Comment by chcomley** [comment]
Hi @Cugtyt, thanks for your feedback. I've updated the article to reflect that if you're recognized as a GitHub user in Azure DevOps, this is what you'll see, rather than the **External guest access** policy. For more information, see the _Enable GitHub invitations_ section of [Sign up and invite teammates](../../repos/get-started/sign-up-invite-teammates.md)](https://docs.microsoft.com/en-us/azure/devops/repos/get-started/sign-up-invite-teammates?msclkid=7bb7789acfc611eca963d3c9dde3f062&view=azure-devops#enable-github-invitations). Once the update goes live, this issue will automatically close. Thanks again!
