### ISSUE TITLE
Proposed solution is not working for us.

### ISSUE THREAD

**Issue by floushee** [MicrosoftDocs/azure-devops-docs#11745]
We tried to follow the documentation but we still get an CORS error message:

Access to XMLHttpRequest at 'https://dev.azure.com/organization/project/_apis/git/repositories/repo_id?path=file&api-version=6.0' from origin 'http://something.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c792d9d-54c9-e8d1-b82c-a60f818a4389
* Version Independent ID: d1f483e8-3bd7-5a29-50e1-cfc7788b64ba
* Content: [Cross-origin resource sharing (CORS) with Azure DevOps REST APIs - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/cross-origin-resource-sharing?view=azure-devops&source=docs)
* Content Source: [docs/integrate/concepts/cross-origin-resource-sharing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/integrate/concepts/cross-origin-resource-sharing.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@floushee - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
