### ISSUE TITLE
work section not included in OOB.

### ISSUE THREAD

**Issue by ReedCao** [MicrosoftDocs/azure-devops-docs#11793]
In my installation of 17.153.29522.3 (AzureDevOps2019.Update1.1), I can't find work section in default global notification page of projects set.

How can I enable it?

**Comment by TimShererWithAquent** [comment]
@ReedCao - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
