### ISSUE TITLE
Inline Commenting on ADO Wiki page

### ISSUE THREAD

**Issue by ccheyyyyyyy** [MicrosoftDocs/azure-devops-docs#11886]
Hello,

Is there any way to place inline comments in ADO wiki pages for collaboration? We need the ability to do this to work in live documents along with the ability to comment at the bottom of each wiki page. Same as in Confluence. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ebb83-c49f-e784-70b5-30c0ac01682b
* Version Independent ID: dc859870-0b8f-bee5-0b2f-e6b2aa3260c6
* Content: [Add comments to wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/add-comments-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/add-comments-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@ccheyyyyyyy - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Also, you might consider a feature request. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

**Comment by ccheyyyyyyy** [comment]
> @ccheyyyyyyy - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:
> 
> * [Azure DevOps Services](https://azure.microsoft.com/support/devops/)
> * [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
> 
> Also, you might consider a feature request. To make sure it gets in front of the right people, please [submit your bug here](https://developercommunity.visualstudio.com/search?space=21).

Thank you. We ended up purchasing Confluence for documentation as ADO Wiki pages are not user-friendly when collaborating with the Business side, who are non-technical.
