### ISSUE TITLE
Documentation on updating test results

### ISSUE THREAD

**Issue by st0ve** [MicrosoftDocs/azure-devops-docs#11885]
I am wondering how I can link my test rerun results to the original test results. My automation test pipeline looks like this:

1. run tests
2. publish results
3. check if there are failed tests
4. rerun failed tests if there are any
5. publish rerun test results

I would like to add the rerun test results to my original test run results so that I can filter tests on the pipeline using the "PassedOnRerun" toggle. Also if a test should fail the original and the rerun it would be nice to be able to have both failure reasons present in the original test run.

The REST API documentation does not provide any examples on how to use the PATCH result request.

**Comment by TimShererWithAquent** [comment]
@st0ve - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

This board doesn't support REST API docs.

**Comment by st0ve** [comment]
I disagree... Can you read through this documentation and attempt to answer my question?
https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/update?view=azure-devops-rest-7.1

**Comment by TimShererWithAquent** [comment]
@st0ve We support the DevOps articles on this board, not the REST API docs. You might want to try the feedback link here: https://docs.microsoft.com/en-us/rest/api/azure/devops/ 

In addition to the resources I mentioned above, consider looking at the developer team [here](https://developercommunity.visualstudio.com/search?space=21). Besides product questions, you can make feature requests, if you think the product could benefit from that.
