### ISSUE TITLE
PR templates not working

### ISSUE THREAD

**Issue by yannvr** [MicrosoftDocs/azure-devops-docs#11887]
I followed every steps but templates are never used (default or branch). Not even when I request it on a QS with `?template`. I can see the files in the correct dir.. Does it require any additional config/permission at the org level?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve pull request descriptions with pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by TimShererWithAquent** [comment]
@yannvr - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
