### ISSUE TITLE
anyway to publish to a artifact feed view?

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#11900]
is there some special syntax to publish to a specific view of an artifacts a feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b934d9e8-d417-1f45-dc87-e0dc25219c97
* Version Independent ID: 14bbdf7d-0608-f517-3b10-26d0e83eca85
* Content: [Universal Package, download and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/universal-packages?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/universal-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/package/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @arob98
* Microsoft Alias: **angrobe**

**Comment by TimShererWithAquent** [comment]
@drdamour - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by drdamour** [comment]
@TimShererWithAquent no ot not an issue im looking for the docs on how to publish to a view. Please reopen

**Comment by ramiMSFT** [comment]
@drdamour It's not possible to publish packages directly to a view. You should publish your package to your feed first and then promote it to a view. I'm updating the article shortly
