### ISSUE TITLE
More details on "SSH keys be manually cleared"

### ISSUE THREAD

**Issue by alexgdcas** [MicrosoftDocs/azure-devops-docs#11979]
Referring to the part 

> Request that SSH keys be manually cleared by [Support](https://azure.microsoft.com/support/devops/). You can find the steps for how to recreate SSH keys [further in this article](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops#inform-users-of-the-completed-change).

It would be good to know, whether it is sufficient to make sure every user removes all SSH-keys, or what are the dangers of not clearing the SSH-keys. Talking to support can take time or become a tedious task at times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f0caaf-2697-c506-339b-2dea64233e48
* Version Independent ID: 7cd2ea02-2079-85d0-09e0-a90af59937d9
* Content: [Switch to another Azure Active Directory - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops)
* Content Source: [docs/organizations/accounts/change-azure-ad-connection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/change-azure-ad-connection.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @alexgdcas, I'm looking into this and will be in touch. Thanks for reaching out.

**Comment by chcomley** [comment]
Hi @alexgdcas, unfortunately, we don't have self-service options for clearing SSH keys after a tenant switch. If you want to share over your support ticket, my PM will do their best to nudge it up the queue to get a support engineer's help on it sooner. Just @mention me, if so. Also, because SSH keys never expire, when a system administrator leaves the organization or an IT automation process gets removed, related keys may still be located in various files and accessed by unauthorized users. So, the risk of exposing access or credentials is serious. Thank you!
