### ISSUE TITLE
Mulit-repo triggering does not work!

### ISSUE THREAD

**Issue by adameska** [MicrosoftDocs/azure-devops-docs#11970]
The multi-repo triggering is not working for us. I'm using this syntax that matches the documentation and it's just not triggering on the other repo in my project, only the repo i'm working in (still in a branch, not merged to master)

resources:
  repositories:
  - repository: OtherRepo
    type: git
    name: Project/Repo1
    trigger:
      branches:
        include:
        - TestTrigger
  - repository: MyRepo
    type: git
    name: Project/CurrentRepo
    trigger:
      branches:
        include:
        - TriggerOnOtherBranch

What am i doing wrong? I don't have a trigger section at the top (though i have tried that and many other things and i have not been able to get this to work!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@adameska - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

I'm going to keep this open as a doc enhancement in case there are problems with the doc. Be sure to update this issue if you find a doc problem.

**Comment by adameska** [comment]
Ah thank you, i just clicked report a problem from the documentation site because what i was seeing didn't match the documentation. I will post this there instead.
