### ISSUE TITLE
DELETE Repository is still possible event if permission is set to DENY

### ISSUE THREAD

**Issue by Christian-e-S** [MicrosoftDocs/azure-devops-docs#11978]
I have set the "Delete Repository" permission to DENY, but it is still possible for the given user to delete a repository.

Screenshot of permission setting:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/59229557/154119540-5d0495ea-3863-449e-a2a7-fe64c4a7c013.png">

How I'm doing the delete operation:
<img width="698" alt="image" src="https://user-images.githubusercontent.com/59229557/154119729-2e10a4e5-78db-4709-a512-2659a69201d5.png">

I would expect this not to work ... but it works.

Am I missing something?

Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4253dae1-49d7-5785-41d5-ce70bc4c9010
* Version Independent ID: 7de01552-ecb6-5594-3294-cbfb41cb4477
* Content: [Set Git repository permissions - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-git-repository-permissions?view=azure-devops)
* Content Source: [docs/repos/git/set-git-repository-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/set-git-repository-permissions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Christian-e-S - If you've set a specific permission to **Deny** for a user, and that user still can perform the associated task - then something else must be going on.  I recommend that you see what other groups the user is a member of. A few things to check: 
- Use [az devops security permission show](https://docs.microsoft.com/en-us/azure/devops/organizations/security/manage-tokens-namespaces?view=azure-devops) to list the user's permissions.
- [Troubleshoot permissions](https://docs.microsoft.com/en-us/azure/devops/organizations/security/troubleshoot-permissions?view=azure-devops)

Since this is not a document issue, if you continue to have issues, I reccomend you post your issue on our [Developer Community page](https://developercommunity.visualstudio.com/report?space=21&entry=problem).
