### ISSUE TITLE
Azure pipeline maven@3 task not picking environment variable.

### ISSUE THREAD

**Issue by nileshpatil1992** [MicrosoftDocs/azure-devops-docs#12061]
I am connecting to GCP services using sdk for integration test. GCP sdk refers to GOOGLE_APPLICATION_CREDENTIALS environment variable for credentials. 
I am executing below maven task in azure pipeline where SDK trying to access environment variable and java code (SDK) is not able access this environment variable.

With below 2 ways I tried to set environment variable.

1.  With **-DGOOGLE_APPLICATION_CREDENTIALS=CRED_FILE_PATH**  option
2.  Using surefire maven plugin
 
I am missing something here ?

```
 - task: Maven@3
     inputs:
      mavenPomFile: 'samples/testproject/pom.xml'
      goals: 'test'
      mavenAuthenticateFeed: true
      options: ' -Dmaven.repo.local=$(mavenCacheFolder), -DGOOGLE_APPLICATION_CREDENTIALS=CRED_FILE_PATH'
    displayName: Build test and set the version, package



<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven-surefire-plugin.version}</version>
        <configuration>
            <parallel>all</parallel>
            <threadCount>4</threadCount>
            <redirectTestOutputToFile>true</redirectTestOutputToFile>
            <environmentVariables>
                        <GOOGLE_APPLICATION_CREDENTIALS>CRED_FILE_PATH</GOOGLE_APPLICATION_CREDENTIALS>
                    </environmentVariables>
        </configuration>
        <dependencies>
            <dependency>
                <groupId>org.apache.maven.surefire</groupId>
                <artifactId>surefire-junit47</artifactId>
                <version>${maven-surefire-plugin.version}</version>
            </dependency>
        </dependencies>
    </plugin>

**Comment by WilliamAntonRohm** [comment]
@nileshpatil1992 -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?  Meanwhile, please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by boothen** [comment]
Hi there, 

Is it possible to reopen this issue? As I'm seeing the same problem. The documentation I'm using is -

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops#we-use-the-mvn--s-switch-to-specify-our-own-settingsxml-file-how-do-we-authenticate-azure-artifacts-feeds-there

With the initial task from here - 

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops#systemaccesstoken

The SYSTEM_ACCESS environment variable isn't being picked up in the Maven task. I've tried using a different variable name. The only workaround is to set a PAT variable directly in the pipeline UI as a non-secret variable. However, that is not very secure.

If I change from using the Maven task to using a Bash script and executing the Maven command directly then I don't see the issue. I'm assuming that the issue is in the Maven task not pulling in any other environment variables.

Let me know if you need further details.

Cheers,
Matt.

**Comment by boothen** [comment]
Further to this, the following does not pass the variable through to the Maven task

```
  - bash:
    env:
      SYSTEM_ACCESS: $(system.accesstoken)
```
but this one does
```
- bash: |
      echo "##vso[task.setvariable variable=SYSTEM_ACCESS]$(system.accesstoken)"
```

**Comment by WilliamAntonRohm** [comment]
@boothen -- Matt, thank you for your follow-up.
