### ISSUE TITLE
gradle plugins does not seem to pull through an upstream feed

### ISSUE THREAD

**Issue by pieterkr** [MicrosoftDocs/azure-devops-docs#12124]
As I understand best practices, it is best to aggregate all your feeds into one eg. 'main' feed that proxies other feeds eg. public3rdParty, buildArtifacts, privateDependencies
This sort of works although not very well, as a lot of things don't seem to pull through eg. gradle plugins and maven snapshots
which is super frustrating...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c152cc-c1d1-abc1-1861-20aab95731bb
* Version Independent ID: 0d75b4b4-3297-fae7-9345-d863f67e6fed
* Content: [Set up upstream sources for your feed - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
@pieterkr -- thank you for your feedback.  This repo is solely for documentation issues, and this issue is product-related. To make sure it gets in front of the right people, [please add it here](https://developercommunity.visualstudio.com/search?space=21).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @ramiMSFT for awareness

**Comment by pieterkr** [comment]
thanks @WilliamAntonRohm I mainly logged it here because I saw that there is a disclaimer that mentions that maven snapshots are not supported, so I figured a note about this would help others that are struggling.
