### ISSUE TITLE
bash.exe: warning: could not find /tmp, please create! error for AWSshellscript task when using microsoft hosted agent windows

### ISSUE THREAD

**Issue by prasanthbangs2016** [MicrosoftDocs/azure-devops-docs#12155]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
@prasanthbangs2016 -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?  Meanwhile, please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by michael-j-hilde** [comment]
I apologize for posting this here, but I'm not sure where else I could post/ask this...
I'd like to set up notifications so that I get an email (or some kind of notification) anytime this page on "Microsoft Hosted Agents" gets updated (it's the MacOS version we're concerned about): https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

Same for a page in Github like this one: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#xcode 

Right now the best I have is an email notification for this entire "MicrosoftDocs" repo, with an email filter removing anything that doesn't say "hosted"...but this isn't very helpful, as there are a lot of comments/issues raised where "hosted" is in there (but not an update to the actual documentation).

**Comment by WilliamAntonRohm** [comment]
@michael-j-hilde -- Michael, no problem!  This page seems relevant to your question:
- https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository

It appears that GitHub only has notifications per-repo, and not per-file.

**Comment by michael-j-hilde** [comment]
yep, I was afraid of that. Thanks anyways for the response, I appreciate it. I figured if there WAS a way to do this, the smart folks of this community would know! :)

**Comment by prasanthbangs2016** [comment]
> @prasanthbangs2016 -- thank you for your feedback. Are you following a particular docs.microsoft.com article? Meanwhile, please consider these resources:
> 
> * [Azure DevOps Services](https://azure.microsoft.com/support/devops/)
> * [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

this didn't help me. please do the needful.

**Comment by WilliamAntonRohm** [comment]
@prasanthbangs2016 -- thank you for your followup.  This repo is solely for documentation issues, and this appears to be implementation-related.
