### ISSUE TITLE
CopyFiles@2 - contradicting info if Contents is required

### ISSUE THREAD

**Issue by milbrandt** [MicrosoftDocs/azure-devops-docs#12196]
In YAML snippet argument `Contents` is commented.
In arguments description `Contents` is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102c142b-869c-0f14-d67e-65e9e5c9c141
* Version Independent ID: b5e1ee58-4e89-255b-bb06-921955e1b9e9
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed (that input is required) in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/copy-files-v2?view=azure-pipelines&tabs=yaml&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
