### ISSUE TITLE
Missing field

### ISSUE THREAD

**Issue by esdrasbeleza** [MicrosoftDocs/azure-devops-docs#12265]
The field "Generate web.config parameters for Python, Node.js, Go and Java apps" is not there. This is what I see:

![Screenshot 2022-05-02 at 13 28 12](https://user-images.githubusercontent.com/205742/166234066-db8d6310-c37b-42c3-811e-361c0d94e02f.png)

I was able to fix my problem by editing the "Package or folder" path, but this field doesn't seem to be there anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ad1fa-cee5-c5c6-7050-21aaec6b714a
* Version Independent ID: 617316ff-2dab-d021-880f-c1c79313c320
* Content: [Azure Function App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-function-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/deploy/azure-function-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

That field only applies when the appType is not functionAppLinux and package NotEndsWith .war.
```
customWebConfig - Generate web.config parameters for Python, Node.js, Go and Java apps
string. Optional. Use when appType != functionAppLinux && package NotEndsWith .war.
```

Please check it out and let us know what you think. Thank you.
