### ISSUE TITLE
windows-latest specifies it should use 2022 but using 2019 in yaml builds

### ISSUE THREAD

**Issue by mfintonis** [MicrosoftDocs/azure-devops-docs#12313]
Our devops builds are using a window-latest declaration for their YAML files. Based on the documentation, this should point to 2022, however it is pulling in windows-2019 instead causing our builds that use .NET 6.0 to fail:
**YAML**
![image](https://user-images.githubusercontent.com/28113870/168141140-7d02209e-fdce-4ccb-bb80-a2c9b2b55c42.png)

**Pool used in DevOps:**
![image](https://user-images.githubusercontent.com/28113870/168141254-17d1315c-26af-4246-8e0d-fd386cd0812e.png)

 We are referencing windows-2022 explicitely for now which does correctly pull in the right pool, but the docs below state that windows-latest should point to 2022. Is this an error with the documentation or an error with DevOps? Or is it user error on our part? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@mfintonis -- thank you for your feedback and questions.  This issue appears to be product-related rather than documentation-related, and so is not any error on your part.

I added an issue report for this in the [Developer Community](https://developercommunity.visualstudio.com/t/YAML-builds----windows-latest-should-res/10040931?space=21&entry=problem).

cc @steved0x for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by WilliamAntonRohm** [comment]
@mfintonis -- please see [this comment](https://developercommunity.visualstudio.com/t/YAML-builds----windows-latest-should-res/10040931#T-ND10046158) in the Developer Community discussion I opened for this issue.
