### ISSUE TITLE
Missing documentation on deployment_environment input parameter

### ISSUE THREAD

**Issue by Boaz101** [MicrosoftDocs/azure-devops-docs#12320]
This page is missing documentation on the deployment_environment input parameter. See https://docs.microsoft.com/en-us/azure/static-web-apps/named-environments?tabs=azure-devops

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Version Independent ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Content: [Azure Static Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-static-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-static-web-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/azure-static-web-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@Boaz101 Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-static-web-app-v0?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
