### ISSUE TITLE
Document the tagPattern argument

### ISSUE THREAD

**Issue by gldraphael** [MicrosoftDocs/azure-devops-docs#12345]
Would expect a tagPattern like `v*` to work (since it does in triggers).
Since it doesn't, would be nice to see examples of what would work.

`tagPattern` is also missing from the arguments table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b12d2c4-f871-1d14-0c16-91e58fb1130b
* Version Independent ID: 6b9e1d67-f303-7445-e573-830309ba49a4
* Content: [GitHub Release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/github-release.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/github-release.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here (it includes a short example snippet).
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

If `v*` doesn't work (and you think it should) please file an issue on the task here: https://github.com/microsoft/azure-pipelines-tasks

Please check it out and let us know what you think. Thank you.
