### ISSUE TITLE
retryCount argument not available in Azure DevOps Server 2020

### ISSUE THREAD

**Issue by frosted69** [MicrosoftDocs/azure-devops-docs#12379]
Hello,

I was looking at the task help file and I saw that there was the retryCount property available when I selected Azure DevOps Server 2020 in the documentation filter.

However, this property isn't part of the yamlschema of that azdo version.
Shouldn't the retryCount property be removed when we filter doc with azdo server 2020?

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 102c142b-869c-0f14-d67e-65e9e5c9c141
* Version Independent ID: b5e1ee58-4e89-255b-bb06-921955e1b9e9
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops-2020&tabs=yaml&source=docs)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@frosted69 This issue is resolved in our new task reference, here is the Azure DevOps Server 2020 documentation for that task: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/copy-files-v2?view=azure-pipelines-2020&tabs=yaml

Please check it out and let us know what you think. Thank you.
