### ISSUE TITLE
clarify that bash shortcut task only takes command(s)

### ISSUE THREAD

**Issue by carlin-q-scott** [MicrosoftDocs/azure-devops-docs#12371]
I found this section confusing:
```yml
bash: # script path or inline
```

From reading that, I expected to be able to write:
```yml
bash: my-script.sh
```

However, that fails because it's not a command. The script has to be executed as a command, like so:
```yml
bash: ./my-script.sh
```

So I'd like that little comment to say:
```yml
bash: # command(s)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e70665-a794-82fd-287b-65a747488efa
* Version Independent ID: 0c34f5c3-bc80-061d-cf7a-f30c224ce3b1
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@carlin-q-scott -- Carlin, thank you for your feedback and suggestion.

@steved0x -- Steve, please review these updates in [private PR 4740](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/4740).

**Comment by steved0x** [comment]
That content has moved, here is the new location for the bash task:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/bash-v3?view=azure-pipelines

Here is the new location for the bash step (shortcut syntax for using the bash task, which I believe you are referring to)
https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-bash?view=azure-pipelines

That one has been changed to remove the script path option, since the shortcut is inline script only (potentially using the commands as in your example)

Thank you for letting us know.
