### ISSUE TITLE
is it AzDevOps user's environment variables I'd add in it's .bashrc if I want to change from /agent/_work?

### ISSUE THREAD

**Issue by mtowersap** [MicrosoftDocs/azure-devops-docs#12382]
[Enter feedback here]
you say if you want to change the agent's working directory on unix from /agent/_work (which is in root partition) to something else, set the env var VSTS_AGENT_INPUT_WORK, create image with it, and then create VMSS with that image. But... this is unix, not windows, there isn't a 'system' set of environment variables.  Which user? if it's AzDevOps, then I'd have to add that user, right? then edit it's bashrc (assuming it's default shell is /bin/bash).  Then generalize and image it? and VMSS will use that user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 756d9c64-a802-61ad-ba6c-6061d2d747cf
* Version Independent ID: 012518b7-0282-f5b0-5206-8a9d1902b8d3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@mtowersap -- thank you for your feedback and questions.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

This issue seems beyond the scope of this documentation set, as being open-ended.  I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @steved0x for awareness

**Comment by mtowersap** [comment]
@steved0x Not sure why this is beyond the scope, the documentation says it, but doesn't say how to do it.  Seems to be relevant to me.

**Comment by WilliamAntonRohm** [comment]
@mtowersap -- thank you for your follow-up.

@steved0x -- please look into this issue.
