### ISSUE TITLE
Anchor Link with Custom ID

### ISSUE THREAD

**Issue by AndyDaSilva52** [MicrosoftDocs/azure-devops-docs#12383]
Is it possible to use an **Anchor Link with custom ID** ? 

Like:

# Heading Example (Using Anchor Link with Custom ID) <a id="1.1"></a>
Usage of the [Heading Example](#1.1)

```md
# Heading Example (Using Anchor Link with Custom ID) <a id="1.1"></a>
Usage of the [Heading Example](#1.1)
```

- Reference Link: [https://gist.github.com/asabaylus/3071099?permalink_comment_id=3965944#gistcomment-3965944](https://gist.github.com/asabaylus/3071099?permalink_comment_id=3965944#gistcomment-3965944)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#anchor-links)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@AndyDaSilva52 -- Andy, thank you for your clear question.  In my research, the answer is yes.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by AndyDaSilva52** [comment]
I tried to use at Azure DevOps, and it didn't work as expected.

![image](https://user-images.githubusercontent.com/1809812/172967449-130f2d8c-0864-4c8f-81f9-98bd8b263d24.png)

Are you sure @WilliamAntonRohm ?

**Comment by WilliamAntonRohm** [comment]
@AndyDaSilva52 --Andy, thank you for your follow-up.  In the first image, the Markdown seems to be rendering and acting correctly.  In the second, I see the heading link id has been parsed as a literal, which is unlikely to match the intended target.  I'm not sure how to interpret the link URL in the third image.

Please add this issue in the [Developer Community](https://developercommunity.visualstudio.com/search?space=21).

**Comment by AndyDaSilva52** [comment]
@WilliamAntonRohm 

I [searched](https://developercommunity.visualstudio.com/search?space=21&q=Anchor+Link+with+Custom+ID&sort=relevance&stateGroup=active) and found some topics:

First, a reference for something at StackOverflow
- [Cross-reference (named anchor) in markdown | StackOverflow](https://stackoverflow.com/a/7335259/2057854)

And three Topics in Developer Community:
- [In wiki, anchor links to headings contain url markdown if the heading text is a link - Visual Studio Feedback](https://developercommunity.visualstudio.com/t/In-wiki-anchor-links-to-headings-contai/462516?space=21)
- [Custom link types! - Visual Studio Feedback](https://developercommunity.visualstudio.com/t/Custom-link-types/843987?space=21)
- [Wiki - Anchor links - Visual Studio Feedback](https://developercommunity.visualstudio.com/t/Wiki---Anchor-links/762156?space=21)

**Comment by WilliamAntonRohm** [comment]
@AndyDaSilva52 -- Andy, thank you for your thorough research.  I upvoted the feature request in your last best link.

**Comment by MattithyahuData** [comment]
Using 'id=' instead of 'name=' in the <a> tag solved this in **Azure DevOps**.
Reference: [StackOverflow response](https://stackoverflow.com/a/7335259/16562519)

`<a id="1.1"></a>` instead of `<a name="1.1"></a>`

**Comment by AndyDaSilva52** [comment]
I'm sorry @MattithyahuData , but this topic is to talk about **Azure DevOps**, specifically about **Wiki Pages**. Are you certain that this approach `<a id="1.1"></a>` works? 

Because I did a test and still doesn't work for me.

```md
[[_TOC_]]

# Heading Example (Using Anchor Link with Custom ID) <a id="1.1"></a>

Usage of the [Heading Example](#1.1)
```

![image](https://user-images.githubusercontent.com/1809812/214980390-36005114-a65e-4892-bb03-0baa1dfd95e5.png)

**Comment by MattithyahuData** [comment]
@AndyDaSilva52, I'm sure it works.

Thanks for sending over your example. **I can see that it's not working because the id attribute begins with a number.** 

See the revision below.. I have added some dummy tables in between the link and `<a>` tag to show it works by navigating to the `<a>` tag. 

`# Heading Example (Using Anchor Link with Custom ID) <a id="t1.1"></a>

| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |  


| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |  


| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |  


| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |

| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |  


| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |  


| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |  


| Heading 1 | Heading 2 | Heading 3 |  
|-----------|:-----------:|-----------:|  
| Cell A1 | Cell A2 | Cell A3 |  
| Cell B1 | Cell B2 | Cell B3<br/>second line of text |

Usage of the [Heading Example](#t1.1)
`
**Note: The id name is case sensitive!

Note: The id name must contain at least one character, cannot start with a number, and must not contain whitespaces (spaces, tabs, etc.).**

Reference: https://www.w3schools.com/html/html_id.asp  

Summary:

To link use good anchor links in any Markdown view on Azure services:

1. Use an `<a>` tag with an id name that corresponds to a `#` with that same id name
2. The id name is case sensitive so it..: 
  -  Must contain at least one character
  -  Cannot start with a number
  - Must not contain whitespaces (spaces, tabs, etc..)


**Note that you can also link dynamically - so both before and after the `<a>` tag!**
