### ISSUE TITLE
AzureStaticWebApp documentation is missing input variables

### ISSUE THREAD

**Issue by gpduck** [MicrosoftDocs/azure-devops-docs#12422]
The following inputs are defined by the task but are not listed on the documentation page:

cwd
skip_api_build
is_static_export
deployment_environment
production_branch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Version Independent ID: 90d9a39d-b739-c778-4147-4026fc646ed6
* Content: [Azure Static Web App task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/azure-static-web-app?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/azure-static-web-app.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/azure-static-web-app.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@gpduck Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-static-web-app-v0?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
