### ISSUE TITLE
Wildcard Version Parameter results in 400 Bad Request

### ISSUE THREAD

**Issue by pridmorej** [MicrosoftDocs/azure-devops-docs#12468]
This article needs more details about what is supported for the version parameter.  It seems that "*" is not supported as I'm getting back a 400 Bad Request error when executing the command:

- task: DownloadPackage@1
  displayName: 'Download PackageName'
  inputs:
    packageType: 'nuget'
    feed: 'feedname'
    definition: 'packagename'
    version: '*'
    extract: true
    downloadPath: $(Pipeline.Workspace)/foldername

Further investigation highlights that the 400 response returns the following message "A potentially dangerous Request.Path value was detected from the client (*)", for a Url such as: "https://pkgs.dev.azure.com/<organisaction>/_apis/packaging/feeds/<feedname>/nuget/packages/<packagename>/versions/*/content".

The Azure Cli download command allows wildcards in the "version" parameter.
https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#download-the-latest-version

I need wildcard version support in the DownloadPackage yaml task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbb58a5-5e29-114a-cad4-dd4856926812
* Version Independent ID: 864f99cb-348d-21e9-c561-8ae1d038bb88
* Content: [Download Package task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/download-package.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-package-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
