### ISSUE TITLE
Mention of "latest" as a version option for Download Package

### ISSUE THREAD

**Issue by ChanceyC** [MicrosoftDocs/azure-devops-docs#12473]
When trying to use the `Download Package` task, getting the latest from the feed is mentioned in documentation via the `*` wildcard character.

I ran into a similar issue as brought up here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/12468

With receiving a `400` error for the wildcard character. I've switched to using `latest` after a suggestion, which resolves this issue for me. I see no mention of 'latest' as a valid input in the documentation for this task or the page for downloading the latest version. https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#download-the-latest-version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbb58a5-5e29-114a-cad4-dd4856926812
* Version Independent ID: 864f99cb-348d-21e9-c561-8ae1d038bb88
* Content: [Download Package task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/download-package.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-package-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
