### ISSUE TITLE
What happens to a PAT if user account is disabled?

### ISSUE THREAD

**Issue by flixman** [MicrosoftDocs/azure-devops-docs#12481]
What happens with the valid PAT, when a User Account is disabled in Azure DevOps. Are the still valid to the given date or are they become invalid?

The answer given [in this previous answer](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2124) is about the behavior of the system when the account is removed, but does not state what happens when the account still exists in AAD, but is disabled.

**Comment by WilliamAntonRohm** [comment]
@flixman -- thank you for your question and research.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@chcomley -- please look into this issue regarding [xxxx](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts).

**Comment by chcomley** [comment]
Hi @flixman, The PAT is also invalidated in Azure AD, as it belongs to the user. We recommend that the user rotate their PAT to another user/service account in order to keep services running. I've just added this as an FAQ in the article. Once published, this issue automatically closes. Thanks so much for your feedback.
