### ISSUE TITLE
Cloning Private repo from github.com

### ISSUE THREAD

**Issue by mikeguyre** [MicrosoftDocs/azure-devops-docs#12524]
[Enter feedback here]
I attempted to use the procedures in this document to clone a private repo on github.com and it didn't work. The Azure page
states "Import request cannot be processed due to one of the following reasons: Clone URL is incorrect Clone URL requires authorization. I am using the correct username and password.

If I try to clone the repo using --bare, I get the following
git clone --bare https://github.com/comverge/GenX_LCS.git
Cloning into bare repository 'GenX_LCS.git'...
Username for 'https://github.com': ###########
Password for 'https://##############@github.com':
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/comverge/GenX_LCS.git/'
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ee2ecc-cc6e-efa6-b377-bfc4b1aaf711
* Version Independent ID: 3c450bc7-7ed5-ea6b-ab6c-364511cf56ed
* Content: [Import a Git repo into your project - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-git-repository?view=azure-devops)
* Content Source: [docs/repos/git/import-git-repository.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/import-git-repository.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@mikeguyre -- Mike, thank you for your feedback.  That error message indicates you'll need to use a personal access token rather than a password.  Please see [this article](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

Also, consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
