### ISSUE TITLE
Ubuntu build server, Azure DevOps web site pipleline bails on syntax for the DeleteFiles input shown on this post

### ISSUE THREAD

**Issue by BillMac4440** [MicrosoftDocs/azure-devops-docs#12567]
Ubuntu build server, Azure DevOps pipeline bails on any input syntax for the DeleteFiles shown in this post.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852af26b-c4bf-d93d-caac-de7809312156
* Version Independent ID: 8fbea064-0ca7-520e-4ba7-c7322804ff78
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@BillMac4440 -- Bill, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- Steve, please look into this potential documentation issue.

**Comment by steved0x** [comment]
@BillMac4440 We just published a new task reference that is autogenerated from the task source, and includes the latest inputs, aliases, dependencies, allowed values, and YAML syntax block. Could you check to see if your issue is resolved using the latest documentation? If it still fails, please open a new doc issue and let us know. Thank you.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/delete-files-v1?view=azure-pipelines
