### ISSUE TITLE
The dropdown menu ⋮ to remove a GitHub connection is not being shown

### ISSUE THREAD

**Issue by NicolasDue** [MicrosoftDocs/azure-devops-docs#12600]
I want to remove a GitHub connection I've made but the button for this step is not there.

Screenshot used in docs:
![image](https://user-images.githubusercontent.com/49825492/185671754-6558af2f-42d0-4d67-8117-89032b20f052.png)

My screenshot:
![image](https://user-images.githubusercontent.com/49825492/185672751-5a205f1c-260f-4930-b8a3-a9035efd54ab.png)

No ⋮ button found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db555e9d-f86e-be8e-be13-d9d10e1b54d0
* Version Independent ID: 21327f5a-4731-3004-86bf-05954134119e
* Content: [Add or remove GitHub repositories - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/add-remove-repositories?view=azure-devops)
* Content Source: [docs/boards/github/add-remove-repositories.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/github/add-remove-repositories.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@NicolasDue - Thank you for your inquiry. Could you check that you are a member of the Project Administrators group for your project? It may be that you were when you added the repo but it has since changed. If that isn't the issue, then I recommend that you report your issue on our [Developer Community page](https://developercommunity.visualstudio.com/report?space=21&entry=problem).  They may be able to help you troubleshoot further.
