### ISSUE TITLE
Is there a limit on the number of work items that are pulled into Delivery Plans?  

### ISSUE THREAD

**Issue by amitamorakhia** [MicrosoftDocs/azure-devops-docs#12740]
[Enter feedback here]
It appears that certain features are not displayed on the delivery plan and when i reduce the number of items brought for delivery plan by remvoing stories , it appears to display all the features. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3b97a42-36e5-7023-a48f-d97c8ef71482
* Version Independent ID: b8ec620f-e9f0-6f5b-d1e6-9877310c3403
* Content: [Frequently asked questions (FAQs) about Delivery Plans - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/plans/faqs?view=azure-devops)
* Content Source: [docs/boards/plans/faqs.yml](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/plans/faqs.yml)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@amitamorakhia - Thank you for your inquiry. There isn't a limit to the number of work items displayed in the delivery plan.  When you say -- "certain features are not displayed on the delivery plan" - what specific features are you referring to? 

Please review the information provided [Review team delivery plans in Azure Boards, Prerequisites](https://learn.microsoft.com/azure/devops/boards/plans/review-team-plans?view=azure-devops#prerequisites) to ensure you have configured everything as required.  

Otherwise, if you continue to see problems, please post your issue on our [Community page](https://developercommunity.visualstudio.com/search?space=21) with as much detail as possible.
