### ISSUE TITLE
PR merged but list of authors not updated

### ISSUE THREAD

**Issue by tymtam2** [MicrosoftDocs/azure-devops-docs#12742]
#12699  is merged and released but the page's list of authors doesn't contain the author of the PR. 

Page affected: docs/project/wiki/wiki-markdown-guidance.md

Is there a threshold of trivial-ness? 

*(It's my PR and my name is missing and creating this issue seems really petty and self-serving, but let's say I'm doing it so that **others** are not left unacknowledged in the future 😉)*

**Comment by WilliamAntonRohm** [comment]
@tymtam2 -- Tymek, thank you for feedback, and yes I do not see you in the list of Contributors.  As to your question, I'm not sure!

@chcomley -- Chrystal, do you know how the Contributors are counted, or who to ask?

**Comment by chcomley** [comment]
@KathrynEE do you know how the list of Contributors works?

**Comment by chcomley** [comment]
@tymtam2, I've contacted the right person and will update you as soon as I hear back. Thanks.

**Comment by WilliamAntonRohm** [comment]
@chcomley -- Chrystal, was that person able to determine the cause here?

**Comment by chcomley** [comment]
My assumption is that although there isn't a strict threshold for what qualifies as “trivial” or “non-trivial” in terms of PR authorship, the omission of an author's name could occur due to the significance of the changes made. If the PR involves substantial modifications, it’s more likely to be recognized. Also, automated changes (e.g., formatting, typo fixes) might not always list authors explicitly. I'm not aware of any specific guidelines on when credit goes to authors for this repo.

Here's what you can do: you could comment on the PR and mention that your name is missing from the list of authors. Our PR reviewers may have more insight. Sorry for any frustration.
