### ISSUE TITLE
Some settings need attention

### ISSUE THREAD

**Issue by skywalker45** [MicrosoftDocs/azure-devops-docs#12839]
[Enter feedback here]
  When scheduling a trigger for a pipeline through the UI. I see "Some settings need attention" on the YAML tab. Literally, any other information would help. What settings need my attention? the yml file? Maybe mention it in the documentation or something. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/process/scheduled-triggers.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@skywalker45 -- Luke, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- Steve, please look into this issue.

**Comment by AndyBird869** [comment]
I'm seeing the same problem on two pipelines created within the last week.

In both cases the pipeline is saved and triggers/runs successfully. No indication of any issues in the UI and no clue about where the problem is.

![image](https://user-images.githubusercontent.com/61562155/199968386-7b422410-115e-4e97-b649-6d92d402441d.png)

**Comment by drolevar** [comment]
Same for me. If I choose an on-prem build agent, the warning disappears. When I choose the hosted one again, the warning appears again.

**Comment by LarsWH** [comment]
Please Azure DevOps! Tell us what setting is needing our attention! This is not a helpful warning message.

**Comment by steved0x** [comment]
@skywalker45 @LarsWH @drolevar @AndyBird869 I can't get this issue to reproduce (I can create a YAML pipeline and add UI schedules on a hosted agent), and I am not sure what the settings are that would need attention. 

My first guess was that it may be a transient issue in the Azure DevOps portal, but this issue has a recent comment indicating the issue is still present.

I agree that is an unhelpful error message, my suggestion would be to file a product bug and request for this error message to be improved: https://developercommunity.visualstudio.com/AzureDevOps - if you have a simple scenario that can reproduce the issue, please include that.
Thank you,
Steve
