### ISSUE TITLE
DownloadPackage@1 does not describe 'latest' version usage

### ISSUE THREAD

**Issue by JasonWhall** [MicrosoftDocs/azure-devops-docs#12911]
The DownloadPackage@1 task looks to support a 'latest' option in the version and was introduced in [this pr to the task](https://github.com/microsoft/azure-pipelines-tasks/pull/12334) however it looks like this has not been updated in the documentation.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbb58a5-5e29-114a-cad4-dd4856926812
* Version Independent ID: 864f99cb-348d-21e9-c561-8ae1d038bb88
* Content: [Download Package task - Azure Pipelines](https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/utility/download-package?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-package.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/tasks/utility/download-package.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@JasonWhall -- Jason, thank you for your feedback and PR.

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference, which is generated using the task source code and includes all task inputs, including any [aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/download-package-v1?view=azure-pipelinesdocs/authoring/yaml-tasks.md#making-life-easier-for-yaml-users) here:
https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/download-package-v1?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
