### ISSUE TITLE
Out of date information. Unusable

### ISSUE THREAD

**Issue by sethpolevoi** [MicrosoftDocs/azure-devops-docs#13046]
This page, https://learn.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#change-settings, is not up to date and it's impossible to follow the instructions. 

https://azure.microsoft.com/en-us/products/devops/boards/ landing page is different. There isn't a "sign up with GitHub" option. And It doesn't prompt you to create a project when you sign up for free and select a github account. 

I can't get to https://dev.azure.com/ and I don't know the name of my "organization". 

I can't figure out how to get to the Azure Boards product

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c985016-9453-7c7f-bbbd-39252037b807
* Version Independent ID: ea8f7d65-dc88-d11d-4358-ac7b31a20827
* Content: [Sign up for and invite teammates to use projects in Azure Boards - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/get-started/sign-up-invite-teammates?view=azure-devops#create-project)
* Content Source: [docs/boards/get-started/sign-up-invite-teammates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/get-started/sign-up-invite-teammates.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@sethpolevoi - I'm sorry you're having problems signing in to https://dev.azure.com/. I just tried signing in using my GitHub account and encountered problems as my GitHub account is associated with my Microsoft organization account. In these cases, signing in requires that I use my Microsoft organization account. Is it possible that your GitHub account is associated with another work or school account? If so, then perhaps you might try using that. 

If you continue to have problems, I recommend that you post your issue here:  [Developer community page](https://developercommunity.visualstudio.com/AzureDevOps/report).

**Comment by NenoLoje** [comment]
@sethpolevoi Try navigating to https://aex.dev.azure.com - after signing in, it shows any Azure DevOps organizations you are a member of.

**Comment by KathrynEE** [comment]
@sethpolevoi - We are investigating the changes that have been made and will update our content accordingly.

**Comment by NenoLoje** [comment]
@KathrynEE I think this is related to #13048 and has been resolved with the landing page now showing a "Sign in with GitHub" button again.

@sethpolevoi Can you confirm that?

**Comment by KathrynEE** [comment]
@sethpolevoi - The starting page had been changed but has now been refreshed and reverted to its former view, so I think the documentation is up to date. The page now shows the **Start free with GitHub** option.  I'm closing this issue as no need to fix. 

![image](https://user-images.githubusercontent.com/10856840/213790599-10b606af-2a80-4b44-a4e8-b3775f449e5f.png)
