### ISSUE TITLE
add System.JobPositionInPhase and System.TotalJobsInPhase to predefined variables list

### ISSUE THREAD

**Issue by SanderMeesterIndepender** [MicrosoftDocs/azure-devops-docs#13053]
It would be great if the existence of System.JobPositionInPhase and System.TotalJobsInPhase would be mentioned on this paage

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thanks for your suggestion @SanderMeesterIndepender. I checked with the product team on this one and they said that the reason these two variables aren't documented is because they do not consistently behave the same way. The value of `TotalJobsInPhase` can vary depending on the stage and how it was created. `JobPositionInPhase` isn't guaranteed to replicate the order of your YAML, which can be confusing to customers. 

I'm closing this but please feel free to open an issue in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) if these are variables that you need to have consistently work the same way.
