### ISSUE TITLE
Pull Requests templates not working as explained in docs

### ISSUE THREAD

**Issue by akserikawa** [MicrosoftDocs/azure-devops-docs#13056]
Pull Request template is not being applied on my repositories. Tried all the options and is not working. 
Are there any other steps necessary? Settings in DevOps?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve pull request descriptions with pull request templates - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/pull-request-templates.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by Breno709** [comment]
Same issue here.
In my case, mysteriously in some repos it works and others dont.

I can't even add a template manually because it doesn't show the option. The only option showed is "add commit messages":
![image](https://user-images.githubusercontent.com/8755602/215103042-4671807e-de87-49a3-97f4-f01b08c6680b.png)

In the repos where PR template is working, it shows the option to add template:
![image](https://user-images.githubusercontent.com/8755602/215103429-35e88cde-7076-45c4-a108-698e530df2e8.png)

Why does it happens?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
