### ISSUE TITLE
Project/Team image resolution information

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/azure-devops-docs#13057]
It is proving to be difficult to find the correct image resolution to use for setting a project's image. While the file size is specified the image resolution is not. Our company logo doesn't fit and it doesn't appear it resizes the image to fit in the desired space either. This leaves us with a guessing game as to what resolution the image should be in order to fit properly in the UX.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd1eb12-58c8-4128-d5de-bda134e9c5f6
* Version Independent ID: dac4ba9d-20ef-50e6-dacf-88db9c4f3d92
* Content: [Manage teams, configure team tools - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/manage-teams?view=azure-devops)
* Content Source: [docs/organizations/settings/manage-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/settings/manage-teams.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mtaylorfsmb - I've reached out to the product team to get additional information. You might also try posting your request on our [Developer community page](https://developercommunity.visualstudio.com/AzureDevOps/report).

**Comment by chcomley** [comment]
According to the [Organization image guidelines](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-image?view=azure-devops), the max image size allowed is 2560 x 1024, and then we resize to 200 x 200. I believe this also applies to project/team images. Thanks.

**Comment by CoolDadTx** [comment]
@chcomley Why did you close this? The issue is that it isn't documented anywhere on the page that is mentioned. As a user we have to keep uploading and trying images until one that fits works. If there is a separate page that discusses the rules then at a minimum it should be mentioned on the page mentioned in this issue as nobody is going to find a random page in the docs that mentions this. 

I do not consider this issue resolved and believe it should be reopened and the documentation updated.

**Comment by chcomley** [comment]
The PR just went through, thanks for following up.
