### ISSUE TITLE
Missing information about ARM64 and ARM32 support in Microsoft Hosted Agent

### ISSUE THREAD

**Issue by hlavingia** [MicrosoftDocs/azure-devops-docs#13209]
[Enter feedback here]

This page is missing information about ARM64 and ARM32 support for Microsoft Hosted Agent. I have to build docker images for X64, ARM32 and ARM64 and research to see if Microsoft hosted agent works for ARM32 and ARM64 platform but can't find specific information on Microsoft Doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/hosted.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@hlavingia -- thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- please look into this issue.

**Comment by steved0x** [comment]
Microsoft-hosted agents are available in the platforms listed on the page under the Software section:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

The virtual machine specs are listed in the Hardware section:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#hardware

There aren't any sections about ARM64 and ARM32 support because that doesn't apply to Microsft-hosted agents.

For information on self-hosted agents, see: https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/v3-agent?view=azure-devops which has a list of supported OS using ARM64.
