### ISSUE TITLE
How to use a PAT in YAML for Build/Release via AzureDevOps

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/azure-devops-docs#13233]
Can you add to the documentation how to use a PAT in YAML for Build/Release via AzureDevOps? I created a PAT and set it it as a secret Pipeline variable. However, I'm unable to use the token in YAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Use personal access tokens - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
Hi @ilantom -- thank you for your question.  While we look into changes for the article, please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by chcomley** [comment]
Hi there, I haven't received feedback on this from anyone. I've searched our resources and found some information that I hope is helpful. If you're still experiencing issues, please see [Run commands in a YAML build pipeline/Authenticate with Azure DevOps](https://stackoverflow.com/questions/52837980/how-to-allow-scripts-to-access-oauth-token-from-yaml-builds) and this Stack overflow item: https://stackoverflow.com/questions/52837980/how-to-allow-scripts-to-access-oauth-token-from-yaml-builds. Please @mention me if you need more help, but I'll close this issue for now, since there's no update to the original article. Thank you.
