### ISSUE TITLE
Why does the burndown widget show also the completed work items?

### ISSUE THREAD

**Issue by royaza** [MicrosoftDocs/azure-devops-docs#13265]
[When I clicked on the remaining work items on the burndown diagram, it also shows me the work items whose state is closed. 
I think this is wrong and they must be categorized as completed. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9d627b9-9aa8-c52c-3178-cffbefe9727a
* Version Independent ID: 31967bb3-2635-da97-782c-641f432750f7
* Content: [Configure Burndown & Burnup widgets - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops)
* Content Source: [docs/report/dashboards/configure-burndown-burnup-widgets.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/report/dashboards/configure-burndown-burnup-widgets.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-analytics**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@royaza -- Roya, thank you for your feedback.  This issue seems product-related, rather than documentation-related.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
