### ISSUE TITLE
If Azure DevOps charges for users account that has been disabled but not deleted ?

### ISSUE THREAD

**Issue by TapanKumarBarik** [MicrosoftDocs/azure-devops-docs#13275]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 325bc6fd-a373-5be4-01e6-3e07f9a7b6b1
* Version Independent ID: 9f8ff78f-5e2c-522b-ebd4-3086f444cac3
* Content: [Billing FAQs - Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops)
* Content Source: [docs/organizations/billing/billing-faq.yml](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/organizations/billing/billing-faq.yml)
* Service: **azure-devops**
* Sub-service: **azure-devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by TimShererWithAquent** [comment]
@TapanKumarBarik - I want to be sure to understand your question - are you asking Azure DevOps charges for users account that has been disabled or are you _suggesting_ that this would be a good question for the FAQ to address? Please let us know.

If you want to find out more about the question, consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by TapanKumarBarik** [comment]
Hi @TimShererWithAquent ,

I tried searching for the answer and could not find any direct answer, it would be good if we could add this question to FAQ.

It would be really helpful.

**Comment by chcomley** [comment]
Hi @TapanKumarBarik, thanks for reaching out. We already have it covered. If you have further suggestions, please let me know. Thank you!
[FAQ - What happens when a user is deleted in Azure AD?](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#q--what-happens-when-a-user-is-deleted-in-azure-ad-)
We call out that the user's automatically removed only when they’re permanently deleted in Azure AD, which implies that we don’t remove them automatically before then.

[FAQ - How can I stop paying for users who aren't actively using Azure DevOps?](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#q--how-can-i-stop-paying-for-users-who-aren-t-actively-using-azure-devops-)
Here we explain how to stop getting charged, for example, remove them from the organization.

**Comment by chcomley** [comment]
Hi @TapanKumarBarik, thanks for reaching out. We already have it covered. If you have further suggestions, please let me know. Thank you!
[FAQ - What happens when a user is deleted in Azure AD?](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#q--what-happens-when-a-user-is-deleted-in-azure-ad-)
We call out that the user's automatically removed only when they’re permanently deleted in Azure AD, which implies that we don’t remove them automatically before then.

[FAQ - How can I stop paying for users ](https://learn.microsoft.com/en-us/azure/devops/organizations/billing/billing-faq?view=azure-devops#q--how-can-i-stop-paying-for-users-who-aren-t-actively-using-azure-devops-)
Here we explain how to stop getting charged, for example, remove them from the organization.

**Comment by TapanKumarBarik** [comment]
Hi @chcomley , Hi @WilliamAntonRohm , Thanks for the quick response . Yes i am happy with the response , sorry missed it .Now i am clear .

In a side note i also wants to contribute to microsoft docs . How i can do it ? or it is only for internals ?

**Comment by chcomley** [comment]
@TapanKumarBarik we'd love to have you contribute to our docs! https://learn.microsoft.com/en-us/contribute/
