### ISSUE TITLE
No possible to select base-branch for New branch

### ISSUE THREAD

**Issue by WardLootens** [MicrosoftDocs/azure-devops-docs#13277]
The screenshot that shows how to create a branch starting from a work item (git-dev-create-branch.png) shows that it should be possible to select
* the repo
* the branch in that repo to start from

However, when I create a 'New branch' from a work item, all I can select is
* the repo

So I have no possibility to select the starting branch.
It seems to create the branch starting from the branch marked as  'Default' in the repo, which is not always desired.

Anything I'm missing?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d125435-dbfb-c199-65ed-34ad33b1f522
* Version Independent ID: 04cae7ee-1e54-a002-bb7b-c93a606e982f
* Content: [Drive Git development from user story and requirements - Azure Boards](https://learn.microsoft.com/en-us/azure/devops/boards/backlogs/connect-work-items-to-git-dev-ops?view=azure-devops)
* Content Source: [docs/boards/backlogs/connect-work-items-to-git-dev-ops.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/boards/backlogs/connect-work-items-to-git-dev-ops.md)
* Service: **azure-devops-boards**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@WardLootens -- Ward, thank you for your feedback and question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@chcomley -- Chrystal, please look into this potential documentation issue.

**Comment by teddy5** [comment]
@WilliamAntonRohm it was previously possible to select a base branch and this functionality seems to have been removed in the last week or two. It is also still possible when navigating through the Branches tab.

Instead of looking at this as a documentation issue, could it instead be looked at to put this functionality back in? This change has broken the general workflow of creating branches off a feature branch while updating a work item/user story.

**Comment by KoenVanhove** [comment]
@WilliamAntonRohm We are experiencing the same issue since this morning, so no longer able to select the correct base branch of a repo. 
This broke our workflow we've been using for years of creating work items, and then create a branch which is linked automatically.

As @teddy5 requested: would it be possible to put this functionality back in?

**Comment by WilliamAntonRohm** [comment]
@teddy5, @KoenVanhove -- thank you for your follow-up.  Please add this issue here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
