### ISSUE TITLE
Agents folder not available in Azure Devops 2022

### ISSUE THREAD

**Issue by blakeduffey** [MicrosoftDocs/azure-devops-docs#13368]
The documentation references the following:

`For servers with no internet access, manually copy the agent zip file to C:\ProgramData\Microsoft\Azure DevOps\Agents\ to use as a local file.`

This folder existed on Azure Devops Server 2019 and I used this method regularly to keep the onprem agents updated.

I recently upgraded to Azure Devops Server 2022 (fresh install on a new host).  This folder doesn't exist.  There is only 

```
Configuration
Server Configuration
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c09c1b4b-fe93-9c4e-32d7-055c88eb902d
* Version Independent ID: 020f1e59-284e-439f-2cab-d12bdb807a87
* Content: [Azure Pipelines Agents - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops-2022&tabs=browser)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/agents/agents.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@blakeduffey -- Blake, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
@blakeduffey I just went to my test Azure DevOps Server 2022 VM, and the Agents folder is there, but I am not sure that is a valid comparison with you, since I just recently updated the agent on that 2022 version (from an earlier RTW to the latest after I upgraded my installation) and I wouldn't be surprised if that folder was created at that time. Subsequently to that I manually did an agent version upgrade, and I also can't be sure that I didn't create the Agents folder myself before downloading the zip file.

But, I do have a clean Azure DevOps Server 2020 VM, on which I have never updated this agent version. It does not have the agent folder, it just has "Server configuration". I created the Agents folder, downloaded a newer agent zip file from the Agents GH releases page and copied it into that folder, and when I instructed the agent to update itself, it did using the newer version I downloaded. I will reach out to the team to confirm but I believe if the Agents folder isn't there, you can create it before copying the agent file.

I will update the documentation to reflect this detail in the agents article once I confirm.

Please reactivate this issue (or open a new one) if creating the agents folder in the designated location and copying the agent file into that location doesn't work for you.

Thank you,
Steve

**Comment by blakeduffey** [comment]
@steved0x - thanks for your help.  I will confirm that creating the folder works but it isn't there by default on a fresh install.

Appreciate your help.
