### ISSUE TITLE
Need to update pipeline lesson with instructions for running with local agent.

### ISSUE THREAD

**Issue by dennisreda** [MicrosoftDocs/azure-devops-docs#13549]
There are no instructions for how to run the pipeline using my own hosted agent. With the recent cutoff of free parallel jobs by Microsoft, all of my pipelines need to be run with a local agent. 

I have successfully installed the local agent and I've run and "empty" pipeline with success. So, I know that I'm ready to set up on my side. But I don't know how to edit the yaml file or make other changes to run using my local agent.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad567ab-0513-570b-74dc-a0827815c6a1
* Version Independent ID: 5e549605-cac8-98ea-ac5b-89f4a40a5f3c
* Content: [Create your first pipeline - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/create-first-pipeline.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@dennisreda -- Dennis, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
@dennisreda You can apply for the free grant of parallel jobs by submitting a form [here](https://aka.ms/azpipelines-parallelism-request). The response is usually 2-3 business days. Unfortunately Pipelines team has had to [disable the automatic free grant due to abuse](https://learn.microsoft.com/en-us/azure/devops/release-notes/2021/sprint-184-update#azure-pipelines-1), primarily from crypto currency mining. If you can wait a few days, this is probably the simplest choice.

Another choice for getting started while waiting for the free grant is to check out our training module, [Create a build pipeline](https://learn.microsoft.com/en-us/training/modules/create-a-build-pipeline/) which has an option for using a self-hosted agent using GitHub Codespaces. While this is not a production scenario, it does allow the training module to be complete without waiting for the free grant or having to pay for a parellel job.

When creating a pipeline (either using a private/local agent or a Microsoft hosted agent), you have 2 choices for editing the pipeline:

1. You can edit the azure-pipelines.yml file directly in the repository that hosts the pipeline
2. You can edit the pipeline in the [YAML Pipeline editor](https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/yaml-pipeline-editor?view=azure-devops) in the Azure DevOps portal

For example, if you have created an empty pipeline, and you want to add some stuff to it, you can browse to the [Pipeline details](https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline#view-pipeline-details) and choose **Edit**.

I will add some more detail to this article to cover these points and will report back here when I do.

Thank you,
Steve

**Comment by steved0x** [comment]
I have added some notes to these articles:
https://learn.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline#view-pipeline-details
https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/yaml-pipeline-editor
