### ISSUE TITLE
How to import private network repository into Azure Devop

### ISSUE THREAD

**Issue by Pun-Mengly** [MicrosoftDocs/azure-devops-docs#13570]
I have a gitlab was called URL https://gitlab.organization-name.com/ that is a my **private network** for internal access only. And I have a Azure DevOps account, I wanna import my **private network** repo in https://gitlab.organization-name.com/username/test-ci-cd.git to my Azure account. Does is it possible for importing? And, How should I do?

*Note: for **public network** repo like https://gitlab.com/username/test-ci-cd.git, It is work fine when importing to Azure DevOps repo. 
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/azure-devops-docs/issues/11947
```

**Comment by WilliamAntonRohm** [comment]
@Pun-Mengly -- Mengly, thank you for your questions.  Are you following a particular learn.microsoft.com article?  Meanwhile, please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by Pun-Mengly** [comment]
@WilliamAntonRohm Thanks, I have review them a long time, Make clear about my issue.
Is it possible for migration Gitlab Enterprise Server in Azure DevOps pipline?

I found only Github Enterprise Server. So, is it possible for Gitlab Enterprise Server? And, How to archieved this? kindly to help mw with this issue. Thank you...

**Comment by WilliamAntonRohm** [comment]
@Pun-Mengly -- Mengly, thank you for your follow-up.  This repo is solely for documentation issues, and this is implementation-related.  I hope these links and their context will help with your scenario:
- [What happens if a developer tries to push directly to production?](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/governance/end-to-end-governance-in-azure#what-happens-if-a-developer-tries-to-push-directly-to-production)
- [Install GitLab on Microsoft Azure](https://docs.gitlab.com/ee/install/azure/)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again

**Comment by diegodelico** [comment]
Hi @Pun-Mengly, we have the same issue in my company, how have you resolved it? we have 2 ideas, first one (and easy) is public to internet our gitlab. the second one is trying to connect through VPN to our private network.
