### ISSUE TITLE
Clarification on export user list with AD Groups?

### ISSUE THREAD

**Issue by breakpoint7** [MicrosoftDocs/azure-devops-docs#13637]
Related documentation link: https://learn.microsoft.com/en-us/azure/devops/organizations/security/export-users-audit-log?view=azure-devops&tabs=azure-devops-cli

The documentation for exporting users states that "You can list the users in an organization with the [az devops user list] command, **which doesn't apply to users added via Azure Active Directory groups**. To get started, see [Azure DevOps CLI](https://learn.microsoft.com/en-us/azure/devops/cli/?view=azure-devops)."

However, when the list is exported it does seem to list group users and indicate via assignmentSource that the license is assigned via "groupRule" instead of "account".

What is meant by "doesn't apply to users added via Azure Active Directory groups"?

**Comment by WilliamAntonRohm** [comment]
@breakpoint7 -- Reed, thank you for your feedback and question.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@chcomley -- Chrystal, please look into this issue.

**Comment by chcomley** [comment]
Thanks for your feedback. I've updated the article with some clarification, which should be live shortly. Basically, when you export the list, you might notice that group users are indicated with an “assignmentSource” of “groupRule.” This signifies that their access is determined by the group membership rules rather than individual settings. Thank you!
