### ISSUE TITLE
It is not able to set permission as this document

### ISSUE THREAD

**Issue by hoikin** [MicrosoftDocs/azure-devops-docs#13669]
[Enter feedback here]

There is no way to use tf.exe and please check if this page is out of date or note 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ddce170-618e-1307-d9bd-7113921521cc
* Version Independent ID: d60a1133-34d9-8e56-e716-526584fd67e0
* Content: [Require branches to be created in folders - Azure Repos](https://learn.microsoft.com/en-us/azure/devops/repos/git/require-branch-folders?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/require-branch-folders.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/repos/git/require-branch-folders.md)
* Service: **azure-devops-repos**
* Sub-service: **azure-devops-repos-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
@hoikin -- thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@vijayma -- please look into this issue.

**Comment by ramiMSFT** [comment]
@hoikin Thanks for your feedback! I've tested it, and it's working on my end. Make sure you have Visual Studio installed because it includes tf.exe. You can run it from Visual Studio Tools > Command Line > Developer Command Prompt. You can also use the Windows search bar to look for Developer Command Prompt, open it, and run your tf.exe commands from there.
See [Use Team Foundation version control commands](https://learn.microsoft.com/en-us/azure/devops/repos/tfvc/use-team-foundation-version-control-commands?view=azure-devops)
and [Visual Studio Developer Command Prompt and Developer PowerShell](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022) for details
