### ISSUE TITLE
Ability to get status badge for latest pipeline run irrespective of branch

### ISSUE THREAD

**Issue by JPStrydom** [MicrosoftDocs/azure-devops-docs#13826]
Curranty, there is no way to get a status badge for the latest pipeline run irrespective of the branch that triggered the pipeline. One either gets the latest pipeline run status for the default branch, or the specified branch. But if one were to use feature branches or versioned tags to run pipelines from, the only way to get the status is to manually update the status badge branch, which is not maintainable.

[This issue](https://developercommunity.visualstudio.com/t/status-badge-for-all-branches-latest-build/684754) seems to cover it, but there doesn’t seem to be a solution for the issue.

[Here](https://developercommunity.visualstudio.com/t/Ability-to-get-status-badge-for-latest-p/10527472) is a link to the related issue I captured on Azure's dev community.

**Comment by WilliamAntonRohm** [comment]
@JPStrydom -- JP, thank you for your thorough feedback, and for raising that Azure dev issue.  Please consider these resources, if you haven't already:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

As this is a product issue, rather than related to documentation, I am closing this now.  You are welcome to @ mention me for any followup.
