### ISSUE TITLE
document Pipeline.StartTime variable on "Predefined variables" page

### ISSUE THREAD

**Issue by carlin-q-scott** [MicrosoftDocs/azure-devops-docs#13835]
The Pipeline.StartTime pre-defined variable is [documented here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#format) but it's not documented on this pre-defined variables page.

#11535 Also points out that this variable is confusingly named because it's the Agent.StartTime, not the Pipline.StartTime. So that should be called out in the documentation.

I'm also unsure what format the start time variable is in, and I want to reference it directly in a bash script. So an example of the format would be very helpful. Or better yet, an example of how to convert it to Unix time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11d3469c-83c2-c2f6-41d0-08f82c330bbc
* Version Independent ID: a373c48d-6395-3002-d2d8-bbc1fea2e48e
* Content: [Predefined variables - Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/main/docs/pipelines/build/variables.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by rufer7** [comment]
As far as I understood when reading the [linked docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#format), `pipeline.startTime` is not available outside of expressions. As it can not be referenced as environment variable and because it's only available inside expressions, I assume it's intended to not be listed under [Predefined variables](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml).

```
pipeline.startTime is not available outside of expressions. pipeline.startTime formats system.pipelineStartTime into a date and time object so that it is available to work with expressions. The default time zone for pipeline.startTime is UTC. You can [change the time zone](https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/change-time-zone?view=azure-devops) for your organization.
```

Source: https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by juliakm** [comment]
There are other predefined variables with unique circumstances that are also not included in the predefined variables article. You can see all of the predefined variables available in a pipeline with a script task.

```
- script: 'env | sort'
```
