### ISSUE TITLE
Building Azure DevOps extension using Blazor 2024

### ISSUE THREAD

**Issue by GeorgeS2019** [MicrosoftDocs/azure-devops-docs#13953]
We need a coordinated approach between Azure DevOps team and user-initiated Blazor as technology to build Azure DevOps Extension

This issue will discuss **what tricks are needed** to make this work.

@MaciekWin3
> https://github.com/MaciekWin3/azure-devops-blazor-extension
> We need discussion [what modifications needed](https://github.com/MaciekWin3/azure-devops-blazor-extension/issues/2) to the Azure DevOps through SDK

**How these tricks** could be **integrated into future versions** of e.g. Azure DevOps Server to support Azure DevOps Extension development using Blazor a seamless approach.

This issue also **tracks interest** in better supporting Blazor for developing the Azure DevOps Extension

### [Develop a web extension](https://learn.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)

**Comment by GeorgeS2019** [comment]
This could potentially address the missing Mermaid diagrams currently not available in e.g. Azure DevOps Server
https://github.com/TrueCommerce/MermaidJS.Blazor

**Comment by WilliamAntonRohm** [comment]
@GeorgeS2019 -- George, thank you for your feedback.  If you feel this is a product issue, please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

@chcomley -- Chrystal, please look into the documentation aspects of this issue.

**Comment by MaciekWin3** [comment]
Hi @GeorgeS2019,
Regarding your question, I think the best way forward is to make sure we have solid documentation and officially confirm that building it with Blazor is doable. In my experience, I've successfully developed an extension that's currently operational in a production environment.
In my [repository](https://github.com/MaciekWin3/azure-devops-blazor-extension) which showcases an Azure extension built with Blazor, I employed several workarounds to ensure functionality:
- The entire project, including the Blazor runtime, is compiled into the 'dist' folder. This is then packaged as an extension. You'll need to configure this in the [vss-extension.json](https://github.com/MaciekWin3/azure-devops-blazor-extension/blob/master/src/AzDevOpsBlazorExtension/vss-extension.json) file. Also I recommend checking [build script](https://github.com/MaciekWin3/azure-devops-blazor-extension/blob/master/src/AzDevOpsBlazorExtension/build.ps1).
- A significant challenge involves the Azure DevOps SDK. I created a specific file based on [azure-devops-extension-sdk](https://github.com/microsoft/azure-devops-extension-sdk). From what I recall, I had to compile two files (SDK.ts and XMD.ts) into JavaScript, merge them, and then make additional modifications due to some compatibility issues I encountered, particularly with features not supported by ES6.
- A minor point, but worth mentioning: The command I used for debugging `dotnet watch run --pathbase=/dist` doesn’t work with .NET 8. However, a fix is already in progress, and a temporary workaround is described [here](https://github.com/dotnet/aspnetcore/issues/52294).

My recommendation is to focus on providing comprehensive documentation, and we developers can manage the rest 😁 Additionally, some assistance in supplying the JavaScript SDK file would be beneficial, as my current implementation was more of a trial to test functionality rather than an effort to maintain updates. If you have any more questions, I am happy to answer them. Also, try to use my [repo](https://github.com/MaciekWin3/azure-devops-blazor-extension) as a template. That will give you a clearer picture of the challenges. I tried to document the whole process in README.md, so check that too. If you encounter any bugs, feel free to submit an issue or PR.

Also, if I can add my two cents here, I was a little bit surprised that there was almost zero info or effort on building Azure DevOps extensions using Blazor WebAssembly. I think it presents a great chance to explore this framework and attract more interest within the Azure DevOps community, especially considering that many of them are already utilizing C# or possibly even Blazor in their professional tasks. However, they are then forced to use React to develop Azure DevOps extensions. By providing the option to develop Azure DevOps extensions in Blazor, we not only enhance the user experience but also contribute to the broader adoption of this promising technology. We are not just incorporating it; we're offering the choice to use Blazor, thus contributing to its wider acceptance. I see it as a win-win situation, offering a chance to showcase the capabilities of Blazor and provide developers with a more intuitive and efficient extension-building experience.

**Comment by GeorgeS2019** [comment]
@MaciekWin3 

Please kindly add a **suggest feature** request [here ](https://developercommunity.visualstudio.com/AzureDevOps)

I will try to get more people (blazor and mermaid and plantuml people who have tried [many many years since 2019](https://github.com/MicrosoftDocs/azure-devops-docs/issues/5872) to make the Azure DevOps server support Blazor so people can add more up to date features to e.g. Azure DevOps Wiki

**Comment by MaciekWin3** [comment]
I believe we don't necessarily require anything new at the moment. As evidenced by the POC in my repository, the solution I've created is functional. Therefore, I don't perceive a need for any updates to Azure DevOps to ensure its functionality. However, it would be beneficial to have an officially supported repository that encompasses everything one needs to kickstart the process of creating an Azure DevOps Blazor extension. This repository could include the latest JavaScript SDK and other relevant resources.

Additionally, there might be performance or other improvements that the Azure DevOps team could potentially implement. However, since I don't have access to their code and infrastructure, it's up to them to recognize whether they want to support building extensions in Blazor.

If you believe that creating a ticket using the provided link will contribute to this effort, please go ahead, and I will do my best to provide support when possible. I simply don't see the necessity of initiating another thread on a different platform and managing it separately
