### ISSUE TITLE
i want to get the email notification alert before expire of PAT token in azure devops

### ISSUE THREAD

**Issue by chauhanankit321** [MicrosoftDocs/azure-devops-docs#14065]
i want to get the email notifications before 1 week expire of PAT token in azure devops organization.

**Comment by steved0x** [comment]
@chauhanankit321 It looks like this is the default behavior based on this article: https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows#notifications

If your issue is different than this, please go to that article and add a new feedback that is linked to that article. This will put your feedback into our new documentation feedback system. Thank you.
