### ISSUE TITLE
Contracts.WorkItemExpand.Links not listed in documentation, but is in the API

### ISSUE THREAD

**Issue by tmcoma** [MicrosoftDocs/azure-devops-docs#2243]
I came here after using the REST client directly and noticed that "Links" isn't listed here, but it does appear in the contract (values as of right now appear to be {None, Relations, Fields, Links, All}).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1194ad40-5135-a623-b0d8-ac2d840a30f4
* Version Independent ID: d74ee28c-1040-fa33-0d35-716d5e80904a
* Content: [TFS/WorkItemTracking/Contracts WorkItemExpand API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/workitemtracking/contracts/workitemexpand?view=vsts)
* Content Source: [docs/extend/reference/client/api/TFS/WorkItemTracking/Contracts/WorkItemExpand.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/WorkItemTracking/Contracts/WorkItemExpand.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @willsmythe , is this something we want to document?

**Comment by chcomley** [comment]
This issue is stale and we're no longer updating this content regularly, so this issue will be closed. Please check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported. For more extension information, see the [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/develop/extensions), [REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-5.1), [Extension samples](https://github.com/Microsoft/azure-devops-extension-sample), and resources in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
