### ISSUE TITLE
Downloading secure file on Linux using Bash in CD

### ISSUE THREAD

**Issue by heruwala** [MicrosoftDocs/azure-devops-docs#2431]
I have built Build and Release pipeline using ubuntu.  Build was a smooth sail as yaml file took care of downloading. There is no YML (in pipeline) support in CD. How can I download a secure file in CD pipeline on hosted Ubuntu agent. is there a command for that in bash?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Hi @heruwala.  There's not a way to download a secure file from your own script.  Since "release pipelines" don't yet support YAML, the only way is to use the "Download Secure File" task in your release pipeline.  That will make the secure file available on disk for your script, and the file will automatically be deleted at the end of the release.  Please reopen this issue if we can provide additional help.

**Comment by hareesh309** [comment]
Hi @davidstaheli & Team,

I have stuck in a similar issue, do we have an improvement in the above mentioned requirement?

**Comment by WilliamAntonRohm** [comment]
@hareesh309 -- thank you for your follow-up.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@davidstaheli -- has there been any change in the product in this regard?
