### ISSUE TITLE
Default options

### ISSUE THREAD

**Issue by steevokovsky** [MicrosoftDocs/azure-devops-docs#2576]
Issue:
 - I can't find any default options for this or any other ui-control on this site or on  the api reference.

Solution:
- Add the default options either here or (which would make more sense) on the api page.
- Add the full list of options to the api site

Thanks a lot :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0953986b-fd40-e559-9072-e6f977f3040f
* Version Independent ID: 9b110d21-35db-6a36-a663-b275b318a264
* Content: [Use the Dialog Control](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/modaldialogo?view=vsts)
* Content Source: [docs/extend/develop/ui-controls/modaldialogo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/modaldialogo.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @steevokovsky , sorry about that. You've definitely hit a weak point in our docs. Adding @matthewisabel for awareness, we are going to try to get something in the backlog to make these docs stronger..and usable.

**Comment by lizhaoting** [comment]
you can find the options from the source code in the Network Console by F12

{
     urlReplacementObject: t.urlReplacementObject,
     height: t.height,
     width: t.width,
     draggable: t.draggable,
      resizable: t.resizable,
      ......
}

hope to help you

**Comment by chcomley** [comment]
Adding @jtpetty for further guidance, thank you!

**Comment by chcomley** [comment]
This issue is stale and we're no longer updating this content regularly, so this issue will be closed. Please check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported. For more extension information, see the [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/develop/extensions), [REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-5.1), [Extension samples](https://github.com/Microsoft/azure-devops-extension-sample), and resources in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
