### ISSUE TITLE
Missing documentation for "applyTheme" option.

### ISSUE THREAD

**Issue by nmiller-gauge** [MicrosoftDocs/azure-devops-docs#3068]
I have found no documentation for the "applyTheme" option.
The only way that I found that it existed was by reading through the type definitions found here:
https://raw.githubusercontent.com/Microsoft/vss-web-extension-sdk/master/typings/vss.d.ts

I found this option to be critical as it is the only way that I could find to get the Azure DevOps theme data into an extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c108d2f2-0e4a-5f86-713d-b360fde577b1
* Version Independent ID: af4e073c-a272-fea4-f17e-62751ccdfb4d
* Content: [VSS/References/VSS.SDK.Interfaces IExtensionInitializationOptions API](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/vss/references/vss_sdk_interfaces/iextensioninitializationoptions?view=vsts)
* Content Source: [docs/extend/reference/client/api/VSS/References/VSS_SDK_Interfaces/IExtensionInitializationOptions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/VSS/References/VSS_SDK_Interfaces/IExtensionInitializationOptions.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @nmiller-gauge, I'm adding @willsmythe for his input here into how we could make this experience better.

**Comment by chcomley** [comment]
Adding @jtpetty for further guidance, thank you!

**Comment by chcomley** [comment]
This issue is stale and we're no longer updating this content regularly, so this issue will be closed. Please check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported. For more extension information, see the [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/develop/extensions), [REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-5.1), [Extension samples](https://github.com/Microsoft/azure-devops-extension-sample), and resources in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
