### ISSUE TITLE
Inconsistency in "Sharing your Code"

### ISSUE THREAD

**Issue by damonfutter** [MicrosoftDocs/azure-devops-docs#3248]
At the start of the page it says, "Before you check in your code, ...."

Shortly after, it says, "To ask for a code review, make sure you have shared your code in TFVC.". The linked page describes how to check in your code, but not how to shelve your code. If the documentation is talking about "before you check in your code", it would be better if it linked to a page describing how to create a shelveset and get it reviewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bb12a7-a20c-1dd5-bca0-4873f7ab9e36
* Version Independent ID: 360739fd-e98a-535f-9872-ed58ece28194
* Content: [Get your code reviewed with Visual Studio - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/get-code-reviewed-vs?view=azure-devops#)
* Content Source: [docs/repos/tfvc/get-code-reviewed-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/get-code-reviewed-vs.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by trdsolutions** [comment]
It's not neccessary to know how to explicitly create shelvesets for Code Reviews, because creating a Code Review will shelve automatically (as far as I understood and as far as you don't request a Code Review based on a changeset, which is also possible). The linked article is used to be a Knowledge base how to synchronize your Code with TFVC in general. The article further explains how to check in code as changeset, so you know what to do after your code has been reviewed successfully.

**Comment by MaximMalygin** [comment]
@damonfutter Do you still need any help here?

**Comment by damonfutter** [comment]
@MaximMalygin No need for further help. Thanks for the nudge, I'll close this now.
