### ISSUE TITLE
Missing git info

### ISSUE THREAD

**Issue by MiroslavMikus** [MicrosoftDocs/azure-devops-docs#3253]
I assume that this feature is based on top of some kind of  `git rebase` feature. If so, it would be great to add this info to the docu. And add some side note like:

&gt; This feature (squash merge) is a destructive change to your git history!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dec464-f25a-5c46-52e7-2cbf17a2db1d
* Version Independent ID: bbe4d6d1-71a7-0c47-7bfb-1577760e003b
* Content: [Squash merge your pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=azure-devops)
* Content Source: [docs/repos/git/merging-with-squash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/merging-with-squash.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by apawast** [comment]
Hi @MiroslavMikus. The definition of the squash merge in the document is as follows: 

"Squash merging is a merge option that allows you to condense the Git history of topic branches when you complete a pull request. Instead of each commit on the topic branch being added to the history of the default branch, a **_squash merge takes all the file changes and adds them to a single new commit_** on the default branch...A simple way to think about this is that **_squash merge gives you just the file changes_**, and **_a regular merge gives you the file changes and the commit history._**"

 Does that help clarify further? If not, is there anything I can clarify further or specifically add to the document?

**Comment by MiroslavMikus** [comment]
Hi @apawast. Thank you for your answer.

The feature description is really great! I personally would like 2 more information or side notes.

1. This function is based on top of the **git rebase** feature.
2. Therefore it does **destructive changes** to the git history!

Thank you in advice.
