### ISSUE TITLE
Source Link works with private repositories

### ISSUE THREAD

**Issue by ctaggart** [MicrosoftDocs/azure-devops-docs#3709]
I think this page needs some major revision. There is confusion between source indexing and Source Link. For .NET, Source Link is recommended using https://github.com/dotnet/SourceLink/. 

This answer isn't correct:

> Q: Can I use source indexing on a portable .pdb file created from a .NET Core assembly?
A: No, source indexing is currently not enabled for portable .pdb files because SourceLink doesn't support authenticated source repositories. The workaround at the moment is to configure the build to generate full .pdb files.

It is recommended to use Source Link. Source Link can be used with private repositories. The Visual Studio debugger supports authentication. Authentication to GitHub Enterprise works. Some users are not able to get [authentication to TFS](https://github.com/dotnet/sourcelink/issues/207) to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cddddb9-2731-3366-2a76-9089b58d7f96
* Version Independent ID: b34de428-c3d2-14d6-a452-302c68b74c87
* Content: [Publish symbols for debugging - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/symbols?view=azure-devops)
* Content Source: [docs/pipelines/artifacts/symbols.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/symbols.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **amullans**

**Comment by seangwright** [comment]
In researching Source Link over the past year or so I've found the documentation, links and instructions to all be conflicting and confusing.

I realize that Source Link as a product has gone from experiment to fully supported, but the documentation has fallen so far behind that it appears to be leading developers down the wrong path.

Is there any definitive, up to date source for information about how to use Microsoft's technologies together? In this case Source Link and Azure DevOps.

**Comment by mikeblakeuk** [comment]
Any news on this?

**Comment by daghb** [comment]
Still no news? Really? Docs are still in error, and no information whatsoever on how to publish .snupkg packages to Artifacts?

**Comment by seangwright** [comment]
I did get SourceLink working in Azure DevOps private repos using DevOps artifacts and Azure AD auth through Visual Studio to download the package source when debugging (so it _is_ possible).

That said, there are tons of different flags, buttons, toggles, and values that need to be entered _just right_ to make everything work.

It's worth it in the end, but it's a log of work and research to wire it up.

I would post my solution here but honestly it would require a very long blog post, or completion of the incomplete documentation on the topic, to explain it correctly.

**Comment by ctaggart** [comment]
@seangwright 🥳 , glad you got it working with Azure DevOps private repos! Please do jot down some notes here that we can use to update the docs for others. A very long blog post would be amazing! I donated months of my time over several years for this and the docs need a fresh set of eyes.

**Comment by mkane91301** [comment]
Please @seangwright and @ctaggart my team really needs this to work and I would greatly appreciate the knowledge transfer of how to make this happen.

**Comment by peter-bertok** [comment]
I really shouldn't be trawling through GitHub pull requests diffs at 6:45 pm to figure out how to "tick a checkbox" to make a core feature of Azure DevOps work with Visual Studio.

This really ought to Just Work.

Not just for GitHub. Not just for NuGet. Not just for some types of project... sometimes... with errors going nowhere that is immediately visible. 

It should work with multiple repo types. It should work for complex projects with embedded libraries. It should work when downloading memory snapshots from Azure App Services.

Not.. sometimes... for some people.. maybe... if they log in to IE first... and sacrifice a small fuzzy animal at midnight with a bronze dagger that curves *just so*.

**Comment by WilliamAntonRohm** [comment]
@peter-bertok -- Peter, thank you for your follow-up.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by peter-bertok** [comment]
@WilliamAntonRohm thank you for the document references, but the reason that I'm here is that the documentation is incomplete, confusing, and often outright incorrect.

For example, the documentation mentions that "full" mode need to be used to enable "PDB" symbols. That's the extension for both the "old" and "new" symbol formats, which aren't compatible! The new Linux-compatible format ought to have been given a different file extension. I still have no idea which format is being created, and which one I need.

The DevOps pipeline source indexing step *says* it's doing things, it even uploads several megabytes of something to Azure Artifacts, but when inspecting the PDB I couldn't see any references to the repo. From the perspective of an end-user of this, they're basically being deceived. A tool shouldn't report success if it's failing to do its intended purpose. A source indexing tool should always index sources, or report an error.

After randomly flipping task flags, I finally saw a HTTPS URL being added to the PDB file pointing back to the repo and commit id. Still no joy: when opening an Azure App Service debug snapshot, it still prompts users to locate the matching .cs file instead of downloading the source code like it is supposed to.

At this point I have no idea why Visual Studio 2022 is doing this. The PDB is there. It has the source link. I can access the source link manually in a browser. There's no errors. Authentication seems to work. Yet the whole thing does nothing at the end of the day!
