### ISSUE TITLE
No actions are associated with the specified consumer identifier.

### ISSUE THREAD

**Issue by 10ARK-StephenKie** [MicrosoftDocs/azure-devops-docs#3743]
If I following this article at https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-service-hook?view=azure-devops I get the following error when trying to test it after installation on our Azure DevOps:

"No actions are associated with the specified consumer identifier."

<img width="615" alt="Screenshot 2019-03-22 at 16 00 17" src="https://user-images.githubusercontent.com/4106136/54827902-b32a4d00-4cbb-11e9-9208-125c85e4d9b5.png">
<img width="611" alt="Screenshot 2019-03-22 at 16 00 26" src="https://user-images.githubusercontent.com/4106136/54827903-b32a4d00-4cbb-11e9-8363-e5db8abc4ebf.png">
<img width="612" alt="Screenshot 2019-03-22 at 16 00 37" src="https://user-images.githubusercontent.com/4106136/54827904-b3c2e380-4cbb-11e9-85a3-a2df8cb55ec7.png">
<img width="607" alt="Screenshot 2019-03-22 at 16 00 46" src="https://user-images.githubusercontent.com/4106136/54827905-b3c2e380-4cbb-11e9-88e1-97e501ba5df0.png">

I cannot find any other examples of how the vss-extensions.json file should be formatted.

Any assistance would be appreciated as we are trying to develop a Service Hook Consumer that can submit data to a custom RESTful service for processing.

**Comment by jmazouri** [comment]
I'm also having this problem when following the documentation [here](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-service-hook?view=azure-devops). I noticed this article was last updated in 2016 - has the extension schema changed since then?

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by olljanat** [comment]
@cxwtool this issue is still valid and should be reopened. It is not possible to create service hook extensions does not hit
> No actions are associated with the specified consumer identifier.

error with current examples and documentation.

I did some investigations by installing Azure DevOps Server 2020 and checking `C:\Program Files\Azure DevOps Server 2020\Application Tier\Web Services\bin\Microsoft.VisualStudio.Services.ServiceHooks.Consumers.dll` file content with JetBrains and I can see that there consumers and their actions are registered with C# code is what Azure DevOps expect other why it gives this error.

However I cannot use those reverse engineered codes to building open source extension as those are Microsoft property but we need something similar published by Microsoft which is included to that file. Also what is interesting is that old projects like https://github.com/am385/vsts-discord-webhook/tree/master/Extension have ended up send payload to Azure Function for modification but it shouldn't be needed if we would have working example where those can be processed with C# code inside of Azure DevOps server it selves.

**Comment by WilliamAntonRohm** [comment]
@olljanat -- Olli, thank you for your follow-up.

@steved0x -- Steve, please look into this issue.

**Comment by AdrianLC** [comment]
Datadog's [new custom consumer extension](https://github.com/DataDog/ci-visibility-azure-pipelines) is being affected by this.

Here is a sample 500 response that we get when the Test button is clicked before having saved the subscription:
```json
{
  "$id": "1",
  "innerException": null,
  "message": "No actions are associated with the specified consumer identifier.",
  "typeName": "Microsoft.VisualStudio.Services.ServiceHooks.WebApi.ServiceHookException, Microsoft.VisualStudio.Services.ServiceHooks.WebApi",
  "typeKey": "ServiceHookException",
  "errorCode": 0,
  "eventId": 4501
}
```

**Comment by WilliamAntonRohm** [comment]
@AdrianLC -- Adrián, thank you for your follow-up.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

If you feel this is a product issue, please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

**Comment by rgundogmusm** [comment]
I wish to thank everyone who helped bring this issue to our attention. This problem has been resolved with the latest Azure DevOps update. If it reoccurs, please don't hesitate to let us know. Your continued support is greatly appreciated.
