### ISSUE TITLE
Ubuntu git-credential-manager Not Working

### ISSUE THREAD

**Issue by drjinying** [MicrosoftDocs/azure-devops-docs#3799]
Hi, could you please verify again that the Ubuntu instruction is still working? The git-credential-manager installation is different from expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by johnfidel98** [comment]
yeah... i keep on getting fatal: Authentication failed, each time i try to add git remote

**Comment by johnfidel98** [comment]
seems like using ssh option works

**Comment by Kira-Lappo** [comment]
it works on Linux Mint 19.1 which is based on Ubuntu 18.04
i can't really say what doesn't work in your case. I followed their steps on GitHub page
https://github.com/Microsoft/Git-Credential-Manager-for-Mac-and-Linux/blob/master/Install.md

In general I:
1. installed rpm package. Seems like I could just user .jar file for all actions, but as is
2. manually set credential.helper config globally and used correct path to .jar file and parameter --replace-all (or kind of that)
3. removed ~/.git-credentials file, so I don't keep password in a plain text anymore
4. tried to push some changes to my github repo and made sure that password record appeared in keychain in seahorse and did not in ~/.git-credentials

**Comment by yelenapakumirzakova** [comment]
It is an error, there is not supposed to be "-" between git and credential.
Try git credential-manager install

**Comment by toddwayne** [comment]
I am using Ubuntu under WSL (Windows System for Linux).  Here's my recipe for something that works...  Similar to something I found at stackoverflow: https://stackoverflow.com/questions/45925964/how-to-use-git-credential-store-on-wsl-ubuntu-on-windows 

1) Install Git for Windows; this comes with it's own Credential Manager
2) Run Ubuntu, and instead of configuring your credential manager to something linux local, set it (using the procedure at the link above) so that your git config on Ubuntu resembles:
credential.helper=/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe
[do not forget to escape the backslash, \\ to get properly escape the '\ ' sequence in the setting]

Hope this helps!
Todd
[aka Todd.Wayne@microsoft.com]
