### ISSUE TITLE
azureContainerRegistry needs to be json

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/azure-devops-docs#3928]
The azureContainerRegistry value is parsed as json:

https://github.com/Microsoft/azure-pipelines-tasks/blob/5214488bfc43a27f3faeb4589536af2bff387b39/Tasks/AzureIoTEdgeV2/pushimage.ts#L15

So the value must be json and not as documented the login server url.
```yaml
    'azureContainerRegistry: '{"loginServer": "contoso.azurecr.io"}'
```

(If this an good parameter design is an other question...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoTEdge task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **dastahel**

**Comment by gregnrobinson** [comment]
This has solved hours of wondering what my problem is. This should be dealt with as Microsoft documentation has nothing about this but says to place the registry URL as contoso.azurecr.io which fails the pipeline. This is also over a year old?? Come on Microsoft... fix it.

**Comment by gregnrobinson** [comment]
cheers @StefanSchoof for allowing me to move past this.

**Comment by simonachmueller** [comment]
Please fix documentation examples: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-iot-edge-v2?view=azure-pipelines#push-module-images and https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops#push-module-images. I wasted few hours as well fixing the validation error.

**Comment by StefanSchoof** [comment]
Auto closing and fixing this after 5 years is bad :(

**Comment by steved0x** [comment]
@StefanSchoof I'm un-auto-closing it :) Looking at the example here in our new task reference (since this original feedback was posted), we are showing it as json, and using a variable.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-iot-edge-v2?view=azure-pipelines#push-module-images

I will add a note to that property and clarify that the correct format is json so readers don't need to go down to the examples, it should be live shortly. 

![image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/1580889/6e2b9c3e-60e1-4de8-bdd3-95f2a062b67b)

Please let me know if I have misunderstood the intent of your feedback and I can make additional updates.

**Comment by StefanSchoof** [comment]
Thank, that is looking good. Like the comment. Now I happy and you close this.
