### ISSUE TITLE
Understanding manual PR comment triggers

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/azure-devops-docs#4206]
I have a long validation build that I want to run only on new commits to `master` and when explicitly requested in a PR via a comment `/azp run Validation`.

The YAML for the `Validation` pipeline contains:
```yaml
trigger:
- master
pr: none
```
When I post the "/azp .." comment in the PR then the bot responds with:
&gt; Azure Pipelines could not run because the pipeline triggers exclude this branch/path.

How should this work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by TimLariviere** [comment]
I had the exact same problem but finally figured it out.

Setting `pr: none` in the YAML will disable this pipeline for any PR, even with comment triggers.
That's why AZP is reporting it can't run the pipeline.
So you should either not specify `pr` or set it to a branch you want to restrict it to. (like `pr: master` for only PRs targeting master)

Now the problem is that PRs will automatically trigger your pipeline.
To allow only comments to trigger it, you need to follow these instructions:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#build-github-pull-requests-only-when-authorized-by-your-team
Note that there is no way of letting one of your contributors (without access to Azure DevOps) to trigger a build with a comment.

The way the docs is structured is a bit misleading here.
Those instructions are mandatory to enable comment triggers, but is put in a subpart which can be understand as optional and there is no mention of `pr: none` disabling comment triggers.

It took me a while to understand how it was actually supposed to work.

**Comment by thomps23** [comment]
@TimLariviere Thanks for your follow up- tagging as a doc-bug for triage on our side.

**Comment by JoeBrockhaus** [comment]
@thomps23 2 follow-up questions:

1. Should it be possible to have 2 Pipelines, where `Pipeline1` is triggered automatically (for PRs), while `Pipeline2` is (only) triggered via `/azp run Pipeline2`?

2. Within an executing Pipeline, do any Variables indicate the Build was Triggered from a PR Comment? I've noticed `Build.Reason` is still `PullRequest` for builds triggered with PR Comments.  `Build.TriggeredBy.*` are unrelated.

**Comment by thomps23** [comment]
@JoeBrockhaus Thanks. We'll consider those questions during triage but I can't put a fine point on when. If this is urgent please consider creating a discussion at [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops).

**Comment by grav** [comment]
@JoeBrockhaus We're doing 1, eg. having two pipelines, where one is always triggered (fast, just compiles and runs tests), and the other one only on comment triggers (slower, builds and deploys for QA)

**Comment by worldspawn** [comment]
@TimLariviere this falls down if you have more than 1 build that you want to manually trigger. I have 3 and if do /azp run Deploy-Dev all 3 are triggered because now my PR has a comment on it. Seems like a pretty half-baked feature implementation.

**Comment by GuuBu** [comment]
I get similar problem, by run /AzurePipelines run, I get "
 Azure Pipelines could not run because the pipeline triggers exclude this branch/path."
Then I tried /azp run slow-pipeline, then it gives "No pipelines are associated with this pull request". But after that, a pipeline actually get run, and I do include the branch. But I keep get the same message when run /azurePipelines run, while a pipeline is actually triggered.

**Comment by rmarinho** [comment]
I also have the same issue that @GuuBu  refers.. 

I get a message of `No Pipelines are associated` but then it starts

**Comment by vijayma** [comment]
Thanks for the comments in this thread. We updated the doc to clarify the steps needed to enable comment triggers. There are no explicit variables indicating that the PR has been triggered by a comment.

**Comment by JulioCVaz** [comment]
@letmaik @TimLariviere 
Hey guys, how you doing?
I hope you are very well!

We had the same problem and checked that is not possible to add a trigger by comment using yaml file.

We solved this problem config the pr flag, like:

```yaml
trigger: none

pr:
  branches:
    include:
      - develop
      - master
  paths:
    include:
      - packages/*
      - .github/workflows/azure-pipelines # temporary
    exclude:
      - packages/_*
```

and configure in the azure devOps panel

steps:

Select the pipeline > Edit > Menu(three dots) aside `Run` > Triggers > Follow the image attached
![triggers](https://user-images.githubusercontent.com/20933173/228040100-3de0e95e-e52b-404c-a2e2-5d2e9241dff3.png)

![set_comment](https://user-images.githubusercontent.com/20933173/228040381-fc2db63b-fa33-4e69-a27e-474d1f657f20.png)
