### ISSUE TITLE
How to switch to Visual Pipeline Designer experience

### ISSUE THREAD

**Issue by githubavi** [MicrosoftDocs/azure-devops-docs#4305]
Hi, I want to build pipeline using old visual design. Will switch to YAML schema later. But, right now I can only see YAML pipeline and no option to switch back to Visual Design. How to switch to Visual Pipeline Designer experience?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Create your first pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=tfs-2018-2&ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-aWiG_QhvLq5J0VcXmccZgQ&epi=je6NUbpObpQ-aWiG_QhvLq5J0VcXmccZgQ&irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir__zszomqxmv0kfrnby0ckzh9lp2u2xme9npwejn22i00)(7593)(1243925)(je6NUbpObpQ-aWiG_QhvLq5J0VcXmccZgQ)()&irclickid=_zszomqxmv0kfrnby0ckzh9lp2u2xme9npwejn22i00&viewFallbackFrom=vsts)
* Content Source: [docs/pipelines/create-first-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/create-first-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@githubavi Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by andyjlewis** [comment]
@githubavi are you using Azure Pipelines, DevOps Server, or TFS?

**Comment by githubavi** [comment]
Using Azure Pipeline

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WilliamAntonRohm** [comment]
@githubavi -- Avijity, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

My apologies for the delay in responding.

**Comment by WilliamAntonRohm** [comment]
@steved0x -- please look into this issue.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
