### ISSUE TITLE
Cannot find "Automatically link new work in this build" option in YAML build

### ISSUE THREAD

**Issue by MarkyDeParky** [MicrosoftDocs/azure-devops-docs#4559]
https://devblogs.microsoft.com/devops/automatic-linking-work-items-to-builds/

According to the above article, you should be able to automatically link work items to builds by setting the option "Automatically link new work in this build" in a build definition.

I cannot find this option anywhere in my YAML-based build def. Is it even possible to auto-link builds to work items this way?

**Comment by LXBdev** [comment]
You can enable it here:

![image](https://user-images.githubusercontent.com/48275577/83498914-d30ef080-a4bc-11ea-8a8e-e63f27c40c58.png)


![image](https://user-images.githubusercontent.com/48275577/83498874-c5596b00-a4bc-11ea-98b5-e7c82c6e750c.png)

**Comment by yang-xiaodong** [comment]
This feature appears to be available only in Azure DevOps Services and not Azure DevOps Server. Is that correct?

**Comment by maxcarl** [comment]
Is there any way to link to multiple branches? We need this feature to track work across different releases using the same pipeline.
Isn't this a feature the old pipelines used to support?

**Comment by AElharouny** [comment]
@LXBdev 
That's my view:
![image](https://user-images.githubusercontent.com/52023187/90704217-40b80500-e2d3-11ea-8bab-1dd85c9a2a62.png)

Will this feature be in Azure DevOps soon?

**Comment by derselbst** [comment]
@ramiMSFT Can you please make a statement, if or when this feature will be available in Azure DevOps Server?

**Comment by ramiMSFT** [comment]
My apologies for the delayed response. You can link your build to your work item from the **Development** section in your user story. Select **branch** to open the dialog box.  Select **Build** from the drop down menu and find your **Build number** then **OK**.

![image](https://user-images.githubusercontent.com/60942540/109081790-aab4cb00-76b7-11eb-91a4-27d3b1ab9f39.png)

**Comment by AElharouny** [comment]
Hi @ramiMSFT 
That question is regarding **automatically** linking work items to pipelines not manual which is supported in "Classic releases". What you're describing is a manual process.

**Comment by derselbst** [comment]
@ramiMSFT Since you have closed this issue while giving an evasive answer, can we conclude that Microsoft has no intentions to add this feature to Azure DevOps Server?

**Comment by ramiMSFT** [comment]
@derselbst The feature is **already available** in Azure DevOps server for both the [Classic editor](https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2017-update2#automatic-linking-from-work-items-to-builds) and [YAML](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#link-work-items-with-multi-stage-yaml-pipelines). 

![image](https://user-images.githubusercontent.com/60942540/109229034-9df7ac00-7777-11eb-921a-d2c84d878aca.png)

-------------------

![image](https://user-images.githubusercontent.com/60942540/109229096-af40b880-7777-11eb-9fc8-229b00b51945.png)

**Comment by AElharouny** [comment]
@ramiMSFT Yeah we also know that but this issue is related to Azure Devops (the Cloud offering) not Azure Devops Server?
When do we expect this in Azure DevOps (not Azure DevOps Server)?

**Comment by derselbst** [comment]
@AElharouny This time you got confused. This feature has been available in DevOps Services for much longer than in DevOps Server. The question was indeed about availability in DevOps Server.

Although Rami has linked the documentation of DevOps Services, he is right. To my surprise, this feature is indeed available since DevOps Server 2020, [as pointed out here](https://docs.microsoft.com/en-us/azure/devops/server/release-notes/azuredevops2020?view=azure-devops#link-work-items-with-multi-stage-yaml-pipelines). I just tested this in DevOps Server Express 2020.0.1 myself.

**Comment by AElharouny** [comment]
@derselbst But I don't see that in my Azure Devops tenant. Screen shot attached in this comment:
https://github.com/MicrosoftDocs/azure-devops-docs/issues/4559#issuecomment-676834118

Pipeline Settings view doesn't include UI to link work items.

**Comment by derselbst** [comment]
@AElharouny Please double-check which version of Azure DevOps Server you are running. It looks like it's 2019.

**Comment by AElharouny** [comment]
@derselbst I'm not sure where that confusion is coming from but I keep saying I'm not interested in "Azure Devops Server". I want this feature in "Azure Devops" which is managed and updated by Microsoft.

**Comment by derselbst** [comment]
> I want this feature in "Azure Devops" which is managed and updated by Microsoft

@AElharouny  So, you mean "Azure DevOps Services", hosted at https://dev.azure.com . And for that, Rami has already provided [the correct link](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#link-work-items-with-multi-stage-yaml-pipelines) stating that it is available since July 2019. However, it is only visible for pipelines that access a Git Repository that is located within Azure DevOps.

**Comment by AElharouny** [comment]
> > I want this feature in "Azure Devops" which is managed and updated by Microsoft
> 
> @AElharouny So, you mean "Azure DevOps Services", hosted at https://dev.azure.com . And for that, Rami has already provided [the correct link](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#link-work-items-with-multi-stage-yaml-pipelines) stating that it is available since July 2019. However, it is only visible for pipelines that access a Git Repository that is located within Azure DevOps.

Ok sorry for the confusion. Is there plans to make this work when code is in Github?

**Comment by pbcahill** [comment]
> > > I want this feature in "Azure Devops" which is managed and updated by Microsoft
> > 
> > 
> > @AElharouny So, you mean "Azure DevOps Services", hosted at https://dev.azure.com . And for that, Rami has already provided [the correct link](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#link-work-items-with-multi-stage-yaml-pipelines) stating that it is available since July 2019. However, it is only visible for pipelines that access a Git Repository that is located within Azure DevOps.
> 
> Ok sorry for the confusion. Is there plans to make this work when code is in Github?

I have the same question on when the repo is in GitHub. As that automatic linking option is not there when repo is in GitHub. And I'm only trying to do that because the API call for [Getting Build Work Items](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get-build-work-items-refs?view=azure-devops-rest-6.0) does not return the related work items for a build for a GitHub repo/commit, even though you can see the work items under the Related work items section on the build summary (when linking through CI Azure boards/github connection).
