### ISSUE TITLE
Missing any information about feed authentication in Azure Pipelines

### ISSUE THREAD

**Issue by chasewilson** [MicrosoftDocs/azure-devops-docs#4717]
@Paul-Dempsey
One of the basic frequent issues with azure pipelines and nuget feeds (both private and Azue Devops artifact feeds), is feed authentication. This topic and the others in this area are silent on authentication and how to get things to actually work. This is an urgent and critical area that needs addressing.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops

referencing: https://github.com/MicrosoftDocs/vsts-docs/issues/3850

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by Paul-Dempsey** [comment]
Not true.  This was totally an issue with the documentation when I opened it, because the topic was silent on the issue of authentication.

**Comment by mijacobs** [comment]
Hi Paul-Dempsey,
My apologies that the issue was incorrectly categorized, thank you for your quick response. Re-opening the issue and re-categorizing.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
