### ISSUE TITLE
Question on ‘Each repository should only reference one feed’

### ISSUE THREAD

**Issue by jrdodds** [MicrosoftDocs/azure-devops-docs#4993]
Hi,
We have multiple teams working on multiple projects for multiple products in one Team Project using one TFVC repository.

Can you explain why “Each repository should only reference one feed” is being promoted as a “best practice”? What problem or issue is being avoided?

The description speaks of ‘projects’. Is this a Team Project? Because if not, we have multiple projects in one repository. (I wouldn’t do git this way but we are not using git yet.)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf693ac-c5c3-96a6-7f4b-bbc2271a6375
* Version Independent ID: 4f76c74c-1d6c-644f-f00d-97d7738d7b01
* Content: [Best practices for using packages in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/best-practices?view=azure-devops#feedback)
* Content Source: [docs/artifacts/concepts/best-practices.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/best-practices.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by chasewilson** [comment]
Hey @jrdodds, Thanks for the question. @elbatk Do you have any input on this one?

**Comment by elbatk** [comment]
Hey @jrdodds, 

By project, we do mean team project in Azure DevOps. Having multiple feeds just creates another layer of dependencies on top of an already potentially complicated package graph. 

We are rolling out project-scoped feeds now, and I believe good practice there would be one project-scoped feed per project, and then 1 org-scoped feed with common packages that could be set up as an upstream source, or just configured separately. 

Does that make sense?

**Comment by jzserai** [comment]
We recently began migrating our TFVC content to Azure GIT. And because we support a vast and varied ecosystem of applications, we have a lot of repositories. We setup our repositories to reflect what we consider our various value streams. And it seems to be working well.

However, we also have a number of individual class library projects that are used by multiple clients, which appears to be a good candidate for using Artifacts.

My question concerns the possibility for different interpretations between what is stated at the beginning of this page and your last reply. We plan on creating a feed for each repository using shared libraries, not one single feed for everyone. Is "repository", as used in this article, intended to refer to the entire code repository for a single Azure DevOps project, regardless of SC provider, or should it be interpreted in alignment with GIT repositories?

As an fyi, we have defined naming conventions and policies for each major section of Azure DevOps, to include repositories. And as we embark on using Artifacts, conventions and policies will be defined for these as well.

Thank you

**Comment by ramiMSFT** [comment]
@jrdodds Thank you for your feedback. Yes by "project" we mean Team project. The reason behind: “Each repository should only reference one feed” is to make sure that a repository doesn't rely on more than one feed, but you can still use a feed for more than one repository.

If you want to use packages from multiple feeds, you should use [upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops) to bring packages from multiple feeds together into a single feed.

See [Setup upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops) for a guidance on how to setup your upstream source.
