### ISSUE TITLE
Manually selecting Xamarin versions

### ISSUE THREAD

**Issue by dansiegel** [MicrosoftDocs/azure-devops-docs#5076]
The docs on `How can I manually select versions of tools on the Hosted macOS agent?` are pretty vague. It approaches the topic as if what matters is the overall Xamarin SDK. While that may work a large percentage of the time we really need to approach this from the perspective that perhaps we need to use a specific version of Xamarin.iOS or Xamarin.Android.

I understand there are some poorly documented scripts on the Host but really we need a built in Task that can help us manage this all as easily as installing the .NET Core 3 Preview or a specific version of NuGet. The real fix for this is ultimately a multi team approach. 

Docs: Improve docs on how to select specific versions of the Xamarin.SDK, Xamarin.iOS, Xamarin.Android, XCode
Pipelines: Include an easy tool out of the box similar to [Boots](https://github.com/jonathanpeppers/boots) that is capable of either selecting a version that's pre-installed or installing one which could be a nightly, preview or stable build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @joebourneMS
* Microsoft Alias: **jobourne**

**Comment by thejoebourneidentity** [comment]
For the pipelines issue, please file an issue over at our image generation repo with yoru suggestion: https://github.com/microsoft/azure-pipelines-image-generation

For the docs issue: @davidstaheli do you or someone on Madhuri's team have the Xamarin expertise to offer up a docs suggestion here?

**Comment by W0GER** [comment]
The answer from thejoebourneidentity is an example of why getting all this to work is a monumental task. No one at Microsoft wants to OWN the build process for Xamarin across the various tools (Azure DevOps Build Pipelines, Hosted Images, Xamarin SDK, etc.). The provided documentation is poorly written and circular; when issues are raised the "buck" is passed and apparently dropped as there are few improvements. I am very disappointed with the overall quality regarding getting a Build Pipeline for Xamarin projects working with Microsoft's own tooling.

**Comment by acoats2** [comment]
I agree this is way too hard and ambiguous.  

These docs: https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/old-version-xcode indicate you should use the latest versions of all the things when possible.  When you can, that's great.  When you can't, what are the options?  The link does have suggestions, but no solid answers.

Here's the thing, especially during major iOS updates, we may need to run two configurations.  For example, xcode 10 with iOS 13 has some different behaviors than xcode 11 with IOS 13, all other things being the same.  As developers, it would be great to be able to switch back and forth between configurations during a migration period for supporting production while migrating for the future.  However, if I point VS for mac at an older xcode, it complains that there could be unexpected errors.  Why can't I easily have options here?

Additionally, for my automated Azure DevOps pipeline, I should be able to use code as configuration to define exactly what I need my code built against.  Currently this only seems realistic on the MS hosted mac agents.  We run our own mac build agent and I can't find any download locations or documentation on how to install old Xamarin sdks.  Stand-alone installs of mono may be possible, but it would be nice to have this documented rather than scratching something together.  Then there are scripts that only seem to exist on the hosted build agents that seem to be critical for allowing this.  Why do the built in tasks in Azure DevOps not support these options rather than pipelines having to rely on scripts that only reside on Microsoft hosted build agents?

Don't get me wrong, I love Xamarin and I love Azure DevOps, but this part is really painful.

**Comment by sugarjig** [comment]
I agree with the comments here. The advice should not be to call an undocumented script, which doesn't even work anyway (#2129, #1660). There should be one or more tasks to set the tool versions, a la `UseDotNet@2`. Alternatively, the tasks `XamarinAndroid@1` and `XamariniOS@2` could take in the desired Mono, Xamarin.iOS, and Xamarin.Android versions as parameters. Either way, building Xamarin apps in DevOps should be simpler.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
