### ISSUE TITLE
Case enforcement no longer in Repo options

### ISSUE THREAD

**Issue by Mekkaspark** [MicrosoftDocs/azure-devops-docs#5082]
Case enforcement option is no longer in the Repo options page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ba72fe-98e6-cb93-f4e4-6950573a2a8c
* Version Independent ID: 260aaae9-0df1-74e6-9d39-7723d2bc7d2c
* Content: [Repository settings - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/repository-settings?view=azure-devops#feedback)
* Content Source: [docs/repos/git/repository-settings.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/repository-settings.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by apawast** [comment]
Hi @Mekkaspark, case enforcement is still an option. Are you seeing this in the Repository settings?

<img width="1439" alt="Screen Shot 2019-07-31 at 5 06 24 PM" src="https://user-images.githubusercontent.com/47400341/62248312-cb228380-b3b5-11e9-8c58-6d7777675f52.png">

If not, that is definitely an issue because it should still be there.

**Comment by msebolt** [comment]
If there are any further issues, please comment below.

Closing this issue now.
