### ISSUE TITLE
error on 'git push bare' step

### ISSUE THREAD

**Issue by CastleArg** [MicrosoftDocs/azure-devops-docs#5447]
Nfo refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
atal: The remote end hung up unexpectedly
error: failed to push some refs to 'c:\new-bare.git'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd6cbc8-5e3b-c3a1-4672-d42510cc058b
* Version Independent ID: 8fe81fb5-7c2d-2562-5659-55fccbb3126c
* Content: [Migrate from Subversion (SVN) to Git](https://docs.microsoft.com/en-us/azure/devops/repos/git/perform-migration-from-svn-to-git?view=azure-devops)
* Content Source: [docs/repos/git/perform-migration-from-svn-to-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/perform-migration-from-svn-to-git.md)
* Product: **devops**
* Technology: **devops-whitepapers**
* GitHub Login: @hkamel
* Microsoft Alias: **hkamel**

**Comment by MamadouBAH139** [comment]
I had the same error as you but I specify the name of the branch "master" in my case 'git push bare master'and it worked

**Comment by gitarian** [comment]
I could reproduce the error with either cmd and PowerShell.

The reason is in the documentation line:
`git config remote.bare.push 'refs/remotes/*:refs/heads/*'`

Here, the <refspec> parameter is surrounded by single quotes, just remove them as in
`git config remote.bare.push refs/remotes/*:refs/heads/*`

and the following `git push bare` works as expected.
