### ISSUE TITLE
In need of update

### ISSUE THREAD

**Issue by memark** [MicrosoftDocs/azure-devops-docs#5610]
Not much is correct here when it comes to the Azure function. The code doesn't even compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 915c7aa9-0969-912b-bbc4-a2b0bf9b1533
* Version Independent ID: 6a97a5e8-8397-be98-5528-70d20e8fbed8
* Content: [Use Azure Functions to create custom branch policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server-with-azure-functions?view=azure-devops)
* Content Source: [docs/repos/git/create-pr-status-server-with-azure-functions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server-with-azure-functions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **yohasna**

**Comment by juangps96** [comment]
I have to use {organization} instead of accountName variable

I realized that with this version: 

https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses?api-version=5.1-preview.1

On this link:

https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20statuses/create?view=azure-devops-rest-5.1
