### ISSUE TITLE
Loop through custom variables of a release pipeline

### ISSUE THREAD

**Issue by paolosalvatori** [MicrosoftDocs/azure-devops-docs#5752]
How do I loop through the custom variables for a given release pipeline or stage? From PowerShell, I can run Get-Children Env: but this command returns all the environment variables, including the custom variables defined at the Release and Stage level, whereas I just want to loop through the custom variables defined at the Release or Stage level. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#feedback)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by sijucm** [comment]
This is still an issue. There is no documentation that says how to loop through a variable. All examples are about looping through parameters not about variables set at runtime.       - ${{ each AppName in  AppNameListVariableCreatedInAzureCliTask  }}:
The above just does not work and Azure just forgets to document if this is not possible I read that ${{}} is at compile time and not run time, but then is it possible to do it as $[ ]. No, that is not possible. These are all wild goose chases when it comes to the stuff that comes out of Microsoft stable. All this reminds me of the VB-script, just pure time waste

**Comment by juliakm** [comment]
@paolosalvatori  I don't think that this is supported but I will double-check with the product team.

**Comment by asolvent** [comment]
After something similar, an example showing loop through a variable group would be nice.

**Comment by juliakm** [comment]
I've confirmed that for release pipelines you can't use the `each` syntax and there isn't a way to iterate. Part of the challenge of iterating in general is that the value of a list is dynamically generated at runtime and the `each` syntax gets evaluated at compile time. If you'd like to make a feature request, please post in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
