### ISSUE TITLE
Clarification on the Authorization process for variable groups

### ISSUE THREAD

**Issue by gmoed** [MicrosoftDocs/azure-devops-docs#6043]
Add to the documentation that in order to get the approval link to authorize the use of a variable group, the group needs to be under the job and not on the top of the yaml definition. otherwise it just says the variable group is not found or authorized but does not provide a mean to authorize it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@gmoed  Thank you for the feedback, assigning this to the author for review.

**Comment by shashban** [comment]
@gmoed The behavior isn't intended to be different depending on where the variable group is defined. Let me check why is there a difference. I guess we would like to fix the problem than documentation only. Thanks

**Comment by melezhik** [comment]
How to deny permissions to link/use given variable group for certain users? 
checkbox "Allow access to all pipelines" does not help here.

**Comment by melezhik** [comment]
also I can revoke "use" permission for given descriptor for a given variable group but it still does not help, it does not prevent this user to use this variable group ( e.g. he could easily link it to a build definition ).

**Comment by shashban** [comment]
@melezhik I am not sure I follow.
- Use permission for users control who all can link the variable group to a pipeline using the UI, mostly for designer pipelines
- For YAML pipelines, the use permissions do not help as the UI can be mypassed and the group can be directly referenced in the file. The checkbox ensures YAML pipelines do not silently end up using the group, and each pipeline has to permitted by a user with Use permissions. 
- For existing pipelines, any user can trigger a run that would internally consume the variable group if it was already linked to it and the pipeline is permitted.
Could you emphasize on your requirement and what's not working?

**Comment by melezhik** [comment]
@shashban our use case is following:

- we have a variable groups that linked to keyvaults and so have a sensitive information ( passwords and so on )

- nowv everyone who has a permission to create a build definition could write a simple yaml  pipeline, create a build definition to run the pipeline and link variable group to that build definition so that code inside pipeline gain an access to those variables.


All the mechanism mentioned so far does not prevent  such a scenario: 

* "all access from all pipelines" effectively does nothing when build definition, pipeline and variable group belongs to the same project. It only I guess makes a sense for cross projects access but we don't use that

* I tried to change an ACL (using Azure devops RestAPI) for a certain user ( security descriptor ) and for certain token ( variable group ), removing all permissions bits ( including "use" bit )  but this does not help - user still able to link variable group to the build definition and run it.


Moreover the Microsoft documentation on azure devops security permission management through the RestAPI is very incomplete and vague. Sometimes it takes an effort and reverse engineering to understand how it works.

**Comment by melezhik** [comment]
@shashban  any updates here? thanks

**Comment by shashban** [comment]
@melezhik Apologies, I missed your update late last week. "Allow access from all pipelines" is meant to address exactly the scenario you have. We'll need to check why it does nothing within the same project.

**Comment by weevil44** [comment]
I am looking for this also.  We have multiple teams sharing the same project but do not want variable groups shared between the pipelines.  How do we restrict someone from authorizing the variable group from another team for access on their pipeline?

**Comment by melezhik** [comment]
I've sorted it out by setting ACL for a certain variable group.

`token = $project/library/$variable-group-id`
