### ISSUE TITLE
MIssing explanation of how to edit credentials after first-tuime clone

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/azure-devops-docs#608]
This doc gets you started, but doesn't help if you need to change/update credentials after cloning. How do you edit/update/delete credentials after the initial setup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers](https://docs.microsoft.com/en-us/vsts/git/set-up-credential-managers?view=vsts)
* Content Source: [docs/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/set-up-credential-managers.md)
* Service: **unspecified**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TedHoward** [comment]
Is there anyway to list known/store credentials?

**Comment by steved0x** [comment]
@TedHoward I don't think there is a way to list known/stored credentials from GCM. Also I am sorry to hear that the delete didn't work for you. This repo is just for documentation, but you could file a couple of GitHub issues to represent these two items at [Git Credential Manager Issues](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues) - they are the developers and would know for sure and may be able to help you troubleshoot your delete issue.

@Paul-Dempsey I'm going to close this issue, but please feel free to file additional issues with your feedback, we appreciate it very much!

**Comment by Paul-Dempsey** [comment]
The Windows GCM credentials are exposed in the control panel under **Credential Manager**. The can be added/deleted/modified there. To set which one is used for a repo or machine, use the appropriate git --configure commands.  the full lifecycle of credentials and how to manage them is an appropriate thing to address in the documentation.

**Comment by TedHoward** [comment]
I tried the system-level Credential Manager (CM). I couldn't locate the one I needed - maybe it was stored with a guid instead of a url? I considered emptying the entire CM and would have if I hadn't located the tenant.cache solution.

fyi
My specific scenario, btw, was rather messed up. I had setup a VSTS with AAD then switched back to MSA authorization. My id was the same both in my AAD and in MSA, so git was using the AAD to access git. That used to work, but no longer did due to switching to MSA. It would prompt for password and attempt login with AAD. It never prompted AAD vs MSA (the 'work account' 'personal account' dialog).
