### ISSUE TITLE
Add Default elements for missing mime types

### ISSUE THREAD

**Issue by VAllens** [MicrosoftDocs/azure-devops-docs#6189]
`tfx-cli` throw warning:
```powershell
TFS Cross Platform Command Line Interface v0.7.9
Copyright Microsoft Corporation
warning: Could not determine content type for extension .woff2. Defaulting to application/octet-stream. To override this, add a contentType property to this file entry in the manifest.
warning: Could not determine content type for extension .ttf. Defaulting to application/octet-stream. To override this, add a contentType property to this file entry in the manifest.
warning: Could not determine content type for extension .otf. Defaulting to application/octet-stream. To override this, add a contentType property to this file entry in the manifest.
```

#### I want the following:
* Eliminate the warning.
* Add `Default` elements for missing mime types instead of adding `Override` elements.

Register the `content type/mime type` to the `windows registry`, can help we eliminate the warning.

```winreg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.otf]
"Content Type"="application/x-font-opentype"
[HKEY_CLASSES_ROOT\.ttf]
"Content Type"="application/x-font-truetype"
[HKEY_CLASSES_ROOT\.woff2]
"Content Type"="application/x-font-woff2"
```

FYI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by VAllens** [comment]
FYI:
https://github.com/microsoft/vso-extension-tools/blob/master/src/scripts/package.ts
https://www.cnblogs.com/VAllen/p/azure-devops-extensions-content-types-warning-fix.html

**Comment by msebolt** [comment]
@VAllens Thank you for the feedback and for pin-pointing the fix.

Since this issue is outside the scope of documentation, please consider moving this to the [vso-extension-tools](https://github.com/microsoft/vso-extension-tools/issues) repo.

@willsmythe @chcomley FYI

**Comment by VAllens** [comment]
@msebolt Thanks. but i think the `vsts-docs` should guide developers on how to add `Default` elements and eliminate warnings.

**Comment by msebolt** [comment]
No problem, assigning this to the author for review.

**Comment by VAllens** [comment]
Thanks so much.

**Comment by chcomley** [comment]
Adding @zachariahcox for guidance, thank you!

**Comment by chcomley** [comment]
This issue is stale and will be closed. Please check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported. For more extension information, see the [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/develop/extensions), [REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-5.1), [Extension samples](https://github.com/Microsoft/azure-devops-extension-sample), and resources in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). If you feel this issue should be reopened or if you have any further feedback or questions, don't hesitate to @mention me. Thank you.
