### ISSUE TITLE
Lock Branch misinformation

### ISSUE THREAD

**Issue by RobertoBorges** [MicrosoftDocs/azure-devops-docs#6225]
You've said: ``Use branch policies and pull requests instead of locking if you just want to ensure that changes in a branch are reviewed before they are merged.``

But it's not 100% true, the lock is an excellent way to prevent changes in the branch locked, and after locked, you can use Pull requests to make changes in a branch locked.

As is written, I understand that instead of using the lock, we should use policies, but the truth is that we can use both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ffea81-86af-46cb-a290-5ce83924f235
* Version Independent ID: 2ea32d72-75d8-42f9-bf33-756b1e00b3f2
* Content: [Lock a branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/lock-branches?view=azure-devops)
* Content Source: [docs/repos/git/lock-branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/lock-branches.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by michaelfaith** [comment]
I don't understand this comment.  If i have a branch locked AND have Pull Request branch policy applied, i get an error whenever someone tries to complete the PR, if they're not the person that locked the branch.
`Pull request could not be completed: Target branch locked: TF401389: The reference 'refs/heads/master' cannot be updated because it is locked by michael faith. `
