### ISSUE TITLE
Update VSTest task doc for UWP tests

### ISSUE THREAD

**Issue by PBoraMSFT** [MicrosoftDocs/azure-devops-docs#6239]
Task doc at https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops needs to be updated for UWP.

The following addition to the FAQ section will help.

How can I run tests for UWP apps?

Tests for UWP apps can be run by providing the .appxrecipe input to the test assembly input. 
For e.g., 
    testAssemblyVer2: |
      **\Release\UnitTestProject1.build.appxrecipe
      !**\*TestAdapter.dll
      !**\obj\**

If you use the /p:UapAppxPackageBuildMode=StoreUpload option when building the projects, an additional copy of the unittestproject appxrecipe is generated, which cannot be used to run tests.

Microsoft hosted agents are Server OS and cannot be used to run UWP tests. To run pipelines containing UWP workloads, you must use self hosted agents.

**Comment by PBoraMSFT** [comment]
@steved0x - can you help with this, pls? I have included the information about what needs to change above.

**Comment by mateialexandru** [comment]
@vijayma @PBoraMSFT Thanks for driving this!
Highly recommend getting the documentation in ; spent hours researching online about what and how to do and tried billion of things without success just to find out that you need to do some magic by specificing "*.appxrecipe" pattern for mstest build task; yet that is not enough because in some weird scenarios your output would contain multiple "*.appxrecipe" files; so then it's even better to specify smth like "Release\*.appxrecipe" etc.
But even with these changes there was no easy explanation that if you want to automate testing in VSTS you need a private agent customized with Developer mode on, etc..
Good luck using VSTS Hosted agents like msvc2017-win2016 etc.

My instant reaction was: leave UWP testing aside (although I have everything working on my dev machine) since everything is "magic" and try a cppwinrt test :|

_Originally posted by @mateialexandru in https://github.com/MicrosoftDocs/vsts-docs/issues/6240#issuecomment-564612717_

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by golddove** [comment]
Also spent a while to find this. Docs could really use a callout for UWP.
