### ISSUE TITLE
Docker cache

### ISSUE THREAD

**Issue by PawelHaracz** [MicrosoftDocs/azure-devops-docs#6280]
Is it possible to add a docker cache? on the Microsoft-hosted machine building. The building docker image can be a really long process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by hassanselim0** [comment]
@WilliamAntonRohm It seems like they were asking to add an example in the docs for caching docker images, just like there are examples for caching Nuget and NPM.
I think docker is a common use-case for Pipelines cache, so it would be great to add an example for it in the docs.

**Comment by WilliamAntonRohm** [comment]
@hassanselim0 -- Hassan, you make a good point.

@willsmythe -- Will, please look into this issue.

**Comment by OskarKlintrot** [comment]
Any progress?

**Comment by ramiMSFT** [comment]
@PawelHaracz  Thank you for your feedback and my apologies for the delay. Please refer to this: [9501](https://github.com/MicrosoftDocs/azure-devops-docs/pull/9501)
