### ISSUE TITLE
How can I decompose a Task Group?

### ISSUE THREAD

**Issue by blueelvis** [MicrosoftDocs/azure-devops-docs#6349]
Assuming that I have the permissions, how do I decompose a task group back to its original state i.e. separate tasks in the pipeline?

For example, if I use 4 tasks to create a task group, what should I do to get those 4 tasks back in the pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b773c-dfb0-5c58-1463-e9b865d73af6
* Version Independent ID: 83f332ed-719a-5347-acd8-bfe3bdb397b4
* Content: [Task Groups in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/task-groups?view=azure-devops#manage-task-groups)
* Content Source: [docs/pipelines/library/task-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/task-groups.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by scycer** [comment]
I have the same question, i had to revert the pipeline to get back the tasks in the old form (decomposed)

**Comment by tfosmark** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by scycer** [comment]
Sorry but i dont believe this is a specific scenario or implementation. It's a general question of "Now that i have turns a handful of tasks into a group, how do i ungroup them?"

For anyone else the current work around i did was using the previous version of a pipeline before i made the tasks into a group

**Comment by blueelvis** [comment]
@tfosmark - No, this is not an issue with a scenario. What I meant is, the document is missing the steps/instructions on how to decompose a task group once it has been created. I don't see how that is a scenario.

Please re-open this issue.

**Comment by RoopeshNair** [comment]
@blueelvis - de-composing taskgroup once created is not supported. As @tfosmark suggested, you can revert to a previous version of the pipeline.

**Comment by blueelvis** [comment]
@RoopeshNair - I am not sure why you are so eager on closing this? If this is not possible, this needs to be added in the documentation as a note because it doesn't make sense in reverting the pipeline every time you need to decompose a task group.

**Comment by blueelvis** [comment]
@RoopeshNair @tfosmark -- Could you please reopen this bug and get this clarification in the doc? Would be happy to submit a PR for this.

**Comment by ashokirla** [comment]
Will update the task group documentation accordingly.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by blueelvis** [comment]
This is still not fixed. Please reopen.

**Comment by wesleyolis** [comment]
Menu Item, when right click on a task group -> Decompose Task, would be great.
Menu Item, when right click on a task group -> Edit Task Group as use draft.
When Editing and existing release, one loose the ability to test and fix stages when task are a task group, so please implement Edit Task Group as a draft, were the draft iteration is then used for any redeployments in the release that was created. When one is happen that all is working. then one goes to the release or to the draft that has been kept under task groups and well save to be the official task group again, with the edited release fixies of the task group.

Sadly Task group functionality, which is very well need, is buggy and prevent using drafts, due to inline powershell scripts variables being picked up.

Please improve this feature, very limiting and basically reduce the power of azure pipelines to very little, as one has to clone and reset everything up all the time for a stage. If I have 20 copies of the same group of task, this just becomes silly massive maintenance exercise, in which one going to look for alternative product or run some other external automation tool to do the work, in which azure pipelines in many cases, is just used to trigger recipes. Because issues of Task groups pick up the wrong variables.
