### ISSUE TITLE
Why would a "/move" modifier actually execute a delete?

### ISSUE THREAD

**Issue by opedroso** [MicrosoftDocs/azure-devops-docs#6506]
```
tf vc unshelve /move "My Shelveset"
```
Seems like an amazing misnomer for the "/move" modifier.
From a verb that indicates a "movement", that is a non destructive action, comes a loss of information, since the action executed after the unshelve is the deletion of the named shelveset on the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8483a450-a07f-587a-949d-a2293b50f52c
* Version Independent ID: 304ebcef-0efa-eefc-7d41-56f48caaf5be
* Content: [Unshelve Command - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/unshelve-command?view=azure-devops)
* Content Source: [docs/repos/tfvc/unshelve-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/unshelve-command.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@opedroso -- Osiris, thank you for your feedback.  It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

@apawast -- Apeksha, please look into this potential documentation issue.

**Comment by IlyaChistov** [comment]
#reassign @IlyaChistov

**Comment by MaximMalygin** [comment]
There is no issue in documentation here. From the document:

/move | Deletes the specified shelveset from the server for Team  Foundation version control upon successful completion of the unshelve  operation. This option cannot be combined with an itemspec. You can also delete a shelveset using the shelve command.


@msebolt  Can we close it?
