### ISSUE TITLE
Is there a prefined variable for the location of the azure-yaml pipeline being executed?

### ISSUE THREAD

**Issue by frankfru** [MicrosoftDocs/azure-devops-docs#6512]
Is there a prefined variable that contains the  location of the yml pipeline definition?
For example, if the definirion of the yml pipeline being executed is located in the repo in frontend/component-1/azure-pipeline.yml, the variable should have the value 'frontend/component-1/azure-pipeline.yml'.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@frankfru -- thank you for your question.  You may find an answer here:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

@juliakm -- please look into this potential documentation issue.

**Comment by frankfru** [comment]
I've look at those resources and other ones, but as far as I can see there's no predefined variable that contains the full path of the yml file (i.c. 'frontend/component-1/azure-pipeline.yml', actually I'm only interested in the path-> 'frontend/component-1')

**Comment by pollockm** [comment]
I am also in need of this as a predefined variable.  The reason is that we operate in a monorepo that contains several components, not all of which share a common top-level build pipeline.  

Ex: 
/component A/azure-pipelines.yml
/component A/src/...
/component B/azure-pipelines.yml
/component B/src/...

I want the pipeline for component A to trigger only if an item in the /component A/src hierarchy changes.  Yes, I can hardcode the included paths in the build triggers.

I will have many components, developed by folks with no knowledge of pipelines.  I do not want each component developer to maintain a brittle hardcoded path in the azure-pipelines.yml file for which paths should trigger the build.

Instead, I want something like this:
trigger:
  paths:
    include:
    - $(Pipeline.Directory)/src/*

This would allow me to reuse the same template and not care if my repo structure changes.  It would also allow my developers to stop complaining about the overhead imposed on them by Azure Devops  :)

**Comment by djpugh** [comment]
This would be really helpful as well assuming it contained the "expanded" yaml from any used templates

**Comment by juliakm** [comment]
My understanding is that there is not a predefined variable for this. You could use `Build.Repository.LocalPath` and then combine it with the name of your pipeline file. But, that would not address @pollockm's concern about wanting to be able to preserve a path if your repo structure changes. 

It would be helpful if one of you could open a feature request in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). That forum is monitored by the engineering team.
