### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ChrisColeTech** [MicrosoftDocs/azure-devops-docs#6627]
This does not work for VSTS repos, or *.visualstudio.com repos.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e7fcfcb-c10c-be34-4a9d-94d54245a3da
* Version Independent ID: aa7b7720-7c7e-1b4f-96e8-3bf068efe9fd
* Content: [Clone a Git repository in a public project - Azure DevOps Services Public Project](https://docs.microsoft.com/en-us/azure/devops/organizations/public/clone-git-repo-public?view=azure-devops#feedback)
* Content Source: [docs/organizations/public/clone-git-repo-public.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/clone-git-repo-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ChrisColeTech Thank you for the feedback.

Does this apply to a specific set of instructions in the documentation, i.e. with Visual Studio or command-line and what is the specific error?

Please note that since this is the documentation forum our support options are limited. 

For further support, you will need to move the issue [here](https://developercommunity.visualstudio.com/content/problem/19752/git-cant-clone-remote-repository.html) to get feedback from the product team.

**Comment by msebolt** [comment]
Closing the issue now.

**Comment by ChrisColeTech** [comment]
There is no 'Clone' button on VSTS repos - 

<img width="1404" alt="Screen Shot 2019-12-13 at 7 26 12 AM" src="https://user-images.githubusercontent.com/33706157/70800313-e9dc5200-1d79-11ea-812e-9c18c8c0b1b9.png">

so step 2 fails.

Also, it does not work from the command line:

<img width="565" alt="Screen Shot 2019-12-13 at 7 29 18 AM" src="https://user-images.githubusercontent.com/33706157/70800468-56efe780-1d7a-11ea-9183-a1b3f5a0db71.png">


Using Visual Studio is not an option because I am on a MacBook.

**Comment by msebolt** [comment]
Assigning this to the author for review.

**Comment by vtbassmatt** [comment]
That's not a Git repository, it's TFVC. There is no "clone" button for TFVC.
