### ISSUE TITLE
Helm 3.0.1 is not supported

### ISSUE THREAD

**Issue by devedse** [MicrosoftDocs/azure-devops-docs#6646]
When trying to use the latest Helm 3.0.1 using the install task everything installs fine, however I run into some trouble when I then try to do a Helm deployment using the Helm Install command:

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md

I run into the following error:
```
2019-12-11T15:47:29.9107558Z [command]C:\hostedtoolcache\windows\helm\3.0.1\x64\windows-amd64\helm.exe install --namespace UserProvisioning --values D:\a\r1\a\_UserProvisioning-CI\dropHelm\values.yaml --set containerregistryurl=xxxx.azurecr.io,build=36 --name hello --wait D:\a\r1\a\_UserProvisioning-CI\dropHelm
2019-12-11T15:47:30.5427999Z Error: unknown flag: --name
2019-12-11T15:47:30.5529448Z ##[error]Error: unknown flag: --name
```

According to the documentation this has been changed to --generate-name

E.g. if you manually run the command without the --name it requests this:
```
Error: must either provide a name or specify --generate-name
```

This is currently blocking the releases for our customer, so it's quite high priority for us.

**Comment by WilliamAntonRohm** [comment]
@devedse -- Devedse, thank you for your feedback.  You may find answers here:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

@shashankbarsin -- Shashank, please look into this potential documentation issue.

**Comment by shashankbarsin** [comment]
@devedse, we are yet to update the Helm task to have an option to use either Helm 2 or Helm 3. So right now, the task is generating command scripts that are specific to Helm 2 while using Helm 3 cli that was installed correctly by the Helm Installer task.

We will definitely have an update on this issue soon. However, in the meanwhile, can you try out the following to unblock yourself - 
- Use Helm Installer task to install Helm 3 as you are currently doing
- Use [command line task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml) to write the Helm commands you want to execute instead of using the Helm task

**Comment by devedse** [comment]
Hi @shashankbarsin , thanks for the response.

For now we changed the command to helm upgrade which apparently worked after some tweaking. (I think it doesn't make use of any new or obsoleted values in comparison to Helm v2)

**Comment by shashankbarsin** [comment]
We'll just do a check once of the commands supported by the Helm task currently to see if there any changes required. If no changes are required, that's perfect and I'll close this issue. If changes are required, we will fix it.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
