### ISSUE TITLE
Helm Task doesn't support Helm 3.

### ISSUE THREAD

**Issue by Cutux** [MicrosoftDocs/azure-devops-docs#6672]
Hello,

Currently I'm trying to package my chart in Azure Devops using the Helm task, first I'm installing version 3.0.1 and it completes fine, but when I run 'helm package' I get the following error:

```
/opt/hostedtoolcache/helm/3.0.1/x64/linux-amd64/helm package --save --destination home/vsts/work/1/a/k8s/helm --values /home/vsts/work/1/s/Api-Search-Upload/build/azure-devops/values.yaml /home/vsts/work/1/s/stin-pipelines/deploy/k8s/helm/stin-microservices
Error: unknown flag: --save
##[error]Error: unknown flag: --save
```
This is blocking our releases, so please I hope you guys can help us.

Thanks in advance.

Regards.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

Meanwhile, you may find answers here:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by WilliamAntonRohm** [comment]
@Cutux -- Cutu, thank you for your feedback.

@rootd00d -- Casey, thank you for finding a solution.

@azooinmyluggage -- Atul, please look into this issue.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
