### ISSUE TITLE
Orginazation Scoped Feeds

### ISSUE THREAD

**Issue by RichardMeadowsTC** [MicrosoftDocs/azure-devops-docs#6715]
Where is the documentation for creating an organization scoped feed?  I need a new feed that is Organization-scoped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db27124-fabe-5ab3-0f2e-e866cabff257
* Version Independent ID: c64aad85-16eb-919a-aff1-34f350065019
* Content: [What are feeds? - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/feeds?view=azure-devops#feedback)
* Content Source: [docs/artifacts/concepts/feeds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by anandlukose** [comment]
I am looking for the same as well. Existing feeds are switched to organizational scope and we have to create more but we can only create project scoped feeds now. Any help is appreciated.

**Comment by msebolt** [comment]
@RichardMeadowsTC Thank you for the question, assigning this to the author for review.

Please refer to the open issue [here](https://developercommunity.visualstudio.com/idea/863132/organisation-scoped-feeds.html) for feedback and updates from the product team.

Details on using the API can be found [here](https://developercommunity.visualstudio.com/content/problem/859583/can-no-longer-create-organization-scoped-feeds.html).

**Comment by cdietschrun** [comment]
What's the status here of the documentation? It's not clear at all to me how to make something organization scoped.

**Comment by cdietschrun** [comment]
It looks like we're expected to use the REST API to switch to organization scoped. This does not seem sufficient to me, why was this removed from the UI?

**Comment by kieronlanning** [comment]
Our release pipelines are breaking because the url the DotNetCLI task is generating is based on a organisational feed, not a project one.

Can you update the docs for fix both the creation of organisation feeds and for the DotNetCLI, in particular the `push` command.

**Comment by brunomartinspro** [comment]
Any changes on this?

**Comment by RichardMeadowsTC** [comment]
No change yet.  Microsoft thinks people don’t need Org scoped feeds still.  Last time I checked, the documentation for using REST api to create a feed makes no mention of Org scoped feed.  Possible to do.  But you have to know about not including the Project name in REST url.

Richard Meadows

**Comment by ramiMSFT** [comment]
@RichardMeadowsTC Thank you for your feedback. Creating a new organization-scoped feeds through the UI is not supported.

- All new feeds are recommended to be project-scoped. Creating a new feed through the create feed panel will create a project-scoped feed.

- You can use the [Create Feed API](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed%20%20management/create%20feed?view=azure-devops-rest-5.1) to manually create a new organization-scoped feed. You will have to set the default permissions for the new feed manually either by using the [Feed Permission API](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed%20%20management/set%20feed%20permissions?view=azure-devops-rest-5.1) or the Artifacts feed settings. Creating new organization-scoped feeds is not recommended.

A "Suggest a feature" ticket has been submitted for: [organisation-scoped-feeds](https://developercommunity.visualstudio.com/idea/863132/organisation-scoped-feeds.html)

You can up vote to increase the priority of this feature. Thank you

**Comment by brunomartinspro** [comment]
@ramiMSFT can someone the  explain it to me how are we going to share microservices artifacts if sharing artifacts between projects is not recommended?

Example:

Architecture Project

Project A
Repository A
Repository B

Project B
Repository C uses Architecture Artifacts 
Repository D uses ProjectA Artifacts 

Furthermore there is the issue of the package replacement settings not having a “allow package replacement”.

So this was closed because there is nothing we can do to support microservices?

**Comment by RichardMeadowsTC** [comment]
My security guy is making me use project scoped artifact feed.  Apparently, the security really isn’t there.  Will see about that.  The build account is supposed to have access to feeds from all the projects.  Like what I have.

Richard Meadows

**Comment by brunomartinspro** [comment]
At this point I’m just trying to understand why the concept of feeds of Microsoft is so different from the rest of the solutions out there in the world. 

My first issue was with package replacement - why would anyone force teams to increase the versions of packages? Couldn’t this be a setting? What if something goes wrong in a build and we need to replace it with the same version to send it to the client? Should we say to the client “Hi, unfortunately we ran into an issue and we won’t be releasing 1.0.0, we will be releasing 1.0.1” even though the 1.0.0 version never went to the customer.

If the API allows the creation of Organization feeds(that’s what I read at least), why would it not be in the UI? Since the frontend runs JavaScript couldn’t it call the API with an internal token and configure the permissions in the UI as well? 

So someone works in a company with 3000 projects and wants to share a feed with 2 projects (or the 3000 if it’s an architecture project) - why would it be a security issue to give two clicks in the UI to select a project to give access? Why would it be safer to only have access to a project?
