### ISSUE TITLE
[Approvals] Pipeline variable for environment approval

### ISSUE THREAD

**Issue by aapalm** [MicrosoftDocs/azure-devops-docs#6751]
Is there a way to fetch the approver's id / email and date in the pipeline?  I can't seem to find any predefined variable or REST API for this.

For releases, there was a PreDeployApprovals and PostDeployApprovals we could use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup or to let me know your results.  We hope to hear from you again.

**Comment by nicolasproton** [comment]
I have the same problem with my YAML pipeline. I am not able to (or don't know how to) retrieve the environment approver(s) for a deployment step. There is no documented API.

**Comment by aapalm** [comment]
@nicolasproton , @Materia-xx, created a community feature request, feel free to vote for it
https://developercommunity.visualstudio.com/content/idea/925034/multi-stage-pipeline-variable-for-environment-appr.html

**Comment by cmitescu** [comment]
hello, 
we have the same problem and we really need to extract the message the user is specifying in the approval section in order to pass it further down the pipeline. 
Can we do something about this or is it something already put in place that we can in a similar way?

Thank you in advavnce,
-Cosmin

**Comment by WilliamAntonRohm** [comment]
@aapalm, @nicolasproton, @cmitescu -- thank you for clarifying.

@shashankbarsin -- please look into this potential documentation issue.

**Comment by manivasm** [comment]
any update on this.

**Comment by josegalarceh** [comment]
hello! any update?

**Comment by NagaShekar** [comment]
any update on this. We need this feature.

**Comment by WilliamAntonRohm** [comment]
@manivasm, @josegalarceh, @NagaShekar -- thank you for your followup.  In addition to the [previously-mentioned resources](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6751#issuecomment-569353778), please consider this one as well:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 

Also, please upvote @aapalm's [community feature request](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6751#issuecomment-589328933).

@shashankbarsin -- please look into this issue, or reassign it as needed.
