### ISSUE TITLE
How to deprecate / un-promote package that was promoted to a view for Maven?

### ISSUE THREAD

**Issue by soccerjoshj07** [MicrosoftDocs/azure-devops-docs#6960]
Is it not possible? I am only allowed to promote but not unpromote / deprecate.

See screenshots:
![Screen Shot 2020-01-16 at 9 41 31 AM](https://user-images.githubusercontent.com/19912012/72539320-be4efa80-3844-11ea-9ddf-6d833f0572b9.png)
![Screen Shot 2020-01-16 at 9 41 40 AM](https://user-images.githubusercontent.com/19912012/72539324-c018be00-3844-11ea-8931-80e62f394513.png)
![Screen Shot 2020-01-16 at 9 41 44 AM](https://user-images.githubusercontent.com/19912012/72539328-c1e28180-3844-11ea-953d-4e4b8ac7b901.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven#feedback)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by soccerjoshj07** [comment]
I only consider this an issue with the documentation because is it intended that Maven artifacts can't be demoted once promoted?  It doesn't mention on these page(s)

**Comment by WilliamAntonRohm** [comment]
@soccerjoshj07 -- Joshua, thank you for clarifying.

@chasewilson -- Chase, please look into this issue.

**Comment by ramiMSFT** [comment]
@soccerjoshj07 Thank you for the feedback. Package demotion is not supported. I added a note for more clarification. The updated article will go live shortly.
