### ISSUE TITLE
vstsFeedPublish is inconsistently documented in sections

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/azure-devops-docs#6964]
in Publish your packages vstsFeedPublish is hinted as feed name, but in Package versioning it's feed guid.

it should be feed guid in both places

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish & download Universal Packages - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by hammady** [comment]
How to get the feed guid anyway? I don't seem to find it.

**Comment by hammady** [comment]
Feed name should also work but with the project name as a prefix. For example: `Project1/my-feed`.

**Comment by Justin-DynamicD** [comment]
only way i wa sable to get eh guid was to use the classic method to make a one-step pipeline, then saved it as yaml and took the GUID it assign :/

**Comment by kozmaz87** [comment]
Or you can use the api. 

https://{accountName}.feeds.visualstudio.com/_apis/packaging/Feeds/

The id you need is the project id SLASH(FFS where was that mentioned) the feed id. <org_uuid>/<feed_uuid>.

But I agree it is absolute shite docs. Typical Azure unfortunately. Contradicting themselves in the same page is very common with these guys.

**Comment by Justin-DynamicD** [comment]
OK, I did some extra testing this weekend, and this documentation needs some updating.

downloading vstsfeed by name works, but you must be careful to understand if you are attempting to read an organizational or project scoped feed.

The DefaultFeed in Azure artifacts is organizational, and thus can be downloaded using merely its feed name, however project-scoped feeds must be done in the format of <project name>/<feed name>.

But it gets better.

It appears that once you "unlock" that you can use simple names, it seems you can incorporate views as well (which is completely undocumented and I basically guessed by looking at syntax elsewhere):

<project name>/<feed name>@<view> 

Now I can download the latest version of an artifact that has been promoted to the appropriate view.

I think this means this document needs some good clarification, because this is a pretty big omission.

**Comment by Justin-DynamicD** [comment]
huh ... using certain characters gets swallowed up ...

project/feed

project/feed@view for further filtering will work in download mode.

**Comment by dajoen** [comment]
So, just tried it. And it didn't work using project/feed, but now it worked just using feed name.

**Comment by Justin-DynamicD** [comment]
feed name vs. project/feed depends on the scope of the feed. Organizational Feeds only need the name, project feeds must be prefixed wit the project.

**Comment by ramiMSFT** [comment]
@drdamour Thank you for your feedback. The new version will go live shortly.
