### ISSUE TITLE
SSH Key for pipeline agent

### ISSUE THREAD

**Issue by khbafl** [MicrosoftDocs/azure-devops-docs#7084]
When we need to pull an Azure Devops repository git-ssh-url as a terraform module in a pipeline, we can use the "InstallSSHKey" task to import the private key, but we have to upload the public key in our own account instead of a "pipeline agents account". How can we associate an ssh public key to  "pipeline agents" instead and allow thay ssh key to pull repos? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops&tabs=current-page#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by citypaul** [comment]
Any update on this at all? This is an issue for a project we are working on.

Our use case is we want to be able to consume private terraform modules that are referenced via the git ssh syntax, and stored in a repository inside Azure Devops.

Currently it seems the only way we can do this is for one of us to upload a public key against our personal Devops account.

This is obviously an issue because if the person in question ever left, these pipelines would stop working.

**Comment by vtbassmatt** [comment]
There's no way to associate an SSH key with the pipeline agent identity. Feel free to suggest it on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). In meantime, I suggest switching your `origin` URL to use https instead.
