### ISSUE TITLE
PublishWebProjects and projects

### ISSUE THREAD

**Issue by adamtuliper** [MicrosoftDocs/azure-devops-docs#7149]
If the projects field is used but PublishWebProjects is missing, it defaults to true and tries to find a web project in the solution to publish, ignoring the 'projects' line. The docs should mention projects will be ignored if PublishWebProjects is true (or missing hence defaulting to true)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by nathanbacon** [comment]
Additionally, this documentation suggests that you can use the projects field without setting the publishWebProjects to false.

![image](https://user-images.githubusercontent.com/25492467/90661494-1f381a00-e1fc-11ea-8fd2-127462f4797c.png)

That actually wouldn't work in the current state of the task. I feel like either this is a bug rather than an enhancement, or the docs should be updated to reflect this behavior.

The below [code](https://github.com/microsoft/azure-pipelines-tasks/blob/c6c000cf745d3f0a71cba49f351932b28bddad77/Tasks/DotNetCoreCLIV2/dotnetcore.ts#L354) shows where this is being overridden. 

```
        var searchWebProjects = this.isPublishCommand() && this.publishWebProjects;
        if (searchWebProjects) {
            projectPattern = ["**/*.csproj", "**/*.vbproj", "**/*.fsproj"];
        }
```

**Comment by musmuris** [comment]
I'd also +1 this as odd behaviour for the task. If "projects" is set then that should take precedence over publishWebProjects.
