### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by CJBS** [MicrosoftDocs/azure-devops-docs#7172]
Can this object be used to override a gated check-in requirement for a submission used via the TFS API? If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a554f6-d274-26cb-55cf-a49df7f317d5
* Version Independent ID: 454698b1-3302-62a1-2fdd-29e9e66c770b
* Content: [TFS/VersionControl/Contracts TfvcPolicyOverrideInfo API - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/api/tfs/versioncontrol/contracts/tfvcpolicyoverrideinfo?view=azure-devops)
* Content Source: [docs/extend/reference/client/api/TFS/VersionControl/Contracts/TfvcPolicyOverrideInfo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/VersionControl/Contracts/TfvcPolicyOverrideInfo.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@CJBS -- thank you for your questions.  You may find answers hereL- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by chcomley** [comment]
Adding @zachariacox for further guidance/assistance, thank you!

**Comment by chcomley** [comment]
This issue is stale, so it will be closed. Please check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported. For more extension information, see the [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/develop/extensions), [REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-5.1), [Extension samples](https://github.com/Microsoft/azure-devops-extension-sample), and resources in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Please don't hesitate to @mention me if you have any further questions. Thanks!
