### ISSUE TITLE
What permission is needed to define environments?

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/azure-devops-docs#7200]
What permission is needed to define environments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c6f274-a008-fac6-7d99-13d2ce7c8dc3
* Version Independent ID: 916fef9e-d644-2114-b466-e5bda8028ee9
* Content: [Pipeline permissions and security roles - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/permissions?view=azure-devops)
* Content Source: [docs/pipelines/policies/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/permissions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by ciufudean** [comment]
@WilliamAntonRohm It is also an issue with the documentation as I expected it to document this permission.

**Comment by WilliamAntonRohm** [comment]
@ciufudean -- thank you for clarifying.  My apologies for the delay in responding.

@juliakm -- please look into this issue.

**Comment by juliakm** [comment]
@ciufudean You can find the permissions for environments [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#user-permissions).  I'll also add a link from the permissions page.
