### ISSUE TITLE
"Failed to find project for this organization"

### ISSUE THREAD

**Issue by dan-miller** [MicrosoftDocs/azure-devops-docs#7213]
I am a Project Administrator of several projects, but I see a message "Failed to find project for this organization" after selecting my company's organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by slifland37** [comment]
@WilliamAntonRohm 
This is an issue with the documentation to the extent that it includes virtually no information about what privileges you need in order to complete the steps in the section "Configuring a new connector for Azure DevOps Services." The rest of the documentation is basically useless if people can't get past step 3. The note that you must be a Project Administrator is clearly not the whole story; I belong to that group for my project and I am encountering the same error @dan-miller mentioned.

**Comment by WilliamAntonRohm** [comment]
@slifland37 -- Seth, you make a good point.

@chasewilson -- Chase, please look into this issue.

**Comment by mcalnd70** [comment]
I've spend half a day on this issue and going around and around and around - I don't understand why I keep seeing this message "Failed to find an organization." - it is preposterous

**Comment by dan-miller** [comment]
@mcalnd70 - it turns out that we had OAuth disabled globally for our organization. Check "Organization Settings" -> "Policies"

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by randyburden** [comment]
Ran into the same issue. Found the solution here: https://developercommunity.visualstudio.com/t/MS-Teams---Failed-to-find-project-for-th/10461541?pageSize=15&sort=active&topics=.net

> When connecting Azure DevOps from other MS services, please ensure the “Third-party application access via OAuth” is Enabled in Organization Settings -> Policies -> “Third-party application access via OAuth”.

![B81f9e0ecfd54445495b40ed2b557ac56638297719219010523_20230908-201201-image](https://github.com/MicrosoftDocs/azure-devops-docs/assets/458529/67be1c33-0965-495e-bbd5-781ac240791b)
