### ISSUE TITLE
Tests Associate out of VS ?

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/azure-devops-docs#7385]
Hello, can i do tests associate in some way out of VS 2017/2019 ? I mean in Azure DevOps, VSCode, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by varnk** [comment]
When is this going to be available for Visual Studio 2019?  Currently 2019 does not support TCM, which is a huge oversight.

**Comment by WilliamAntonRohm** [comment]
@jimicze -- thank you for your question.  You may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@varnk -- thank you for your feedback.  It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

@steved0x -- please look into this potential documentation issue.

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
