### ISSUE TITLE
Is there a way to prioritise jobs?

### ISSUE THREAD

**Issue by BlairMcc** [MicrosoftDocs/azure-devops-docs#7441]
I may have many jobs that can kick off at the start of a run, but one of these is essential that it runs early, as that unlocks more jobs

I'll generally have 3 agents available to me, so its possible Job A, B, C will be picked up to run first, but not Core which is where my greater dependencies are?

Core -&gt; Job1
         -&gt; Job2
         -&gt; Job3
                        -&gt; Job4
JobA
JobB
JobC

Is there a way to prioritise a single job over others, when there are multiple that it could run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#dependencies)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@BlairMcc -- Blair, thank you for your question.  You may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@juliakm -- Julia, please look into this issue.

**Comment by BlairMcc** [comment]
Hey @juliakm 

I know I could use dependencies, they're already in place where they are needed, but I don't want these other shorter standalone jobs tied to and delayed by an earlier running process.

ie green is current state, with black showing genuine build dependencies. In green build it is possible my three agents are consumed on run start by the small standalone jobs, delaying the top group of chained jobs. In red build, as you are suggesting, chains those standalone jobs to my higher priority job, delaying builds needlessly

I'm not sure this ultimately has a massive impact on our build times, just want to throw it out there in case there is some hidden support for it

![image](https://user-images.githubusercontent.com/16471369/75923117-4e1a3800-5ec9-11ea-9830-ad17b6c18adf.png)

**Comment by wbin666** [comment]
I get the same requirement to prioritize some standalone jobs in a yaml pipeline.  Any suggestions or plan to support this?

**Comment by Lightw3ight** [comment]
I would like to do this too

I have a distributed task execution pattern in my build where I have a "main" job that feeds work to the "agent" jobs
The problem is that if the "agent" jobs begin but the "main" job is queued, no work will be sent to the agent jobs and they will just spin until the main job starts and begins feeding them work
it would be great if I could set some sort of priority so that "main" always took the first available agent

**Comment by Ruud-cb** [comment]
+1, would like to have this in the Classic Editor as well.

**Comment by zsd4yr** [comment]
@juliakm would you mind re-opening this issue? I don't think the request has been addressed.

I believe the request is "Given some number of jobs which satisfy their dependencies at the same time, what mechanism should be used to determine the order in which they run?" This is a question of overall throughput.

For instance, imagine I have jobs A, B, C, D, E, and F
Job A is a dependency of jobs B, C, and D.
Job D is a dependency of jobs E and F.

<img width="947" alt="Drawing12" src="https://user-images.githubusercontent.com/10677481/171822602-27526be7-2cbd-406f-b72f-f50da2eddcca.png">

Once A is completed, B, C, and D are free to begin.
However, you would obviously want D to start first as it is the only gate on E and F.
Is there a way to ensure that job D has a "higher priority" than jobs B and C so that in a situation with limited machine capacity, D will start before B and C in order to unblock E and F?

<img width="947" alt="Drawing12 (1)" src="https://user-images.githubusercontent.com/10677481/171822978-078387c3-c659-4891-9bbc-a6fbefd01249.png">

This feels like a feature gap. Other build orchestration systems have this feature; jenkins calls this priority, team city priority class, and build tracker also priority.

**Comment by WilliamAntonRohm** [comment]
@all -- thank you for your interest and follow-up.  Please see [Julia's message above](https://github.com/MicrosoftDocs/azure-devops-docs/issues/7441#issuecomment-594557961), and raise this issue as a feature request in the Developer Community.

cc @juliakm for awareness

**Comment by zsd4yr** [comment]
For anyone wanting to add pressure to this feature request, please see https://developercommunity.visualstudio.com/t/Add-a-way-to-prioritize-jobs/10085575

@WilliamAntonRohm, @juliakm  since I am internal, please feel free to reach out to me as a customer over email or teams if you want to discuss further

**Comment by juliakm** [comment]
Closing since this is a feature request.

**Comment by Turbofroggy** [comment]
This is not a feature request, the feature already exist. It is a bug as the feature doesn't work:  https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds/get?view=azure-devops-rest-6.1#queuepriority

**Comment by thisisthekap** [comment]
@juliakm As @Turbofroggy pointed out, this is a bug. Please reopen.

**Comment by WilliamAntonRohm** [comment]
@Turbofroggy, @thisisthekap -- thank you for your follow-up.  If you feel this is a product bug, please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

**Comment by juliakm** [comment]
I've checked with the product team and Azure DevOps does not support job priority for YAML build pipelines. There are no plans to add this feature.

I'm looking into updating the REST API docs and will make this clearer in the jobs article.

@WilliamAntonRohm for reference.

**Comment by thisisthekap** [comment]
@juliakm Can you provide a workaround to achieve build priorization other than clicking "Run next" manually for each pipeline run?

Can you furthermore give us some insights on why there are no plans to implement this feature?
