### ISSUE TITLE
Not able to use the "No authentication" scheme

### ISSUE THREAD

**Issue by anuraagkb** [MicrosoftDocs/azure-devops-docs#7505]
I have added the "No authentication" json code in my vss-extension.json file but it throws the below error when installing my custom extension:

Extension validation error

The following errors were found in service connection contribution: Authentication schemes ms.vss-endpoint.service-endpoint-auth-scheme, are not valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad945cf7-cd73-49da-90f5-21eb88f485e1
* Version Independent ID: d3032766-fb21-d299-e34f-05fe1010132c
* Content: [Authentication Schemas for Service Endpoints - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth-schemes?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/auth-schemes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/auth-schemes.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by VAllens** [comment]
@anuraagkb 
```json
{
	"id": "endpoint-auth-scheme-none",
	"description": "i18n:Creates an endpoint authentication scheme with no authentication.",
	"type": "ms.vss-endpoint.endpoint-auth-scheme-none",
	"targets": [
		"ms.vss-endpoint.endpoint-auth-schemes"
	],
	"properties": {
		"name": "None",
		"displayName": "i18n:No Authentication"
	}
}
```
["No authentication" 's configuration is wrong](https://github.com/MicrosoftDocs/vsts-docs/issues/7693)

##### FYI.

**Comment by chcomley** [comment]
This issue is stale and will be closed. Please check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported. For more extension information, see the [Formula Design System](https://developer.microsoft.com/en-us/azure-devops/develop/extensions), [REST API reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1&viewFallbackFrom=azure-devops-rest-5.1), [Extension samples](https://github.com/Microsoft/azure-devops-extension-sample), and resources in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). Please don't hesitate to @mention me if you have any further questions or if this continues to be a problem. Thanks!
