### ISSUE TITLE
Unable to delete service connections

### ISSUE THREAD

**Issue by dastewa** [MicrosoftDocs/azure-devops-docs#7638]
Hi Team,

I have several service connections for my team's project that I am unable to delete from the DevOps UI or via the Rest Api. When I try to remove these from the UI, it just takes me back to the list where the service connection still exists. When I try to remove them from the Rest Api, I initially get a 204 which should indicate success, but the service connection remains. Subsequent attempts with the Rest Api also don't remove the service connection but give a 500 error (which feels like a bug, I would have expected a 404 response for a operations on a nonexistent resource).

Any help would be appreciated! I would like to have these service connections removed and not shown in the DevOps UI.

Best,
Damiene

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by iashishmittal** [comment]
@dastewa : 
Can you tell me the type of these service endpoints?
Are all of these Azure based endpoint or they are of different kind also?
In case of azure based endpoint for which SPN is autocreated, we try to clean up the SPN when the endpoint is deleted. Sometimes Azure DevOps is not able to delete these endpoint because of issues contacting to Azure.
To overcome this, try deleting this endpoint using rest API and setting the optional parameter deep = false
https://docs.microsoft.com/bs-latn-ba/cli/azure/ext/azure-devops/devops/service-endpoint?view=azure-cli-latest#ext-azure-devops-az-devops-service-endpoint-delete

**Comment by sghaugen** [comment]
@iashishmittal -- I have the same problem -- I cannot seem to be able to delete the SPN from Azure DevOPs.  I tried the endpoint but I am getting a 500 response.

**Comment by juliakm** [comment]
@dastewa I hope you were able to resolve the issue. In the future, the best place to report possible bugs is the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
