### ISSUE TITLE
YAML Conditions for either of the last two stages succeeded (not knowing which one may succeed)

### ISSUE THREAD

**Issue by valmonten** [MicrosoftDocs/azure-devops-docs#7680]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Doc feedback: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml

Is there a way to have a stage dependent on 1 of the previous 2 succeeded not knowing which one might succeed?
Lets say:
stage: A
...
stage: B
...
stage: C
dependsOn: [A,B]
condition: succeeded(A or B)

If one of the two succeeds then run C.

**Comment by WilliamAntonRohm** [comment]
@valmonten -- Nathan, thank you for your question.  You may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm -- Julia, please look into this potential documentation issue.

**Comment by snaquekiller** [comment]
@valmonten did you find the response of your question , i have the same problem as you .

**Comment by juliakm** [comment]
We recently updated the documentation related to this. If the previous job succeeded but a dependency further upstream failed, `succeeded('previousJobName')` will still return true. When you just use `dependsOn: previousJobName`, it will fail because all of the upstream dependencies were not successful. You can also pass multiple arguments to `succeeded()`.  For more complex cases, you can also look at using [dependencies context](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies).

**Comment by snaquekiller** [comment]
thanks for the response. But i try this, but the probleme is that on of the stage is still on waiting for approval, so i need to refuse the approval for going to the next stage ... it's not really what i wanted.
But thanks

**Comment by juliakm** [comment]
I didn't realize you were also using [approvals](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass). I'd recommend asking this implementation question in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
