### ISSUE TITLE
Yaml pipeline: Deployment Jobs do not do checkout implicitly like Jobs

### ISSUE THREAD

**Issue by theBlueclouds** [MicrosoftDocs/azure-devops-docs#7697]
As mentioned [here](https://stackoverflow.com/questions/60844578/yaml-pipeline-deployment-vs-jobs-scriptpath-and-csmfile-not-working/60845198#60845198)

When a Jobs is converted to Deployment jobs the paths fail because the checkout does not happen. Why does it happen in 'Jobs' then ? Why the inconsistency? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@theBlueclouds -- thank you for your question.  It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

@juliakm -- please look into this potential documentation issue.
