### ISSUE TITLE
How do we add tag to the resource group ?

### ISSUE THREAD

**Issue by csamleong** [MicrosoftDocs/azure-devops-docs#7870]
I did not see tags at the resource group level being mentioned here. How do I add to the resource when I am using this task?

Or we have to do it via PowerShell script?

**Comment by WilliamAntonRohm** [comment]
@csamleong -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by csamleong** [comment]
@WilliamAntonRohm  hi, I am referring to [https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops]

I am deploying resources via template file. Which the result would be a resource group with my designated resources as I declared in my template file. 

I can assign a tag to my resources via template file. But is there any properties in the task that I can use to assign my resource group?

Or i have to update my resource group with tag using the ARM template?

**Comment by WilliamAntonRohm** [comment]
@csamleong -- thank you for your questions. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
