### ISSUE TITLE
DockerCompose@0  Combine configuration action Not support Linux

### ISSUE THREAD

**Issue by Nick287** [MicrosoftDocs/azure-devops-docs#7877]
Hi,
I am using Combine configuration action in our project and I found 2 issues here

1. about the Combine configuration action I have code like this. and in my docker-compose.yml file there have some value mark as ${tag} the variable value from AzDO pipeline, all of this works perfectly on Windows VMimage pool BUT our deployment environment is Linux and that doesn't work any more the task cannot find the variable value &{acraddress}/${projectname}/${imagename}:${tag}

        - task: DockerCompose@0
          displayName: Combine configuration
          inputs:
            action: Combine configuration
            dockerComposeFile: '$(Build.ArtifactStagingDirectory)/docker-compose.yml'
            projectName: $(Build.Repository.Name)
            qualifyImageNames: true
            outputDockerComposeFile: '$(Build.ArtifactStagingDirectory)/docker-compose.yml'

###### docker-compose.yml Code snippet ######################################################################

services:
  image-app:
    container_name: app
    image: ${acraddress}/${projectname}/${imagename}:${tag}

2. I moved the Combine configuration action to the CI part and used the Windows image pool but I found another issue which is when I am using variable group link with Azure Key Vault that can not get the value and with out any error message...

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

Meanwhile, here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
