### ISSUE TITLE
Deploy pull request job not working and is skipped in deploy stage

### ISSUE THREAD

**Issue by pretty25** [MicrosoftDocs/azure-devops-docs#7879]
Hi Team, 
I ran this exercise as suggested and get to see deploy pull requests as been skipped but overall build and deploy stages have been run successfully without any errors, so just want to check is this expected to skip as part of this ??

https://docs.microsoft.com/en-gb/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops exercise/lab?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbceb1f5-05c3-487d-6e21-dc1b4936a55c
* Version Independent ID: 35355737-9ad9-9df5-b612-806d9df2462b
* Content: [Deploy to Azure Kubernetes Service - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/ecosystems/kubernetes/aks-template?view=azure-devops)
* Content Source: [docs/pipelines/ecosystems/kubernetes/aks-template.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/kubernetes/aks-template.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by pretty25** [comment]
![image](https://user-images.githubusercontent.com/11729130/78899181-ea0d0580-7a6c-11ea-8cf7-7d6a6ee79995.png)

![image](https://user-images.githubusercontent.com/11729130/78899336-27719300-7a6d-11ea-943d-c26d9783d885.png)

**Comment by WilliamAntonRohm** [comment]
@pretty25 -- thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

cc @steved0x for awareness
