### ISSUE TITLE
ZipAlign uses 19.1.0 SDK, not 29.0.3 SDK, and cannot pass in ZipAlign custom parameters

### ISSUE THREAD

**Issue by titorodi** [MicrosoftDocs/azure-devops-docs#7889]
Looks like the zipalign chosen if using gradle builds (not Android build) is the oldest 19.1.0 SDK. Can it use the latest 29.0.3 instead by default?

Additionally, can we pass in parameters to it please? I need to pass in a '-p' to page align the native libs in our builds so that the APK can install. I've switched to just using a cmd.exe task to manually call ZipAlign otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1fbcd8-d799-879e-d672-9dee164401ef
* Version Independent ID: 7208d03d-9042-7753-ab4d-d1ad8e99ef1d
* Content: [Android signing build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/android-signing?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/android-signing.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/android-signing.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
