### ISSUE TITLE
File path validation not working

### ISSUE THREAD

**Issue by athakkar9033** [MicrosoftDocs/azure-devops-docs#7894]
I have added *test.config in File path validation for Repository policy, but somehow it's not working. Even adding this I am able to change this file and push it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd54e81-9a0c-c5e5-fb89-9534372805ff
* Version Independent ID: f3d49618-32d7-0abc-1c33-8211eb7dd073
* Content: [File matching patterns reference - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/file-matching-patterns.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/file-matching-patterns.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider looking: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

You are also welcome to [file this issue here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).
