### ISSUE TITLE
How to pass Service Connection as a parameter to a Task Group

### ISSUE THREAD

**Issue by danalex07** [MicrosoftDocs/azure-devops-docs#7897]
I haven't seen this option yet, and also the Task Group can't be created without specifying which service connection am i going to use for the specific Task..

**Comment by WilliamAntonRohm** [comment]
@danalex07 -- Daniel, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.  


Also, it looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this now.  Please comment below if there are any further issues.

**Comment by disc-o-boi** [comment]
Hello,

I also tried to parameterize the azure service connection in ARM deployment task, but when I want to use the variable in the service connection field I got error:

![image](https://user-images.githubusercontent.com/35142514/93894825-75aee180-fcef-11ea-85ef-5ea9afdd3ec3.png)

And this vairiable is not listed in parameters list.

I want to parameterize this in the task group, because we got two different service connection for each environment and we have 3 environments, so without that I would need to have 6 different task group instead of 2 :/

Thanks in advance for help!

Regards
Paweł
