### ISSUE TITLE
Creating custom checks

### ISSUE THREAD

**Issue by mmajcica** [MicrosoftDocs/azure-devops-docs#7898]
Is there a way, as there was at example with gates, to create a custom check and ship it in an extension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass#feedback)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
