### ISSUE TITLE
Would be nice for Go Test section of the page to show how to publish test results to azure devops.

### ISSUE THREAD

**Issue by raboley** [MicrosoftDocs/azure-devops-docs#7899]
This is very helpful setting up build test, and gets the test command up there but what I was looking for was to also publish the test results to the pipeline. If that is possible to add would be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86b5c3a-d266-e9fe-621e-eb6244199984
* Version Independent ID: 57ca9f4f-ad07-4ab5-3153-9853e6b24797
* Content: [Build and test Go projects - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/go?view=azure-devops&tabs=go-current)
* Content Source: [docs/pipelines/ecosystems/go.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/go.md)
* Product: **devops**
* Technology: **devops-cicd-ecosystems**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@raboley -- Russell, thank you for your positive feedback.  It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

cc @juliakm for awareness
