### ISSUE TITLE
Query's in powerBi

### ISSUE THREAD

**Issue by mvilches2508** [MicrosoftDocs/azure-devops-docs#7907]
[Enter feedback here]
Al momento de realizar la integración del conector del powerBi desktop con mi proyecto en azure devops, no se despliegan las querys que son mias, compartidas o favoritas, solamente despliega 16 consultas genericas que no contienen los campos que busco desde queries ni desde los wiql.

TRANSLATION: At the time of integrating the powerBi desktop connector with my project in azure devops, the queries that are mine, shared or favorite are not displayed, only 16 generic queries are displayed that do not contain the fields that I look for from queries or from the wiql.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f04bf6a-1455-8770-0a2e-da22f644bced
* Version Independent ID: d63dea23-3678-60c4-c028-c4b618fc3613
* Content: [Analytics permissions and security - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-security?view=azure-devops)
* Content Source: [docs/report/powerbi/analytics-security.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/analytics-security.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mvilches2508 - The generic queries you see are by design, they are the default Analytics Views. If you want to see other date, you can create additional Analytics views and they will show up. See [Create an Analytics view in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-views-create?view=azure-devops) and [Connect to Analytics with Power BI Data Connector](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=azure-devops).
