### ISSUE TITLE
task PublishPipelineArtifact ignoring .git 

### ISSUE THREAD

**Issue by abisekwins29** [MicrosoftDocs/azure-devops-docs#7912]
In a scenario, i need to copy complete workspace to other agent including .git file.
But task PublishPipelineArtifact ignoring .git file.

**Comment by WilliamAntonRohm** [comment]
@abisekwins29 -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by abisekwins29** [comment]
I am using below task, and while uploading it is somehow skipping .git

      - task: PublishPipelineArtifact@1
        displayName: Publish workspace
        inputs:
           path: '$(Build.SourcesDirectory)'
           artifact: workspace
        condition: always()

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options you might consider: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
