### ISSUE TITLE
Does pipelines support building OCaml/OPAM binaries?

### ISSUE THREAD

**Issue by tezzigator** [MicrosoftDocs/azure-devops-docs#7918]
I have a project where the source code lang is OCaml in a git repo.  Is it possible to us Azure Devops CI pipeline to compile the binaries and publish them as artifacts?  Im trying to make a shell/bash script to do so but it seems OPAM isnt loaded in the vm/container.  It seems I can wget to download the binary but then cant execute it at all even after chmod a+x and using ./ to reference it in my local dir.  Is what Im trying to do just not supported?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f15f40a4-bae9-154b-752a-2e9f453d79e3
* Version Independent ID: 3b937e0b-f919-f227-742f-dc740ad4e6f9
* Content: [What is Azure Pipelines? - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/what-is-azure-pipelines?view=azure-devops)
* Content Source: [docs/pipelines/get-started/what-is-azure-pipelines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/what-is-azure-pipelines.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
