### ISSUE TITLE
Azure Build Pipeline - Customize the Tests tab 

### ISSUE THREAD

**Issue by rajachowdhury84** [MicrosoftDocs/azure-devops-docs#7932]
Right now when we supply a JUnit xml as a build step using the PublishTestResults@2 yaml task in the Azure Build Pipeline, it shows the test results under the Tests tab with only few columns - Test Name, Duration, Failing since, Failing build, Tags, Date Completed, Date Started, Owner and Tags in ADO (as shown in the screenshot).

If we want to customize this view under Tests tab and show more columns (having more and different information related to the test) under the Tests tab then, is there a way that we can achieve this?

Below is a sample testcase record and I want to include say, coverage, cputime, etc as columns in the test report

    <testcase time="44" name="default_sanity_regr/Bedrock_Top_sanity_regr/CP_Shell_v2_sanity_regr/CP_Shell_v2_pcie_reg_driver_test/execScript" id="3" status="passed" property="Repeating Task Runnable" cputime="23.40" coverage="36.50"/>

![image](https://user-images.githubusercontent.com/17463073/79257564-6b8adc00-7e4f-11ea-9164-b03b69fe0139.png)

**Comment by WilliamAntonRohm** [comment]
@rajachowdhury84 -- thank you for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
