### ISSUE TITLE
I tried the steps mentioned for oAuth sample code and on click of Authorize , it redirects to oauth/requesttoken, which is not available and gives 404

### ISSUE THREAD

**Issue by nikheelneelay** [MicrosoftDocs/azure-devops-docs#7939]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.
https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by nikheelneelay** [comment]
Link to sample code repo (which is forked) - https://github.com/nikheelneelay/azure-devops-auth-samples/tree/master/OAuthWebSample

**Comment by nikheelneelay** [comment]
Also, is there a sample repo for .Net Core with latest code?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by nikheelneelay** [comment]
Hi, @WilliamAntonRohm , i have fixed this issue in the sample code and created a pull request for it.
https://github.com/microsoft/azure-devops-auth-samples/pull/53

**Comment by WilliamAntonRohm** [comment]
@nikheelneelay -- Nikheel, thank you for creating that pull request.

@chcomley -- Chrystal, please look into this issue.
