### ISSUE TITLE
Disabling concurrent scheduled runs

### ISSUE THREAD

**Issue by sblack4** [MicrosoftDocs/azure-devops-docs#7945]
This may be a limitation of the product and not this documentation but I was wondering if there is a feature that would stop concurrent builds, like setting `trigger.batch: true` for the pipeline triggers (see [these docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#push-trigger).

To give you more information; I have a pipeline scheduled to run every fifteen minutes but which occasionally takes longer than fifteen minutes. If the previous pipeline is still running I'd like the next one to wait so they're not running at the same time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@sblack4 -- Steven, thank you for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

Also, thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
