### ISSUE TITLE
Try to import from GIT-  not the other way around

### ISSUE THREAD

**Issue by gullahoo** [MicrosoftDocs/azure-devops-docs#7950]
[Enter feedback here]    As a student user of your system I was symply trying to push some code to the TFS site, from a git repo-     What I am having difficulty with, is since I have a temporary account, the following command does not seem to want complete the connection: 

powershell 1.3 windows-ssh-tools 2016.05.13 beta iam service-accounts keys list --iam-account svc-2-429@mineral-minutia-820.iam.gserviceaccount.com --project mineral-minutia-820 --format="json"

Can you please redirect me, or simply fill me in on some of the missing details here??    I'm a bit unsure of even when my account expires (here very shortly) whehther or not I will still have student access rights? ? ?

Thanks very much, and have a nice 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61747dfd-9028-e756-145e-6a94370294b2
* Version Independent ID: 3bb5d8e0-1960-d744-743d-25a1399a4477
* Content: [Understand source control - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/source-control?view=azure-devops)
* Content Source: [docs/user-guide/source-control.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/source-control.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
