### ISSUE TITLE
Can we add some file(s) to the exisitng build artifact so that same artifact can be used again and again. 

### ISSUE THREAD

**Issue by pralaymohanty** [MicrosoftDocs/azure-devops-docs#7959]
I have a build pipeline and a release pipeline too.
Artifact in build pipeline is published with name "ArtifactA" t be used in the release pipeline (Stage 1).
Then in Stage 1 of release pipeline we make some more files to be used in Stage 2. If i could update the same artifact "ArtifactA" with the changes then i dnt have to download the changed files as a separate artifact (say "ArtifactB") all together.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
