### ISSUE TITLE
publish new branch

### ISSUE THREAD

**Issue by garylogin** [MicrosoftDocs/azure-devops-docs#7960]
Hi 
1) I want to give a user access to "publish new branch" in the code as a wiki.
What security setting is this controlled by?
2) when using code wikis the 3 dots only gives you 2 options, rename and unpublish....no security. you have to go back to project wiki for that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c86f5178-e331-f45e-b60a-f0f3955f7a08
* Version Independent ID: 8a0882a7-8f48-32bb-c741-12976b428c38
* Content: [Manage permissions for READMEs and wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/manage-readme-wiki-permissions?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/manage-readme-wiki-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/manage-readme-wiki-permissions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

For your second issue, please [submit it]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
