### ISSUE TITLE
VS403169: Maximum number of teams was exceeded

### ISSUE THREAD

**Issue by lizhaoting** [MicrosoftDocs/azure-devops-docs#7975]
I want to know how to resolve this

add 12 teams

VS403169: Maximum number of teams was exceeded

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2b7d4c0a-f79f-87f2-4835-6bd8074d5340
* Version Independent ID: d8927dff-9266-d2a4-2794-847b31f5c5f1
* Content: [Plans - Azure DevOps](https://docs.microsoft.com/zh-cn/azure/devops/integrate/previous-apis/work/plans?view=azure-devops)
* Content Source: [docs/integrate/previous-apis/work/plans.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/previous-apis/work/plans.md)
* Product: **devops**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by WilliamAntonRohm** [comment]
@lizhaoting -- Eric, it looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:​ 

- If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 
- If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 
- If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 You might also look here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
