### ISSUE TITLE
How can i run template jobs in parallel

### ISSUE THREAD

**Issue by allanmoller** [MicrosoftDocs/azure-devops-docs#7979]
Hey running a couple of template jobs, but am unable to get them to run in parallel, tried using "strategy" with no luck! the yaml template has an object parameter and an each "${{ each projectName in parameters.projects }}" this works fine but only in sequence!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&source=docs#parameter-data-types)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
