### ISSUE TITLE
Question: We See Expired PATs from the day before that are named with  GUID

### ISSUE THREAD

**Issue by chassq** [MicrosoftDocs/azure-devops-docs#7987]
We See Expired PATs from the day before that are named with  GUID. We just wanted to know what they were being generated for. See screen shot attached. We are not creating them so I assume they are system generated?
<img width="950" alt="Annotation 2020-04-18 053427" src="https://user-images.githubusercontent.com/4785384/79634100-78048280-8136-11ea-941f-6c46c64ae507.png">

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by chassq** [comment]
Thanks! @WilliamAntonRohm
