### ISSUE TITLE
for single solution have multiple different project types build output and publish output needed in single directory

### ISSUE THREAD

**Issue by himanshukgit** [MicrosoftDocs/azure-devops-docs#7991]
basically output from build and publish folder is needed at centralise location which is not possible when in single solution there are multiple projects and some of them belong to type 1.core 2. standard 3.framework so in this case non ci build the developer needed say build (service).dll or .exe from build output in publish folder, how to do it because 

we define non ci build based on template for repo and if repo is type core then we created different template similarly for standard and framework type projects we did seperate template, how to create universal template while creating new repos(saved on bitbucket or github) so that above condition resolves issue....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
