### ISSUE TITLE
the "Register-PSRepository" command with credentials wont work

### ISSUE THREAD

**Issue by LeonB87** [MicrosoftDocs/azure-devops-docs#7999]
when I try to register the PSRepository, I get the error "ErrorCode: integrated_windows_auth_not_supported_managed_user" and get presented with a url to do a sign-in.

"To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ######### to authenticate."

After that, the Repository is added and I can find and install my module.
Using Powershell Core 7 and module PowerShellGet 2.2.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b3cd51-b365-433b-9149-697582d64e88
* Version Independent ID: 1cb1f4a3-5928-223d-592f-f3462fef4e4c
* Content: [Use Azure Artifacts as a private PowerShell repository - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/private-powershell-library?view=azure-devops#feedback)
* Content Source: [docs/artifacts/tutorials/private-powershell-library.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/tutorials/private-powershell-library.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options you might consider: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by qcc-na** [comment]
@WilliamAntonRohm So is there a way to do this without being prompted?
