### ISSUE TITLE
Three field association

### ISSUE THREAD

**Issue by EstelleGu** [MicrosoftDocs/azure-devops-docs#8017]
Hello! I have some problems with using the WHEN tags.
How to make the third field mandatory when two fields satisfy the condition at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0897217b-652f-b83e-f6e4-bb5b3a2009f3
* Version Independent ID: e18350ad-2a42-702e-96ef-ef716b226193
* Content: [Assign conditional-based values and rules - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/assign-conditional-based-values-and-rules?view=azure-devops-2019#related-articles)
* Content Source: [docs/reference/xml/assign-conditional-based-values-and-rules.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/assign-conditional-based-values-and-rules.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@EstelleGu -- thank you for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
