### ISSUE TITLE
403 error and windows containers

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#8024]
Web App for Windows containers is currently in preview. Can I deploy a windows container using this task?
I tried but I hit this error:

&gt; ##[error]Error: Failed to fetch App Service 'foo-dev' details. Error: The client '9e9c6710-ca7d-4bde-b862-ac4411e17747' with object id '9e9c6710-ca7d-4bde-b862-ac4411e17747' does not have authorization to perform action 'Microsoft.Web/sites/read' over scope '/subscriptions/42139b23-d741-4572-8403-afa7316ce55f/resourceGroups/Development/providers/Microsoft.Web/sites/foo-dev' or the scope is invalid. If access was recently granted, please refresh your credentials. (CODE: 403)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4756ed74-d7d5-d4db-6e72-71f2910f7e1f
* Version Independent ID: 2413f407-8624-7843-a910-c610bd317319
* Content: [Azure Web App for Container task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-containers?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-rm-web-app-containers.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
