### ISSUE TITLE
"modifyOutputPath" does not work if sln file is used in "projects" arguement for publish command

### ISSUE THREAD

**Issue by nidhunge** [MicrosoftDocs/azure-devops-docs#8040]
For the troubleshooting step regarding "File structure for output files is different from previous builds", "modifyOutputPath" does not produce intended result if sln file is used in "projects" argument for publish command. Is this intended? If it is, can you mention it somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

cc @pulkitaggarwl for awareness
