### ISSUE TITLE
Azure SQL Virtual Machine options

### ISSUE THREAD

**Issue by mananshah19** [MicrosoftDocs/azure-devops-docs#8048]
Can i run this pipeline task with Azure SQL Virtual machine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f07c04-6b05-0de0-9b74-e032226528a4
* Version Independent ID: f0363446-1415-4e48-4c40-9b56906654f2
* Content: [Azure SQL Database Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/sql-azure-dacpac-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
