### ISSUE TITLE
Extension not found

### ISSUE THREAD

**Issue by pelizza** [MicrosoftDocs/azure-devops-docs#8061]
I'm trying to use this guide to get data from the Marketplace. However, the mentioned PowerBI plugin apparently doesn't exist.

I've set up my PowerBI account following the guide, clicked "Services > Get", tried to find the plugin, but there are no results related to its name.

Could you please check why is this happening?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4baac6c-eaa0-6e71-75fd-697a665b1b2c
* Version Independent ID: 057516df-2053-ca80-2d57-5ee2af974273
* Content: [Extension Statistics Power BI Content pack - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/extension-statistics-powerbi-contentpack?view=azure-devops)
* Content Source: [docs/extend/extension-statistics-powerbi-contentpack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/extension-statistics-powerbi-contentpack.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by pelizza** [comment]
Hi William,

I think this answer is not appropriate, I'm sorry if I wasn't clear enough.

What I meant to say if that the extension referred in the documentation page (Visual Studio Marketplace Extension Statistics) doesn't exist, so this page is invalid. 

I appreciate if you could review this request.

Thank you.
