### ISSUE TITLE
Where can runtime expressions be used?

### ISSUE THREAD

**Issue by Thilas** [MicrosoftDocs/azure-devops-docs#8062]
> Compile-time expressions can be used anywhere; runtime expressions are more limited.

Could you please clarify where runtime expressions can be used? From what I understand, there are `conditions` and `variables` at least.

According to [one of those samples](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group), it seems that it can also be used in `script`.

Where else?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@Thilas -- Thomas, thank you for your question. Here are a couple of options you might consider: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@juliakm -- Julia, please look into this issue.

**Comment by cb55555** [comment]
@Thilas I found out the hard way through lots of trial and error that runtime expressions can only be used in variable assignments. For example:

variables:
- var1: fred
- var2: $[ variables.var1 ] #assigns whatever is assigned to var1

Note: Runtime expressions work only with variables and not parameters.

parameters:
- name: parm1
  displayName: Parameter 1
  type: string
  default: "fred"

variables:
- var1: $[ parameters.parm1 ] #Unrecognized value: 'parameters'

This is because parameters exist only during template compilation and don't exist at runtime.

**Comment by Thilas** [comment]
@juliakm, any news about this?

**Comment by vtbassmatt** [comment]
Runtime expressions were intended as a way to compute the contents of variables and state (so `condition`). We later added support in `strategy: { matrix: ... }` expressions as well (which was upleveling from the variable-assignment statements inside `matrix`).

Due to quirks of implementation, there are possibly a few other places they happen to work. But I couldn't name them (and I've PM'd the Pipelines Platform team for over 3 years) and wouldn't recommend them.

**Comment by juliakm** [comment]
We had updated this one earlier but perhaps it is tied to a different issue. I'm adding a note that runtime expressions were intended as a way to compute the contents of variables and state.

**Comment by fluffy-cakes** [comment]
> @Thilas I found out the hard way through lots of trial and error that runtime expressions can only be used in variable assignments. For example:
> 
> variables:
> 
> * var1: fred
> * var2: $[ variables.var1 ] #assigns whatever is assigned to var1
> 
> Note: Runtime expressions work only with variables and not parameters.
> 
> parameters:
> 
> * name: parm1
>   displayName: Parameter 1
>   type: string
>   default: "fred"
> 
> variables:
> 
> * var1: $[ parameters.parm1 ] #Unrecognized value: 'parameters'
> 
> This is because parameters exist only during template compilation and don't exist at runtime.

You have explained so easily what I could not understand from M$ documentation
