### ISSUE TITLE
Agent pool not found: 'Self-Hosted' while setting up build agent for first time using PAT

### ISSUE THREAD

**Issue by shivabommakanti03** [MicrosoftDocs/azure-devops-docs#8065]
I am setting up Self-Hosted agent for my Azure Devops and using PAT. But, I get the following error.

Enter authentication type (press enter for PAT) > PAT
Enter personal access token > ****************************************************
Connecting to server ...

>> Register Agent:

Enter agent pool (press enter for default) > Self-Hosted
Error reported in diagnostic logs. Please examine the log for more details.
    - /home/fmlstream/myagent/_diag/Agent_20200423-152220-utc.log
Agent pool not found: 'Self-Hosted'
Failed to find pool name. Try again or ctrl-c to quit

**Comment by WilliamAntonRohm** [comment]
@shivabommakanti03 -- Shivakumar, thank you for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
