### ISSUE TITLE
Is there a way to get notified on new comments on a wiki page?

### ISSUE THREAD

**Issue by nishantsny** [MicrosoftDocs/azure-devops-docs#8071]
We would like to get notified when developers comments on wiki pages related to our team. Is there a way to get subscribed for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c85ebb83-c49f-e784-70b5-30c0ac01682b
* Version Independent ID: dc859870-0b8f-bee5-0b2f-e6b2aa3260c6
* Content: [Add comments to wiki pages - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-comments-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-comments-wiki.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/add-comments-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
