### ISSUE TITLE
If I am mentioned in the work item, I get two mails - one for mention, one as a notification

### ISSUE THREAD

**Issue by agrabhi** [MicrosoftDocs/azure-devops-docs#8075]
If for some changes in a work item, I am also mentioned in the change - I get two mail - one for notification and other for mention. I want to get only one.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3982f11f-c9aa-26fe-0812-f56b855c0c0e
* Version Independent ID: 54a34df8-7172-b2cc-9466-d527f0f324da
* Content: [Manage personal notification settings - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/manage-your-personal-notifications?view=azure-devops&tabs=preview-page#feedback)
* Content Source: [docs/notifications/manage-your-personal-notifications.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/manage-your-personal-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@agrabhi Thank you for the feedback.

Unfortunately your only option is to disable the feature and provide a [custom web hook](https://docs.microsoft.com/azure/devops/service-hooks/services/webhooks) for notifications.

Since this is product-related please consider moving the issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback, or let us know and we can start a ticket for you.  There similar issues such as [this one](https://developercommunity.visualstudio.com/content/problem/74027/duplicate-notifications-are-getting-sent.html) are routinely logged and fixed by the product team.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
