### ISSUE TITLE
It would be good to know how to automatically update all their Visual Studio to consume the feed automatically.

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/azure-devops-docs#8097]
If I have 10,000 developers, it would be good to know how to automatically update all their Visual Studio to consume the feed automatically, so it is controlled by company admins and not the developer themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@dombat  Thank you for the feedback, assigning this to the author for review.

Please refer to the [nuget CLI](https://docs.microsoft.com/nuget/consume-packages/install-use-packages-nuget-cli) for ways on automating this process.

**Comment by AdrianSanguineti** [comment]
@dombat, what you're actually after is adding a [nuget.config](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file) file at the solution level of your repository with the package sources set as desired. Then check that file into source control with everything else.

Visual Studio then will automatically use the nuget.config file that's next to the solution instead of the system wide config. The solution will have to be re-opened for Visual Studio to detect and changes to the file (something I would love the VS team to fix one day).

You can use the [dotnet cli](https://docs.microsoft.com/en-us/nuget/reference/dotnet-commands) as a quick way of creating the nuget.config

If you want to enforce the package sources to be set at a system wide a certain way, then assuming all your devs are using a SOE managed by your IT team, have the IT team replace the system wide nuget.config file with the sources that you want as part of the SOE.

**Comment by ramiMSFT** [comment]
@dombat Thank you for your feedback and thank you @AdrianSanguineti for your contribution
