### ISSUE TITLE
Provision two agents in the same machine for deployment groups to achieve parallel deployment

### ISSUE THREAD

**Issue by narenkv** [MicrosoftDocs/azure-devops-docs#8114]
Hello ,

We wanted to know if there is a possibility to host more than one agents in the same machine for deployment groups.

I would like to deploy two web applications to an on-premise server simultaneously/parallely . Is there a possibility to install more than one agent in the same server so that we achieve parallel deployment of applications on a single physical server/vm.

In this case, web1 and web2 needs to be deployed in parallel in one VM. Currently the deployment happens one after another.

Note: When I tried to configure second agent in the same machine using the installation powershell script generated at the Deployment group, the powershell script hangs while executing at "Connecting to the server."

This is need for an on-premise deployment 

Thanks
Naren

**Comment by WilliamAntonRohm** [comment]
@narenkv -- Naren, thank you for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
