### ISSUE TITLE
Where are constraints coming from?

### ISSUE THREAD

**Issue by sevaa** [MicrosoftDocs/azure-devops-docs#812]
What's the deal with constraints? Are they in the manifest, by any chance? Can't find any mentions elsewhere. The file at https://github.com/Microsoft/tfs-cli/blob/master/app/exec/extension/_lib/targets/Microsoft.VisualStudio.Services/vso-manifest-builder.ts suggests that "constraints" is a manifest property, but the manifest schema at https://docs.microsoft.com/en-us/vsts/extend/develop/manifest?view=vsts doesn't mention them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e00e9825-a2ef-90e5-7212-88136972cd6c
* Version Independent ID: 92d7740a-d7e1-e3ea-e96f-f11734bc35be
* Content: [VSS/References/SDK.Interfaces Contribution API](https://docs.microsoft.com/en-us/vsts/extend/reference/client/api/vss/references/sdk_interfaces/contribution?view=vsts)
* Content Source: [docs/extend/reference/client/api/VSS/References/SDK_Interfaces/Contribution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/reference/client/api/VSS/References/SDK_Interfaces/Contribution.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
hey @sevaa , thanks again for your question. I forwarded it to the product team and hopefully we can get you an answer and also I can document this better for future users.

**Comment by sevaa** [comment]
Wrote a blog post with more info: http://rathertech.blogspot.com/2018/05/constrained-and-dignified.html

**Comment by elbatk** [comment]
Ah, I see you've been investigating! We have to consider about how/when/if we want to expose information regarding constraints, as for now there isn't anything we are ready to publicly document or commit to as constraints are mostly used internally and can change at any point. Going to go ahead and close this issue for now.

**Comment by sevaa** [comment]
You guys have _committed_ to a terribly small subset of the entire API surface :) When it comes to TFS extension writing, it's all undocumented stuff, all the time. Do you realize that the sole parameter of VSS.register() isn't documented? Strictly speaking, you can't put together **_any_** extensions without wading into undocumented territory.

**Comment by elbatk** [comment]
In an effort to make the docs more complete, where are you looking for documentation? We have the VSS.register() method here: https://docs.microsoft.com/en-us/vsts/extend/reference/client/core-sdk?view=vsts#method_register with an example here: https://docs.microsoft.com/en-us/vsts/extend/develop/add-action?view=vsts

Some task.json info can be found here: https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema?view=vsts with a link to the reference for build/release tasks here (linked from that page): https://github.com/Microsoft/vsts-task-lib

But I'd like to know where you were looking/what you were able to find or not find so I can try to get together some info to make the docs more complete and accessible, thanks in advance!

**Comment by pabrams** [comment]
I too would like a complete reference, not the incomplete documentation you currently have.

**Comment by alessandrodalmas** [comment]
same here, trying to develop an extension and jumping page to page for get more informations

**Comment by elbatk** [comment]
I'd like to take some specific items to the product team's attention here. We are currently updating the task.json reference and the "Add a build task" guide so that it includes more information. Also the SDK documentation GitHub has a [schema for the task.json](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json). Is that sufficient in the task.json area?

It looks like the ask is for complete reference, does that mean more explanations of the fields in the [Core Client SDK](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/core-sdk?view=vsts)? Are there other areas you're looking for?

I want to make sure when I collaborate with the product team that we get exactly what what be useful for developers like you all who are using our stuff :)

**Comment by sevaa** [comment]
First priority - core SDK docs, definitely. For task.json, document the fields please. Example: 

```
"demands": {
      "type": "array",
      "description": "Allows you to define a list of demands that a build agent requires to run this build task.",
      "items": {
        "type": "string"
      }
    },
```

How is that useful? What's a demand? Towards the end, most schema fields don't have a description at all. E. g. options, dataSourceBindings.

And, certainly, the schema on Github doesn't constitute a commitment to an API. That's also a concern.

**Comment by pabrams** [comment]
@elbatk Respectfully, you shouldn't need to ask us to explain how your docs are incomplete.  Your developers should be able to see it.  Build tasks and task.json are just one small part of this. ALL extension-related documentation needs to be fleshed out and vetted internally.

**Comment by alessandrodalmas** [comment]
Personaly, I have found very difficult to move around the documentation and try to create my task in typescript (not powershell) together with a tab in the summary pipeline results and a separated tab.
My problem was the extension task (following the tutorial) needed to be compile with "module":"commonjs", while the tabs in "amd".
I am a newbie and this was already a big problem for me.
Now there are also new libraries that replaced the old ones. azure-pipelines-task-lib was not a problem to replace. But I can not do the same with azure-devops-extension-sdk and I can not find the new references or his github project (404 not found, still private or still to be finished or not to become public?).
Is it also possible to run an offline testing area? I think I have did almost 200 vsix versions and updates to complete my first extension.
I am going to publish on my github area the project of my extension. You will see that it is my first time using azure devops from a lot of mistakes probably.

**Comment by pabrams** [comment]
Here's some recent activity.  Please fix your documentation. Thank you.

**Comment by pureliumy** [comment]
Please fix your documentation. Thank you.

**Comment by chcomley** [comment]
Assigning this to @apawast for article fixes please. Thank you.

**Comment by chcomley** [comment]
Adding @jtpetty for further guidance/assistance, thank you!

**Comment by chcomley** [comment]
Hi @sevaa , I have an answer for your original question for this GitHub Issue. Per our source code, constraints are an internal-only mechanism for filtering contributions. There's no public use for them in extensions. I've submitted a PR in that repo for the file you mentioned, which suggests that "constraints" is a manifest property, for removal of that entry. 

As for the other feedback contained in this issue, I invite the participants to create a new issue for which ever article you come across that needs work. This is the best way to get each specific piece of feedback under the noses of our PMs. I also invite you, @pureliumy and @pabrams, to consider [becoming contributors to our docs](https://docs.microsoft.com/en-us/contribute/)! Since this docset is in need of a refresh and we have limited resources allocated to it, it'd be great to get your feedback for all or whichever articles are lacking. As for this issue, I'll be closing it. 
@sevaa, Please @mention me if you need any more clarity or have further feedback on this particular article.

**Comment by sevaa** [comment]
Took you guys 2.5 years to react. At this point, the original issue is irrelevant. Also, I did a halfway decent job of documenting those myself: https://rathertech.blogspot.com/2018/05/constrained-and-dignified.html

>I invite the participants to create a new issue for which ever article you come across that needs work

I've tried that. See https://github.com/MicrosoftDocs/azure-devops-docs/issues/769 

Also, see this: https://rathertech.blogspot.com/2019/03/tfs-and-commitment-issues.html

**Comment by pabrams** [comment]
I have to admit, though, the docs have been improving over the past couple of years.
