### ISSUE TITLE
How can I grant feed permission to a service principal?

### ISSUE THREAD

**Issue by awarberg** [MicrosoftDocs/azure-devops-docs#8141]
We are using Universal Packages and are trying to download artifacts on a Universal Package feed. In the script, we are using the Azure CLI to login as a Service Principal. How do we grant the Service Principal permission to the feed?

Script snippets:
`az login --service-principal --username <username> --password <password> --tenant <tenant>`
`az artifacts universal download ...` # Permission denied error here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e77774e-012a-45cc-d566-7170d86003cd
* Version Independent ID: 778dafea-bf98-3292-f451-d82ce8db5bbc
* Content: [Secure and share packages using feed permissions - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops)
* Content Source: [docs/artifacts/feeds/feed-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/feed-permissions.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by awarberg** [comment]
Hi again. I am still looking for a solution for this. Is it even possible to grant a Service Principal access to a Universal feed? If not, we need to switch to a different package system.

**Comment by kvamsdal** [comment]
Hi. I am interested in having an answer to this as well

**Comment by javierlga** [comment]
Is there any update on this?

**Comment by shaunryan** [comment]
I need to do this too.

**Comment by ramiMSFT** [comment]
@awarberg my apologies for the delayed response and thank you for reaching out. Please refer to the following articles:
[Service connection with SP](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-with-an-existing-service-principal), [ARM SPA](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-azure-resource-manager), and [troubleshooting](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops).
Please don't hesitate to take advantage of our [Azure DevOps developer community](https://developercommunity.visualstudio.com/search?space=21) resources to post questions or request features.

**Comment by javierlga** [comment]
> @awarberg my apologies for the delayed response and thank you for reaching out. Please refer to the following articles:
> 
> [Service connection with SP](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#create-an-azure-resource-manager-service-connection-with-an-existing-service-principal), [ARM SPA](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-azure-resource-manager), and [troubleshooting](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-rm-endpoint?view=azure-devops).
> 
> Please don't hesitate to take advantage of our [Azure DevOps developer community](https://developercommunity.visualstudio.com/search?space=21) resources to post questions or request features.

Why are you closing this? The link that you shared allows access from azure pipelines to create azure resources using a service connection. 

The problem here is that there is no way to use a Service Principal to authenticate against Azure DevOps and interact with other products such as artifacts e.g.

**Comment by ramiMSFT** [comment]
@javierlga Not sure what do you mean by "there is no way to use a Service Principal", did you check the links that I posted? 
The first link shows you the exact steps to connect your project to an existing service principal.

**Comment by javierlga** [comment]
> @javierlga Not sure what do you mean by "there is no way to use a Service Principal", did you check the links that I posted? 
> 
> The first link shows you the exact steps to connect your project with an existing service principal. 


That's for creating a service connection that will be used to create resources in azure.

What we are trying to do here is create a service principal, log in to azure using azure cli e.g. using the SP previously created and have access to Azure DevOps artifacts e.g.

**Comment by ramiMSFT** [comment]
@javierlga Service principals are created through Azure portals and not Azure DevOps. Follow the steps in this article [Create a service principal](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal) to create a service principal, then follow the article that I referenced [Service connection with SP](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops) to connect your project with the service principal you created

**Comment by javierlga** [comment]
> @javierlga Service principals are created through Azure portals and not Azure DevOps. Follow the steps in this article [Create a service principal](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal) to create a service principal, then follow the article that I referenced [Service connection with SP](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops) to connect your project with the service principal you created

I know how service principals are created, the problem here is how can we use a service principal to interact with Azure DevOps services e.g. Artifacts, is that clear?

**Comment by troll-os** [comment]
I have the exact same problem.

I have two projects with python dependencies and in my Bitbucket pipeline I'd like to authenticate with my SP to make a pip install to run my tests. 

So far I haven't found anything concrete except using a PAT which is absolutely not viable on a long run as it's tied to my account. 

Passing the auth args to the url in pipeline like for example : `pip install -extra-index-url=https://myspname:myspsecret@my.python.repo/etc...` would be a great achievement

**Comment by HighWatersDev** [comment]
I'm having the same issue. I'm running self-hosted agent using service principal and getting 403 errors trying to pull packages from Artifacts. It'd be nice to have a solution for this.

**Comment by dxynnez** [comment]
Same issue here... I really don't want to use my PAT for such case. Is there any workaround?

**Comment by javierlga** [comment]
Still no update for this issue, seems like they don't even understand the problem

**Comment by ramiMSFT** [comment]
The links that I provided above contain the answer but let me break down the steps:

1. [Create a service principal](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#register-an-application-with-azure-ad-and-create-a-service-principal). This is done through Azure Portal. If you already have a service principal, go to the next step
2. [Create a new application secret](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-2-create-a-new-application-secret)
3. [Add role assignment](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#configure-access-policies-on-resources)
4. [Create a service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#create-a-service-connection). This step is done in Azure DevOps. Select `Project settings` > ` Service connections` > `New Service Connection` > `Azure Resource Manager` > `Service principal (manual)` > Fill out the form then select **Verify & Save**. Your service principal should be connected to Azure DevOps now.

> ![image](https://user-images.githubusercontent.com/60942540/129283150-519089c1-9f19-4d19-9f3c-bf21f27590a0.png)
>
> ![image](https://user-images.githubusercontent.com/60942540/129283187-6ba5c001-acf0-4b06-ba99-27f801f61e11.png)
> 
> ![image](https://user-images.githubusercontent.com/60942540/129283278-1b3e3c4d-0ddd-44f8-b094-635332e1a590.png)

**Comment by troll-os** [comment]
You still don't get it 

We want to able to identify through a SP on DevOps services such as Artifact Feeds. Your solution just allows DevOps to interact with resources on Azure.

As of now the only way to auth yourself on a third party CI/CD platform, in my case Bitbucket Pipelines, would be to create a PAT which is absolutely not a good idea in an automated environment.

That's really a pain in the a** because I'd rather have the maximum possible of tools at one place than multiply them and right now the only other viable solution is JFrog, and of course if we start using another service there will be no turning back because it would cost too much.

I tend to prefer Azure over the other CSP but I feel like when a resource lacks something you can wait forever to be listened to... I've asked a simple question about ruby 2.7 availability on web apps and no one is able to give answer, come on...

**Comment by javierlga** [comment]
Can we reopen this?

**Comment by ramiMSFT** [comment]
@omokoh Can you take a look at this? I posted about this in Teams a while ago

**Comment by ramiMSFT** [comment]
The product team is looking into this issue. Are you running the scripts in a Pipeline or just the CLI?

**Comment by troll-os** [comment]
I'm personnally running scripts to fetch or upload from third parties pipelines, being Bitbucket in my case, but if we can use SP to identify on Feeds then it wouldn't matter, it would work everywhere.

**Comment by GiorgosPa** [comment]
I am having the same issue. Even though I made it working with a pat linked to my account, I would like to use a Service Principal. The documentation for this task is [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops#manually-configure-authentication) and only refers to PATs.

**Comment by KKnapik** [comment]
You can use the predefined variable $(System.AccessToken) so you will be authorized to Artifacts as **project collection build service**

Below task works for me. 

- task: AzureCLI@2
  displayName: 'name'
  inputs:
    scriptType: bash
    scriptLocation: inlineScript
    azureSubscription: ${{ parameters.serviceConnection }}
    inlineScript: |
      az artifacts universal download --organization $AZURE_DEVOPS_URL \
      --feed $FEED --name $ARTIFACT_NAME \
      --version $PACKAGE_VERSION --path .
env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)


https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops

**Comment by iswariyam** [comment]
Is there an update @ramiMSFT ? I am also looking for a solution which allows a "service principal" to authenticate itself and download packages from an azure devops feed. Currently, I am using my PAT and I'd like to move away from using this.

**Comment by RyannosaurusRex** [comment]
I need this as well. Here's the scenario:

We're looking to hook up an Octopus instance to pull NuGet packages from the Azure DevOps Artifacts feed for deployment elsewhere. I don't want a Personal Access Token governing this as myself or anyone in Ops in case we leave or something changes. It needs to be a service account.

**Comment by ramiMSFT** [comment]
> The product team is looking into this issue. Are you running the scripts in a Pipeline or just the CLI?

@omokoh Any updates about this?

**Comment by armstrong-pv** [comment]
I'd like this for publishing artifacts in GitHub Actions to an Azure DevOps universal feed. CI in GithubActions, CD in Azure DevOps.

**Comment by Peder2911** [comment]
We are also very interested in being able to authenticate to an Artifacts feed using Service Principal credentials, either via `client_id` / `client_secret` or using a bearer token.

Should absolutely be possible!

**Comment by Peder2911** [comment]
> I am having the same issue. Even though I made it working with a pat linked to my account, I would like to use a Service Principal. The documentation for this task is [here](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops#manually-configure-authentication) and only refers to PATs. For the cli there is no issue as the artifacts_keyring package is creating a pat on demand using the device login method. My main issue is with pipelines in github actions where user interaction is not an option.

Using this workaround as well, and it's far from ideal.

**Comment by jorfde** [comment]
It looks like this is not possible and also not artifacts-specific. You can use a service principal through service connections to connect to your azure resources from within an azure devops pipeline, but you can't authenticate against azure devops services with a service principal.

**Comment by ramiMSFT** [comment]
Thank you Jorge! Closing this now.

**Comment by javierlga** [comment]
Why is this being closed? Sorry, but I'm not following, basically @jorfde just confirmed what everybody knew already but it won't be implemented, I'm speechless.

**Comment by troll-os** [comment]
This is amazing at several levels

First for the fact that being tagged or the topic being upped is left unanswered for months without any clear calendar

Second because your misability to read is more important than having the peace of mind to check with the concerned teams to see if this was actually implemented.

Thank you guys, don't change anything, sincerely 🙏

**Comment by twferrell** [comment]
@troll-os, we apparently have the wrong guys tagged on here.

**Comment by shaunryan** [comment]
I'm gonna go out on a limb. This isn't and won't be possible since it undermines MS SaaS commercial model? It's priced by user access and therefore adding in service principals would lead to it being abused. However, I don't see why depending on some usage level there couldn't be an introduction of say 1 service principal limit for base entry and additional service principals based on the number of licenses purchased? The only close to workable solution is to use it with github, create a user token and use that... since at least in github you can have SSO linked tokens. I know some orgs that have just flatly said that it's instant dismissal to use tokens since it just opens up a massive security concern. Which at that point... take a look at the market, maybe Azure Dev Ops isn't the right tool for the job.

**Comment by MigTremblay** [comment]
Nothing worked for me. Answer provided by microsoft seems to be for the other way around when you start from a DevOps pipeline and need to go outside to interact with azure resources. I need to authenticate FROM GitHub actions INTO Azure artifacts using an azure service principal so I can restore nugets while building the project IN GitHub. Seems very basic but so far looks like Azure Artifacts only work with devops??

**Comment by WilliamAntonRohm** [comment]
@All, thank you for your follow-up.  I don't see that these resources have been mentioned yet
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by Peder2911** [comment]
> @ALL, thank you for your follow-up. I don't see that these resources have been mentioned yet
> 
>     * [Azure DevOps Services](https://azure.microsoft.com/support/devops/)
> 
>     * [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Are you suggesting that I should "just Google it"?

We are talking about a missing feature in this thread. One that is would actually make me consider not using or recommending Azdo artifacts at all.

**Comment by WilliamAntonRohm** [comment]
Please add this as a product request here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

**Comment by javierlga** [comment]
> Please add this as a product request here:
> 
> * [Developer Community](https://developercommunity.visualstudio.com/search?space=21)

This issue has reached another level of laziness, I just can't find an appropriate way to describe how incompetent all of the Microsoft team members or collaborators are who have participated in the issue. 

The issue was opened on April 29th, 2020, then @ramiMSFT commented almost one year later, we spent around 7 months with a back-and-forth discussion with him because he wasn't capable of understanding the real issue, just proposing random ideas and links to documentation.  

When @jorfde finally looked into the problem, after waiting 2.5 years, all he said was that it wasn't possible, which everyone already knew, and just without further action, the problem was closed.

Finally, @WilliamAntonRohm joins the conversation and suggests using Azure DevOps Support and/or StackOverflow, my question is: how are they going to be able to help us if this is impossible to do in any way?

Just to wrap up/sum up, we need to create a new issue in the developer community, so how long would it take to get implemented? It's sheer madness, to be honest.

Thank you all, another great history to share amongst the dev community.

**Comment by jorfde** [comment]
Hi folks, 

As a quick update, service principal support for Azure DevOps has been in the works for some time, and the feature is coming soon! Looping in @angelwong for any follow-up questions.

**Comment by jiili** [comment]
Any updates on the matter?

**Comment by avekhteva** [comment]
Hi there!
Any updates?

**Comment by FlorentATo** [comment]
Hi, I've been experimenting with using Service Principals to fetch artifact on Azure Devops.

Use case: I use a Service Principal instead of Azure Devops PAT to allow my Github Action to fetch universal artifact ([since Github Packages doesn't support it yet...](https://github.com/github/roadmap/issues/123)).

Procedure:
1. Authenticate on the Azure tenant (directory) linked to your Azure Devops organization.
   ```
   az login --tenant <az-tenant-uuid>
   ```
2. Create a Service Principal, scoped on any Subscription, with a role "Reader":
   ```
   az ad sp create-for-rbac \
      --sdk-auth \
     --scope /<your-subscription> \
     --role "Reader" \
     --years 10 \
     --display-name "sp-github-ado-artifact-myghproject" > sp-github-ado-artifact-myghproject.json
   ```
3. Initiate some env. variables:
   ```
   SP_CLIENTID=$(jq -r '.clientId' < sp-github-ado-artifact-myghproject.json)
   SP_CLIENTSECRET=$(jq -r '.clientSecret' < sp-github-ado-artifact-myghproject.json)
   SP_TENANT=$(jq -r '.tenantId' < sp-github-ado-artifact-myghproject.json)
   ```
4. Connect to your Azure Devops organization
5. Go to your organization settings, then "Users", then add your Service Principal (without adding it to any project):
<img width="501" alt="Screen Shot 2023-05-15 at 20 01 36" src="https://github.com/MicrosoftDocs/azure-devops-docs/assets/1591516/895c2a06-b937-46a2-993b-28dd204fb0f0">

6. Then go to "Permissions", create a new group; let's call it "Artifact Service Principals" (Optional: I didn't want to add individual SPs to my feed).
7. In the "Permissions" tab, set all value to "Deny" (principle of least privilege).
8. In the "Members" tab, add your Service Principal
9. Go to the project that has your feed configured (or any project if you use a feed scoped to the entire organization).
10. On the top right corner, hit the gear wheel to access "Feed Settings".
11. In the "Permissions" tab, hit "Add Users/Groups" on the right
12. Add the group"`[<organization-name>]\Artifact Service Principals`" as "`Reader`".
<img width="498" alt="Screen Shot 2023-05-15 at 20 12 43" src="https://github.com/MicrosoftDocs/azure-devops-docs/assets/1591516/593e64e5-9f42-4795-8f15-ed0402b8aead">

13. Confirm the SP is able to connect to your feed:
   ```
    az login --service-principal -u ${SP_CLIENTID} -p ${SP_CLIENTSECRET} --tenant ${SP_TENANT}
   ```
   then run
   ```
   az artifacts universal download \
     --organization "https://dev.azure.com/<your-organization>/" \
     --feed "<feed-name>" \
     --name "<archive-name>" \
     --version "<version>" \
     --path .
   ```


Hope it helps :)

**Comment by FlorentATo** [comment]
Perhaps it's worth opening a separe issue at this point @John-Donalson. The initial issue has been addressed. Just my 2 cents :)

**Comment by John-Donalson** [comment]
> Perhaps it's worth opening a separe issue at this point @John-Donalson. The initial issue has been addressed. Just my 2 cents :)

Universal artifacts will not work on your last step, my error results from following your steps to the tee. Permissions to the group, the setup of the SP, your exact commands. json file.

**Comment by DeepakArora76** [comment]
For all Python users, please use "PipAuthenticate@1 - Python pip authenticate v1 task" for authentication. This worked for me :)

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/pip-authenticate-v1?view=azure-pipelines

https://developercommunity.visualstudio.com/t/azure-artifacts-keyring-without-interaction-with-u/905664
