### ISSUE TITLE
Where is the 17.153.29605.3 version? 

### ISSUE THREAD

**Issue by StavroulaSsi** [MicrosoftDocs/azure-devops-docs#8144]
This is maybe not the right place to ask, but I will try anyway. I wanted to run the migration tool. The currently available migration tool is for version 17.153.29605.3. We are actually still in version 17.153.29522.3. I am not able to run the migrator, probably because this version is wrong or does not exist yet. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486447a6-a627-df82-4706-2318135540cc
* Version Independent ID: 7d6953c7-9ee6-50d6-9fce-238a4539ecc9
* Content: [Get support and provide feedback - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/provide-feedback?view=azure-devops)
* Content Source: [docs/user-guide/provide-feedback.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/provide-feedback.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@StavroulaSsi Thank you for the feedback.

Since this is a product-related, please consider moving the issue [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21), or let us know and we can move it for you.

Assigning this to the author of [migration overview](https://docs.microsoft.com/azure/devops/migrate/migration-overview) for awareness.

**Comment by KathrynEE** [comment]
Closing as addressed.
