### ISSUE TITLE
is there any way we can setup round robin fashion to choose agent pool instances ?

### ISSUE THREAD

**Issue by tsaibabu4u** [MicrosoftDocs/azure-devops-docs#8148]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@tsaibabu4u Thank you for the feedback.

Since this is a product-related issue, please move this issue to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) or let us know and we can start an issue for you.

There users can vote and provide input until the product team offers feedback on the overall feasibility.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
