### ISSUE TITLE
Question about the different possible states of a bug

### ISSUE THREAD

**Issue by Dede24** [MicrosoftDocs/azure-devops-docs#8162]
With my team, we use the reporting bug. When the tester report a bug, the state of the bug is "New" and when the developper resolved the bug, he pass in "Resolved" but the bug is not delivered. How to add on the state of the bug a "Delivered" state to inform the tester that the bug is delivered on the update of the software?
"New" is to inform the developper of the bug
"Active" is when the developper correct the bug
"Resolved" the correction is done
"Closed" when the bug is delivered and tested
Thanks for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @ravishan-msft for awareness
