### ISSUE TITLE
Do environment deployments respect the ##vso[build.updatebuildnumber] command?

### ISSUE THREAD

**Issue by thatnerdyguy** [MicrosoftDocs/azure-devops-docs#8164]
If you use:

echo ##vso[build.updatebuildnumber]1.2.3.4

Either in the same or previous stage as a deployment job in some pipeline, it appears the environment still uses the 'original' build number of something like 20200501.1 rather than a custom one of something like 1.2.3.4 when showing the little "label" in the deployment summary list page for the environment. If you click on the label, it will take you to the pipeline, which has the correct custom build number displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

Also, you may have encountered an issue with the product itself. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
