### ISSUE TITLE
Uploading Test Steps via Excel

### ISSUE THREAD

**Issue by Gocoollnath** [MicrosoftDocs/azure-devops-docs#8167]
There is no other way to upload steps ,apart from using Grid option? For 1000's of test cases, adding test steps using grid is a tedious process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Bulk modify work items using Microsoft Excel - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@Gocoollnath - You may find a solution using the REST API for Test, https://docs.microsoft.com/en-us/rest/api/azure/devops/test/?view=azure-devops-rest-5.1. Otherwise, I suggest you Request a Feature,https://developercommunity.visualstudio.com/spaces/21/index.html, to support your needs. 

Closing this issue as it is a product issue and not a document issue.
