### ISSUE TITLE
App not running because of dependencies

### ISSUE THREAD

**Issue by Relent97** [MicrosoftDocs/azure-devops-docs#8172]
Thank you for the post, it was very well detailed and simple to follow.
However I have a problem, the app is not running.
1)  I went through the issues and set my SCM_DO_BUILD_DURING_DEPLOYMENT = false as instructed.
2) I tried installing the requirements through my requirements.txt file however a particular library PyODBC needs an ODBC driver to work. Is there a way to put an instruction in the requirements file for ODBC to also be installed? Particularly these 3 commands 
"a)apt-get update
b)apt-get install g++
c) apt-get install unixodbc-dev"
3) When trying to install them through the bash cloud shell I got an error stating below 
"E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?"
 without these installations my requirements.txt file might not run.
How can I solve this please been on it for over 3 days.
Article Url: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python-webapp?view=azure-devops

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

cc @kraigb for awareness
