### ISSUE TITLE
Do simultaneous deploys to the same environment from different pipelines block/queue?

### ISSUE THREAD

**Issue by adrian-baker** [MicrosoftDocs/azure-devops-docs#8173]
If I have an environment targeted by multiple deploy tasks simultaneously across different pipeline runs, what happens? Eg, lets say I have two branch builds running, both of which try deploying to an integration test environment. I would expect the second pipeline to block until the first pipeline completes it's deploy task before it can begin a deploy.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/environments?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Boosten** [comment]
Also see this thread: https://developercommunity.visualstudio.com/content/problem/590010/multi-stage-pipelines-allow-simultaneous-deploymen.html

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

cc @juliakm for awareness

**Comment by adrian-skybaker** [comment]
Thanks - would it not be reasonable to update the documentation to indicate that deployments to the same environment are permitted?
