### ISSUE TITLE
Are there any plans to allow other testing frameworks to be plugged into DevOps?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/azure-devops-docs#8174]
Since CodedUI is kaput

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6c92a2-2f5c-e34e-f285-3e1a2a02604b
* Version Independent ID: 6f31f4c2-94ac-20eb-da01-e1d47f041945
* Content: [Run automated tests from test plans - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/run-automated-tests-from-test-hub.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by StingyJack** [comment]
@WilliamAntonRohm - if what I am asking for is already present and possible, then this is probably a documentation issue because I cant find info about it. If its not already present this is a product roadmap or feedback item.

Have you tried to use that support bot before? Try asking it something with a simple yes or no answer like "Can I override config file settings in an app Service?"  (yes, you can).

This question would not be a good fit for Stack Overflow.
