### ISSUE TITLE
Is there anyway to set up host name like travis?

### ISSUE THREAD

**Issue by SamYuan1990** [MicrosoftDocs/azure-devops-docs#8178]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Hi, 

I want to know is there any way to set up hosts like below:
```
addons:
  ssh_known_hosts: git.example.com:1234
```
ref: https://docs.travis-ci.com/user/ssh-known-hosts/

https://docs.microsoft.com/zh-cn/azure/devops/pipelines/migrate/from-travis?view=azure-devops

**Comment by msebolt** [comment]
@SamYuan1990 Thank you for the question.

Assigning this to the author for further review to see if the documentation can be updated.

If this feature is not yet available, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback directly from the product team.

Or, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by SamYuan1990** [comment]
> @SamYuan1990 Thank you for the question.
> 
> Assigning this to the author for further review to see if the documentation can be updated.
> 
> If this feature is not yet available, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback directly from the product team.
> 
> Or, for additional support options, see:
> 
> * [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
> * [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

well, for my understanding, just wait for @juliakm 's replay if it is problem/feature right?

**Comment by msebolt** [comment]
Yes, apologies for not understanding if this is feasible or not.  

If you suspect this is not yet supported it couldn't hurt to run it by the product team sooner than later.

**Comment by juliakm** [comment]
@SamYuan1990 My understanding is that the syntax from Travis would not work. I think that you would want to use the [Install SSH Key task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops) to set up known hosts. It looks like there is an [active feature request](https://github.com/Microsoft/azure-pipelines-tasks/issues/10838) to support a known hosts file.  

I think the right place for your question is our [developer community](https://developercommunity.visualstudio.com/spaces/21/index.html) since this is more of a feature request/use case question and there are not docs to update. Please let us know though if you disagree.
