### ISSUE TITLE
Azure Devops Virtual Agent - Please enter a valid email address ("efffdc56-fd4c-aeba-6cd3-d07aaf776d51")

### ISSUE THREAD

**Issue by sblais-nb** [MicrosoftDocs/azure-devops-docs#8186]
When I'm trying to use the @regionmove flow in the Azure Devops Virtual Agent, I have the following error after entering my organization email (sblais@normandin-beaudry.ca) in the region move form.

![image](https://user-images.githubusercontent.com/22942436/80980643-e1eb8000-8df6-11ea-8386-40c96ac8705e.png)

**Comment by msebolt** [comment]
@sblais-nb  Thank you for the question.

If you can you provide a reference to the an article, I can assign this to an author for further review.

Otherwise, if this is a product-related issue, you can use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team.

Or, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.

**Comment by sblais-nb** [comment]
The article is : https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=azure-devops.

The link to the Azure Agent is : https://azuredevopsvirtualagent.azurewebsites.net/
![image](https://user-images.githubusercontent.com/22942436/81441204-5ac44200-913f-11ea-978b-2de51ccee7a4.png)

**Comment by msebolt** [comment]
@sblais-nb Thank you for the reference, assigning this to the author for review.

Please note our support is limited to the examples in the document.

For support on more user-specific scenarios, please refer to [this post](https://powerusers.microsoft.com/t5/I-Found-A-Bug/Cannot-use-quot-Created-by-quot-from-Azure-DevOps-as-a-valid/td-p/288277) or try the following:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by chcomley** [comment]
Hi @sblais-nb, Since this isn't a documentation issue, I'm closing it. But, since it's saying that your email address isn't valid, you may want to contact [Support](https://azure.microsoft.com/support/devops/). Thank you.
