### ISSUE TITLE
Customise the message?

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/azure-devops-docs#8195]
Is it possible to customise the deployment complete message - for example - to include a link to the deployed website?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
