### ISSUE TITLE
File Transform task - messed up formatting after json file transformation

### ISSUE THREAD

**Issue by Anna-3** [MicrosoftDocs/azure-devops-docs#8197]
We are using the task to transform json files during deployments, but after the transformation the new file has always messed up formatting - everything is in one line, and this makes it much more difficult to read.
Could you please do not change file formatting during transformation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 064f48ba-1c34-6422-5fe3-c3e88d2803c4
* Version Independent ID: c38f5761-4718-9aae-bc83-063257a78eb3
* Content: [File Transform task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/file-transform?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/file-transform.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/file-transform.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@Anna-3 Thank you for the feedback.

This was reported earlier [here](https://developercommunity.visualstudio.com/content/problem/527013/file-transform-json-into-single-line.html), so this might be a version issue.  Please be sure you're using the latest version to see if this resolves the issue.

Otherwise, given this is product-related, it will need to be reported to the product team in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

@RoopeshNair

**Comment by msebolt** [comment]
Closing this issue now.
