### ISSUE TITLE
ReleasePipeline details

### ISSUE THREAD

**Issue by Vchawla21** [MicrosoftDocs/azure-devops-docs#8213]
I Can see releasepipelineid in TestRun and TestResults entity but there is no refrence table to get release pipeline details , Are these avaiable in v3.0-preview or any plan to include this 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0406dd-f852-001f-eba5-a665ed4ef7a0
* Version Independent ID: 51657f61-8b0c-3132-59d4-7d876b08af6d
* Content: [Data model for Analytics - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/extend-analytics/data-model-analytics-service?view=azure-devops#feedback)
* Content Source: [docs/report/extend-analytics/data-model-analytics-service.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/extend-analytics/data-model-analytics-service.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by pradeepna** [comment]
@Vchawla21 - TestRuns and TestResults entity just contain enough information to identify the release pipelines that they ran on so that they can be grouped or filtered by those attributes. However, since we do not have Release pipeline data in Analytics, the actual release pipelines tables are not present. It will not be available in v3.0-preview and we do not have plans to do this either. 

//cc - @PBoraMSFT who is the product owner for visibility on this requirement.

**Comment by KathrynEE** [comment]
Closing as addressed.
