### ISSUE TITLE
Override variables

### ISSUE THREAD

**Issue by vatolinrp** [MicrosoftDocs/azure-devops-docs#8214]
I'm using two variable groups in my azure devOps pipeline, configured with yml file: Common-group and Dev-group. I have same variable in each of them. I want to override variable from Common-group with the one from Dev-group. I am able to do it within the deployment job, but not with the regular job. What may be the explanation to such difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@vatolinrp Thank you for the feedback.

Please see if [variable group precedence](https://github.com/MicrosoftDocs/azure-devops-docs/issues/1142) or [overlapping scope](https://developercommunity.visualstudio.com/content/problem/660069/variable-group-precedence-not-working-when-using-o.html) helps resolve the issue.

Otherwise you can search [this list](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=Variable+in+global+variable+group+not+replaced+in+release+definition) of known variable issues and/or contact the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

@juliakm

**Comment by msebolt** [comment]
Closing this issue now.
