### ISSUE TITLE
How to roll out new version of vmss agent if vmss scale set is used?

### ISSUE THREAD

**Issue by majorvin** [MicrosoftDocs/azure-devops-docs#8226]
When creating through the portal, 1 agent pool = 1 vmss. What if we want to roll out a new version? How can we 'use' the same name so there will be no changes in the pipelines?

**Comment by msebolt** [comment]
@majorvin Thank you for the question.

Please provide a link to the documentation and we can assign an author for review, though note the support options here are limited to examples only.  

Otherwise, for more specific use-case scenarios, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by majorvin** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops

**Comment by msebolt** [comment]
@majorvin Thank you for the document link, assigning this to the author for further review.

**Comment by msebolt** [comment]
Please also note, if the issue is product-related or not yet supported, you'll need to use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Or, for additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.
