### ISSUE TITLE
Is there a difference in billing, etc. when Visual Studio Subscription user is granted another access level?

### ISSUE THREAD

**Issue by smabusali** [MicrosoftDocs/azure-devops-docs#8227]
Under the Visual Studio Subscription section it says: "If you assign Basic or Stakeholder, they also receive their Visual Studio subscription benefits upon sign-in."

Do the benefits being referred to include ADO access or is the access level still according to what is assigned? If it includes subscriber access, is the redundancy simply for ease of administration or are there any other implications such as in billing? Is it always best practice to assign a subscription user specifically with subscription access or can they be assigned a specific access level without redundant costs in case their subscription ends so that their ADO access will not be interrupted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db47b85-e178-7969-40d3-3fa83aa3fb54
* Version Independent ID: a78e453b-4b8f-c885-42ee-8a9d9979f345
* Content: [What are access levels? What access levels are supported? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/access-levels.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/access-levels.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@chcomley - Could you address this question on Billing? Is it already documented somewhere?

**Comment by smabusali** [comment]
Hello,

Is there any information available about this yet? Is there somewhere else that would be more appropriate to pose this question?

Thank you

**Comment by KathrynEE** [comment]
@smabusali  - I've tried to address your questions below: 

Q: Do the benefits being referred to include ADO access or is the access level still according to what is assigned? 
A: All benefits refer to Azure DevOps Services.

Q: If it includes subscriber access, is the redundancy simply for ease of administration or are there any other implications such as in billing?
A: To get access to Azure DevOps Services, you must assign an access level to the user.  If the user has a Visual Studio Subscription, then no additional billing is applied. If they aren't covered by that subscription, then your organization is billed according to the access level assigned. 

Q: Is it always best practice to assign a subscription user specifically with subscription access or can they be assigned a specific access level without redundant costs in case their subscription ends so that their ADO access will not be interrupted?
A; There should be no redundant costs.  See answer to the second question.

**Comment by chcomley** [comment]
Hi @smabusali, I wanted to clarify that if you assign _Basic_ or _Stakeholder_, rather than _VS subscription, the user also receives their Visual Studio subscription benefits upon sign-in. However,  the Visual Studio subscription is only recognized if the user has signed in. So, the user would be charged the Basic rate unnecessarily, until they've signed in. I'm updating the article to make this clear. Please @mention me if you have any further questions. Thanks!
