### ISSUE TITLE
batch is not supported

### ISSUE THREAD

**Issue by Leon99** [MicrosoftDocs/azure-devops-docs#8228]
`batch` in YAML is not supported yet as admitted by MS support engineers, it should be removed from the documentation until it is.
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Leon99  Thank you for the feedback, we apologize for any issues you're having.

`batch` is officially supported and cannot be removed from the documentation unless a specific reference is provided and we will update accordingly.

Otherwise, please see if the [following batch issues](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=yaml+batch) relate to your issue or get additional feedback from the product by reporting the issue [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by msebolt** [comment]
Closing this issue now.
