### ISSUE TITLE
are webhooks retried in case of no response?

### ISSUE THREAD

**Issue by ashishgrazitti** [MicrosoftDocs/azure-devops-docs#8233]
Hi Azure Devops team,

I am thinking of a webhook subscription based integration with Azure Devops.  I have a doubt if my system is down when the webhook is fired, will that event be fired again? or that piece of information is lost?

**Comment by msebolt** [comment]
@ashishgrazitti Thank you for the question.

If you reference an article we can assign this to an author for review, though note our support options are limited to documentation examples only.

Otherwise, for additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.
