### ISSUE TITLE
yaml schema file

### ISSUE THREAD

**Issue by qbikez** [MicrosoftDocs/azure-devops-docs#8248]
There's an endpoint in DevOps REST API that provides YAML schema: https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/yamlschema?view=azure-devops-rest-5.1
It should be mentioned in docs here (the schema in vscode extension can get outdated).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@qbikez It looks like that might be there as part of some autogenerated API ref, but I'll see if I can get that updated. What it returns unfortunately isn't very readable, just from curiosity, how are you using the returned values? Note that it is specific to your organization and includes tasks and things that you have registered there.

**Comment by artisbiuro** [comment]
The last section of the document ("Syntax highlighting") mentions a VSCode extension that "includes a JSON schema for validation". I'm using this extension and was getting syntax errors on a valid yaml pipeline, because the schema version that this extension uses was outdated. After some digging I found this API endpoint and used the returned value to update the schema. And intelisense started working on custom tasks installed within my org, so that's a plus :)

In general, I think this schema can be useful to other extensions and should be exposed in docs. There's already a link to a schema file, but having a reference to a 'live' source for that schema is much better.

**Comment by qbikez** [comment]
The last section of the document ("Syntax highlighting") mentions a VSCode extension that "includes a JSON schema for validation". I'm using this extension and was getting syntax errors on a valid yaml pipeline, because the schema version that this extension uses was outdated. After some digging I found this API endpoint and used the returned value to update the schema. And intelisense started working on custom tasks installed within my org, so that's a plus :)

In general, I think this schema can be useful to other extensions and should be exposed in docs. There's already a link to a schema file, but having a reference to a 'live' source for that schema is much better.

**Comment by steved0x** [comment]
I'm seeing if I can get some information that we can publish about that API and will send a note to the Visual Studio Code folks.
