### ISSUE TITLE
Please confirm where bash binaries come from (for Windows)

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/azure-devops-docs#8269]
This was asked in #7613, but closed without resolution, siting your complex repo system. 

Could you answer it please, as a fresh Windows install of the agent does not seem to come with any version of bash. 

As your documentation suggests this task works on Windows, it would be good to highlight any prerequisites.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/714283/81561506-43649f00-9361-11ea-9873-0bab59ff54da.png">

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/714283/81561559-59725f80-9361-11ea-884c-a7ebe0ac5ea1.png">

**Comment by arcotek-ltd** [comment]
Hi @vtbassmatt,

Thank you for your terse reply. I like spending my time opening these tickets. I guess I didn't ask the question clearly enough!

Your documentation states this task should work on Windows. However, on a new installation of the DevOps agent, where is the bash binary? On a new instance of Windows server (Core or otherwise), with nothing installed apart from the agent, the documented command to find bash returns:

```
C:\>where bash
INFO: Could not find files for the given pattern(s).
```
 
To me, this indicates bash is not present on the system. In your documentation, you don't mention that Bash has to be installed and the path environment variable configured before this task will work. 

As far as I know, Windows does not come with Bash binaries and installing the vsts agent does not install it either. Typically, one installs Git for Windows which gives us bash.exe, although I am sure there are other ways.

All I am asking is for you to make a note in the documentation that states Windows bash binaries need to be installed and the path environment variable updated before this task will work.  If this is not correct and bash should be installed with the agent, then we (I) need to raise a ticket for the agent maintainers.

If bash is a prerequisite of installing the agent, then, again, a little note linking to the prerequisite would also not go amiss. 

Thanks.

**Comment by vtbassmatt** [comment]
:wave: I'm sorry that my response didn't address your question adequately. #7613 was not closed without resolution. The Bash task topic was improved to make it explicit where it would search for Bash. Our dual-repo thing makes that change impossible to see from the outside, so I screenshotted the resolution (both the PR and published change) in order to answer your issue.

The agent doesn't come with Bash. It also doesn't come with Python, MSBuild, and many other things that we ship tasks for. They aren't prereqs - if you don't use a tool, you don't need to install the tool. We get a lot of fairly niche suggestions in the task docs, so maybe I'm filtering too strongly here, but this seems obvious enough not to rate documenting.
