### ISSUE TITLE
Better Example Required

### ISSUE THREAD

**Issue by mrbrennonwilliams** [MicrosoftDocs/azure-devops-docs#8272]
"Replace the placeholders with the respective values" - a functioning example would be better here. The Syntax shown isn't broken down and it's just annoying to hunt down what these commands are supposed to look like.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec99483d-828e-093b-a5af-bd2d25ea27d1
* Version Independent ID: 36f67ced-654b-3cbb-2f4e-4f7b540959ba
* Content: [Publish a NuGet package from the command line - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops#feedback)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/publish.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by shadargee1982** [comment]
> 2. Publish the sample NuGet package to your feed.
> ...Replace the placeholders with the respective values.
> nuget sources add -Name <SourceName exp:(Fabrikam_Feed)> -Source <SourceURL exp:(https://pkgs.dev.azure.com/microsoftLearningModule/.../index.json)> -username <UserName exp:(jdoe)> -password <PersonalAccessToken>
> nuget push -Source <SourceName exp:(Fabrikam_Feed)> -ApiKey az <PackagePath exp:(.\Get-Hello.1.0.0.nupkg)>

Same type of change for the sample code in #3

**Comment by ramiMSFT** [comment]
@mrbrennonwilliams Thank you for your feedback. 

please refer to the beginning of that section: [Publish a NuGet package by using the NuGet CLI](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops#publish-a-nuget-package-by-using-the-nuget-cli). The article states that you will need 4 different variables and it showed you how to get them (SourceName, SourceURL, UserName and PAT).

Those are the same variables that you will use instead of the placeholders (Snapshot below).

For the packagePath, there is an example included to show you the format (highlighted in yellow). This will be the path to your `.nupkg` file.


![image](https://user-images.githubusercontent.com/60942540/84210212-f7df0700-aa6c-11ea-8f3c-aa3f7b1319e4.png)
