### ISSUE TITLE
Can this be enabled when a Load Balancer is already on the VMSS?

### ISSUE THREAD

**Issue by OOPMichael** [MicrosoftDocs/azure-devops-docs#8273]
I do not understand why the requirement of a blank LoadBalancer Configuration on the VMSS is required. we have some under utilized Service Fabric Clusters we are interested in running the Azure Devops agents on but they have load balancers on then which is required for sf.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2476ab-d8db-bd41-689c-8d3b7c4a16d8
* Version Independent ID: 6d2e5dd0-8678-d850-a1f3-f664a653bac3
* Content: [Azure virtual machine scale set agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/scale-set-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/scale-set-agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@OOPMichael Thank you for the question.

**Please note I'm not familiar enough with the platforms to confirm running the suggestion below in any sort of production environment.**

Based on the reference documentation for [vmss](https://docs.microsoft.com/cli/azure/vmss?view=azure-cli-latest#az-vmss-create) the `load-balancer` parameter of the `create` command is used to create a new, refer to an existing, or use with no load balancer.  By using an empty string (selecting no load balancer) you are effectively preventing it from interfering with anything currently running on the VM and should by default be able to run independently of your Service Fabric Cluster.

If you have a development environment available you could try running them side-by-side.

However, since this is more of a question for the product team I'd recommend posting this to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

I'll assign this to the author for review in case more information can be added on this scenario.

**Comment by OOPMichael** [comment]
@msebolt we attempted this on our Dev Cluster, and unfortunately, the Service Fabric Extension requires the Automatic Update Mode, (this was the error when we tried to switch it to manual mode)

```Failed to update virtual machine scale set 'Primary'. Error: Virtual Machine Scale Sets with extension Microsoft.Azure.ServiceFabric.ServiceFabricNode must be set to automatic upgrade mode.```

**Comment by OOPMichael** [comment]
This can be closed, looks like it is not possible at this time. Thanks for the information.
