### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by wjdavis5** [MicrosoftDocs/azure-devops-docs#8286]
Trying to use this example:
steps:
- script: echo ${{ resources.repositories['self'].name }}

Results in an error

/azure-pipelines.yml (Line: 9, Col: 15): Unrecognized value: 'resources'. Located at position 20 within expression: format('echo {0}', resources.repositories['self'].name). For more help, refer to https://go.microsoft.com/fwlink/?linkid=842996

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f7712f-f527-4326-21d5-34f1c300bdd7
* Version Independent ID: d3e588cc-8552-ddae-1f82-0856cc84f2d9
* Content: [Pipeline decorator context - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/pipeline-decorator-context?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/pipeline-decorator-context.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/pipeline-decorator-context.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
This fails in a decorator?

**Comment by vtbassmatt** [comment]
Yeah, `${{ resources }}` will only work in a decorator. (In fact, my clue was that you posted your question from the decorators topic :grin:) Coming soon you'll be able to refer to `$[ resources ]` as a runtime expression, though.

I'm going to close this since it's neither a doc nor product bug. Release notes should go up soon if they aren't already, describing how to use the `$[ ]` version.
