### ISSUE TITLE
Grant read access only to master branch of a Git repository in Azure DevOps

### ISSUE THREAD

**Issue by michaelatvaronis** [MicrosoftDocs/azure-devops-docs#8303]
Using pipelines in Azure DevOps, defining the pipeline to take sources from an Azure DevOps Git repository, setting the master branch.

​I don't want users to be able to choose from the drop down list, want them to only use the master branch.

But actually the drop list contains all the branches in that Git repository, so they can choose from which branch to take the sources.

Is it possible to grant a user/group with read access only to the master branch of a Git repository, but not on any other branches in that repo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf345ce-1831-bc64-bc2a-617fb69b3352
* Version Independent ID: 3f1e08ea-3db8-92e8-1873-953d1f026f25
* Content: [Set Git branch security and permissions - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops#feedback)
* Content Source: [docs/repos/git/branch-permissions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/branch-permissions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@michaelatvaronis Thank you for the question.

Please see if [this recent post](https://developercommunity.visualstudio.com/content/problem/724470/creating-reposbranches-grants-explicit-security-pe.html) addresses your issue and provide feedback below.

**Comment by michaelatvaronis** [comment]
Thanks for the prompt answer, @msebolt !

From a permissions point of view, that post would fulfill the requirement.

However, rethinking about the use case again, I was wondering if it is possible to set the pipeline to lock on a specific branch in the sources repository, without allowing users to choose another branch when queuing a new run.
This feels more of a pipelines feature request, rather than a permissions issue with Git for Azure DevOps.
WDYT @msebolt?

**Comment by msebolt** [comment]
@michaelatvaronis You're welcome.  

I would try [manual locking](https://docs.microsoft.com/azure/devops/repos/git/lock-branches?view=azure-devops) or using custom REST as discussed [here](https://developercommunity.visualstudio.com/content/problem/714155/how-to-unlock-and-lock-branches-at-a-time-using-az.html) or [here](https://developercommunity.visualstudio.com/content/problem/594300/is-there-an-api-for-lock-a-branch.html) first, otherwise then yes a feature request would be required.

Please refer to the [Azure DevOps community](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) for additional feedback.
