### ISSUE TITLE
Scope to create yaml build definition?

### ISSUE THREAD

**Issue by jkewley** [MicrosoftDocs/azure-devops-docs#8315]
Looking for which scope applies to `az pipelines create` when using the `--yaml-path` option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0 - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops#scopes)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @jkewley, I'm following up on this and will be in touch. Thanks for reaching out!

**Comment by chcomley** [comment]
Hi @jkewley, The product group has asked that you please open a feedback ticket on the Developer Community website. Go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Report a problem** > **Azure DevOps**. Enter your title and details, and then select **Submit**. The team will engage from there. Since this issue isn't directly related to documentation, I'll be closing it. Please feel free to @mention me if you have any further questions about the article. Thank you!
