### ISSUE TITLE
Will it be safe to install the deployment agent to on premise production environment

### ISSUE THREAD

**Issue by gautamksr** [MicrosoftDocs/azure-devops-docs#8320]
Hi,
We are trying to figure out a secure way to deploy web app from Azure DevOps to our on-premise environments (Dev, QA, Staging, and Prod).

My security team has asked, how installing the agent is safe for our on-premise environments (Dev, QA, Staging, and Prod)? I have googled but didn't find any clue. I wonder if Azure DevOps product team use deployment groups to deploy apps to their on-premise "production" server? Any best practice?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fa0c14-9937-41bc-cc34-179edb379083
* Version Independent ID: 10fe3600-21a5-12db-5e21-5ade3a8fa484
* Content: [Provision agents for deployment groups - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops&WT.mc_id=devopslab-c9-dabrady)
* Content Source: [docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@gautamksr  Thank you for the question.

This issue is more support-related, for support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)

Otherwise, for issues relating to the documentation please include your references in the comments below.

**Comment by msebolt** [comment]
Closing this issue now.
