### ISSUE TITLE
Should be able to create paths if they don't exist

### ISSUE THREAD

**Issue by okezieokpara** [MicrosoftDocs/azure-devops-docs#8322]
This task should be able to create all the paths along it's way. Considering the fact that there is no separate task to create paths.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@okezieokpara  Thank you for the suggestion.

On product-related issues we recommend using **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback.

You can also try starting an issue [here](https://github.com/Microsoft/azure-pipelines-tasks/issues).

Otherwise, to request changes to the documentation please include a reference below.

**Comment by msebolt** [comment]
Closing this issue now.
