### ISSUE TITLE
IP addresses and range restrictions is out of date

### ISSUE THREAD

**Issue by AceHack** [MicrosoftDocs/azure-devops-docs#8334]
This table is out of date as IPs like 20.44.80.197 are now returned
```
ping vs-ssh.visualstudio.com
Pinging tfsprodeus2su1.eastus2.cloudapp.azure.com [20.44.80.197] with 32 bytes of data:
```

IP V4 ranges | IP V6 ranges
-- | --
13.107.6.0/24 | 2620:1ec:4::/48
13.107.9.0/24 | 2620:1ec:a92::/48
13.107.42.0/24 | 2620:1ec:21::/48
13.107.43.0/24 | 2620:1ec:22::/48

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#feedback)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by chcomley** [comment]
Hi @AceHack, Thanks for reaching out. Those IP addresses that you provided are for Azure Front Door to enhance availability and decrease latency. Most customers reach Azure DevOps via the Azure Front Door rather than directly to Azure DevOps devices. See detailed blog here:  https://devblogs.microsoft.com/devops/new-ip-firewall-rules-for-azure-devops/. tfsprodeus2su1.eastus2.cloudapp.azure.com [20.44.80.197] is our internal device and not the Azure Front Door., hence, you're seeing 20.44.80.197 address returned. Please @mention me if you have any further questions. Thank you!

**Comment by AceHack** [comment]
We just need the list of all IP addresses so we can configure our firewall correctly to allow outgoing ssh to only Azure DevOps.

**Comment by AceHack** [comment]
The IP ranges listed don't work because they don't allow us to hit the git repos.

**Comment by AceHack** [comment]
@chcomley

**Comment by AceHack** [comment]
With just the IP addresses listed, we get denied ssh to our git repos from our firewall because DNS is giving us the IP address I showed you.

**Comment by chcomley** [comment]
Hi @AceHack, You can follow the directions [here](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops#ssh-connections) for SSH connections to Git repo. Thanks.

**Comment by AceHack** [comment]
What I'm saying and the reason I created this bug is because those instructions absoutly do not work.  They leave out IP addresses like the ones I mentioned.  This bug should not be closed.  @chcomley This causes firewalls to block talking to ssh.

**Comment by chcomley** [comment]
Hi @AceHack, I've circled back with the PM and they've requested that you submit a support ticket. Please go [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Report a problem**.  If you provide a link to this issue in your support request, I can be notified of whether a solution is determined which warrants an article update.  Since this issue isn't resulting in an article update at this time, I'm closing it. Thank you.
