### ISSUE TITLE
Example of Package Promotion with REST API

### ISSUE THREAD

**Issue by reynoldsbd** [MicrosoftDocs/azure-devops-docs#8350]
This page mentions that packages can be promoted "using REST APIs," but it does not explain how or link to the relevant APIs.

It would be great if we made the following changes:

* Link to the specific REST API that can be used to promote a package:
  https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/universal/update%20package%20version?view=azure-devops-rest-5.1
* Add an example of using this API to promote a package. IMO this example should be in the API docs themselves, but this page would also be an acceptable location.

#2333 contains a previous discussion and some examples of calling the API, but it looks like that issue was closed due to inactivity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with prerelease and release views - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by reynoldsbd** [comment]
Thanks, I see the page has been updated with more details! However, the examples are incomplete because they don't include the body of the PATCH requests, which should look something like this:

```json
{
    "views": {
        "op": "add",
        "path": "/views/-",
        "value": "<view name>"
    }
}
```

This is the part that took me a while to figure out, as it's not very easy to piece together from the API docs.

**Comment by ramiMSFT** [comment]
@reynoldsbd Thank you for your feedback. the API documentation is done by the engineers on the product team. We don't own that part and we are only responsible for the Azure DevOps docs (Azure pipelines, artifacts, etc..).
I included the HTTP request commands as an example along with a link to the API page for more details but the issue is that the actual API page does not have a full example with the body of the request.

I suggest you file an issue under the API docs or open a ticket on the [Developer Community ](https://developercommunity.visualstudio.com/spaces/21/index.html).
