### ISSUE TITLE
Azure Devops Generator bugs

### ISSUE THREAD

**Issue by gsuttie** [MicrosoftDocs/azure-devops-docs#8358]
When using the Azure DevOps Generator I want to create a project template and reuse this.

I notice that if I create a brand new project to use as a bad template for all ongoing projects with things like removing Artifacts and Test plans. When I save the base template and then export my template to reimport for a brand new project (for best practice)

Most of the settings I save in my base template are ignored when I go to create a new project by importing the exported zip file.

Are these issues likely to get fixed?

I'm using https://azuredevopsdemogenerator.azurewebsites.net/extractor/index to extract a base template.

An using this link https://vstsdemodata.visualstudio.com/AzureDevOpsDemoGenerator/_wiki/wikis/AzureDevOpsGenerator.wiki/58/Build-your-own-template to build my own template.

--------------

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@gsuttie Thank you for the feedback.

Unfortunately our support options are limited to documentation examples only.

Please refer to the [custom template tutorial](https://docs.microsoft.com/azure/devops/demo-gen/build-your-own-template?toc=%2Fazure%2Fdevops%2Fdemo-gen%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fdemo-gen%2Fbreadcrumb%2Ftoc.json&view=azure-devops) and if you can find specific issues with the steps, please add references to the document below and we will assign an author for review.

Otherwise, to solicit feedback from the product team in response to a general issue, please use **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by gsuttie** [comment]
So I created a new project in Azure Devops - https://dev.azure.com/gregorsuttie/DemoTemplateProject which has Test Plans and Artifacts removed.
If I export the template and then reimport as the basis of a new project then I see Test Plans and Artifacts https://dev.azure.com/gregorsuttie/BrandNewProjectBasedOffOfTemplate - I was hoping the new project would be based on my template project and this would be hidden.

So a large number of the settings I configure in my baseline project don't get carried over to the new project which is pretty disappointing.

Is this a bug in the export functionality?

**Comment by msebolt** [comment]
Quite possibly, again if this is a bug you will need to direct this to the product team.

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
