### ISSUE TITLE
Badge Appearance

### ISSUE THREAD

**Issue by edebdev** [MicrosoftDocs/azure-devops-docs#8362]
Is there a way to change the badge style and color? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6203e4-5a94-d265-783e-8525051324b5
* Version Independent ID: f03c2d8e-aa65-611c-b404-316b7e47ff47
* Content: [Enable Kanban board badge status for GitHub repo - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/github/configure-status-badges?view=azure-devops#feedback)
* Content Source: [docs/boards/github/configure-status-badges.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/github/configure-status-badges.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@edebdev Thank you for the feedback.

Unfortunately this issue is still considered low priority to the product team, see [these posts](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=%22No+color%22+for+Kanban+card+styles).  

Please consider adding your suggestion there for further engagement and/or to have this feature added to the release cycle.

**Comment by msebolt** [comment]
Closing this issue now, for additional help please refer to [Azure DevOps support](https://azure.microsoft.com/support/devops/).
