### ISSUE TITLE
Closed vs Resolved

### ISSUE THREAD

**Issue by bjrienzo** [MicrosoftDocs/azure-devops-docs#8417]
Can this behavior be customized to set what state the work item should be placed in? I would like to have items move into 'Resolved' status rather than 'Closed', so it can follow the workflow as described here:
https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/agile-process-workflow?view=azure-devops#track-progress

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d98917-0ca1-1a1e-1163-bac0af6adc71
* Version Independent ID: ea047ee3-299a-f7b2-b009-5fcc4224dece
* Content: [Close work items using commit messages - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/resolution-mentions?view=azure-devops#feedback)
* Content Source: [docs/repos/git/resolution-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/resolution-mentions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@bjrienzo  Thank you for the question, please refer to [changing the workflow](https://docs.microsoft.com/azure/devops/reference/xml/change-workflow-wit?view=azure-devops) or use REST to [manually set the status](https://docs.microsoft.com/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.1#update-a-field).

For additional feature suggestions or help with the above, please move this to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for product team engagement.

For any other documentation concerns, please comment below.  

Otherwise, for more support options refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
