### ISSUE TITLE
Parent field error when importing or bulk update items in DevOps

### ISSUE THREAD

**Issue by roturn** [MicrosoftDocs/azure-devops-docs#8422]
I am trying to update the parent field via a bulk update once imported items are assigned an ID.   It is saying that field is read only.

"Value of a readonly field Parent was modified. Please revert the Parent values or remove the column from the input file and and try to import again."

Is there a way to make the parent field an updateable field?

**Comment by msebolt** [comment]
@roturn  

This sounds more like a question with the product team in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Please start a thread there and provide a link back to this issue.

Or, for documentation concerns please cite the article with needed changes.

For additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.

**Comment by Kitwradr** [comment]
Having the same issue, is there any fix for this?

**Comment by msebolt** [comment]
Please review this similar issue [here](https://developercommunity.visualstudio.com/content/problem/1050030/unable-to-update-parent-field-with-csv-update.html) for guidance, otherwise we'd recommend starting an issue with the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).
