### ISSUE TITLE
No usable version of the libssl was found

### ISSUE THREAD

**Issue by fabiobds** [MicrosoftDocs/azure-devops-docs#8429]
This message occurs when I try a docker run with Docker for Windows (Linux images):
3. Configuring Azure Pipelines agent...
&gt;&gt; Connect:
No usable version of the libssl was found
./config.sh: line 86:    67 Aborted                 ./bin/Agent.Listener configure "$@"

What may be going wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by fabiobds** [comment]
I can run with Ubuntu 16.04, but in this case occurs an error with the git version.

**Comment by msebolt** [comment]
@fabiobds  Thank you for the feedback.

Please refer to the issue https://github.com/microsoft/azure-pipelines-agent/issues/2454 for additional guidance.

Otherwise for further support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
