### ISSUE TITLE
Why is **View execution of in-progress tests** only available on release pipelines and not build pipelines?

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/azure-devops-docs#8463]
Why is **View execution of in-progress tests** only available on release pipelines and not build pipelines?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cca257-5f81-190e-b50c-7b7f69217234
* Version Independent ID: 1d84dc61-a8bb-b45a-6c93-5bec211c19a5
* Content: [Review test results - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#view-execution-of-in-progress-tests)
* Content Source: [docs/pipelines/test/review-continuous-test-results-after-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/test/review-continuous-test-results-after-build.md)
* Product: **devops**
* Technology: **devops-cicd-test**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by msebolt** [comment]
@mikeblakeuk Thank you for the question.

For product questions, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

For issues with the documentation, please provide doc references below and we can assign this to an author for further review.

Otherwise, for additional support options, check out:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
