### ISSUE TITLE
Any condition I can use for pull requests from/to certain branches?

### ISSUE THREAD

**Issue by RobinZergiebel** [MicrosoftDocs/azure-devops-docs#8465]
Hey there,

was wondering if there was a condition I can use for pull requests from/to certain branches?
Something like:
`condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), eq(variables['PullRequest.TargetBranch'], 'refs/heads/master'))`

Cheers,
Robin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@RobCoPKC Thank you for the question, assigning this to the author for review of documentation.

For product questions, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Otherwise, for additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by RobCoPKC** [comment]
Any news?

Cheers,
Robin

**Comment by juliakm** [comment]
@RobCoPKC  I apologize for the delay. Are you using GitHub or Azure Repos? If so, you should check out pull request triggers:
* [PR triggers in Azure Repos Git](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#pr-triggers)
* [PR triggers in GitHub](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/bitbucket?view=azure-devops&tabs=yaml#pr-triggers)

**Comment by RobCoPKC** [comment]
Hey @juliakm,

yes, we are using Azure Repos Git and we are already using PR triggers. You seem to be misunderstanding the intention of my question.
I'm asking if there is a condition we can use for pull requests targeting specific branches so that this task (in our case the increase of the minor version variable) is executed during the PR trigger build IF the target branch is a certain branch (in our case the master branch).
Please reopen this issue.

Cheers,
Robin

**Comment by juliakm** [comment]
@RobinZergiebel Can you try this and let me know if it does what you were expecting?

```yaml
jobs:
- job: NotMaster
  condition: eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/not-master')
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "Hello world"
```

**Comment by RobinZergiebel** [comment]
Hey @juliakm,

thank you so much, that is exactly what I was looking for!

Cheers,
Robin
