### ISSUE TITLE
Is there any way to define that PR validation builds must be queued that is no PR builds can be executed parallel but queued by time.

### ISSUE THREAD

**Issue by ferike86** [MicrosoftDocs/azure-devops-docs#8468]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@ferike86 Thank you for the feedback.

For product-related issues, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

If there are issues with the documentation, please cite references below and we can assign this to an author for further review.

Otherwise, for additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
