### ISSUE TITLE
@mention Identity Picker doesn't work in TFS 2017

### ISSUE THREAD

**Issue by rahul230691** [MicrosoftDocs/azure-devops-docs#8476]
@mention Identity picker doesn't work for me in TFS 2017 while writing the comment for someone individual.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ae521f-6ae4-4d7f-2cce-f844e5811b66
* Version Independent ID: 18098490-1f34-e966-3135-cb90197bfa6f
* Content: [Use @mentions in work items and pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/at-mentions?view=azure-devops)
* Content Source: [docs/notifications/at-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/at-mentions.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@person Thank you for the feedback.

For product-related issues, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

For documentation concerns, if you include references below we can assign an author for further review.

Otherwise, for additional support options, refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by rahul230691** [comment]
Thanks @msebolt for the guidance. Should I report the same problem again in the Azure DevOps community?

**Comment by msebolt** [comment]
@rahul230691 You're welcome, apologies for the typo.

Yes, please direct all product-related issues to the community and link back to this issue and/or provide a link below.

**Comment by rahul230691** [comment]
Thank you @msebolt 

https://developercommunity.visualstudio.com/content/problem/1068505/-68.html

**Comment by msebolt** [comment]
You're welcome, thank you for moving this to the product team's forum.

Closing this issue now, if any documentation changes are required please comment below and we can re-open.
