### ISSUE TITLE
Unable to access Build.Buildnumber from Deployment Pipeline

### ISSUE THREAD

**Issue by contactvikasgupta** [MicrosoftDocs/azure-devops-docs#8480]
CODE:
echo "(Build.Buildnumber) 										:	$(Build.Buildnumber)"
buildNumbertest= "Build.Buildnumber"
echo "buildNumbertest											:	$buildNumbertest"
echo "(buildNumbertest)											:	$($buildNumbertest)"
[Enter feedback here]

OUTPUT:
2020-05-28T20:50:05.0263387Z (Build.Buildnumber) 										:	2020.515.94
2020-05-28T20:50:05.0266228Z /home/vsts/work/_temp/eece4524-81e3-42d6-b7ca-a6d208853b8b.sh: line 12: Build.Buildnumber: command not found
2020-05-28T20:50:05.0268635Z buildNumbertest											:	
2020-05-28T20:50:05.0269958Z (buildNumbertest)											:	

How do I get to access value after doing string operations and passing it as $($VARIABLE_NAME)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@contactvikasgupta Thank you for the question.

For product-related issues and support requests, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

For documentation concerns, please cite references below and we can assign an author for further review.

Otherwise, for additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
