### ISSUE TITLE
publishing by CLI: Step 4 image shows correct value but the written instructions are wrong

### ISSUE THREAD

**Issue by CarteriTrellis** [MicrosoftDocs/azure-devops-docs#8489]
At step 4, the instructions read in part:
4. Complete the form:

- Name your token.
- Select your organization.

The picture accompanying Step 4 shows "All accessible organizations" being selected, which is the only value that will work with Marketplace PATs. If you only pick one organization, publishing via CLI will result in a 401 error even if the PAT is valid.

The text instructions need to match the picture - only "All accessible organizations" will work for publishing extensions with the TFX CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b2914b5-105a-32f7-c7be-5f1604775f61
* Version Independent ID: 0070cd88-c1f7-6a69-ef9c-fb5b4f3b8544
* Content: [Publishing and Packaging an Extension from the Command Line - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/publish/command-line?view=azure-devops)
* Content Source: [docs/extend/publish/command-line.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/publish/command-line.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@CarteriTrellis Thank you for the question, assigning this to the author for further review of the documentation.

Please note for specific use-case scenarios, use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

Otherwise, for additional support refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by chcomley** [comment]
Hi @CarteriTrellis, Thanks for this. I've updated the article, which should be live shortly. Thanks again!
