### ISSUE TITLE
Undelete Azure DevOps Wiki pages

### ISSUE THREAD

**Issue by sdksmm** [MicrosoftDocs/azure-devops-docs#8492]
It does not seem possible to redo an accidental delete of a Azure devops wiki page. 
I find it to be a big lack that this feature is missing.

**Comment by msebolt** [comment]
@sdksmm  Thank you for the feedback, your input is highly appreciated.

For product-related issues, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Otherwise, for additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
