### ISSUE TITLE
ok ok

### ISSUE THREAD

**Issue by q28wertyuio** [MicrosoftDocs/azure-devops-docs#8498]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5b4734-b75e-95c3-73d2-78216e166bf1
* Version Independent ID: e4404510-ff79-aabf-1214-1d1ccb968aba
* Content: [Understand what you get with Azure Boards - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/get-started/what-is-azure-boards?view=azure-devops&tabs=agile-process)
* Content Source: [docs/boards/get-started/what-is-azure-boards.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/get-started/what-is-azure-boards.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by q28wertyuio** [comment]
ok

**Comment by q28wertyuio** [comment]
ok

**Comment by msebolt** [comment]
@q28wertyuio Thank you for the feedback.

If you'd like to ask a question or have changes you want made to the documentation, please comment below.

Otherwise, for additional support options, please refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
