### ISSUE TITLE
REF ISSUE: #408 - What is the Operation API "resource-area-id"?

### ISSUE THREAD

**Issue by SeanCLeavitt** [MicrosoftDocs/azure-devops-docs#8555]
I've tried to find the Resource Area ID for 'Operations' Resource Area and cannot find it in the 218 listed in the "[https://org.visualstudio.com/_apis/resourceAreas](https://ORG.visualstudio.com/_apis/resourceAreas)" response.

I also took a look it within the Swagger Spec ([here](https://github.com/MicrosoftDocs/vsts-rest-api-specs/tree/master/specification/operations)).

Is it missing? This article "[Work with URLs in extensions and integrations](https://docs.microsoft.com/en-us/azure/devops/extend/develop/work-with-urls?view=azure-devops&tabs=http#how-to-get-the-base-url-for-a-rest-api)" leads me to believe that I must always form my base url based on the Resource ID. Is that incorrect for the case of the "Operations" Api?

Thank you,

Sean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a28256c7-e0d2-fc25-289e-55c64e23f27c
* Version Independent ID: c93daa34-b846-728f-a570-fa7764ab133b
* Content: [Working with URLs in extensions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/work-with-urls?view=azure-devops&tabs=http#how-to-get-the-base-url-for-a-rest-api)
* Content Source: [docs/extend/develop/work-with-urls.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/work-with-urls.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@SeanCLeavitt Thank you for the question.

Unfortunately, due to the high volume of requests in the documentation forum, we are unable to handle support requests at this time.

Please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

Or, for additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
