### ISSUE TITLE
Using PAT as Bearer for authorization Header is not working

### ISSUE THREAD

**Issue by jesslinocon** [MicrosoftDocs/azure-devops-docs#8559]
It seems that using PAT as Bearer whether it's encoded to Base64 or not is not working.
I also disable Git Credential helpers 

```
git -c http.extraHeader="Authorization: Bearer $B64Pat" clone <repo_uri>                                                                Cloning into '<repo_uri'...
Username for 'https://dev.azure.com':                                                                                   
Password for 'https://dev.azure.com':                                                                                   
fatal: Authentication failed for <repo_uri>
```

The question would be why this would still need to me get prompted with username as anything and password as PAT. would be this just causing a redundancy if Bearer <token> is taken place?

> Git interactions require a username, which can be anything except the empty string. The PAT is used as the password. Additionally, you have to Base64-encode the username & PAT in order to use it with HTTP basic authentication. On Linux or macOS, in Bash, you can type:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f99d2d-363b-d01d-039d-4fdc636fa2df
* Version Independent ID: f47330d5-e2de-36a4-e5b3-5bc77505b161
* Content: [Authenticate with personal access tokens - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@jesslinocon Thank you for the feedback.

Unfortunately our support options in the documentation forum are limited to provided examples only.

Please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit help from the product team and include a link back to this issue.

Otherwise, for additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
