### ISSUE TITLE
Run agent as VSTS service.

### ISSUE THREAD

**Issue by ashutoshbarve** [MicrosoftDocs/azure-devops-docs#8568]
Is there any way that I can run docker self-hosted agent as a VSTS service.
I am facing an issue related to Authentication like I am not able to access file share from inside the container. I would like to hast the agent as VSTS service.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/26390486/84030217-48912a00-a9b1-11ea-9440-b4007c33d147.png)
It would be a great help if you can add this feature(Add agent as a service)

**Comment by msebolt** [comment]
@ashutoshbarve Thank you for the feedback, your input is valuable to us.

For issues with the documentation comment below, otherwise please use **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit input on this from other users and get the product team's thoughts on feasibility.
