### ISSUE TITLE
External guest access not visible & working in DevOps

### ISSUE THREAD

**Issue by ransemsvsg** [MicrosoftDocs/azure-devops-docs#8592]
Hi Support,

Like [#2881](https://github.com/MicrosoftDocs/azure-devops-docs/issues/2881) I am unable to give external people access to my organization & projects, the option is not visible in the organization settings(even within newly created organizations) and the invitations do not work (access denied error when loading the page). 

The account which holds the organization and projects is a private Microsoft account. When I logon to DevOps with my Office365 account from my company, I am able to create an organization and invite external people (the option is also visible in the organization settings).

**Comment by msebolt** [comment]
@ransemsvsg Thank you for the feedback and apologies for the issues.

Please make you have [enabled preview features](https://docs.microsoft.com/azure/devops/project/navigation/preview-features?view=azure-devops&tabs=new-account-enabled) and/or try using a test organization with preview features enabled to see if this is an issues with the settings.

Otherwise, start a ticket [here](https://developercommunity.visualstudio.com/spaces/21/index.html) and I'll assign this to a member of the team referenced above.

**Comment by ransemsvsg** [comment]
@msebolt : The preview features are enabled on user & organization level. I will open an ticket at the url you send me.

**Comment by msebolt** [comment]
Please post a link to the ticket reference so the author's can keep track of the status.

**Comment by msebolt** [comment]
Closing this issue now, if any changes are needed for the documentation please comment below.
