### ISSUE TITLE
IIS Web App Manage task, vDAuthUserPassword is not working

### ISSUE THREAD

**Issue by jq-yeraz** [MicrosoftDocs/azure-devops-docs#8594]
The parameter vDAuthUserPassword seem to not working, IIS is not updated with the credentials and I have an access denied. Below my YAML :

    steps:
    - task: IISWebAppManagementOnMachineGroup@0.  
      displayName: 'Manage IISVirtualDirectory'
       inputs:
         IISDeploymentType: IISVirtualDirectory
        ParentWebsiteNameForVD: fqdn.tld
        VirtualPathForVD: /packages
        PhysicalPathForVD: '\\remote\folder\folder'
        VDPhysicalPathAuth: VDWindowsAuth
        VDAuthUserName: 'DOMAIN\setup'
        VDAuthUserPassword: '$(password)'
      continueOnError: true

**Comment by msebolt** [comment]
@jq-yeraz Thank you for the feedback and apologies for the issues.

Are you using [secret variables](https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables) for the `VDAuthUserPassword`?  

If not, try using the standard [variables syntax](https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax) along with an `echo` command to ensure it's being referenced correctly.

Otherwise, please transfer this to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo for feedback from the product team.
