### ISSUE TITLE
steps:   - bash: echo This script could use $SYSTEM_ACCESSTOKEN     env:       SYSTEM_ACCESSTOKEN: $(System.AccessToken)   - powershell: Write-Host "This is a script that could use $env:SYSTEM_ACCESSTOKEN"     env:       SYSTEM_ACCESSTOKEN: $(System.AccessToken)

### ISSUE THREAD

**Issue by Romyanmar4** [MicrosoftDocs/azure-devops-docs#8595]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Triggers in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd-build**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@Romyanmar4 Thank you for the feedback.

If there are issues with the documentation please add details below, otherwise for additional support options see:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
