### ISSUE TITLE
While the shallow-fetch tooltip redirects to this page for additional information, there is no additional information about shallow-fetch

### ISSUE THREAD

**Issue by i3anaan** [MicrosoftDocs/azure-devops-docs#8601]
There should probably be some extra information about the shallow-fetch option on this page, or alternatively (but less desirable) the tooltip should not give the indication of there being additional information on this page.

Tooltip, which is part of the 'Get Sources' page of an Azure DevOps pipeline:
![image](https://user-images.githubusercontent.com/2911348/84380864-6399af00-abe8-11ea-8ed8-dd7f48c4667f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e59bebc3-fe8a-ad9e-7c55-884a8c7b4bac
* Version Independent ID: 7db3d604-b118-2f7b-85f4-1bd52244b279
* Content: [Build source repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/?view=azure-devops)
* Content Source: [docs/pipelines/repos/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/index.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by vtbassmatt** [comment]
We should warn that shallow fetch can sometimes speed up fetches, but depending on the repo shape and how fast it's moving, can also occasionally make things worse. For instance, because we fetch by ref but then checkout by commit (to ensure we build _exactly_ what the user wanted built), if fetch depth is very low, then occasionally the ref may no longer point to the commit we snapped.
