### ISSUE TITLE
Linux and Windows Service Containers

### ISSUE THREAD

**Issue by sdolenc** [MicrosoftDocs/azure-devops-docs#8608]
Our team wants to run steps within a Linux container that uses a Windows service container (https://hub.docker.com/r/microsoft/azure-cosmosdb-emulator)

Do you have any advice for how we can achieve this today? Is it something that will be possible in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@sdolenc Thank you for the question.

The product team is only addressing [running Linux from Windows containers](https://developercommunity.visualstudio.com/idea/366304/support-for-docker-with-linux-containers-on-window.html), for Windows from Linux please suggest a feature [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

Otherwise, you'll need to use both Linux and Windows containers from a [multi-platform pipeline](https://docs.microsoft.com/azure/devops/pipelines/get-started-multiplatform?view=azure-devops) to provide external customization.
