### ISSUE TITLE
How do I see log/history of changes for Azure DevOps/TFS agent pool?

### ISSUE THREAD

**Issue by Alex2357** [MicrosoftDocs/azure-devops-docs#8634]
In a big organisation, too many people working on TFS someone disables, adds or removes the agents in/from the pool. I'd like to find out who did latest changes(what they did and when they did) to a certain pool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Alex2357** [comment]
Up. This is a high priority for us. Can we somehow see the change history of pool agent?

**Comment by msebolt** [comment]
@Alex2357 Thank you for the feedback.

Please see if [audit logs](https://docs.microsoft.com/azure/devops/organizations/audit/azure-devops-auditing?view=azure-devops&tabs=preview-page) can provide the information you're looking for.

Otherwise, start a ticket with the product team [here](ttps://developercommunity.visualstudio.com/spaces/21/index.html) to have this added as an audit log event or [supported event type](https://docs.microsoft.com/azure/devops/notifications/oob-supported-event-types?view=azure-devops).
