### ISSUE TITLE
for YAML pipelines which pre-defined variables available compile time

### ISSUE THREAD

**Issue by mohanrajatnetapp** [MicrosoftDocs/azure-devops-docs#8658]
[Enter feedback here]
Initially only System.* variables were available in template expressions. Is it expanded to all PreDefined Variables (including Agent variables too?) 
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
or only
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#pipeline-variables

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#functions)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by mohanrajatnetapp** [comment]
+1

**Comment by msebolt** [comment]
@mohanrajatnetapp Thank you for the question.

Please refer to the **Available in template** column on the [Predefined variables](https://docs.microsoft.com/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables) page.

If you find there are any discrepancies please comment below, otherwise to suggest additional variables be added, solicit feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
