### ISSUE TITLE
Many versions wait for approval

### ISSUE THREAD

**Issue by slawekww** [MicrosoftDocs/azure-devops-docs#8662]
Let's assume YAML multi-release pipeline with stages.
Run many releases of pipeline and stage-X with approval is reached by many versions.

In old Release pipeline, new version cancels waiting for approval by old version.
In YAML pipeline, both of them are active for approval.

Is it expected behavior?
Is it possible to configure auto-cancel waiting for approval for old versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@slawekww Thank you for the question.

Unfortunately in this forum we can only focus our support on referenced documentation and/or samples.

For questions on product behaviour and/or feature sets, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team.

Otherwise, for additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
