### ISSUE TITLE
Cache result of ngcc (Angular Ivy Compatibility Compiler) in Pipeline

### ISSUE THREAD

**Issue by stevewarsa** [MicrosoftDocs/azure-devops-docs#8687]
I'm trying to cache the result of the ngcc command that runs automatically as a result of ng build --prod.  I've set up a Cache task.  Here are the relevant details:

**variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/my-sub-folder/node_modules
...
\- task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | **/my-sub-folder/yarn.lock, !**/my-sub-folder/node_modules/\**/yarn.lock'
          restoreKeys: |
            yarn | "$(Agent.OS)"
          path: $(YARN_CACHE_FOLDER)
        displayName: Cache node_modules packages**

I can see that the caching works - it is both restored and saved.

However I still see the messages that the ngcc compiler is running on every build:

Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
...
That process takes anywhere from 6-9 minutes.  I want that to be cached so that ngcc will only run when the yarn.lock file is changed.

Note, I have also tried following the exact yarn example in this documentation with the variable set like this:

**YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn**

But it still runs ngcc.  Maybe this is not an Azure pipeline issue, but an angular issue.  Maybe I'm not understanding the Cache task?  I don't know.

I don't see a way to troubleshoot and find out where this cache is restored to and why ng build is not "seeing it".

So far, I've been unsuccessful in doing this.  Any clues on what I'm doing wrong?

**Comment by msebolt** [comment]
@stevewarsa Thank you for the question.

Please provide a reference to documentation example and we can assign this to an author for review.

Otherwise, for general support, please see:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by Maximaximum** [comment]
@stevewarsa did you manage to succeed with caching ngcc results?

**Comment by stevewarsa** [comment]
@Maximaximum No, I haven't succeeded yet

**Comment by msebolt** [comment]
For review, please see if cache issues [here](https://stackoverflow.com/questions/59487604/caching-npm-dependencies-in-azure-pipeline-for-in-built-windows-latest-image) and [here](https://stackoverflow.com/questions/62575032/how-do-i-make-azure-devopss-pipeline-cache-store-its-result-even-if-a-step-fail) apply.  Also a similar issue was raised in the **Azure DevOps community** [here](https://developercommunity.visualstudio.com/content/problem/931221/yarn-caching-doesnt-work.html).

Assigning this to the author of [Cache task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/cache?view=azure-devops) in case any updates are needed to the documentation.

**Comment by damccorm** [comment]
Hey @msebolt, I believe @johnterickson actually owns this task (or maybe @phil-hodgson at this point?)

**Comment by stefanmatar** [comment]
Hi! Any update on this?

**Comment by stevewarsa** [comment]
I haven't tried the change yet as I'm busy with other things.  Hopefully soon.

**Comment by hiepxanh** [comment]
I still have issue on docker workflow, already try everything to precompile but not work, I find out that it complie library different for each project and that why reason `ngcc --properties es2015 browser module main --create-ivy-entry-points` cannot solve the problem

**Comment by marklagendijk** [comment]
Since Angular 13 you can [enable a build cache folder](https://angular.io/cli/cache) for the Angular CLI in your `angular.json`:
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "cache": {
    "enabled": true,
    "environment": "all"
  }
}
```
By default the cache will be saved under `.angular/cache`.

With this I created the following cache task:
```yaml
- task: Cache@2
  displayName: Cache Angular build
  inputs:
    key: 'angular | "$(Agent.OS)" | MyApp/package-lock.json'
    path: MyApp/.angular/cache
```

The issue with above approach is that the package-lock.json will not always change when the cache changes, because it will only change when our dependencies change, but not when only our application files change.
Now the question is: does the Cache task only save the cache when the key changed, or also when the contents of the cache changed?
If it only saves when the key changed, we probably should change it to something like this:

```yaml
- task: Cache@2
  displayName: Cache Angular build
  inputs:
    key: 'angular | "$(Agent.OS)" | MyApp/.angular/cache/**'
    restoreKeys: |
      angular | "$(Agent.OS)" | MyApp/package-lock.json
      angular | "$(Agent.OS)" | MyApp/package.json
    path: MyApp/.angular/cache
```
