### ISSUE TITLE
Not only Complete, In Progress, removed also

### ISSUE THREAD

**Issue by sungle3737** [MicrosoftDocs/azure-devops-docs#8695]
I can complete item #323 by commit message by`fix #323`
How about more features like `start #323` & `remove #323` for more productivity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d98917-0ca1-1a1e-1163-bac0af6adc71
* Version Independent ID: ea047ee3-299a-f7b2-b009-5fcc4224dece
* Content: [Close work items using commit messages - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/resolution-mentions?view=azure-devops)
* Content Source: [docs/repos/git/resolution-mentions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/resolution-mentions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@sungle3737 Thank you for these suggestions.

For documentation concerns, please add additional references below.

Otherwise, for feature reqeusts, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solict additional feedback from the product team.
