### ISSUE TITLE
Group/endgroup tag doesn't work

### ISSUE THREAD

**Issue by gladjoe** [MicrosoftDocs/azure-devops-docs#8727]
##[group]
##[endgroup]
Both the about tags doesn't work in azure DevOps server 2019 update 1.
Can you please check and confirm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd-scripts**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by NelsonG6** [comment]
I'm having this issue too.

**Comment by juliakm** [comment]
@gladjoe I'm able to reproduce your issue in DevOps Server 2019 update 1. Since this may be a product bug, can you please post in our [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). That space is actively monitored by the product team. This issue queue is just for documentation.
