### ISSUE TITLE
I couldn't find how we can update an AZ module on Azure pipeline Agent. 

### ISSUE THREAD

**Issue by Kamyar5353** [MicrosoftDocs/azure-devops-docs#8729]
Given the fact that PowerShell modules are changing very often, sometimes there is a need to immediately get the latest version in the agent. I know that I can create a self-host agent and then use that for such cases, but if we have a kind of idea about the updating process or schedule, we may be able to get along with that. Also, if there is any way that we can update the Azure pipeline Agent, that would be great to know as well; I couldn't find any documentation about that. 

For example, the [current version of AZ](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md) in the pipeline agent is 3.8.0, but the latest is 4.3.0, this is a huge difference in between. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by paulhill** [comment]
I've been wrestling with Azure Powershell tasks that fail because the Az module versions on the Hosted agents are out of date. I can't make sense of the oddball combos of tasks and Powershell versions either. 
It would be nice if it was clearer how to get the required modules onto the hosted agents to run the latest commands.
In my case:
```
Add-AzWebAppAccessRestrictionRule -ResourceGroupName $ResourceGroupName -WebAppName $WebAppName -Name $Name -Priority $Priority -IpAddress "$IpAddress/32" -Scope CurrentUser
```
fails with "Unable to deserialize the response" because, via some dependency I don't quite understand, the Az command is using and older Az module < 5.1.0 and thus chokes on the AzureFrontDoor.Backend service tag in my firewall rules.
