### ISSUE TITLE
Update documentation for Pipelines Resource tag filters

### ISSUE THREAD

**Issue by BlairMcc** [MicrosoftDocs/azure-devops-docs#8743]
As per the latest sprint release notes here - 
https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-171-update#tag-filter-support-for-pipeline-resources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#resources-pipelines)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by t-l-k** [comment]
I'm confused - What are these "tags" - there is quite the confusing ambiguity around all the different artifacts/resources/repos&commits/builds/deployments/environments/pipelines/etc.... that could very well be "tagged".

The entire concept of tags could benefit from its own article so that they can be completely disambiguated between all the different usages.

I _think_ this is the tag filtering I'm looking for, but I'm not sure! I want to filter my pipeline trigger to only execute when the referenced pipeline run is tagged accordingly, I am assuming it is talking about "pipeline run" / "build" tags?

**Comment by juliakm** [comment]
You can learn more about tags in pipelines for resources in the [updated Resources article](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#evaluation-of-artifact-version).
