### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by JoseFMP** [MicrosoftDocs/azure-devops-docs#8761]
I followed the instructions as described in this document: https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops however, when issuing `go get` to get my Go library in a private Azure DevOps repository, the command line hangs indefinitely to then prompt:
```
fatal: unable to connect to dev.azure.com:
        dev.azure.com[0: 13.107.42.20]: errno=Connection timed out
        dev.azure.com[1: 2620:1ec:21::20]: errno=Network is unreachable
```

 The packege is not installed / available.

Any ideas on how to debug this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d650f-9948-2492-86d2-a5423ce043fb
* Version Independent ID: 9c95f2fb-44be-5dbb-be51-0c498ed692d2
* Content: [Go get support - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/go-get?view=azure-devops)
* Content Source: [docs/repos/git/go-get.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/go-get.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by msebolt** [comment]
@JoseFMP Thank you for the question and for contacting the product team [here](https://developercommunity.visualstudio.com/content/problem/1099148/go-get-from-private-azure-devops-repositories-not.html). 

Please see if you have access to [basic REST calls](https://docs.microsoft.com/rest/api/azure/devops/git/repositories/get?view=azure-devops-rest-4.1) to determine if this is a DevOps or Go issue, for DevOps connection issues see [troubleshooting connections](https://docs.microsoft.com/en-us/azure/devops/user-guide/troubleshoot-connection?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops) for additional help.

Otherwise, for further support options please refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
