### ISSUE TITLE
Several limitations

### ISSUE THREAD

**Issue by andrzejmartyna2** [MicrosoftDocs/azure-devops-docs#8763]
Today we needed to implement this scenario (rather a simple need):

Do automatic cleanup after a timeout of 15 days if a person who initiated the release didn't rejected (this is to support temporary environments deployed with first stages that someone uses and is automatically cleaned in additional stage if the person do not intentionally prevent it).

But the current implementation does not allow to:
- set approver to the person who initiated a release
- set timeout for automatic **approve** - there is only automatic rejection
- set timeouts for 15 days (current timeouts are waaaaay too short)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16b27fd8-df35-5e98-8c6e-2924f541a504
* Version Independent ID: 4c6e6300-2354-a9ec-0cf3-7f935ea268ce
* Content: [Understand approvals, gates, and checks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/approvals/index.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **shashban**

**Comment by msebolt** [comment]
@andrzejmartyna2  Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Or, for additional support options, please refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
