### ISSUE TITLE
Is it possible to include some default review comments?To track whether developer has done the required checks

### ISSUE THREAD

**Issue by krishnaGottuparthi** [MicrosoftDocs/azure-devops-docs#8769]
When a developer sends something for Code Review ,as a reviewer I want to know whether he/she has done some basic checks and want to take confirmation from him/her.
We need a template where we can define some questions and the developer who sends for code review should put comments and moves them to **Resolved** State
This way we don't miss some mandatory things which are required for development

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0197b69a-56ae-8cef-88e3-2165b07e23de
* Version Independent ID: 336f8906-e816-48ed-18ff-5ac7a8aa7a76
* Content: [Code review and feedback field reference - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/guidance-code-review-feedback-field-reference?view=azure-devops)
* Content Source: [docs/boards/work-items/guidance/guidance-code-review-feedback-field-reference.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/work-items/guidance/guidance-code-review-feedback-field-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@krishnaGottuparthi Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Or, for additional support options, please refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by KathrynEE** [comment]
@krishnaGottuparthi - The easiest way to do what you want is to to define a work item with the defaults you'd like to see, save the work item, and then choose the actions icon for the work item and choose Templates>Capture. The template you create will have all the defaults - including any content you've formatted in the Description field. If you want - you can add a custom rich-text field that is READ-ONLY and place your text in that field.
