### ISSUE TITLE
Required permission/role info on Azure AD

### ISSUE THREAD

**Issue by ragesh-urolime** [MicrosoftDocs/azure-devops-docs#8776]
Hi, Could you please add the least privilege role required in Azure side (in Azure AD and Subscription) in order to configure billing for Azure DevOps.

**Comment by msebolt** [comment]
@person Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.
