### ISSUE TITLE
Deployment for IIS Web App Manager and IIS Web App Deploy don't use standard IIS variables

### ISSUE THREAD

**Issue by Joebeazelman** [MicrosoftDocs/azure-devops-docs#8784]
Among many broken things about your product, Deployment for IIS Web App Manager and IIS Web Deploy tasks don't understand IIS variables such as %IISRoot%.  Why?  The point of using variables is to free us from hardcoding directories.  Instead, you make it necessary in order to get your turdware to work!

**Comment by msebolt** [comment]
@Joebeazelman Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Or, for additional support options, please refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
