### ISSUE TITLE
Add Bindings in IIS Web App Manage and IIS Web App Deploy bindings options suck!

### ISSUE THREAD

**Issue by Joebeazelman** [MicrosoftDocs/azure-devops-docs#8785]
I can't begin to tell you how terrible the deployment tasks are!  If you're lucky enough to find these options buried deep in hell, then you're pain isn't over.  The bindings section of the stage sets up http as expected, but for https it's useless.  I have to manually type in 443 for the SSL port number for it, but not for http?  What's going on here?  

The SSL certificate thumbprint forces you to find this mysterious number which is also called a fingerprint.  There are two of them.  One has 40 characters while the other has 256 characters. It would be nice if you clued us into exactly which one you wanted before cutting and pasting it!   Why use this long code instead of a friendly name that can be easily obtained?  Once you've copied the thumbprint you then have to manually remove all the spaces so that it's acceptable by the field. 

Clearly, you guys are too lazy to do quality work, so you leave it to your victims to do it for you.  After all, this is all free stuff and we should be grateful!

**Comment by msebolt** [comment]
@person Thank you for the feedback, we apologize for the issues you're experiencing.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Otherwise, please add a reference to the documentation in question and we can assign an author for review.
