### ISSUE TITLE
How do I authenticate to the Azure CLI for all tasks in a job?

### ISSUE THREAD

**Issue by atrauzzi** [MicrosoftDocs/azure-devops-docs#8786]
If I have scripts that want to call the Azure CLI outside of this task, how do I permanently authenticate the current job?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by msebolt** [comment]
@atrauzzi Thank you for the question.

Unfortunately the support options in this forum are limited to specific documentation examples only.

Please reference the documentation below, or use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit support from the product team.

Otherwise, for additional support options, please see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by atrauzzi** [comment]
Feature requests just take too long and the number of snags I encounter is just far too many.

**Comment by msebolt** [comment]
Sorry for the delay, you can refer to [Azure CLI service principals](https://docs.microsoft.com/cli/azure/create-an-azure-service-principal-azure-cli?view=azure-cli-latest) or use one of the support options listed above.

Closing this issue now.

**Comment by atrauzzi** [comment]
So casually dismissed it is.
