### ISSUE TITLE
Is `workingDirectory` not a control option?

### ISSUE THREAD

**Issue by LukeCarrier** [MicrosoftDocs/azure-devops-docs#8804]
e.g. for using the `Maven@3` task for performing build/package/test operations -- it's a little surprising that `workingDirectory` is neither an input for this task nor a control option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#controloptions)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@LukeCarrier Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.
