### ISSUE TITLE
Workspaces are always cleaned.

### ISSUE THREAD

**Issue by krischik** [MicrosoftDocs/azure-devops-docs#8818]
In the documentation it's stated that:

> “When you run a pipeline on a self-hosted agent, by default, none of the sub-directories are cleaned in between two consecutive runs.”

is not what I am observing. Looking at my build it seems that outputs are cleaned:

```
##[command]git version
git version 2.26.2
##[command]git config --get remote.origin.url
##[command]git clean -ffdx
Lösche Android/Build/
Lösche Appium/Build/
Lösche Appium_Test/Build/
Lösche Browser/Build/
Lösche iOS/Build/
##[command]git reset --hard HEAD
```

Needless to say that cleaning the workspace before running automated tests will make those tests fail.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67504b34-d64b-02a4-2e10-ab99f3b8cfe4
* Version Independent ID: 2cf63b2e-184b-7726-3b8a-d8baffd6fcce
* Content: [Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by steved0x** [comment]
@krischik Is it a YAML pipeline or designer pipeline? If it is a designer pipeline there is a setting in the UI for cleaning that may be overriding the default behavior, or in a YAML pipeline, if you edit the pipeline, and choose the context menu at the right->Triggers, you can get to some UI settings for a YAML pipeline and there is a clean setting under get sources.

If it is a YAML pipeline you can also specify a clean step in the checkout (I don't think it is that, but for completeness I am adding that here). 

Can you check to see if any of those might be the issue?

**Comment by msebolt** [comment]
Closing this now, please comment below if there further issues.

**Comment by krischik** [comment]
I was migrating from designer to YAML. In the designer had clean off and for YAML I had to restructure around the mandatory clean.

**Comment by steved0x** [comment]
@krischik I am glad you were able to work around it, and I am looping back to this issue since I am adding an update to workspace clean. Those options delete directories in the Initialize Job step in a job. In addition to workspace clean,  the UI setting for a YAML pipeline and checkout clean:true are the two options that add the git clean and git reset steps. The designer setting for YAML pipelines is kind of hidden, to get there:

Edit your pipeline, choose ..., and select Triggers.
![image](https://user-images.githubusercontent.com/1580889/97922917-32528480-1d2b-11eb-84ab-3625e6d1d4e7.png)

Then, Select YAML, Get sources, and configure your desired Clean setting. The default is false, but if it is true, all your checkout steps will get the git clean and git reset step, unless checkout clean is explicitly set to false in YAML.

![image](https://user-images.githubusercontent.com/1580889/97922985-50b88000-1d2b-11eb-8acb-05204d2b9cba.png)

I have made some updates to the article that clarify this and hopefully will avoid trouble for the next time. When that doc goes live it will close this issue, but please reply back if you are still getting git clean and git reset even with the UI setting to false and no checkout clean: true step in your YAML, and I will report it to the team as a bug.
