### ISSUE TITLE
Please provide the reasoning behind the percentage to expect for the season, features, 3-sprint plan and sprint

### ISSUE THREAD

**Issue by mbalke** [MicrosoftDocs/azure-devops-docs#8826]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
@mbalke Thank you for the question.

This will need to be addressed by the product team, please use either **Report a problem** or **Suggest a feature** in [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

Otherwise, if you can provide a reference to documentation we can assign an author for further review.
