### ISSUE TITLE
Needs clarity on how to use the copied code from this section.

### ISSUE THREAD

**Issue by RohitSarangi-MS** [MicrosoftDocs/azure-devops-docs#8854]
The following anchor link has some code provided but there is no instruction on how to use it, where to use it.

https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/faq-user-and-permissions-management.md#q-how-do-i-find-the-organization-owner

Please describe, how to use the copied code from this section.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34a09840-ed5d-8a72-cb80-20bac219e065
* Version Independent ID: 8a686d5e-af9f-e269-2603-f122ab964d86
* Content: [Troubleshoot user and permissions management - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/faq-user-and-permissions-management?view=azure-devops)
* Content Source: [docs/organizations/accounts/faq-user-and-permissions-management.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/accounts/faq-user-and-permissions-management.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @RohitSarangi-MS, Thanks for reaching out. The content you're speaking of in the answer to "How do I find the organization owner?" isn't code for copying, it's actually markdown to display a few images, for which I've just created a pull request. They were indented too far, which is why the images weren't displaying. This update should be live shortly. Thank you!
