### ISSUE TITLE
YAML Deployment Job unable to use Deployment Group or Deployment Pool?

### ISSUE THREAD

**Issue by FilBot3** [MicrosoftDocs/azure-devops-docs#8876]
I am trying to get a Deployment Job to work in a YAML pipeline. I can use an Agent Pool, but I am unable to use Deployment Groups as specified in the documentation. However, can I use the Deployment Pool, or is that the same kind of blocker?

Is the plan for YAML Pipelines that do Deployment Jobs to migrate from Deployment Pools and Deployment Groups to Agent Pools and use the various strategies like rolling as specified here?

* https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#rolling-deployment-strategy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45bcaa19-4ee9-55c5-9b1c-92f8d0f2dfa7
* Version Independent ID: d9424c8a-571d-0f48-e8f7-4bb7a9544efb
* Content: [Deployment group jobs in Build and Release - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-group-phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/deployment-group-phases.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-group-phases.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@FilBot3 Thank you for the question, apologies for the delay.

Is there a specific documentation example you are having issues with?

If so, please cite the example below, otherwise we recommend moving the issue to one of the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
