### ISSUE TITLE
Scheduled run parameters?

### ISSUE THREAD

**Issue by KimShepherdVibrato** [MicrosoftDocs/azure-devops-docs#8883]
Is there any way of adding a schedule to a pipeline with runtime parameters to use something other than the defaults?

As a workaround I can create a seperate pipeline using the same templates, but I would love to see the ability to specify different runtime parameters on different schedules if it is not currently possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea2c851-bd1e-cddc-b4d0-e9f4112b8565
* Version Independent ID: 07c23fdd-14b5-985b-1c63-3f26f3a216ad
* Content: [Configure schedules to run pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#limits-on-the-number-of-scheduled-runs)
* Content Source: [docs/pipelines/process/scheduled-triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/scheduled-triggers.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by nikoudel** [comment]
Any news on this one? This issue makes runtime parameters pretty much useless because running pipelines manually is only needed during testing the pipeline code.

**Comment by msebolt** [comment]
@KimShepherdVibrato Thank you for the question.

Please refer to the issues posted [here](https://stackoverflow.com/questions/59893621/azure-devops-build-parameters-for-scheduled-builds) and under https://github.com/microsoft/azure-pipelines-yaml/issues/39.

Otherwise, this will likely need to be addressed by the product team in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) (see [here](https://developercommunity.visualstudio.com/content/problem/975368/how-to-make-values-dynamic-for-parameters.html) for a similar request).

**Comment by martingalvan-nordic** [comment]
I'm surprised that this feature is missing, since it's quite essential. Are there any plans to introduce this at some point?

**Comment by dimtix** [comment]
I am missing this feature too

**Comment by AlfredWang01** [comment]
+1

**Comment by nkoudelia** [comment]
The ticket is closed, guys... no point in whining.
