### ISSUE TITLE
Authenticate feed option name

### ISSUE THREAD

**Issue by snate** [MicrosoftDocs/azure-devops-docs#8885]
Hi!

I was browsing the documentation of the [Maven Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops) and I've noticed something confusing.

In the YAML snippet I see the option to authenticate to a feed is called `mavenAuthenticateFeed`, but in the arguments list it is called `mavenFeedAuthenticate`. Which one of the two is correct?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by steved0x** [comment]
They are both correct, due to something called [task input aliases](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/yaml-tasks.md), by which a single input can have more than one name.

Our new task reference provides the names (and aliases when present) for all task inputs, you can see the new page for the Maven task here: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/maven-v3?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
