### ISSUE TITLE
Is the extensions development documentation being deleted?

### ISSUE THREAD

**Issue by lolpez** [MicrosoftDocs/azure-devops-docs#8889]
I was developing an Azure DevOps extension and I had saved plenty of helpful URL pages of how to develop it. However most of them has been deleted recently, and they are not redirecting to another page related to it or to a new version of the documentation.

Here are some of them:

[API Work item Tracking rest client](https://docs.microsoft.com/en-us/previous-versions/azure/devops/extend/reference/client/api/TFS/WorkItemTracking/RestClient/WorkItemTrackingHttpClient2_1?view=azure-devops)

[Target for hubs in manifest](https://docs.microsoft.com/en-us/previous-versions/azure/devops/extend/reference/targets/overview?view=azure-devops#targetable-hub-groups)

**Comment by msebolt** [comment]
@lolpez  Thank you for the feedback and apologies for the redirects.

Documentation redirects are generally added to the repo's [redirection.json](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/.openpublishing.redirection.json) file.  Please note that to view this file, you may need to join **Microsoft Docs** with your GitHub account, see [becoming a contributor](https://docs.microsoft.com/contribute).

Otherwise, please refer to [work item tracking](https://docs.microsoft.com/rest/api/azure/devops/wit/) and [add a hub](https://docs.microsoft.com/azure/devops/extend/develop/add-hub) for further information.
