### ISSUE TITLE
Does 'downloadPath' creates folder with same name as artifact name

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/azure-devops-docs#8941]
Hi, guys. I found that 

`downloadPath: '$(Pipeline.Workspace)\MyArts'`

creates folder _work\1\MyArts\MyArts instead of just downloading it to _work\1\MyArts.
Is it feature or bug?

For example 'Download Pipeline' task do not create such folder.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@VerdonTrigance Thank you for the feedback.

Since this question is more product-related, please direct this issue to the product team in the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo.

If there are any concerns with the documentation please comment below.
