### ISSUE TITLE
No clone link

### ISSUE THREAD

**Issue by brycehoopes-summit** [MicrosoftDocs/azure-devops-docs#8963]
[Enter feedback here]

The page refers to a Clone link in the upper right.  It would be nice to show a picture of exactly where that link is expected to be, and perhaps what would cause that link to not appear (wrong type of user perhaps)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4e7f5a-08f4-5c12-cb6d-424d6e5dadaa
* Version Independent ID: e317a392-cb78-7fcc-fcf8-2cecaa9e6580
* Content: [Code with Git - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/code-with-git?view=azure-devops)
* Content Source: [docs/user-guide/code-with-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/user-guide/code-with-git.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@brycehoopes-summit Thank you for the feedback.

This issue has previously been reported under https://github.com/MicrosoftDocs/azure-devops-docs/issues/8701, and is likely due to unassigned permissions.

For addtional configuration help, please try the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
