### ISSUE TITLE
Resource webhook Trigger Issues - missing UI

### ISSUE THREAD

**Issue by inuvano-labs** [MicrosoftDocs/azure-devops-docs#8982]
In this section of the article https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#yaml-resource-trigger-issues-support-and-traceability it mentions about a Trigger Issues UI - I am unable to find this in the pipeline definition page.

Has this UI been rolled out generally?

**Comment by msebolt** [comment]
@inuvano-labs Thank you for the question.

On changes to the documentation, please comment below, otherwise new product features and enhancements can be found via the [features timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline).

For specific suggestions or product feedback, please use the **Azure DevOps** [community](https://developercommunity.visualstudio.com/spaces/21/index.html).
