### ISSUE TITLE
How to configure notification for YAML pipeline if stage is completed

### ISSUE THREAD

**Issue by slawekww** [MicrosoftDocs/azure-devops-docs#8983]
For UI release pipelines, once stage is completed, email notification is sent.
How to configure the same rule for YAML pipeline?

Now email is sent only if all stages are completed.
Email is not sent if some stages wait for Environment approval as release (DefinitionID) is not completed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c845a7-d230-c0b0-e68c-174246f866bc
* Version Independent ID: a773099c-3af5-dc66-b303-335ccf9875dc
* Content: [Manage notifications for a team or group - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/manage-team-group-notifications?view=azure-devops&tabs=new-nav&viewFallbackFrom=vsts)
* Content Source: [docs/notifications/manage-team-group-notifications.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/notifications/manage-team-group-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by dmcweeney** [comment]
+1 for this it is definitely a big gap. 
Also the current email lists the jobs completed but does not include the stage names that the jobs belong to.
Note jobs are not ordered correctly.

**Comment by msebolt** [comment]
@slawekww  Thank you for the feedback.

Please refer to [approval checks](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass) as the latest feature released to address this problem.  The product team's response on this can be found [here](https://developercommunity.visualstudio.com/idea/677633/approval-check-notifications-in-yaml-pipelines.html) in the **Azure DevOps** community.

To solicit additional feedback from the team, please start a ticket [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

Otherwise, please try the following options for direct support:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by slawekww** [comment]
@msebolt I use approval check. 
What about notification to users if stage is completed even if no approvals are required?

**Comment by msebolt** [comment]
@slawekww For more complex issues, users are required to utilize the REST API such as [update approval](https://docs.microsoft.com/rest/api/azure/devops/release/approvals/update?view=azure-devops-rest-6.0) and [create notification](https://docs.microsoft.com/rest/api/azure/devops/hooks/notifications/create?view=azure-devops-rest-6.0).

To add more to the existing UI you would need to solicit feedback from the product team.

**Comment by slawekww** [comment]
@msebolt For sure, for any case REST API could be used. 
My feedback is about discrepancy between Release UI pipelines and new YAML pipelines - notifications are not working on stage level on YAML pipeline. To say more, it is not possible to configure them. Only custom step using REST API could do it.

**Comment by msebolt** [comment]
Understood, unfortunately issues in this repo can only cover documentation concerns.

As for product gaps and/or other related issues please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Closing this issue now.
