### ISSUE TITLE
Full access to code

### ISSUE THREAD

**Issue by pyce-lb** [MicrosoftDocs/azure-devops-docs#9010]
Why is it necessary to give the app **full** access to code? Shouldn't **read** access be enough?
(I could not find a better platform to ask this, hope it is fine here.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43aa8c60-c25d-535b-2166-f51fa9f171c6
* Version Independent ID: 8890a537-9eda-5606-4be4-580bdc9e8269
* Content: [Azure Repos with Microsoft Teams - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/integrations/repos-teams?view=azure-devops)
* Content Source: [docs/repos/integrations/repos-teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/integrations/repos-teams.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @divya
* Microsoft Alias: **divais**

**Comment by msebolt** [comment]
@pyce-lb Thank you for the feedback.

This is a good question, though an issue with the product itself, rather than with the documentation.

Please use the [**Azure DevOps** community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue for additional feedback from the product team.

Or, for additional support options, please refer to [support](https://azure.microsoft.com/support/devops/)

**Comment by pyce-lb** [comment]
@msebolt thank you for looking into this.
I created a feature suggestion [here](https://developercommunity.visualstudio.com/idea/1262229/read-only-access-to-code-for-the-azure-repos-for-m.html).
