### ISSUE TITLE
macOS in Environment

### ISSUE THREAD

**Issue by raphaelbraun** [MicrosoftDocs/azure-devops-docs#9049]
[Enter feedback here]
Is there a way to create an environment using macOS instead of Windows or Linux?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@raphaelbraun We're sorry, but unfortunately this is not yet supported.

Please try [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21) to solicit feedback for addtional feature sets from the product team.

Otherwise for the traditional macOS feature set, please refer to [macOS agents](https://docs.microsoft.com/azure/devops/pipelines/agents/v2-osx).

**Comment by raphaelbraun** [comment]
Thanks @msebolt
