### ISSUE TITLE
Is looping through a variable array possible within a pipeline?

### ISSUE THREAD

**Issue by ranjitk92** [MicrosoftDocs/azure-devops-docs#9068]
I have a text file with name1 and name2 in it. 

I also have a Powershell script made `$clientvariable = Get-Content -Path {FilePath}/{File};Write-Host "vso[task.setvariable variable=clientname]$clientvariable`

The variable clientname has values name1 and name2 associated to it after running the script.

In my pipeline is it possible to use clientname = name1, pass that variable value through for overriding parameters in my ARM template, then loop back and run clientname = name2 and repeat?

I am trying to essentially take each name and create resources for it with a certain naming convention. My ARM template can pass through a single name fine and create resources. Once I include a second name in the array the pipeline run returns an empty key value error and this is most likely due to the fact that clientname = name1 name2 as a concatenation.

**Comment by andyflatt** [comment]
+1

**Comment by msebolt** [comment]
@ranjitk92 Thank you for the question.

Please see if [this post](https://stackoverflow.com/questions/59387555/using-for-loop-in-azure-pipeline-jobs) or [this post](https://stackoverflow.com/questions/62835740/loops-and-arrays-in-azure-devops-pipelines) can help offer solutions for variable looping.

Otherwise, for addional support, please move this issue to one of the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
