### ISSUE TITLE
Are publishing Screenshots possible in the Pipeline for JUnit or NUnit?

### ISSUE THREAD

**Issue by j-hudgins** [MicrosoftDocs/azure-devops-docs#9072]
Hi. 
I am working on a test pipeline for my automation tests written in Selenium with NUnit Framework. I wrote in the tests to take screenshots after each assertion. I am not able to find out how to publish those screenshots into a location in the Pipeline? It seems that there is documentation for MSTest but that this is not possible for NUnit. I can't imagine that to be the case. 

Can you please confirm for me if capturing screenshots of failed tests or any test results for that matter is possible when using NUnit or JUnit?

Best Regards, 
Jessica Hudgins

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764b5c96-75f0-09dd-e9a9-d873743b389f
* Version Independent ID: 5007d9f8-a540-1866-a8e2-888231ff7c7d
* Content: [Collect screenshots, video, logs, and attachments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/collect-screenshots-and-video?view=azure-devops#help-and-support)
* Content Source: [docs/pipelines/test/collect-screenshots-and-video.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/collect-screenshots-and-video.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@j-hudgins Thank you for the question.

Currently this can be achieved through Selenium and/or C# (for NUnit).  Please refer to the following post:

- [Add screenshot in Selenium](https://stackoverflow.com/questions/48427012/how-can-i-add-ui-test-screenshot-to-tfs-test-report-as-an-attachment)
- [NUnit C# attachments](https://stackoverflow.com/questions/60389685/nunit-how-to-attach-screenshot-to-test-attachments-in-azure-pipeline)
- [Add screenshot in C#](https://stackoverflow.com/questions/33490397/add-a-failure-screenshot-to-an-nunit-test)

For JUnit, please refer to:

- [Add screenshots to JUnit](https://stackoverflow.com/questions/59511868/can-we-add-screenshots-as-an-attachment-to-the-test-result-in-azure-pipeline)
- [Show Jasmine screenshots](https://stackoverflow.com/questions/56734331/show-jasmine-screenshots-in-azure-devops-test-results)

Otherwise for addtioinal options, please try one of the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
