### ISSUE TITLE
Deploying to SQL MI 

### ISSUE THREAD

**Issue by pingyin97** [MicrosoftDocs/azure-devops-docs#9087]
Is it possible to perform this same task but to a SQL MI database or any other alternatives? I couldn't find any options to do this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd85890a-ccba-8697-b406-b662aabeb27f
* Version Independent ID: a1d371df-c0a0-1cd6-37f8-4b60913a2e97
* Content: [Deploy to Azure SQL Database - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/targets/azure-sqldb.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/targets/azure-sqldb.md)
* Product: **devops**
* Technology: **devops-cicd-targets**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@pingyin97 Thank you for the question.

Please refer to [this post](https://developercommunity.visualstudio.com/content/problem/868683/couldnt-deploy-dacpac-to-azure-sql-server-managed.html) on using DACPAC.  Otherwise, this may require using a custom agent as mentioned [here](https://stackoverflow.com/questions/52962697/azure-devops-deployment-to-azure-sql-managed-database).

For additional options, please refer to the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
