### ISSUE TITLE
Is action required or not?

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/azure-devops-docs#9109]
The action argument is listed as both required and having a default value. If you have to specify it there is no default, if you can leave it to be a default it isn't required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
That makes a good point. The new task reference we just published is autogenerated from the task source, and lists required status for inputs, but also all available allowed values for inputs that provide them, and default values when provided. Because it has a default you could omit it in your YAML: pipeline and it would take the default value.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-resource-group-deployment-v2?view=azure-pipelines&viewFallbackFrom=azure-devops

The action parameter is required and has a default value of 'Create Or Update Resource Group'.

https://github.com/microsoft/azure-pipelines-tasks/blob/fa2b8640460975baaf165c01969caa2a699ba53b/Tasks/AzureResourceGroupDeploymentV2/task.json#L61

I agree that the required could be set to false in the source code for this task input with no change in behavior.
