### ISSUE TITLE
jdkDestinationDirectory

### ISSUE THREAD

**Issue by daurelio-deloitte** [MicrosoftDocs/azure-devops-docs#9176]
[Enter feedback here]
The `jdkDestinationDirectory` isn't populated (or available in the form) when adding the task via the UI Pipeline Editor.
This results in deleting the repository contents from the directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182d85e3-f124-b440-78cb-2b1c52617ae0
* Version Independent ID: 26372d15-3e1a-0e8b-f5bb-abf0165f6480
* Content: [Java Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/java-tool-installer.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/tool/java-tool-installer.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@daurelio-deloitte  Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

For issues with the task's functionality, please move this issue to the [azure-pipelines-tasks](https://github.com/Microsoft/azure-pipelines-tasks/issues) repo.
