### ISSUE TITLE
This documentation is inconsistent with https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#authentication

### ISSUE THREAD

**Issue by kmcneelyshaw** [MicrosoftDocs/azure-devops-docs#9177]
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops#download-and-configure-the-agent the agent says "Log on to the machine using the account for which you've prepared permissions as explained above."

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#authentication says "To register an agent, you need to be a member of the administrator role in the agent pool. ... In addition, you must be a local administrator on the server in order to configure the agent."

From this document, I would expect that if I created a PAT while authenticated to Azure DevOps with my CORPORATION\my.username identity, I would have to be able to log in to my Self-hosted agent as CORPORATION\my.username.  My self-hosted agent is itself in Azure, and is not configured to be on the CORPORATION domain.  Instead, I authenticate to this VM as OTHER_DOMAIN\my_user_name .  If the PAT is the authentication used for the initial communication with ADO, why would I need to log in as any **particular** administrator of my self-hosted agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425b68d1-4ba0-5657-4e09-f3aac361ea09
* Version Independent ID: f8044e9d-98e2-6e00-b513-a91e772b2ef8
* Content: [Deploy an Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@kmcneelyshaw Thank you for the feedback.

The document describes the use of two accounts needed in the agent deployment process:

1.  The agent user, in your case, **OTHER_DOMAIN\my_user_name**
1.  The agent pool administrator, in your case, **CORPORATION\my.username**

Both statements `Log on to the machine using the account for which you've prepared permissions as explained above.` and `In addition, you must be a local administrator on the server in order to configure the agent.` are ambiguous and should be edited to reflect which user above the statement is referring to.

Assigning this to the author for further review.

**Comment by kmcneelyshaw** [comment]
@msebolt @steved0x any updates on this issue?  Today I had occasion to revisit the pending work that led me to read this documentation in the first place.  From my quick search it appears neither document has been updated.

Thank you.

**Comment by kmcneelyshaw** [comment]
@steved0x @msebolt has this been looked at in two years? Unfortunately, I do not have the domain knowledge to submit a pull request.
