### ISSUE TITLE
How do I rollback Azure Boards to a point in time?

### ISSUE THREAD

**Issue by successhawk** [MicrosoftDocs/azure-devops-docs#9181]
Regarding this [section](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops#mistakes-happen): 

> Mistakes happen
> To protect against accidental deletion of data, either by our **customers** or by our operation team, we also take point-in-time backups of both the Azure blob and the SQL databases.

How do customers initiate a point in time recovery?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52eb9f91-b952-afb6-6d17-d7092f46440d
* Version Independent ID: bb9113a5-8b8b-b20b-9c6f-09a57f53ba7c
* Content: [Azure DevOps - Data Protection - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/data-protection?view=azure-devops)
* Content Source: [docs/organizations/security/data-protection.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/security/data-protection.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by msebolt** [comment]
@successhawk Thank you for the question.

For Azure blob, please refer to [Point-in-time restore](https://docs.microsoft.com/azure/storage/blobs/point-in-time-restore-manage?tabs=portal).

For Azure SQL database, please refer to [Azure SQL database recovery](https://docs.microsoft.com/azure/azure-sql/database/recovery-using-backups#point-in-time-restore).

Otherwise, for additional help, please refer to one of the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
