### ISSUE TITLE
Bulk add Steps Test Case in work items with Excel

### ISSUE THREAD

**Issue by PauloRobert** [MicrosoftDocs/azure-devops-docs#9182]
I'm using the excel plugin, but I can't load the **steps**, just the other information.

Is it possible to upload the test case steps to Azure, with Excel?

-

**Comment by msebolt** [comment]
@PauloRobert Thank you for the question.

Please see if [CSV imports](https://docs.microsoft.com/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops) or [this post](https://stackoverflow.com/questions/55136232/how-to-import-test-cases-from-excel-to-vsts) can help resolve the issue.

Otherwise, for additional feedback, please contact the product team in the **Azure DevOps** [community](https://developercommunity.visualstudio.com/spaces/21/index.html), or see a similar post [here](https://developercommunity.visualstudio.com/idea/404717/upload-test-cases-to-azure-devops-via-excel.html).

For additional options, please try one of the following support channels:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
