### ISSUE TITLE
Updating variable in Azure DevOps Variable group from Pipeline

### ISSUE THREAD

**Issue by ayadav4** [MicrosoftDocs/azure-devops-docs#9192]
Hi Team,

I am retrieving new consumer key  from SFDC sandbox. and trying to update variable group with this command.

npx sfdx sfpowerkit:azpipelines:updatevariable -u $(azure_devops_user) -p $(pat) -k env.consumerkey -v $(newconsumerkey)  -i $(variable_group_id) -o xx.com  -g xxxx

I am getting below error.

Warning: sfpowerkit:azpipelines:updatevariable is not a sfdx command.

**Comment by msebolt** [comment]
@ayadav4 Thank you for the question.

Please note the support options here are limited to documentation examples.

Otherwise, please move this issue to one of the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
