### ISSUE TITLE
The pipeline environment option

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-devops-docs#9199]
Is there a way to deploy an Azure VM Extension that enables the VM as an agent as part of a Azure Pipelines Environment?
As Deployment Groups are not an option with yaml pipelines, we need to enable the target VM as part of a Pipeline Environment. 

One way the documentation describes is to kick off an agent through an install script that needs to be run locally on the virtual machine.

Ideally we would be using the same or comparable extension as we are currently using for deployment groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fa0c14-9937-41bc-cc34-179edb379083
* Version Independent ID: 10fe3600-21a5-12db-5e21-5ade3a8fa484
* Content: [Provision agents for deployment groups - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=azure-devops)
* Content Source: [docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@cveld Thank you for the feedback.

You'll need to run the [environment's registration script ](https://docs.microsoft.com/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops) as part of an [Azure Custom script extension](https://docs.microsoft.com/azure/virtual-machines/extensions/custom-script-linux) in order to join an agent to the pipeline.

To make this task easier with deployment groups in YAML, please refer to [this post](https://developercommunity.visualstudio.com/idea/665340/use-deployment-groups-in-a-multi-stage-yaml-file.html) for feedback from the product team.

For additional help, please refer to one of the following support channels:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
