### ISSUE TITLE
Deployment Job -- do these support workspace.clean?

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/azure-devops-docs#9201]
Do depoyment jobs support workspace.clean?  It looks like by default, they will continue to pile up downloaded artifacts, which is different from the classic release jobs.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aeeaace-1c5b-a51b-e41f-f25b806155b8
* Version Independent ID: fd7ff690-b2e4-41c7-a342-e528b911c6e1
* Content: [Deployment jobs - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops)
* Content Source: [docs/pipelines/process/deployment-jobs.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/deployment-jobs.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@cmeyertons Thank you for the question.

You can use [traditional jobs](https://docs.microsoft.com/azure/devops/pipelines/process/phases) alongside deployment jobs, which support [workspace clean](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#workspace) functionality.

For similar issues that have been raised in the **Azure DevOps** [community](https://developercommunity.visualstudio.com/spaces/21/index.html), please see [here](https://developercommunity.visualstudio.com/content/problem/614016/there-is-no-way-how-to-clean-workspace-in-deployme.html) and [here](https://developercommunity.visualstudio.com/content/problem/959548/yaml-pipeline-deployment-job-workspace-clean-all-d.html).

Otherwise for additional help, please refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by cmeyertons** [comment]
Based on your response and the content of those issues, it looks like they do. 

Can we add that to the documentation on this page?

**Comment by juliakm** [comment]
@cmeyertons  I've added `workspace` to the schema.
