### ISSUE TITLE
Sample OData query code does not work for Feature Progress Rollup sample report

### ISSUE THREAD

**Issue by cccinkc** [MicrosoftDocs/azure-devops-docs#9217]
The OData code at the top of the page does not seem to work. When I used it in Power Query, it threw the following error:

DataSource.Error: OData: The property 'TotalEffort' does not exist on type 'Microsoft.VisualStudio.Services.Analytics.Model.WorkItem'. Make sure to only use property names that are defined by the type or mark the type as open type.
Details:
    DataSourceKind=OData
    DataSourcePath=https://analytics.dev.azure.com/clement0621/Marine%20Software/_odata/v3.0-preview/WorkItems

I am set up with an inherited Scrum process rather than Agile, so I am dealing with Product Backlog Items and Effort rather than User Stories and Story Points and have adapted the sample query code accordingly (thus, 'TotalEffort'). For what it's worth, the problem appears to happen anytime there is an aggregation happening inside of an expand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8719e400-4445-59a4-c68e-628243710c36
* Version Independent ID: d6a76999-81c0-33cb-47a5-9ca4d8be80c3
* Content: [Feature Progress rollup sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-featureprogress?view=azure-devops&tabs=odata#feedback)
* Content Source: [docs/report/powerbi/sample-boards-featureprogress.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/sample-boards-featureprogress.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by ksmis-gh** [comment]
@cccinkc Can you try pasting the whole query, and maybe try a derivative of the following (adjust the filters as per your liking). The column over which one sums is 'Effort' instead of 'TotalEffort', you can rename it afterwards. It seems to work for me.

https://analytics.dev.azure.com/{organization}/{project}/_odata/v3.0-preview/WorkItems?
$filter=(WorkItemType eq 'Product Backlog Item' and State ne 'Cut' and endswith(Area/AreaPath,'{areapath}'))
&$select=WorkItemId,Title,WorkItemType,State,AreaSK
&$expand=Descendants($apply=filter(WorkItemType eq 'Bug')
/groupby((StateCategory), 
aggregate(Effort with sum as TotalEffort)
))

**Comment by cccinkc** [comment]
@ksmis-gh Naming the summation column "Effort" instead of "TotalEffort" seemed to take care of things. Thanks!

**Comment by ksmis-gh** [comment]
@cccinkc Glad to hear it. Can you close the issue as well? It seems i don't have permissions to
