### ISSUE TITLE
Is this curl command correct? Maybe a little more detail is needed

### ISSUE THREAD

**Issue by dwhiteddsoft** [MicrosoftDocs/azure-devops-docs#9227]
In the curl command you have listed, the first part is written as: 
curl -u {username}[:{personalaccesstoken}]

The problem becomes is this is a bit ambiguous. Do I leave the curly braces? What about the brackets? If they aren't needed, why are they there? I can tell you on OSX the only way I was able to get it to work was to simply use
curl -u username:personalaccesstoken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77b02d80-9d76-e517-45a2-8d8a550fd8d4
* Version Independent ID: c76f14b4-4730-6600-8983-b61779d5f75d
* Content: [Get started with the REST APIs for Azure DevOps and TFS - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/how-to/call-rest-api?view=azure-devops#versions)
* Content Source: [docs/integrate/how-to/call-rest-api.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/integrate/how-to/call-rest-api.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for reaching out, @dwhiteddsoft . I've reached out to the PM for confirmation and will be in touch. Thanks!

**Comment by chcomley** [comment]
Hi @dwhiteddsoft, This issue is from a year ago, but better late than never, I suppose. You were absolutely correct in using the command without the curly braces and square brackets. The curly braces are there just to show where your input is needed, replacing the curly braces, and it looks like the square brackets must have accidentally been added somehow. They don't belong in the command at all. I've made an update to the article, based on your feedback, so thanks so much.
