### ISSUE TITLE
WinRM SQL Server DB Deployment task - Argument names

### ISSUE THREAD

**Issue by MizardX** [MicrosoftDocs/azure-devops-docs#9228]
The name of the arguments are not included in the argument description.
"taskType" in yaml is documented as "Deploy SQL Using".
Both "additionalArguments" and "additionalArgumentsSql" is documented as "Additional Arguments".
The reader must guess based on the order which argument is intended. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b7e6f9e-5aae-51b7-b237-282d0af40018
* Version Independent ID: 33966728-39bc-37f6-af71-e90564fb7193
* Content: [WinRM SQL Server DB Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-dacpac-deployment-on-machine-group?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/sql-dacpac-deployment-on-machine-group.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/sql-dacpac-deployment-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/sql-dacpac-deployment-on-machine-group-v0?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
