### ISSUE TITLE
Please indicate how the totals get automatically saved to the Parent Work Item

### ISSUE THREAD

**Issue by salipour1105** [MicrosoftDocs/azure-devops-docs#9238]
When adding sub tasks to a parent work item, the subtasks with the original estimates are totaled in the parent and show in the Sprint board. However, when you open the parent work item, the original estimates are not available. How are the subtask estimates totaled automatically and included in the parent work item?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6ed3f5-b5a4-10a9-f823-8591da27096d
* Version Independent ID: 1e955842-c971-2e15-777f-bbb95096698a
* Content: [Support rollup of work and other fields - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/support-rollup-of-work-and-other-fields?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/reference/xml/support-rollup-of-work-and-other-fields.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/reference/xml/support-rollup-of-work-and-other-fields.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@salipour1105 - The rollup of estimates is a feature of the Sprint backlog. There is no function that populates that value into the parent work item. You may find a solution in the [Marketplace Extensions](https://marketplace.visualstudio.com/search?target=AzureDevOps&category=Azure%20Boards&sortBy=Installs), such as [VSTS Rollup](https://marketplace.visualstudio.com/items?itemName=canarysautomationspvtltd.vstsrollup&ssr=false#review-details) or [Aggregator CLI](https://marketplace.visualstudio.com/items?itemName=tfsaggregatorteam.aggregator-cli&ssr=false#overview).  Otherwise, you can suggest a feature enhancement on our [Developer Community page](https://developercommunity.visualstudio.com/idea/365423/support-calculated-fields-in-tfs.html).
