### ISSUE TITLE
Interface error in pipeline library

### ISSUE THREAD

**Issue by rfs-sergiodouglas** [MicrosoftDocs/azure-devops-docs#9270]
There is no field to edit the description of a secure file in the pipiline library
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140dcb9a-2ed0-11d5-064b-068f863ed97f
* Version Independent ID: 672d2aa3-cf0d-9207-c97c-e2eba14506b7
* Content: [Secure files for Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops)
* Content Source: [docs/pipelines/library/secure-files.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/library/secure-files.md)
* Product: **devops**
* Technology: **devops-cicd-library**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@rfs-sergiodouglas Thank you for the feedback.

Unfortunately this is still a known issue, please refer to https://github.com/MicrosoftDocs/azure-devops-docs/issues/791 or [this post](https://stackoverflow.com/questions/62983252/how-do-i-set-the-description-of-an-azure-pipeline-secure-file) for further information.

Otherwise you can use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit additional feedback from the product team.
