### ISSUE TITLE
I wish to know if exposing code in public projects can be whitelisted

### ISSUE THREAD

**Issue by Eldar1205** [MicrosoftDocs/azure-devops-docs#9274]
[Enter feedback here]
Hi, I wish to know if code in public projects can be exposed on need basis since we want the project itself to be public and accessible to everyone, in particular Wikis and such, but the code we want to keep hidden. Is this possible to have this fine grained control?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cd88fb-ff0f-5c7a-4c69-e3bb850836b4
* Version Independent ID: d29e4f48-37d9-c581-0fc5-91cc6829df1b
* Content: [Browse repos, files, branches, pushes, commits, pull requests - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/public/browse-code-public?view=azure-devops)
* Content Source: [docs/organizations/public/browse-code-public.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/organizations/public/browse-code-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Eldar1205 Thank you for the question.

For now you are required to use [public projects](https://docs.microsoft.com/azure/devops/organizations/public/about-public-projects), but this issue is currently under consideration with the product team.  

Please refer to [this post](https://developercommunity.visualstudio.com/idea/447468/public-facing-wiki-for-private-projects.html) for more information.
