### ISSUE TITLE
Not able to find TestPlanHttpClient in .Net Standard and .NET Core projects

### ISSUE THREAD

**Issue by jereesh** [MicrosoftDocs/azure-devops-docs#9324]
Even though documentation says there is a class TestPlanHttpClient  in the AzureDevops Client SDK it seems missing in .Net standard 2.0 and .Net Core 3.1 Libraries . Tried adding the latest version of the nuget which seems to contain this class Microsoft.TeamFoundation.Server.Client (16.153.0). It is available if the target is full framework. There is an issue reported earlier [https://github.com/MicrosoftDocs/azure-devops-docs/issues/5710] on this and the provider answer is it is fixed , But It seems missing.

**Comment by msebolt** [comment]
@jereesh Thank you for the feedback and apologies for the issues.

Please see [this post](https://developercommunity.visualstudio.com/idea/1220091/need-testplanhttpclient-in-microsoftteamfoundation.html) so that the product team can properly prioritize the issue.

In the meantime, you'll need to use a [standard web API client](https://docs.microsoft.com/dotnet/csharp/tutorials/console-webapiclient) and manually call the [test API](https://docs.microsoft.com/rest/api/azure/devops/test/?view=azure-devops-rest-6.0).
