### ISSUE TITLE
Publishing NuGet packages via REST API?

### ISSUE THREAD

**Issue by DM2489** [MicrosoftDocs/azure-devops-docs#9325]
Is this really the only way to publish NuGet packages up to an Azure Artifact feed? I've scoured the DevOps Docs (https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/nuget/update%20package%20version?view=azure-devops-rest-6.1) and there is functionailty to get, update and delete NuGet packages, but no REST API for creating new packages or even publishing version increments for existing packages.

I was expecting to be able to throw an uploaded file at the REST endpoints using a PAT without running in to something like this!

Why is this not possible? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f386bad4-494d-fcd3-b3f3-44a33601e866
* Version Independent ID: c1fe07ab-8092-26b7-f3f0-a3fce718da51
* Content: [Publish a NuGet package from the command line - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/publish?view=azure-devops)
* Content Source: [docs/artifacts/nuget/publish.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/nuget/publish.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@DM2489  Thank you for the feedback and apologies for the inconvenience.

Unfortunately this feature is not yet supported.  To request this added, please use **Report a problem** or **Suggest a feature** in the [community](https://developercommunity.visualstudio.com/spaces/21/index.html) for additional feedback from the product team.

In the meantime, you can refer to [this post](https://stackoverflow.com/questions/58271605/vsts-nuget-publishing-using-rest) for possible workarounds, otherwise you are limited to something like a call to [Run Pipeline](https://docs.microsoft.com/rest/api/azure/devops/pipelines/runs/run%20pipeline?view=azure-devops-rest-6.0) API using the basic [Nuget](https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget?view=azure-devops) task.
