### ISSUE TITLE
Incomplete documentation: admin permissions are required to connect to a BitBucket Cloud repo

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/azure-devops-docs#9340]
admin permissions are required for the account used to connect to the BitBucket Cloud repo, even it the pipeline does not use PR and CI integrations:
```
trigger: none
pr: none
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf09cc7f-cd4d-6647-e47b-82744bd3d2dd
* Version Independent ID: 75e80c27-0e2e-41d1-272f-e3da856f5071
* Content: [Build Bitbucket Cloud repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/bitbucket?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/bitbucket.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/bitbucket.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by vijayma** [comment]
Updated the doc to state that user needs admin access to Bitucket since that identity is used to register webhook. This is required since we always register a webhook even if you do not configure a ci or pr trigger in the YAML file. Azure Pipelines needs to inspect the YAML file after every change since that change can enable triggers in the yaml file.
