### ISSUE TITLE
Public upstream is too limited

### ISSUE THREAD

**Issue by eric-labelle** [MicrosoftDocs/azure-devops-docs#9358]
Why are we forced to use mavencentral as a maven repo? There is a multitude of maven repo hosted by companies that won't publish to maven central. ie. Google (https://maven.google.com/web/index.html) 

I'd like to be able to define a custom maven repo by pasting the url of their repo and giving them a name, like sonatype (nexus) allows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c152cc-c1d1-abc1-1861-20aab95731bb
* Version Independent ID: 0d75b4b4-3297-fae7-9345-d863f67e6fed
* Content: [Set up upstream sources for packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/set-up-upstream-sources?view=azure-devops#:%7E:text=Add%20an%20Azure%20Artifacts%20feed%20in%20your%20organization,dialog%20where%20you%20can%20choose%20Add%20upstream%20source.)
* Content Source: [docs/artifacts/how-to/set-up-upstream-sources.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/set-up-upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by msebolt** [comment]
@eric-labelle Thank you for the feedback.

Unfortunately, this issue is still pending, see [here](https://developercommunity.visualstudio.com/idea/365864/add-upstream-sources-for-maven-feeds.html), or for the issue's latest status, please refer to [here](https://developercommunity.visualstudio.com/idea/658181/adding-custom-maven-feed-or-proxying-the-maven-rep.html).

For any documentation concerns comment below, or for any other product-related issues please try the [community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by eric-labelle** [comment]
Allright @msebolt I'll follow linked issues. 
> Take note that your certificate for developercommunity.visualstudio.com is expired or invalid

**Comment by msebolt** [comment]
Interesting, possibly due to more restricted security settings...

![image](https://user-images.githubusercontent.com/6675884/101557429-da362000-3971-11eb-80d2-a79b18d8af0f.png)

(from https://www.ssllabs.com/ssltest/analyze.html?d=developercommunity.visualstudio.com)

Closing this issue now.
