### ISSUE TITLE
Consuming output variables of deployment jobs

### ISSUE THREAD

**Issue by michaldudak** [MicrosoftDocs/azure-devops-docs#9362]
The syntax for consuming output variables of another jobs (`$[ dependencies.A.outputs['ProduceVar.MyVar'] ]`) does not work if `A` is a deployment job. Could you please provide some explanation on how to use such variables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@michaldudak Thank you for the feedback.

Please see if the issue reported [here](https://developercommunity.visualstudio.com/content/problem/845394/yaml-pipeline-deployment-job-output-variables.html) addresses your issue.  The issue was recently confirmed and labelled as fixed.

If the issue remains or for any additional concerns please comment below.

**Comment by msebolt** [comment]
Another possibly related issue, https://github.com/MicrosoftDocs/azure-devops-docs/issues/9622.
