### ISSUE TITLE
Add Xcode Task Option to Publish Code Coverage

### ISSUE THREAD

**Issue by mikerunnals** [MicrosoftDocs/azure-devops-docs#9365]
Add a true/false option to publish a code coverage report to Azure Pipelines/TFS.
Similar to the `publishJUnitResults` option, this new option could publish a Cobertura supported by Pipelines.
e.g. `publishCoberturaResults`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36460c87-c713-0930-461b-92da65e415e6
* Version Independent ID: 047d39f1-481b-c135-36e9-6cfc1cc92e99
* Content: [Xcode build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xcode?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/xcode.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/xcode.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@mikerunnals Thank you for using **Microsoft Docs**!

Unfortunately this will require use of the [Publish Code Coverage Results](https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-code-coverage-results) task with the `cobertura` option.

For additional feedback, please consider moving the issue to [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) to solicit feedback from the product team.

Otherwise, you will need to try **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to report this as a product-related issue.
