### ISSUE TITLE
How to keep the tasks inside the work item template

### ISSUE THREAD

**Issue by dandynamite** [MicrosoftDocs/azure-devops-docs#9369]
[Enter feedback here]

How can I create a template for a work item that has a lot of common tasks inside it? This feature is not likely to support this circumstance.
Is there another way to do that?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1debd814-eb48-c984-a4f9-7606093e9617
* Version Independent ID: f48ef796-c2e3-8fa3-6c41-326a5b252a3d
* Content: [Use work item templates to update stories, & more - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/work-item-template.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/work-item-template.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@dandynamite Thank you for the feedback, please refer to [this post](https://developercommunity.visualstudio.com/idea/365579/work-item-template-or-clone-including-subtasks.html) on the latest supported feature set.

Otherwise, to solicit additional feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

**Comment by KathrynEE** [comment]
@dandynamite - The best guidance currently is provided here: https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/work-item-template?view=azure-devops&tabs=browser#how-do-i-create-a-template-with-links-to-other-work-items.
