### ISSUE TITLE
What happens with existing packages when you enable the retention policy on an existing nuget feed 

### ISSUE THREAD

**Issue by YvesRoyer** [MicrosoftDocs/azure-devops-docs#9374]
additional info could be usefull.

We have a nuget feed which exists for about 2 years and at the beginning of the project somebody forgot to enable the retention policy. Today we hit the 5000 package limit. 
Based on the article It's not clear what will happen when enabling the retention period:
- will existing packages, generated prior when we enabled the policy, still be cleaned up based on the policy settings?
- if so, when will the clean up be triggered? once a day just like other retention policy settings on pipelines, test runs, ... ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by herenhuang** [comment]
Hey there! 

Previous package versions will be considered as part of the policy settings. 

What happens when you set retention policy is that those package versions will be moved to the Recycling Bin in a soft-deleted state. Tthe job does run once per day, but there could be an initial delay due to an influx of packages to send to the recycling bin after the policy is turned on for the first time. Items within the Recycling Bin are part of your billable charge, until they are hard-deleted automatically in another 30 days (30 days after they enter the Recycling Bin). At that point they are permanently deleted, and removed from your billable storage. 

However, you are able to batch (hard-)delete all packages within the recycling bin prior to the automatic 30 days. You can do this by using the API documented [here, for example for Nuget](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifactspackagetypes/nuget/update%20recycle%20bin%20package%20versions?view=azure-devops-rest-6.1). You'll also see on that docs site a corresponding [get batch API](https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/artifact%20%20details/get%20packages?view=azure-devops-rest-6.0) for packages in the recycle bin.

Hope this helps!

**Comment by YvesRoyer** [comment]
After a while the packages were indeed soft deleted (after the 3rd day, a lot of packages had to be removed ;-) ). But based on the existing documentation at that time it wasn't what would happen :-)
