### ISSUE TITLE
How to disable this?

### ISSUE THREAD

**Issue by zjzhang88** [MicrosoftDocs/azure-devops-docs#9414]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@zjzhang88 Thank you for the question.

Markdown actually does support basic text editing in addition to the syntax renders.  

Otherwise, for product suggestions, we recommend to use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).
