### ISSUE TITLE
Automatic versioning is only supported with pack command

### ISSUE THREAD

**Issue by alexmajor** [MicrosoftDocs/azure-devops-docs#9420]
The documentation does not state that versioningScheme only works with the pack command. 

The YAML snippet could state:
`#versioningScheme: 'off' # Optional when command == Pack # Options: off, byPrereleaseNumber, byEnvVar, byBuildNumber `

It is only evident when using the 'Edit' view within AzureDevOps.
![image](https://user-images.githubusercontent.com/5017286/95101380-1219b080-0700-11eb-9e9b-15678bd42876.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d9884-19f7-592b-f47c-8cf100639ff0
* Version Independent ID: 555c3826-60d9-2589-54af-850efbfbb13a
* Content: [.NET Core CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @pulkitaggarwl
* Microsoft Alias: **puagarw**

**Comment by steved0x** [comment]
This is partially fixed in our new task reference, which is autogenerated from the task source code. In the task assistant, that option is listed under Pack options (your screenshot). We now include this information in the YAML syntax block:

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/dotnet-core-cli-v2?view=azure-pipelines#syntax

```
  # Pack options
    versioningScheme: 'off' # 'off' | 'byPrereleaseNumber' | 'byEnvVar' | 'byBuildNumber'. Required. Automatic package versioning. Default: off.
    #versionEnvVar: # string. Required when versioningScheme = byEnvVar. Environment variable. 
    #majorVersion: '1' # string. Alias: requestedMajorVersion. Required when versioningScheme = byPrereleaseNumber. Major. Default: 1.
    #minorVersion: '0' # string. Alias: requestedMinorVersion. Required when versioningScheme = byPrereleaseNumber. Minor. Default: 0.
    #patchVersion: '0' # string. Alias: requestedPatchVersion. Required when versioningScheme = byPrereleaseNumber. Patch. Default: 0.
```

Some task inputs have information like "Optional. Use when parameterA = 123". The versioningScheme doesn't include that metadata in the task source so we don't include it in the text description of the input.
