### ISSUE TITLE
Missing information on schedule syntax

### ISSUE THREAD

**Issue by dhvik** [MicrosoftDocs/azure-devops-docs#9424]
I read that you could use schedule triggers in the yaml file and since it's missing from this page I thought I should mention this.
(Or do you have a better page where the documentation should be?)

See release notes from last year <https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-153-update#use-cron-syntax-to-specify-schedules-in-a-yaml-file>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@dhvik We have got a dedicated topic for scheduled triggers here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml

Since scheduled triggers are the same across different repo types (vs CI and PR triggers which have some differences) the article for them is in a separate topic, which used to be in the same TOC node as the repos articles but it has moved and may not be as discoverable. However, I think we could add some info and links to the Azure Repos Git page (and the others) about the this, I will do so next week. Sorry that you ran into trouble and thank you for letting us know.
