### ISSUE TITLE
Guidance on auto-launching dockerized agents after reboot

### ISSUE THREAD

**Issue by IngmarVoigt2** [MicrosoftDocs/azure-devops-docs#9437]
Dear team,

launching a dockerized agent with `docker run -d --restart always` seems help only register it once, hence I am hoping the personal access token, is only needed once, right? Would you mind to enhance the documentation accordingly?

It is not clear however, what is best practice to auto-launch Docker on Windows hosts: auto-logon (e.g. using https://docs.microsoft.com/en-us/sysinternals/downloads/autologon)  seems to be a reasonable workaround. On the other hand there are suggestions on Stackoverflow to setup a service, however these basically either required a personal access token each time (which will expire at some point) or would only work on a Linux host (not Windows)

Any suggestions are highly appreciated!

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
