### ISSUE TITLE
What is the solution for Load Testing in Azure and when would that be available? 

### ISSUE THREAD

**Issue by samuelrajadorai** [MicrosoftDocs/azure-devops-docs#9477]
What is the solution for Load Testing in Azure and when would that be available? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74322585-effa-ba29-a9f3-982843169913
* Version Independent ID: 15e8e929-eda0-88af-b173-4773407e95f2
* Content: [Run URL-based cloud load tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-simple-cloud-load-test?view=azure-devops)
* Content Source: [docs/test/load-test/get-started-simple-cloud-load-test.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/test/load-test/get-started-simple-cloud-load-test.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Please ask your question in the community forums:
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
