### ISSUE TITLE
Copy children recursive

### ISSUE THREAD

**Issue by The-DevOps-Guy** [MicrosoftDocs/azure-devops-docs#9491]
The ability to copy children recursively has not been mentioned. I note that when copying children, there is no mention that this is limited to one level deep only. This means copying a Feature work item for example,  will only include the Stories, but non of the tasks. This is a serious limitation that needs to be explicitly detailed here. Not sure why there is no "recursive" option.

This would work perfectly as long as there are no circular reference in the chain. This could be mitigated by a warning when this condition is detected and prompting the user to break the chain at the self reference point. This should be very rare anyway as edge cases go.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa195a89-e867-a1a2-b217-7897eaf658cc
* Version Independent ID: dbca0b38-fbd2-0e97-5494-b7303b4b3f4b
* Content: [Copy or clone stories, issues, or other work items - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/copy-clone-work-items?view=azure-devops&tabs=browser)
* Content Source: [docs/boards/backlogs/copy-clone-work-items.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/backlogs/copy-clone-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@The-DevOps-Guy - Thank you for your feedback. The feature as written is by design, however, I'll update it to reflect that it is not recursive. I checked with the product team and there are no plans to make it recursive. If you'd like to make that suggestion for this feature, please do so on our  [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
