### ISSUE TITLE
Cannot use environment variables for PAT to run 'az devops login' successfully. 

### ISSUE THREAD

**Issue by gary918** [MicrosoftDocs/azure-devops-docs#9497]
[For https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows#use-environment-variables, I'm running the command on Windows 10. Neither of the following environment variable settings works for me:
CMD:
set AZURE_DEVOPS_EXT_PAT = xxxxxxxxxx
PowerShell:
$env:AZURE_DEVOPS_EXT_PAT = 'xxxxxxxxxx'

az devops login --org https://dev.azure.com/xxxx always pop up 'Token:' ask for the input.

Any suggestions?
Thanks in advance!
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af3bebb5-3c18-a905-67b7-a1c6bd4f4522
* Version Independent ID: d6c7802a-dfdf-9852-a51b-d2ba30be70fe
* Content: [Sign in with a Personal Access Token (PAT), Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/log-in-via-pat?view=azure-devops&tabs=windows#use-environment-variables)
* Content Source: [docs/cli/log-in-via-pat.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/cli/log-in-via-pat.md)
* Product: **devops**
* Technology: **devops-reference**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@gary918 - I've found the PowerShell entry works. I haven't had success yet with the Command Shell. 
PowerShell:
$env:AZURE_DEVOPS_EXT_PAT = 'xxxxxxxxxx' 

I'd double check your PAT. Since this isn't a document error, if you continue to have problems, post your issue on [Developer Community page](https://developercommunity.visualstudio.com/spaces/21/index.html).
