### ISSUE TITLE
How to use multiple repositories with no YAML pipeline?

### ISSUE THREAD

**Issue by irriss** [MicrosoftDocs/azure-devops-docs#9529]
My pipeline is a pipeline without YAML with the classic editor. How can I checkout from an additional Bitbucket repository?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by irriss** [comment]
Any help please?

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
