### ISSUE TITLE
Passing an array of int through release pipeline variables results in error

### ISSUE THREAD

**Issue by mihaibozesan123** [MicrosoftDocs/azure-devops-docs#9536]
Hi,
I am trying to deploy a logic app that is set up with parameters that are to be replaced with pipeline variables upon deploy.
For schedule hours I need to pass an array as it is to run at multiple hours of the day. I am passing the array in the pipeline as such:
![image](https://user-images.githubusercontent.com/15121285/97003282-e2620980-1543-11eb-9751-e5ee50280d7d.png)

I get this error message: 
`Message=Deployment template language expression evaluation failed: 'Unable to parse language expression '7, 10, 12, 14, 16, 20, 22': expected token 'EndOfData' and actual 'Comma'.'.`

I know it is not from the Logic App setup as it works when I deploy locally and I pass the value the same way.

I assume that in the pipeline I should define the array in a different way, but the google search is void of any documentation or suggestion as to how to do It, so I found myself posting the question here,

Can you help me please?
Thanks

Edit: I've also tried without brackets, but the error message in this case is:
`Message=Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Array'. Actual 'Object'.`

**Comment by msebolt** [comment]
@mihaibozesan123 Thank you for the feedback.

This message appears to be due to syntax-related errors, see [this post](https://powerusers.microsoft.com/t5/Building-Flows/List-of-Errors-and-Meanings/td-p/15217).

Unfortunately, we are only able to provide changes to documentation in this repo.

For additional support, please refer to:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
