### ISSUE TITLE
view test results / coverage in teams using azure pipline subscription

### ISSUE THREAD

**Issue by khanzzirfan** [MicrosoftDocs/azure-devops-docs#9543]
[Enter feedback here]
Is there a way to access test summary and code coverage summary published to Teams via Azure Pipeline Subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Server](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
