### ISSUE TITLE
How To Specify Ordering of Stages / Jobs

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/azure-devops-docs#9556]
When multiple stages / jobs are configured to run in parallel (`dependsOn: []`), their ordering in the ADO UI is indeterministic.  Is there a way to order stages / jobs?  neither ordering them in the YAML template nor alphabetizing seems to work.

When there are later stages dependent on these jobs, the lines end up getting crossed and it becomes difficult to determine what is dependent on what in the UI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d322215c-8025-4f21-0700-7dfa7dc5c46e
* Version Independent ID: 141fcdbb-8394-525b-bb29-eff9a693a9c4
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
