### ISSUE TITLE
Required arguments?

### ISSUE THREAD

**Issue by epernst** [MicrosoftDocs/azure-devops-docs#9582]
I think it is very misleading the way you specify which arguments are required and which are not. 
As for what I have learned so far, then it depends on which templateType you use. If you use the "builtin" then your list is mostly correct, except customTemplateLocation is only required if "custom" is selected. Same with subscriptionId and resourceGroup, this can also be specified via the customTemplateParameters.
I expect that the Yaml example is as close to a correct picture of which arguments must be used or not.
I also expect that you really do not need to specify arguments with a default value like templateType.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2f7a83-5e63-e305-4cc1-d443db82893e
* Version Independent ID: 35b19b29-3f7b-19a3-5bb5-a3af2bbfe4d8
* Content: [Build Machine Image task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/packer-build?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/packer-build.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/packer-build.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by steved0x** [comment]
Thanks for letting us know. This issue is fixed in our new task reference here (which includes all task input requirements and dependencies on other inputs): 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/packer-build-v1?view=azure-pipelines&viewFallbackFrom=azure-devops

Please check it out and let us know what you think. Thank you.
