### ISSUE TITLE
Failing to clone submodule

### ISSUE THREAD

**Issue by lipalath-ms** [MicrosoftDocs/azure-devops-docs#9599]
I created a git repo in Azure devops and added the github project as a git submodule

On running the build, I see the following error:

git: 'credential-manager-core' is not a git command. See 'git --help'. 
fatal: could not read Username for 'https://github.com': terminal prompts disabled 
fatal: clone of 'https://github.com/microsoftgraph/group-membership-management.git' into submodule path 'D:/a/1/s/group-membership-management' failed 

I tried adding the PATH ‘C:\Program Files\Git\mingw64\libexec\git-core\’  but that didn’t help. Could you please let me know what might be causing this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5c0726-1492-650f-3ebb-08407acb21f9
* Version Independent ID: 53e88c46-86d7-74af-3b82-b630c3c9d689
* Content: [Build source repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/?view=azure-devops)
* Content Source: [docs/pipelines/repos/index.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/repos/index.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
