### ISSUE TITLE
Why just the happy path?

### ISSUE THREAD

**Issue by lensmithjr** [MicrosoftDocs/azure-devops-docs#9640]
What happens if the cherry pick doesn't work and you have to do it manually? I get the constantly wanting to make things seem easy in your documentation, but the real world doesn't work that way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@lensmithjr Thank you for the feedback.

Please refer to the use of [git commands](https://docs.microsoft.com/azure/devops/repos/git/command-prompt?view=azure-devops) or consider using a [Git command script](https://docs.microsoft.com/azure/devops/pipelines/scripts/git-commands?view=azure-devops&tabs=yaml).

Otherwise, for additional support options, please use the following:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
