### ISSUE TITLE
List the standard points of extensibility

### ISSUE THREAD

**Issue by sevaa** [MicrosoftDocs/azure-devops-docs#9642]
There's no list of built-in contribution targets and what contribution types they accept. The only doc page with extensibility points listed is the explicitly obsolete one at https://docs.microsoft.com/en-us/previous-versions/azure/devops/docs/extend/reference/targets/overview?view=azure-devops 

@chcomley 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops-2020)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @sevaa, Thanks for reaching out. Since we aren't updating this extension documentation regularly, I recommend going to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is quite active. Select **Report a problem** > **Azure Devops**, enter what you're looking for, and then select **Submit**.  

You've probably already seen the following, but I'm providing links in case they help in any way: 
- [Formula Design System Extension Development](https://developer.microsoft.com/en-us/azure-devops/develop/extensions)
- [Azure DevOps Extension API](https://github.com/microsoft/azure-devops-extension-api/blob/451451671ff96b7839c8095377a90f16d518ed09/src/Contributions/Contributions.ts)

Feel free to @mention me. I'm sorry I'm not more helpful.
