### ISSUE TITLE
Check in Policies 

### ISSUE THREAD

**Issue by gperrego** [MicrosoftDocs/azure-devops-docs#9673]
A couple of questions related to this page:

Question 1 - Can a check-in policy be applied at a sub folder level instead of to a whole project?  for example if my source repo has three main folders at the top:

- $Project
-- FolderA
-- FolderB
-- FolderC

Can I turn on a check in policy for just one folder?  

Question 2 - Can I somehow associate a branch with an epic or feature?  Branch A is meant to contain Feature 1 and Branch B is for Feature 2 changes.  If the Developer checks into branch A but attempts to associate to a work item that is a child of Feature 2 can i stop the check-in somehow?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d0b3e2e-f717-5ec2-a573-4bfc4ed98214
* Version Independent ID: 495552ec-10a6-cb16-8561-3479fd82e00f
* Content: [Add Check-In Policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/add-check-policies?view=azure-devops)
* Content Source: [docs/repos/tfvc/add-check-policies.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/tfvc/add-check-policies.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @MaximMalygin
* Microsoft Alias: **v-maksim**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
