### ISSUE TITLE
Mistaken image tag in article

### ISSUE THREAD

**Issue by JacobusH** [MicrosoftDocs/azure-devops-docs#9687]
The images in this article have a misplaced

```
 [!div class="mx-imgBorder"]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d589bb13-a51a-77a5-d2f0-f424e42ede04
* Version Independent ID: 7b250082-a9c0-7dc2-9381-d04fbc5b7624
* Content: [Define a multi-stage CD release pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/define-multistage-release-process?view=azure-devops)
* Content Source: [docs/pipelines/release/define-multistage-release-process.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/define-multistage-release-process.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by Tkrogholt** [comment]
Is it possible to preview exactly how it will look with CSS and html parsed from the markdown file? This seems like a pretty simple issue to start dipping into contributing, but none of the previews I am able to render includes the final processing of [!NOTE], [!div] and so forth, so it is difficult to verify that the issue is solved.

**Comment by mijacobs** [comment]
It looks like @msebolt fixed the article.
