### ISSUE TITLE
Why? "For critical stages like production, Pull request deployment should not be turned on."

### ISSUE THREAD

**Issue by t-l-k** [MicrosoftDocs/azure-devops-docs#9689]
This to me seems like a totally arbitrary statement. There is no reason to restrict pull request deployments into production environments.

E.g, with a GitHub Flow branch strategy, pushing builds from from pull requests into production is described as a normal practice.

So this **Important!** note should be either justified for good reasons, or removed.

![image](https://user-images.githubusercontent.com/15836198/99432535-332b0f00-2904-11eb-9594-af065e82cd1e.png)

Edit: Clicked the wrong 'new issue' link copied in the Github linking below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbb2877-5e10-4065-e3c6-7883e9df4b3c
* Version Independent ID: 58122a19-2258-3cf3-8335-74bb0dad892f
* Content: [Deploy pull request Artifacts - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-pull-request-builds.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/deploy-pull-request-builds.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @raiyanalam
* Microsoft Alias: **moala**

**Comment by raiyanalam** [comment]
Thanks for reaching out. 
Different organizations have different ways for reducing deployment risk. The idea here is to shift left(find issues earlier in the cycle)  as much as possible. If your organization is comfortable with deploying PRs in production as it employs other ways( like feature flags, or having a separate early adopter environment etc) to reduce impact of a change, then you can  use this production, the product will not restrict you.
However, in general, a more risk mitigating approach is to deploy and test PR branch in a dev environment and then merge it with main branch so that the changes done by all developers are deployed and again goes through a dev->test->prod environment. 
Hope this helps.

**Comment by msebolt** [comment]
@t-l-k  Thank you for the feedback, if there are any further issues please comment below.

Closing this issue now.
