### ISSUE TITLE
Git has new credential manager called manager-core. Is there any change after this ? 

### ISSUE THREAD

**Issue by dotnetstep** [MicrosoftDocs/azure-devops-docs#9759]
Recently I have installed new version of git for windows. 

Things I have mention over here. 
https://stackoverflow.com/questions/65085379/disable-git-credential-manager-for-windows-from-visual-studio-2019

After installing new version that popup  keeps coming. Now if I provided official credential of my Azure devops then it is not working. I have to generate PAT and then in this box I have to add username as PersonalAccessToken and password as PAT. 

In another machine where I still have old version of git, git extension for visual studio working fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8b4989-21f0-53c5-dfce-6d5f1a66b8b2
* Version Independent ID: 2f4419a7-408b-40cd-9190-985a9976d556
* Content: [Authenticate with your Git repos - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=azure-devops)
* Content Source: [docs/repos/git/auth-overview.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/repos/git/auth-overview.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
