### ISSUE TITLE
Cannot be monitored

### ISSUE THREAD

**Issue by aeioaeu** [MicrosoftDocs/azure-devops-docs#9770]
> Azure Boards app for Microsoft Teams helps to easily monitor the events
> Azure Pipelines app for Microsoft Teams helps to easily monitor the events

But now it doesn't work.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Server](https://docs.microsoft.com/ja-jp/azure/devops/service-hooks/services/teams?view=azure-devops)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by msebolt** [comment]
@aeioaeu Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

Or, for additional support options, please refer to:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)
