### ISSUE TITLE
How to secure the service hook subscription?

### ISSUE THREAD

**Issue by dmsehuang** [MicrosoftDocs/azure-devops-docs#9786]
Hello, I want to understand how to secure the service hook subscription that I created. Basically I want to disable the 'edit' function after the service hook is created. Reason being the service hook could contain an Azure Function code and I want to make it invisible to the user. Here's an example of Zapier service hook:
![image](https://user-images.githubusercontent.com/2761304/101262149-4ce49880-36f1-11eb-9332-4e7365da61e2.png)

**Comment by TimShererWithAquent** [comment]
@dmsehuang -  Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
