### ISSUE TITLE
Schedule a Pipeline based on tag.

### ISSUE THREAD

**Issue by GaganDhamija3** [MicrosoftDocs/azure-devops-docs#9800]
I am unable to schedule trigger on a pipeline based on tag, Please suggest what can be done. Thanks!
schedules:
- cron: '0 * * * *'
  displayName: Nightly Build
  tags:
    include:
    - v*
  always: true

![image](https://user-images.githubusercontent.com/75719950/101598005-8123c600-3a1d-11eb-92a0-c2679129af58.png)

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
