### ISSUE TITLE
[azure-devops-docs] Review the external links to GitHub Actions documentation

### ISSUE THREAD

**Issue by martin389** [MicrosoftDocs/azure-devops-docs#9815]
The following doc contains external links to GitHub Actions content on [docs.github.com](https://docs.github.com/):

- "Quickstart: trigger a pipeline run from GitHub Actions": [[Published article]](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions) - [[Markdown source]](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/ecosystems/github-actions.md).

For the doc listed above:
1. Review each link to [docs.github.com](https://docs.github.com/) and [help.github.com](https://help.github.com) to determine if its directing users to the best section for that topic.
2. If there's a more preferable link, or if the link gets redirected: create a PR to update the docs with the new link.

**Comment by martin389** [comment]
👋 We'll be working on this with @juliakm.

**Comment by martin389** [comment]
Checked link:

- https://docs.github.com/en/github/getting-started-with-github/create-a-repo
   - Confirmed that this is the right link for this content 👍

**Comment by skedwards88** [comment]
The links here look correct! However, a few things in the content itself could be updated (listed below). I [opened up a PR](https://github.com/MicrosoftDocs/azure-devops-docs/pull/9832) to address them, but feel free to reject all/part of it.

For the text "2. Select Set up your workflow yourself."
  - (super minor discrepancy) the text the user sees is "Skip this and set up a workflow yourself" with "set up a workflow yourself" clickable.
  - This link only appears if the repository does not contain any workflows. If the repository does contain workflows, the user needs to click "New workflow" to get to the page

For "5. Copy this workflow and replace the contents of your GitHub Actions workflow file", at first I thought it meant I should copy the text from the Azure Pipelines Action in marketplace (since I already had part of the file set up and since step 4 directed me to the marketplace entry). However, this does not work since the jobs, job.id, job.id.runs-on, and job.id.steps keys are missing. 

For "6. On the Actions page, verify that your workflow ran", the workflow won't run unless it is triggered (in this case, by a push or pull request to master). 

For step 6, this screenshot and text is outdated since the UI got a new refresh last week. Here are more up-to-date screenshots/text as an example: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/viewing-workflow-run-history. (I'm not sure how to add a screenshot, so I didn't put this in the PR.)

For "If you're not going to continue to use the GitHub Action, delete the workflow with the following steps:", it might make more sense to [disable to workflow](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) instead.

**Comment by skedwards88** [comment]
Update after talking with @martin389 -- we are going to include `en/free-pro-team@latest` in all of the URLs to reduce redirects further. I will update the PR with this change.

**Comment by juliakm** [comment]
@skedwards88 Should we close this issue? The associated PR has been merged.

**Comment by skedwards88** [comment]
Excellent! I'll go ahead and close this.
