### ISSUE TITLE
In depth Documentation about Service Hook payload

### ISSUE THREAD

**Issue by xlight05** [MicrosoftDocs/azure-devops-docs#9818]
In REST API Documentation such as https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-6.1 under the URI Parameters section it contains the indepth documentations about the fields that we are getting received including required, Data types and stuff. 

However, When it comes to Service hook responses, I couldn't find anything similar to that. There is an example json payload that we are receiving but it does not cover all the possible scenarios, fields and details.  Can you please point me into the correct direction regarding this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96287641-3e4f-b038-148f-08e8471bd573
* Version Independent ID: b0034cd1-4f29-2e2d-c2bb-49004552dae8
* Content: [Troubleshoot your service hooks integrations - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/troubleshoot?view=azure-devops)
* Content Source: [docs/service-hooks/troubleshoot.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/service-hooks/troubleshoot.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @aaronhallberg
* Microsoft Alias: **aaronha**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the  documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
