### ISSUE TITLE
Missing documentation on which team's "Board Column" values are shown in query results, when more than one team is assigned a given Area Path

### ISSUE THREAD

**Issue by vhhughes** [MicrosoftDocs/azure-devops-docs#9839]
This documentation is ambiguous when it comes to understanding which team's "Board Column" values are shown in query results, when more than team is associated with Area Paths in query results. I cannot seem to determine how Azure DevOps decides which team's board column values to use in query results. It seems arbitrary. The deterministic logic used needs to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8acd801-cb9c-fa87-b4a7-5a44094bbd00
* Version Independent ID: e471c7e6-2ace-9029-ae22-62f1725168fa
* Content: [Query by account, user, workflow, or board changes - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-workflow-changes?view=azure-devops)
* Content Source: [docs/boards/queries/query-by-workflow-changes.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/boards/queries/query-by-workflow-changes.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@vhhughes - Thank you for your inquiry. This note at the end of  the [Kanban board change queries](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-workflow-changes?view=azure-devops#kanban-board-change-queries) section  indicates that querying on a Kanban board where the work items appear on more than one team yields indeterminate results. There is no work around for this. 

**Important**

Work items that appear on more than one team's Kanban board can yield results that don't meet your expectations. Each team can customize the Kanban board columns and swimlanes. Therefore, the values assigned to Board Column or Board Swimlane may differ from what you expect when another team updates the work item from a different board.

The primary work around for this issue is to maintain single ownership of work items by Defining area paths and assign to a team. Another option is to add custom workflow states which all teams can use. For details, see Customize the workflow (Inheritance process).
