### ISSUE TITLE
Template variables for template jobs

### ISSUE THREAD

**Issue by arynaq** [MicrosoftDocs/azure-devops-docs#9841]
Hi,

This is more a question than an issue, the following is not possible and is not strictly necessary to make things work but I like the idea of templates as being type definitions with some preset values I pass around to compose pipelines but the following not working really makes it hard to argue for that:

```c#
- stage: Test
    jobs:          
      - template: Service.yml
        variables: 
          - template: Service.Variables.yml
          - template: Service.Variables.Test.yml
```

Alternatively I could do (added Foo to demonstrate problem with this approach)

```c#
- stage: Test
    variables: 
      - template:  Service.Variables.yml
      - template:  Service.Variables.Test.yml
      - template : Foo.Variables.yml
    jobs:
      - template: Foo.yml
        parameters:
          keyvault: ${{variables.vault}}
          
      - template: Service.yml
        parameters:
          keyvault: ${{variables.vault}}
```
But there is a potential for name collision (high likelyhood) since more than one job at a stage level may reference the same variable by name but with different expectations of value.

How do I deal with this?

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
