### ISSUE TITLE
VSTS.AccountContents() authentication doesn't work 

### ISSUE THREAD

**Issue by dronkoff** [MicrosoftDocs/azure-devops-docs#9843]
Simple code like 
`VSTS.AccountContents("https://vsrm.dev.azure.com/{org}/{proj}/_apis/release/deployments?$top=100&?api-version=6.0")`
works as expected from PowerBI Desktop, but when you publish it, it can't authenticate from the portal.

Dataset -> Settings -> Data source credentials -> VSTS | Edit credentials

Whatever you enter here, you will receive a huge html error window sayin "<title>The resource cannot be found.</title>".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdc5841-fa63-c6df-8b26-90f05ffb6210
* Version Independent ID: dba4d2b1-7f7f-adeb-d8f3-f25a97c10093
* Content: [Connect using Power Query & Azure DevOps functions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-functions?view=azure-devops)
* Content Source: [docs/report/powerbi/data-connector-functions.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/report/powerbi/data-connector-functions.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
