### ISSUE TITLE
download of SNAPSHOT version like 'development-SNAPSHOT' not supported

### ISSUE THREAD

**Issue by abisekwins29** [MicrosoftDocs/azure-devops-docs#9877]
Hi Team,

We have requirement to download SNAPSHOT version as  development-SNAPSHOT. (  - task: DownloadPackage@1)

From documentaion its menationed as 
      version: '1.0.0-snapshot' # Should be normalized version

can this be enhanced to support any SNAPSHOT version?

**Comment by TimShererWithAquent** [comment]
@abisekwins29 

Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
