### ISSUE TITLE
run number variables - Unclear what "scope all" restriction means

### ISSUE THREAD

**Issue by davisnw** [MicrosoftDocs/azure-devops-docs#9883]
The "variables" section states:

>You can also use user-defined and predefined variables that have a scope of "All" in your number

It is not clear to me what "Scope of All" means.  When I look at the predefined variables on https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml , I don't see any mention of an "all" scope.

**Practical Example**

Evidently however, $(Build.SourceVersion) is not an "all" scope, because if I attempt to use it in a build number format, e.g. `$(Build.DefinitionName)_C$(Build.SourceVersion)_$(Rev:.r)`, the actual number shown in the DevOps pipelines run UI looks like
>MyBuild_C$(Build.SourceVersion)_.1

So `$(Build.SourceVersion)` does not get replaced in the build number as shown in DevOps.

Curiously, however, it is replaced later in the pipeline, because I simultaneously had a publish artifact task with **Artifact Name** `$(Build.BuildNumber`, and DevOps correctly shows the artifact name as 
>MyBuild_C14236_.1

So I'm not sure if this behavior is due to not being "Scope all" or if it's a bug in DevOps - but it is curious that the build number is not replaced for the pipeline run UI, but when the same build number is referenced in the artifact name, it is replaced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57f8545-bb15-3a71-1876-3a9ec1a59b93
* Version Independent ID: 28c87c8d-c28d-7493-0c7c-8c38b04fbcd7
* Content: [Run (build) number - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml#variables)
* Content Source: [docs/pipelines/process/run-number.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/process/run-number.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by TimShererWithAquent** [comment]
@davisnw Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

You might also consider searching issues or [submitting a bug](https://developercommunity.visualstudio.com/search?space=21). 

At-mention me if your issue needs more documentation follow up.
