### ISSUE TITLE
Order of execution of test cases in Visual Studio Test task using Test Plan

### ISSUE THREAD

**Issue by Nischal455** [MicrosoftDocs/azure-devops-docs#9887]
Visual Studio Test task - Azure Pipelines

While using Visual Studio Test task, when there are 'n' tests received and discovered to execute, how the order of execution decided?
Out of those 'n' tests that are identified to execute, which one is picked up first and what is the logic behind this? 
Is this sorted by testcase ID or GUID or any other algorithm?

Is there a way that I can choose the order of execution in a single Visual Studio Test Task , that is executed with Test Plan( Version 2.*).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @shashban
* Microsoft Alias: **shashban**

**Comment by TimShererWithAquent** [comment]
@Nischal455 Thanks for your question. It looks like you're asking a product question, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
