### ISSUE TITLE
There is no patch command

### ISSUE THREAD

**Issue by thinkriver** [MicrosoftDocs/azure-devops-docs#9890]
Will you please support patch command in this task ? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72bba72b-235b-ce64-b8fd-2c6ed52a9f1f
* Version Independent ID: 2ae1b3f1-e125-a9d2-a17c-d13047d69801
* Content: [Kubernetes manifest task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes-manifest?view=azure-devops#bake-action)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes-manifest.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes-manifest.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by msebolt** [comment]
@thinkriver Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

For additional support options, please see [Azure DevOps support](https://azure.microsoft.com/support/devops/).

**Comment by TimShererWithAquent** [comment]
@thinkriver Hi Jeff - I think this should be categorized as a doc enhancement. I'll change the tags and find the author to assign it to. Thanks, again, for bringing this to our attention.

**Comment by steved0x** [comment]
Thanks for letting us know. This patch command is added in our new task reference here: 
https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/kubernetes-manifest-v0?view=azure-pipelines

Please check it out and let us know what you think. Thank you.
