### ISSUE TITLE
What is considered an "older" artifact?

### ISSUE THREAD

**Issue by richardgavel** [MicrosoftDocs/azure-devops-docs#9898]
The default sort is by version number, but "older" could also be based on publish date. Generally, these two data points fall into line, but not always. Just looking for clarification. I am migrating a bunch of packages from our internal NuGet repository to Azure Artifacts. So publish date isn't reflective of the original publish date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8d31b-229b-7383-1cc0-f3d7c65eca84
* Version Independent ID: 70ba7acf-adae-e1b7-a42d-3f1344c5293c
* Content: [Delete and recover packages - Azure Artifacts](https://docs.microsoft.com/en-us/azure/devops/artifacts/how-to/delete-and-recover-packages?view=azure-devops&tabs=maven)
* Content Source: [docs/artifacts/how-to/delete-and-recover-packages.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/artifacts/how-to/delete-and-recover-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by TimShererWithAquent** [comment]
@richardgavel Thanks for your question. It looks like a question about the product itself, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
