### ISSUE TITLE
There must be a bug in the windows variant, because it fails while downloading the agent. Linux works fine but on windows it cannot find the host (used exact same host name)

### ISSUE THREAD

**Issue by thomasvanveen** [MicrosoftDocs/azure-devops-docs#9910]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@thomasvanveen Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

For additional support options, please see [Azure DevOps support](https://azure.microsoft.com/support/devops/).
