### ISSUE TITLE
Make ToC and RHS responsive panes hideable/adjustable as to not waste space in portrait mode [whole site]

### ISSUE THREAD

**Issue by thelazydogsback** [MicrosoftDocs/azure-devops-docs#9915]
The ToC pane on the left takes up too much room when viewed on a portrait mode monitor -- which otherwise is an excellent way to read documentation. 
It would be great if one could (a) un-pin the ToC so that it collapses, (b) make the divider movable, or at least (c) shrink-to-fit so that there isn't any extra trailing whitespace preserved. 

If I reduce the font size to try and add more main content, then I get a responsive right-hand column added with "Is this helpful?" and "in this article..." which is also not collapsible. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94a6e7d-3cb5-790c-2b8b-c09abd1de3f6
* Version Independent ID: a0d381e1-07ad-9191-4697-6faf600a7bd8
* Content: [Use Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops)
* Content Source: [docs/pipelines/get-started/pipelines-get-started.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/get-started/pipelines-get-started.md)
* Product: **devops**
* Technology: **devops-cicd-get-started**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@thelazydogsback Thank you for the feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation.

To solicit feedback from the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and provide a link back to this issue.

For additional support options, please see [Azure DevOps support](https://azure.microsoft.com/support/devops/).

**Comment by TimShererWithAquent** [comment]
@thelazydogsback Thanks for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
