### ISSUE TITLE
Is it possible to link an agent to multiple pool ?

### ISSUE THREAD

**Issue by warlof** [MicrosoftDocs/azure-devops-docs#9988]
Good morning,

I'm running in a case when we had to process pipeline releases from another project than the one hosting sources.
This remote project is already using a pool with an agent that's running on the server to be targetted.

Instead deploying another one, I would know if an agent can be linked to multiple pool a time ?

- Project A
  - Pool Customer
    - Agent Server 1

- Project B
  - Pool X
    - Agent Server 1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6f63ad-e95d-0105-c73a-de6e904edc09
* Version Independent ID: c97bfa1a-5aca-80a9-d9aa-8cca9987ad82
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by TimShererWithAquent** [comment]
@warlof - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
